### ISSUE TITLE
Encountered an error while parsing DTD is prohibited

### ISSUE THREAD

**Issue by sonnenx** [mozilla/policy-templates#10]
Hello,

I received this communicate when I try to edit GPO:

Encountered an error while parsing DTD is prohibited.
File \\do.ma.in\Policies\PolicyDefinitions\firefox.admx  line 7, column 9.

**Comment by mkaply** [comment]
Did you install the adml files and the ADMX files?

I'll create a ZIP file to make it more clear.

**Comment by mkaply** [comment]
I've put a ZIP file here that should work

https://github.com/mozilla/policy-templates/releases/tag/v0.1

**Comment by sonnenx** [comment]
Yes, I did.
Have you tested it on Windows Server 2016?

**Comment by mkaply** [comment]
> Have you tested it on Windows Server 2016?

I have not. Some folks have said it happens when you accidentally download the files as HTML instead of raw?

Can you try using the ADMX files from the zip?

Thanks

**Comment by sonnenx** [comment]
OK, I will test and answer.

**Comment by sonnenx** [comment]
Hej,

You're right. It's working now.
Thanks!

**Comment by sonnenx** [comment]
Hej Michael,

I have created a GPO that changes the Homepage and bookmarks, and no changes have been made. Firefox Quantum 59 64-bit and Windows Server 2016. What could have gone wrong?

**Comment by mkaply** [comment]
Our ESR support is on Firefox 60, so you need to use the Firefox 60 beta.

https://www.mozilla.org/en-US/firefox/channel/desktop/
