### ISSUE TITLE
Make all GPOs available for RR releases and not only ESRs

### ISSUE THREAD

**Issue by alexhass** [mozilla/policy-templates#100]
Title says all. Not idea why a homepage can only set in ESRs we are not using.

**Comment by spec1re** [comment]
Same for Extension installation.

**Comment by HeiHei90** [comment]
May I ask why you don't use the ESR?

**Comment by alexhass** [comment]
- Because Mozilla released more than one unstable ESRs in past that had serious bugs and we cannot wait 5 versions until it is fixed, when already fixed in +1 after the ESR.
- Our customers are using the standard releases and tell us about your bugs that we need to be able to reproduce.
- We never used ESR. So we are earlier aware what you break.
- I see no reason why we should not use RR.

Enterprise does not mean we have the need for ESR, BUT for a full-fledged MSI installer (not a shit wrapper) that is still not available!

**Comment by HeiHei90** [comment]
First of all: a little less Hass ;)
Secondly: It's not "my bugs" as I am not a Member of Mozilla

This is an Open Source Project. If you need something, you try to confince the people building it. If not, built it by yourself and contribute!

**Comment by alexhass** [comment]
Oh, the github account looks like official mozilla.

For about several years I‘m asking for msi. A few months ago someone closed an 11 years old and still unresolved case to create an msi. They really really do not understand enterprise needs! I pleased to reopen it, had contact with project manager and setup developer. However no answer since weeks. They really know how msi can be created, but try to build a shot msi/exe wrapper because of a build system. They also try to embed the updater, that every enterprise removes/disables. Enterprise can have it‘s own installer that does not need to follow the exe setup. Now they try to add more command line arguments to the exe setup. Something that still do not allow an active directory gpo deployment. And again - nobody wants an msi/exe wrapper. I honestly tried to help them, but they seem not very interrested.

Than they started with the policy engine. Not unimportant, but the wrong order. 

I had no time yet to fully test the policy json files, but it is still very unclear how I can use the admx to configure some settings as locked preferences and others as default preferences. Currently i‘m forced to customize the mozilla.cfg and cannot use gpo‘s. Embedding custom mozilla.cfg into frontmotion msi is not done in 5 minutes. And sorry, but the default homepage is not a setting limited to ESR. I‘m not using this, but it is the perfect example of general wrong.

Are you really saying mozilla is not working on this policies? How should this ever become in sync with the product releases than?

I can write admx files, but I have no clue about the new settings mozilla adds into their products. I also strongly suggest to tag the admx releases with firefox versions... otherwise I never know if they are compatible with newest versions. The block send screenshot to cloud policy is brand new in firefox 60 as one example.

**Comment by mhoye** [comment]
The risks to, expectations of and threat models facing our release channel users are very different from those facing enterprise administrators, and consequently we do not expose the same policy and management options to both of those groups. We are working - cautiously - to make more of these policy options available in release, but I do not expect that process to be quick or for the results to ever be identical, given those two communities' radically different needs.

If you have specific bugs in the Firefox that you would like to bring to our attention, we would be happy to listen. You can file them here:

https://bugzilla.mozilla.org/

However, I encourage you to take a moment to review Mozilla's participation guidelines, available here:

https://www.mozilla.org/en-US/about/governance/policies/participation/

should you chose to do so. Thank you, 

- mhoye

**Comment by mkaply** [comment]
Brainstorming ideas on the right way to do this here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1461730
