### ISSUE TITLE
looking for "create according to custom settings" in Privacy and security 

### ISSUE THREAD

**Issue by MichaelWie** [mozilla/policy-templates#1001]
Hello,

I am looking for the setting in the ADMX files to enable and configure "create according to custom settings" on the Chronicle (Privacy and security).
Does this option not even exist or am I missing it?

Greets,
Michael

102.8.0esr

![01](https://user-images.githubusercontent.com/29143968/220913319-a678b2eb-ac9e-4335-a6a8-bbf3967944f3.png)

![02](https://user-images.githubusercontent.com/29143968/220913368-92d95ce4-9c37-4572-b13f-ae01add8f1ff.png)

**Comment by mkaply** [comment]
That's covered by SanitizeOnShutdown

**Comment by mkaply** [comment]
No problem, difference in terminology, sorry.

It's the "Clear data when browser is closed" section on the left.

**Comment by MichaelWie** [comment]
No need to apologize.   I had looked at the part you mentioned before, but it didn't cause any change in the browser itself. Also when I added "Locked" to it, I would have expected the setting to be locked for the user. 
I'll test this again now that I know I'm in the right place. I'll get back to you in a few days. Thanks already!

**Comment by MichaelWie** [comment]
No need to apologize.   I had looked at the part you mentioned before, but it didn't cause any change in the browser itself. Also when I added "Locked" to it, I would have expected the setting to be locked for the user. 
I'll test this again now that I know I'm in the right place. I'll get back to you in a few days. Thanks already!

**Comment by MichaelWie** [comment]
It works as it should do. Thank you!
