### ISSUE TITLE
Preferences GPO wrong type

### ISSUE THREAD

**Issue by Xelosy** [mozilla/policy-templates#1003]
Hi, 

im trying to set a Windows GPO with 

```
{
  "pdfjs.cursorToolOnLoad": {
    "Value": 1,
    "Status": "user"
  },
  "pdfjs.sidebarViewOnLoad": {
    "Value": 0,
    "Status": "user"
  }
}
```

Its working but also not working. The values in my Firefox instances are boolean values. But they have to be numeric. 
Tried setting it to bool ("Value": true/false) also sets it to bool, wich is correct). "Value": "1" is a string ofcourse.
Am i doing something wrong? I am on policy templates 4.8 and Firefox 110.0.1 (64-Bit).

**Comment by mkaply** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1820195

**Comment by mkaply** [comment]
A fix for this has landing in Firefox. It won't be in next week's release, but the one after.

And I'll put in the ESR too.
