### ISSUE TITLE
DisableBuiltinPDFViewer

### ISSUE THREAD

**Issue by flagoda** [mozilla/policy-templates#1004]
Hi,
I want to add the ability to choose DisableBuiltinPDFViewer it's a lockPref or not.
For example on Proxy:
	"Proxy": {
      "Mode": "none",
      "Locked": false

I want to set default behavior but add the ability to the user can change it.
Or maybe it's possible but i don't find how

**Comment by mkaply** [comment]
A user would only be able to do this via about:config. but if you want to set it and not lock it, you can use the preferences policy

https://github.com/mozilla/policy-templates/blob/master/README.md#preferences

The preferences is

pdfjs.disabled

and you would set it to true
