### ISSUE TITLE
installaddonspermission respects default value but not exceptions

### ISSUE THREAD

**Issue by pnp-computopic** [mozilla/policy-templates#1005]
In linux, firefox 111.0 (64-bit), Mozialla firefox snap for Ubuntu.
Canonical-002-1.0
setting "Default": false prevents any installation no matter the URL added for "Allow":

Example:

`{
  "policies": {
    "InstallAddonsPermission": {
        "Allow": ["https://addons.mozilla.org/firefox/downloads/file/3650887/"],
        "Default": false
    }
  }
}`

**Comment by mkaply** [comment]
The InstallAddonsPermissions is only used to configure domains (origins) that are allowed to install extensions, it does not work with specific paths like that.

And if you set Default False, you are turning off all extensions.

If you want to allow the installation of one particular extension, you would use the ExtensionSettings policy:

https://github.com/mozilla/policy-templates/blob/master/README.md#extensionsettings

**Comment by pnp-computopic** [comment]
Thank you!
