### ISSUE TITLE
Allow *every* about:config setting

### ISSUE THREAD

**Issue by alexhass** [mozilla/policy-templates#101]
It looks like the current versions is quite useless as we still have a lot of settings that are not implemented as GPO yet like https://github.com/mozilla/policy-templates/issues/99 that is a serious privacy issue. Maybe this ADMX are just a start, but it is always bad if GPOs are behind the functions of a release.

We cannot ask you here for every small setting to get implemented. So it is useful to implement everything in case you missed something or you predicted wrong what you believe the admins need.

**Comment by HeiHei90** [comment]
That would be awesome, can you support with manpower and knowledge?

**Comment by mkaply** [comment]
We will not be allowing the setting of arbitrary preferences in group policy.

AutoConfig will continue to be available to set preferences that we miss.

We are asking that people let us know what preferences we missed and we will add policies. And we will be working with our developers to make sure they are more proactive in creating policies when they create new preferences.

**Comment by HappyPony** [comment]
@alexhass What mean you with GPO?

**Comment by alexhass** [comment]
https://en.m.wikipedia.org/wiki/Group_Policy
