### ISSUE TITLE
FR: Implement Force-pinning in ExtensionSettings

### ISSUE THREAD

**Issue by cakoronkowski** [mozilla/policy-templates#1011]
Hi there,

I am trying to roll out Firefox as a standard browser for an organization, and am trying to implement a GPO for standardized extensions the same way it is done in chrome. unfortunately several options available in Chrome ExtensionSettings are not available in Firefox. the one i am after is "toolbar_pin": "force_pinned". i am trying to pre-set the pinned extensions for everyone when i roll out the computers. ideally i would also like the "locked" option to be implemented in ExtensionSettings as well but since its implemented in Extensions currently that's not strictly necessary.

**Comment by mkaply** [comment]
Toolbar pinning will be in the next release of Firefox and the ESR (In four weeks).

What do you mean by "locked"? I don't see that in Chrome Extension Settings.

If you force_install an addon, it can't be uninstalled.

A user will still be able to remove the icon from the toolbar though.

**Comment by rungitringit** [comment]
> Toolbar pinning will be in the next release of Firefox and the ESR (In four weeks).

Has this been implemented as planned please?
If so what's the specific syntax?

Thank you!

**Comment by mkaply** [comment]
Sorry, forgot to add this to the docs. It's there now. Search for default_area

| `default_area` | (Firefox 113) String that indicates where to place the extension icon by default. Possible values are `navbar` and `menupanel`.
