### ISSUE TITLE
Need to be able to disable/reenable OCSP stapling via policy

### ISSUE THREAD

**Issue by ryanedlund** [mozilla/policy-templates#1016]
We've run into an issue where we are having to have colleagues disable OCSP stapling in order to make certain internal sites function. Seeing as there is no way to set security.ssl.enable_ocsp_stapling from GPO currently, we're having to have each user do this manually. We are going to want to revert this back once the issue with OCSP stapling is resolved, but would like to be able to set that via policy instead of having to have users revert it manually.  Can we please get security.ssl.enable_ocsp_stapling added as one of the settings configurable with "Preferences"?

**Comment by mkaply** [comment]
This will be configurable in Preferences starting with Firefox 113 and Firefox 102.11 which will be released next week.

Docs will be updated accordingly.
