### ISSUE TITLE
[Readme.md] Move policy list to wiki

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#1019]
I suggest that you move the pokicy list to the wiki or an othe md file. Because of the kong file it needs some time to show the repository/readme when using the smartphone app.

Maybe it makes sense to split ut into different documents.

**Comment by mkaply** [comment]
That's probably a good idea. Need to think about how to organize.

**Comment by mkaply** [comment]
I actually moved it to a page.

https://mozilla.github.io/policy-templates/
