### ISSUE TITLE
[GPO Error] Depreciated cookie setting undocumented

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#1027]
After installing FF 115 ESR I see the following warning:
```
'ExpireAtSessionEnd' has been deprecated and it has no effect anymore.
```

But there is no notice on the GitHub documentation, the ADMX templates or any release notes. 

What setting is replacing it?

**Comment by mkaply** [comment]
I'll update the docs.

You should use SanitizeOnShutdown and just clear cookies.

https://mozilla.github.io/policy-templates/#sanitizeonshutdown-selective

See:

https://bugzilla.mozilla.org/show_bug.cgi?id=1764761
