### ISSUE TITLE
GPO wish - Custom presets

### ISSUE THREAD

**Issue by epionier** [mozilla/policy-templates#103]
Hello,
it would be nice to have a GPO that allows predefined Settings from the about:config field with the possibility to set them as true/false locked/default, like the autoconfig method.
e.g.

accessability.typeaheadfind      true     locked 
general.autoscroll                      false   default

Kind regards

**Comment by Hurg84** [comment]
Hi,

allowing settings from about:config to be made via GPO would be very nice.

I personal need "network.http.spdy.enabled.http2" to set to false since I don't want
to mess around with Exchange 2016 and Sharepoint 2016 config hosted on Server 2016.

Kind Regards.

**Comment by jjurkus** [comment]
Indeed, my home users have a few locked settings, while a lot more are default. At work a lot more settings are locked.

**Comment by asadotzler** [comment]
see also #262 and #244

**Comment by mkaply** [comment]
This is settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences

general.* is not there yet, I'll add it to the list.
