### ISSUE TITLE
Policies on MacOS partly not working

### ISSUE THREAD

**Issue by kiepenflicker** [mozilla/policy-templates#104]
OS: MacOS 10.12.6
Firefox 60 ESR
I have created the file policies.json as described. The setting "DontCheckDefaultBrowser": true does not work. Also .jsons like this example below are ignored. The become broken, when i add the authentication part. When the file is cahnged to contain only DisableAppUpdate, DisableFirefoxAccounts and DisableFeedbackCommands it works.

{
	"policies": {
		"DisableAppUpdate": true,
		"DisableFirefoxAccounts": true,
		"DisableFeedbackCommands": true,
		"DontCheckDefaultBrowser": true
    	"Authentication": {
      		"SPNEGO": ["unicorn.example", "unicorn.local"],
      		"Delegated": ["unicorn.example", "unicorn.local"],
      		"NTLM": ["unicorn.example", "unicorn.local"]
    	}
    }
}

**Comment by mkaply** [comment]
You're missing a comma after "DontCheckDefaultBrowser": true

I would suggest using jsonlint.com to validate your JSON.

As far as DontCheckDefaultBrowser goes, I'll look into that.

**Comment by mkaply** [comment]
This is a bug in the policy engine. I've opened up a bugzilla bug for it:

https://bugzilla.mozilla.org/show_bug.cgi?id=1463882

I'm going to close this bug as it is not a problem with the policy templates.
