### ISSUE TITLE
"Sanitize on shotdown (Selective)" not looks "Clear cockies and website data"

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#1040]
## Expected
Enabling the policies
		- SanitizeOnShutdown/Locked
		- SanitizeOnShutdown/Cookies
		- SanitizeOnShutdown/OfflineApps
		- SanitizeOnShutdown/Cache
should look the "Delete cookies and site data when Firefox is closed" checkbox in the settings ui.

## Problem
If the user unchecked "Delete cookies and site data when Firefox is closed" then the "Settings" button for "Clear history when Firefox closes" changes to disabled state until pressing F5. 
![image](https://github.com/mozilla/policy-templates/assets/61519853/6fed104e-3c8b-40d1-8183-e1a308778d61)

## Additional notes
- The disabling of the checkbox was working in FF102esr and is now broken in FF115esr.
- Configure the sanitize policy for Coockies, Offline apps and Cache is the same as checking "Delete cookies and site data when Firefox is closed".
![image](https://github.com/mozilla/policy-templates/assets/61519853/87d1b8b9-978c-4df2-aa33-be47d3e09e58)

## Technical details
A 100% correct behavior should do the following:
	- Locked=enabled & one of Cockies/OfflineApps/Cache enabled should set the checkbox to unchecked and disabled.
	- Locked=enabled & all of Cockies/OfflineApps/Cache enabled should set the checkbox to checked and disabled.
	- Locked=enabled & none of Cockies/OfflineApps/Cache enabled should set the checkbox to unchecked and enabled.
	- Locked=disabled & one of Cockies/OfflineApps/Cache enabled should set the checkbox to unchecked and enabled.
	- Locked=disabled & all of Cockies/OfflineApps/Cache enabled should set the checkbox to checked and enabled.
	- Locked=disabled & none of Cockies/OfflineApps/Cache enabled should set the checkbox to unchecked and enabled.
	- Locked=NotConfigured & one of Cockies/OfflineApps/Cache enabled should set the checkbox to unchecked and disabled.
	- Locked=NotConfigured & all of Cockies/OfflineApps/Cache enabled should set the checkbox to checked and disabled.
	- Locked=NotConfigured & none of Cockies/OfflineApps/Cache enabled should set the checkbox to unchecked and enabled.

**Comment by mkaply** [comment]
OfflineApps was supposed to be marked as deprecated with the new sanitize dialog. I'll fix that in the next release.

If you have a specific new problem, please open a new issue.

The original problem in this bug is fixed. We now properly enable/disable all the checkboxes.
