### ISSUE TITLE
How to deploy app.update.langpack.enabled setting?

### ISSUE THREAD

**Issue by fdimkin** [mozilla/policy-templates#1042]
I've run into an issue where a lot of our clients are not updating via the Background Update task because by default app.update.langpack.enabled is set to True. When I manually set it to False in about:config and test the task again it succeeds.

Is there any way to deploy this via Group Policy? In the documentation I can't see any settings that reference the ability to set this on an enterprise level unlike AppAutoUpdate or BackgroundAppUpdate

**Comment by mkaply** [comment]
Is this still important to you? I never got a good answer internally.
