### ISSUE TITLE
Wrong translation in German

### ISSUE THREAD

**Issue by MaikLHD** [mozilla/policy-templates#1043]
Hi, I have found a wrong translation for a Setting and It will be greate to correct it.
Setting: DisableFormHistory
https://github.com/mozilla/policy-templates/blob/master/README.md#disableformhistory
Title: Disable Form History
Explain in English: 
If this policy is enabled, Firefox will not remember form or search history.
If this policy is disabled or not configured, Firefox will remember form and search history

In German:
Title: Chronik deaktivieren
Explain in German:
Wenn Sie die Richtlinieneinstellung aktivieren, wird Firefox dieselben Einstellungen wie im Privaten Modus verwenden und keinerlei Chronik anlegen.
Wenn Sie die Richtlinieneinstellung deaktivieren oder nicht konfigurieren, Firefox wird eine Chronik anlegen.

It will be better to write it like this: 
Tilte: Formular-Historie deaktivieren
Explain in German:
Wenn diese Richtlinie aktiviert ist, speichert Firefox keine Formular- oder Suchverläufe.
Wenn diese Richtlinie deaktiviert oder nicht konfiguriert ist, merkt sich Firefox den Verlauf von Formularen und Suchvorgängen.

Thanks :)

**Comment by mkaply** [comment]
@vossni Can I get your opinion here since you do this?

**Comment by vossni** [comment]
@mkaply In fact, a mistake has crept in here. I have corrected it in PR #1045.
