### ISSUE TITLE
Tab Unloading

### ISSUE THREAD

**Issue by FMCUSystemAdmins** [mozilla/policy-templates#1044]
It appears that the tab unloading feature is an all-or-nothing setting. Even at that, the actual setting is written to the user's prefs.js file in their profile. So, it's not easily deployable.

We have a use case that we'd preferably like to exclude a particular domain from tab unloading vs. disabling it all together. Are there any plans to implement this as a policy template rather than in the prefs.js?

**Comment by mkaply** [comment]
There are no plans to make this domain specific, but you can set it via preference  using the Preferences policy.

**Comment by FMCUSystemAdmins** [comment]
@mkaply, thanks. Didn't know about the Preferences policy. Got it configured and it's working great!
