### ISSUE TITLE
How do i know which policies should be in computer and which should be in user gpos

### ISSUE THREAD

**Issue by departet** [mozilla/policy-templates#1047]
Hey!
We are using a mix of ESR and Release FF. ESR on our rds collection and release on standalone clients.
We do use every gpo as a user one except for the homepage one. AFAIK there is no source that states which gpo only works in computer and which only works as a user gpo. Heck i don't even know if the other start page settings have to a computer one as well or if it's just "homepage".
Maybe i'm just missing an overview somewhere that explains this?

**Comment by departet** [comment]
Thats how things should work. But the homepage policy is simply not working as a user one. There are multiple (closed) issues on that topic. So i was wondering if thats the case on more than this policy.

I unwillingly tested this on the weekend when i cleaned up stuff and deleted the homepage value in the computer configuration (user one was still in place). This morning i had a bunch of users calling me saying the company wide start page was gone so i reverted the change.

**Comment by mkaply** [comment]
>  But the homepage policy is simply not working as a user one. There are multiple (closed) issues on that topic. So i was wondering if thats the case on more than this policy.

I haven't seen reports of this. There is no difference between computer and user policies from a technical point of view.

If you set both user and group policies, though, we will only pick one or the other, we will not combine them. Maybe that's what you were seeing?

**Comment by departet** [comment]
Obviously i can't find the issues now too haha.
So i removed the machine gpo again and set the "lock homepage" tick on the user gpo. This seems to have worked. I will test this further but i think this can be closed.

I also checked for multiple firefox gpos but it was just one so it shouldn't interfere with another one. Also user gpo and computer gpo had the same startpage set so it wouldn't be too important which one would take the upper hand.

Thank you very much @mkaply
