### ISSUE TITLE
GPO wish: Disallow adding new root certificates

### ISSUE THREAD

**Issue by episodeiv** [mozilla/policy-templates#1053]
This comes (as could be expected) from a compliance requirement but seems like a good idea to me.
There should be a way to block users from adding additional root certificates while retaining the ability to add, for example, client certificates.
I could use the policy to make Firefox use the operating system's certificate store but I'd prefer to keep Firefox as self-contained as possible.

**Comment by mkaply** [comment]
You can do this now by removing access to the certificate manager.

You can set

security.disable_button.openCertManager

to true and lock it in the Preferences policy.
