### ISSUE TITLE
FirefoxSuggest documentation typo

### ISSUE THREAD

**Issue by corobin** [mozilla/policy-templates#1054]
The [v5.3 release](https://github.com/mozilla/policy-templates/releases/tag/v5.3) added a policy for [FirefoxSuggest](https://mozilla.github.io/policy-templates/#firefoxsuggest).

In the linked documentation, there appears to be a number of typos:

The references to "FirefoxHome" look like they should actually be "FirefoxSuggest" based on browser's behaviour.

**Comment by mkaply** [comment]
Dang it. I thought I proofed that. Argh. Fixing.
