### ISSUE TITLE
DNS over HTTPS (DoH) and Encrypted Client Hello (ECH)

### ISSUE THREAD

**Issue by GHM3434** [mozilla/policy-templates#1055]
Hello,

**In summary, there are 3 requests/problems:**

1) There is no option in the group policy to select "Default Protection , Increased Protection and Max Protection settings under "Enable secure DNS using:" (I am specifically interested in being able to select "Max Protection"

2) Please have an option, in the above new group policy, to add a custom URL, for example, let me force: https://security.cloudflare-dns.com/dns-query

3) There is a group policy to enable Secure DNS in group policy, however, I was under the impression that once you enable secure DNS in firefox settings that ECH would be enabled automatically - but it's not the case as i've enabled secured DNS via group policy but this test website still says Secure SNI is disabled: https://www.cloudflare.com/ssl/encrypted-sni/#results

**What I've done:**

1) Downloaded latest version of group policy files for version 118 of firefox
2) imported the new .admx and .adml files into windows server group policy management
3) enabled secure DNS group policy
4) Applied group policy to computers
5) Run gpupdate /force and reboot computer
6) Open firefox

**Versions:**

1) Windows 11 22H2 computer
2) Firefox version 118.0.1 (64-bit)

**Why:**

1) I'd like the above requests/problems to be fix because i'd like to force dns over https, force enable Encrypted Client Hello (ECH) and to force the DNS over HTTPS URL provider

**Comment by mkaply** [comment]
I haven't actually updated the policy there, but yes this will be in Firefox 124

https://bugzilla.mozilla.org/show_bug.cgi?id=1868669
