### ISSUE TITLE
GPO Wish: Disable New Tab Page

### ISSUE THREAD

**Issue by dihmandrake** [mozilla/policy-templates#106]
I would love to disable the new tab page via a gpo. It is already possible in a cfg file via
`defaultPref("browser.newtabpage.enabled", false);`

For us, similar policies are in use for IE, Chrome and partly Edge. So this would be great to have this in all major browsers

**Comment by dihmandrake** [comment]
Looks like this has been fixed in Firefox 68.
https://github.com/mozilla/policy-templates/releases/tag/v1.8
I am a bit short time lately, but I ll try to confirm the functionality in the coming weeks.

**Comment by mkaply** [comment]
yep.
