### ISSUE TITLE
"FirefoxSuggest" policy settings don't take effect on first run when not locked

### ISSUE THREAD

**Issue by blkeller** [mozilla/policy-templates#1063]
The "FirefoxSuggest" policy does not appear to take effect on the first run of the browser if "Locked" is false.  Preferences such as `browser.urlbar.suggest.quicksuggest.nonsponsored` and `browser.urlbar.suggest.quicksuggest.sponsored` are shown in `about:config` as set to the default value with the default value being "true" even when the policy is supposed to set them to "false".  The Settings UI also shows the Firefox Suggest items "Suggestions from the web" and "Suggestions from sponsors" as enabled when the policy is supposed to disable them.  Entering a query into the address bar confirms the incorrect behavior.

Interestingly, if the user makes no changes to the Firefox Suggest settings, quits Firefox, and then relaunches it, the policy *does* take effect on the second run and all subsequent runs.  The preferences in `about:config` now show the expected value of "false", with "false" being the new default.  The Settings UI shows the Firefox Suggest settings as disabled, and the behavior in the address bar is indeed disabled.

I've worked around this bug temporarily by hacking up a solution in AutoConfig, but it would of course be preferable if the policy worked on the first run (and every run).  I also tested with "Locked" set to true, and in that case everything works OK on the first run, but I don't want to have to lock this policy.

### Environment
- Windows 10 21H2 (64-bit)
- Firefox 120.0 (64-bit)
- Policy set via `policies.json`

### Policy settings
```json
{
  "policies": {
    "FirefoxSuggest": {
      "ImproveSuggest": false,
      "Locked": false,
      "SponsoredSuggestions": false,
      "WebSuggestions": false
    }
  }
}
```

### Steps to reproduce
1. Apply the `policies.json` listed above.
2. Start with a clean state and no existing Firefox profile.  I just deleted the `%APPDATA%\Mozilla\Firefox` directory.
3. Launch Firefox
4. Look in `about:config` and observe the relevant settings have the default values shipped by Mozilla instead of those of the policy.
5. Also observe in **Settings -> Privacy & Security -> Address Bar - Firefox Suggest** that the policy has not been honored.
6. Type "home" in the address bar and get an ad for Home Depot.
7. Quit Firefox
8. Launch Firefox again
9. Look in `about:config` and observe that *now* the relevant settings have the new default values as set by the policy.
10. Observe in **Settings -> Privacy & Security -> Address Bar - Firefox Suggest** that the policy *has* been honored now.
11. Type "home" in the address bar and the sponsored result no longer appears.

**Comment by mkaply** [comment]
Thanks for reporting this. Would you mind opening a bugzilla bug for this?

https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Enterprise+Policies

If not, I can.

**Comment by blkeller** [comment]
@mkaply Thanks for the info.  As you requested, I've filed a Bugzilla bug for this over here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1876223

**Comment by mkaply** [comment]
Thanks! I'm going to close this since we're tracking it there.
