### ISSUE TITLE
Failed to set `geo.enabled`

### ISSUE THREAD

**Issue by qupig** [mozilla/policy-templates#1072]
According to documentation [`Preferences`](https://mozilla.github.io/policy-templates/#preferences), it supports `geo.`

But after setting:

```xml
<key>Preferences</key>
<dict>
	<key>geo.enabled</key>
	<dict>
		<key>Value</key>
		<string>false</string>
		<key>Status</key>
		<string>locked</string>
	</dict>
</dict>
```

In `about:policies#errors`:
> Unable to set preference geo.enabled. Probable type mismatch.

This is what it looks like before and after in `about:config`:

![before](https://github.com/mozilla/policy-templates/assets/61939856/7d0f2edd-6450-414b-8dc7-502b654ace2f)
![after](https://github.com/mozilla/policy-templates/assets/61939856/4cd09b17-d483-4557-80c1-3a2ea33178d7)

**Comment by mkaply** [comment]
Because it;'s a boolean, it needs to be set as:

<false/>

**Comment by mkaply** [comment]
No problem. Please let me know if you need anything else.
