### ISSUE TITLE
AutoLaunchProtocolsFromOrigins does not seem to work

### ISSUE THREAD

**Issue by Mrgaton** [mozilla/policy-templates#1075]
i have the allowed origins to https://* and doesnt work

**Comment by mkaply** [comment]
It must be explicit as an origin:

https://somesite.zoom.us

You can't do wildcards.

**Comment by Mrgaton** [comment]
but i want to acept all domains that use https

**Comment by mkaply** [comment]
> but i want to acept all domains that use https

Most sites use HTTPS now, so that wouldn't be a safe thing to do.

For security reasons, this policy is designed to make you choose the specific sites for which you allow allow protocols to be automatically launched. It's that way on all other browsers as well.
