### ISSUE TITLE
GPO Wish: Disable Hints

### ISSUE THREAD

**Issue by dihmandrake** [mozilla/policy-templates#108]
For most frequent users the hints are just a annoying, when they switch workstations. I would only need this policy as an enforced one, because I cannot think of an scenario, where a user wants to reenable hints.
`lockPref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);`

**Comment by havx** [comment]
Agreed. Yet I request the ability to disable hints entirely.

**Comment by mkaply** [comment]
We no longer have this feature. If there are other hints you need to disable, please open a separate issue. I'm looking at adding a policy to just disable all of these.
