### ISSUE TITLE
Pin deployed bookmarks to the start of the bookmark toolbar?

### ISSUE THREAD

**Issue by bvdo** [mozilla/policy-templates#1080]
Hi!

We would like to deploy a small set of intranet bookmarks relevant for daily work using GPOs.

Using the "Bookmark 01", Bookmark 02",... policies we can add those bookmarks to the end 
of the toolbar. That's fine for new profiles where they get added to the end of an empty toolbar.

As soon however as the users have added their own bookmarks to the toolbar and we feel the
need to modify our list of deployed bookmarks, things will get fuzzy... Bookmarks once deployed
to the empty profile will remain in front of the list while new additions to our list will get added
after the user bookmarks. 

Is there any other solution conceivable to this than the obvious one employing a subfolder?
Is there any possibility to assign fixed positions 1,2,3... on the toolbar to a deployed bookmark
so our list of bookmarks will remain at the front of the toolbar? Probably not but I thought I
should at least ask, hope dies last... ;-)

Cheers

**Comment by mkaply** [comment]
Take a look at the ManagedBookmarks policy.

https://mozilla.github.io/policy-templates/#managedbookmarks

That's more what you're looking for.

**Comment by bvdo** [comment]
Ooops, sorry! Seems I've been blind and only looked in the Bookmarks subfolder.
Using English manuals with German adml files can be confusing, will check that
other policy, thanks...

**Comment by mkaply** [comment]
Sorry, I totally missed this.

Unfortunately there is not. 

We copied Chrome on this and it made the most sense to have everything in a folder.
