### ISSUE TITLE
GPO Wish: Install language add-on's and specify default language

### ISSUE THREAD

**Issue by PDWDSVC** [mozilla/policy-templates#109]
it would be nice if we could specify which language add-ons need to be installed and what language is the default language for the interface

**Comment by Chartman123** [comment]
You can install the language add-ons with the "Extensions to install" policy. :)

However, adding the possibility to set the localization via GPO would be very nice, so that we don't have to change it manually with "about:config" and changing/setting the value of "intl.locale.requested".

**Comment by mkaply** [comment]
We've added this policy. It will be in ESR 60.4 and Firefox 64.
