### ISSUE TITLE
https-only mode and https-only exceptions

### ISSUE THREAD

**Issue by miharix** [mozilla/policy-templates#1091]
Hi,

Sorry for stupid question....

Where in this GPO can I find

force https-only mode
and
website exceptions for https-only mode

Since today (FF 125.0.1) we have problem that
 if website that is http (not https) and has a link for download (any file) it wont download because it report's as security issue.
The solution is if I manually add the (internal)website as exception under https-only mode exceptions.

**Comment by TheSin-** [comment]
you are looking for

Set dom.block_download_insecure to False

I'm here for the same reason but it doesn't seem to have a GPO, you can fix it by changing that option in about:config, but that's a localized fix.

**Comment by jonesiscoding** [comment]
I believe that that you can enable or disable both `dom.block_download_insecure` and `dom.security.https_only` within the [preferences](https://mozilla.github.io/policy-templates/#preferences). 

Currently, there does not seem to be a way to add a list of exceptions for either.

**Comment by TheSin-** [comment]
you can I figured it out yesterday using this.  Just need to remove the older Preferences and use the json version and it works.  I only did `dom.block_download_insecure`

**Comment by miharix** [comment]
So this need to be a request for repo of the browser directly ? Where exactly ?

When I saw this problem it reminded me,
 that it would be about time to push our company to https only and allow only centrally whitelisted http sites.
 
 I like the idea of mozila  pushing forward implementation of https, but not first enabling simple deplorable exceptions is not nice.

**Comment by tracktor-git** [comment]
> you can I figured it out yesterday using this. Just need to remove the older Preferences and use the json version and it works. I only did `dom.block_download_insecure`

Hi [TheSin-](https://github.com/TheSin-)
How can I do this with GPO? Can you wrote an example or screenshot of this setting in GPO? I tried but there was no any effect :( Maybe i use wrong format for the setting...

**Comment by miharix** [comment]
I created Bug https://bugzilla.mozilla.org/show_bug.cgi?id=1892658

@tracktor-git 
![slika](https://github.com/mozilla/policy-templates/assets/5471326/eaefa0fa-4746-4d03-bb0b-ba022ead5323)
User Configuration -> Administrative templates  -> Mozilla -> Firefox -> Policy -> Preferences
````
{
	"dom.block_download_insecure": {
	"Value": false,
	"Status": "locked"
	}
}
````

**Comment by tracktor-git** [comment]
@miharix thanks a lot! I used wrong JSON format...

**Comment by technomancer-101** [comment]
> So this need to be a request for repo of the browser directly ? Where exactly ?
> 
> When I saw this problem it reminded me, that it would be about time to push our company to https only and allow only centrally whitelisted http sites.
> 
> I like the idea of mozila pushing forward implementation of https, but not first enabling simple deplorable exceptions is not nice.

I agree, I think Mozilla needs to create a whitelist option as an alternative to the "all or nothing" approach. While we could in theory setup SSL for all of our intranet sites, it's a lot of overhead for services that really wouldn't benefit from the traffic encryption.

Unfortunately I'm also unsure how to go about this. I suppose https://connect.mozilla.org/ would be the best bet, and then we can all upvote it there.

**Comment by technomancer-101** [comment]
Thank you very much, that will be hugely beneficial.

**Comment by mkaply** [comment]
This was implemented
