### ISSUE TITLE
Bug: DNSOverHTTPS policy ignores other settings when "Locked": true is used.

### ISSUE THREAD

**Issue by EmerGen-AI** [mozilla/policy-templates#1096]
```
    "DNSOverHTTPS": {
      "Enabled":  false,
      "Locked":  true,
      "Fallback": false
    }
```

**Comment by EmerGen-AI** [comment]
Adding the above policy will lock DNSOverHTTPS settings to the default (Cloudflare DNS), rather than locking it to Disabled/Off.

**Comment by EmerGen-AI** [comment]
Ah, excellent. Much appreciated.

**Comment by mkaply** [comment]
Yeah, just to confirm what @qupig said, these are mapping to one preference behind the scenes which made thing kind of clunky.

If you're curious:

https://searchfox.org/mozilla-central/source/browser/components/enterprisepolicies/Policies.sys.mjs#1053
