### ISSUE TITLE
Remove deprecated keys in example templates?

### ISSUE THREAD

**Issue by qupig** [mozilla/policy-templates#1097]
This really confused new adopters, for example we have in the template:

```json
{
  "policies": {
    "Cookies": {
      "Allow": ["http://example.org/"],
      "AllowSession": ["http://example.edu/"],
      "Block": ["http://example.edu/"],
      "Default": true | false,
      "AcceptThirdParty": "always" | "never" | "from-visited",
      "ExpireAtSessionEnd": true | false,
      "RejectTracker": true | false,
      "Locked": true | false,
      "Behavior": "accept" | "reject-foreign" | "reject" | "limit-foreign" | "reject-tracker" | "reject-tracker-and-partition-foreign",
      "BehaviorPrivateBrowsing": "accept" | "reject-foreign" | "reject" | "limit-foreign" | "reject-tracker" | "reject-tracker-and-partition-foreign",
    }
  }
}
```

But in the [documentation](https://github.com/mozilla/policy-templates/blob/3b451bb4cb00354288bddb2e6f71d8a9cd9d8cbf/docs/index.md?plain=1#L1200-L1226) we don't describe all the keys.

Through my background knowledge, I know that there is a conflict between `Default`, `AcceptThirdParty`, `RejectTracker` and `Behavior`, I even need to doubt their priority because I think they all ultimately affect `network.cookie.cookieBehavior`.

But through more investigation, I found that they were once already marked as deprecated in the documentation:
[Remove deprecated policies from the documentation (they remain in the GPO templates)](https://github.com/mozilla/policy-templates/commit/ca0083999dee770d74eb458d73264c75f58fd81d)

If it were my choice, I might prefer to keep the deprecation description in the documentation for a while and remove those keys in the example templates, since that's probably where people will start editing and modifying.

Including them in the example templates without a deprecation flag really confuses newcomers. But the deal is done, and maybe all we can do now is remove those deprecated keys from the example templates as well, without confusing more people.

**Comment by mkaply** [comment]
That's a good callout. I'll put them back (and remove from the examples)

**Comment by mkaply** [comment]
Fixed!
