### ISSUE TITLE
Dead link in document `Adding policy support to your extension`

### ISSUE THREAD

**Issue by qupig** [mozilla/policy-templates#1104]
https://github.com/mozilla/policy-templates/blob/e6c67d8234573afdd95831b2f260421ca64ac8d8/docs/index.md?plain=1#L130

https://extensionworkshop.com/documentation/enterprise/adding-policy-support-to-your-extension/

> Do not delete - This page is gone but we need to keep the file for the redirect, see /.utils/setup-object-redirection.sh

**Comment by mkaply** [comment]
We're actually planning to deprecate those completely.

They only exist because we didn't originally have enterprise policy.

But the answer is that 3rdparty is read first and if found,  it is used unstead of the .json.
