### ISSUE TITLE
GPO Wish: dom.block_download_insecure

### ISSUE THREAD

**Issue by HashidaTKS** [mozilla/policy-templates#1105]
It seems that sometimes users should or want to disable `dom.block_download_insecure`.

E.g.

https://support.mozilla.org/en-US/questions/1445114

I know that we can specify `dom.block_download_insecure` with `Preferences`, but I think it would be more convenient if we could specify `dom.block_download_insecure` individually in a GPO.

**Comment by mkaply** [comment]
I'm not ready to give a policy yet for this as I'm hoping the bugs get fixed.

In addition, I'll be landing a policy to allow to the Https upgrade list.

**Comment by HashidaTKS** [comment]
@mkaply  Thank you for your reply!

Sorry for my ignorance, what will become when we specify a policy to allow to the Https upgrade list?
Is it used for control [HTTPS-Only Mode](https://support.mozilla.org/en-US/kb/https-only-prefs)'s exceptions?
Or it is something completely different?

**Comment by mkaply** [comment]
It will exclude from HTTPSOnly mode and any other place where we force HTTPS

This will be in Firefox 127  Firefox ESR 115.12

**Comment by HashidaTKS** [comment]
Thank you!

It seems fine for my(our) use case, so I'll close this issue.
