### ISSUE TITLE
`PasswordManagerEnabled` should also hide `Manage Passwords` menu

### ISSUE THREAD

**Issue by qupig** [mozilla/policy-templates#1109]
![图片](https://github.com/mozilla/policy-templates/assets/61939856/bd86a7cb-ebc4-4362-9316-1289291d2aa1)

In addition, its `Preferences Affected` description also needs to be updated.

**Comment by mkaply** [comment]
Doc updated and opened https://bugzilla.mozilla.org/show_bug.cgi?id=1906916 to track the fix.
