### ISSUE TITLE
GPO Wish: Block Access to file:///c:/

### ISSUE THREAD

**Issue by thesepix** [mozilla/policy-templates#111]
GPO to Block access to c: or file:///c:/
This is a Security Risk f.e. in RDS Environments.

**Comment by CarolPhelps** [comment]
Adding GPO support is great news for schools--but we second this comment. We need to prevent access to c: or file:///c:/

**Comment by aeaton29** [comment]
I work for a public library. It would be great to keep people from roaming around computers. Other browsers prevent this through GPO, it'd be great if we could lock down Firefox too.

**Comment by ravi76b** [comment]
How can we block file:/// protocol to prevent any access to local disk drive from the Firefox browser. Its blocked on all browsers except in Firefox.

**Comment by thorstenvogel** [comment]
+1

**Comment by JonathanPitre** [comment]
I've tried file:///c:/ with the Blocked websites user GPO and it does nothing.

Works fine with Chrome and MS Edge...

**Comment by mkaply** [comment]
This has been on our list for a while, but haven't gotten to it. I currently have it targeted for this quarter.

**Comment by JonathanPitre** [comment]
> This has been on our list for a while, but haven't gotten to it. I currently have it targeted for this quarter.

Awesome, thank you!

**Comment by joandriessen** [comment]
Mike, 

If posible, try to make a solution that we can block, for example, **file:///c:/** and **\\localhost\c$** and **file://///localhost/c$/** URI’s. But can freely use group shares such as **file:///g:/**

**Comment by mkaply** [comment]
I've never seen a file://///localhost URL. Is that a UNC path?

**Comment by rhandqkez07** [comment]
Hi,
I'm a colleague from joandriessen, hereby our answer to this question.

\\localhost\c$ is the original UNC path to a default share on Windows machines (admin share)
When this UNC is entered in the URL bar of Firefox, Firefox converts it to the file: URI with five slashes. 
This format is used deliberately by Mozilla, see https://bugzilla.mozilla.org/show_bug.cgi?id=107540#c31
FYI: Chromium and MS Edge Chromium (default installs) convert \\localhost\c$ to file://localhost/c$/ (2 slash format) and display the share.

We found out that a default install of ESR 52 can still display \\localhost\c$, but ESR68 and ESR78 give an error: “The file at ///localhost/c$/ is not readable”, in which the UNC path has one slash too many. 
This seems to be a separate Firefox bug in itself which could be fixed at some time, and then we want to be able to block this path for SBC users.

We want to make sure both local drive mapping and local admin share access can be blocked for users. 
So ie. A blocklist for file:///c:/ but also the admin share UNC/URI’s (\\localhost\c$, file://localhost/c$/ or file:////localhost/c$/)

Current Firefox behaviour:
\\localhost\c$                                  ->           file://///localhost/c$/ 
![1](https://user-images.githubusercontent.com/68916588/88692338-410f1700-d0fe-11ea-8b8c-96632ecdc518.jpg)
              

![2](https://user-images.githubusercontent.com/68916588/88692377-49675200-d0fe-11ea-9239-1609440e58bf.jpg)

**Comment by joandriessen** [comment]
Hi Mike, 
Any news regarding blocking the local drives?

**Comment by mkaply** [comment]
This is my last item for this quarter. I really plan to have something by end of September.

**Comment by moundam** [comment]
Hi Mike, Is there any update on blocking the local drives ?

**Comment by joandriessen** [comment]
Will be available in Firefox 83/Firefox ESR 78.5

**Comment by mkaply** [comment]
>Will be available in Firefox 83/Firefox ESR 78.5

Yes. You'll be able to use file:/// URLs in WebsiteFilter.

I'll close this once we ship.

**Comment by mkaply** [comment]
We finally have this via WebsiteFilter. It's in Firefox 83 and ESR 78.5 released today.

**Comment by rhandqkez07** [comment]
It works great. We still have one issue regarding this solution. The drives are still approachable through the view-source URI scheme.
view-source:file:///c:/

Could this also be blocked in WebsiteFilter?
Thanks

**Comment by mkaply** [comment]
Yes, I'm working on it so they get blocked automatically:

https://bugzilla.mozilla.org/show_bug.cgi?id=1465847

Having some testing issues.
