### ISSUE TITLE
Intune Policy for "Signon.autofillForms" missing?

### ISSUE THREAD

**Issue by JiPa2022** [mozilla/policy-templates#1113]
Hello, I would like to control the Password Autofill Function of Firefox without actually disabling the whole Password Manager. But I can´t find the policy here: https://mozilla.github.io/policy-templates/

Any Idea how to control it anyway?

**Comment by mkaply** [comment]
All of the signon.* preferences can be set with the Preferences policy.

https://mozilla.github.io/policy-templates/#preferences

You can also just turn off the "offer to save logins" feature:

https://mozilla.github.io/policy-templates/#offertosavelogins
https://mozilla.github.io/policy-templates/#offertosaveloginsdefault

**Comment by JiPa2022** [comment]
> I set it like this:
> 
> Name: `signon.autofillForms` `OMA-URI: ./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox/Preferences` Value: `<enabled/> <data id="JSON" value=' { "signon.autofillForms": { "Value": false, "Status": "locked" } }'/>` But it didn´t have any effect, any idea?

Found the issue, You need to remove all spaces for this to work.
