### ISSUE TITLE
`NetworkPrediction` and bug 1596935?

### ISSUE THREAD

**Issue by Jee-Hex** [mozilla/policy-templates#1125]
It would appear that [bug 1596935](https://bugzilla.mozilla.org/show_bug.cgi?id=1596935) changed what both `network.dns.disablePrefetch` and `network.dns.disablePrefetchFromHTTPS` control. They now only cover the `rel="dns-prefetch"` part of DNS prefetching and the rest is split into `dom.prefetch_dns_for_anchor_http_document` and `dom.prefetch_dns_for_anchor_https_document`.

Obviously I can just use the `Preferences` policy, but IDK if set-and-forget users would be aware of this change.

**Comment by mkaply** [comment]
I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1906917 for this since it will be fixed in Firefox.
