### ISSUE TITLE
[Help] How to add multiple URLs to Allowed Notification Policy?

### ISSUE THREAD

**Issue by Asinin3** [mozilla/policy-templates#1127]
I'm stumped on this policy 

The example given only shows how to add one url instead of the syntax for multiple entries:
`<enabled/>
<data id="Permissions" value="1&#xF000;https://example.org"/>`

 I've tried numerous methods on some of our Intune test devices but with the sync taking a few hours this was rather slow to test with. What's the solution here? And can the documentation please be updated so its more clear?

Thanks!

**Comment by mkaply** [comment]
Here's an example from another policy

<data id="Authentication" value="1&#xF000;mydomain&#xF000;2&#xF000;https://myotherdomain.com"/>

It's terrible Intune syntax.

I'll update that policy to have more than one so it's clear.

**Comment by mkaply** [comment]
I just pushed an update to the docs that show multiple strings.

**Comment by Asinin3** [comment]
Thanks, How do you do wildcards though?
E.g the below both examples wont work and needs the full URL.
`<data id="Permissions" value="1&#xF000;[*.]office.com&#xF000;2&#xF000;office.com"/>`
The [*.] method works for Chrome and Edge. https://techcommunity.microsoft.com/t5/microsoft-intune/chrome-policies-admx-ingestion-and-oma-uri-values/m-p/2216162

**Comment by mkaply** [comment]
We use origins instead of path globs.


So just doing https://office.com should cover office.com and all subdomains.

**Comment by Asinin3** [comment]
Thanks, not super intuitive as people wouldn't expect that to work with https://outlook.office.com, but good to know.

**Comment by mkaply** [comment]
I agree. We used to do it that way, but they switched to origins in Firefox unfortunately.
