### ISSUE TITLE
proxy setting problem

### ISSUE THREAD

**Issue by jandyf** [mozilla/policy-templates#113]
When trying to enable the "Proxy Settings" I set the connection type to any of the automatic or system settings and click OK I get a pop-up dialog saying "No value was entered for this field. Make sure that you enter a value.". I click OK and it doesn't highlight or jump to a field to let me know what is required. With the automatic I just entered a URL and it's still not happy.

**Comment by mkaply** [comment]
Unfortunately this is a bug in GPO. I mention it in the description of the policy:

"Select the connection type and then fill in the appropriate sections. Due to a bug, you must select a value for the SOCKS proxy version."
