### ISSUE TITLE
Documentation for FirefoxSuggest Policy has incorrect OMA-URI

### ISSUE THREAD

**Issue by ckennedy666** [mozilla/policy-templates#1134]
Hello.  The documentation at docs/index.md has incorrect OMA-URIs listed for all FirefoxSuggest policies.

`./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~FirefoxSuggest/WebSuggestions` is what is documented, but it should be `./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~FirefoxSuggest/FirefoxSuggest_WebSuggestions`.  This same error is repeated for all OMA-URIs under FirefoxSuggest.

**Comment by mkaply** [comment]
Thank you!
