### ISSUE TITLE
"Website Advertising Preferences: allow websites to perform privacy-preserving ad measurement" setting is not exposed in policy template

### ISSUE THREAD

**Issue by cinderbdt** [mozilla/policy-templates#1135]
I expected to be able to download the Windows ADMX and ADML files, place them into `Windows\PolicyDefinitions` folder, run `gpupdate /force`, then use Local Group Policy Editor (`gpedit.msc`) to turn off this setting in Firefox 128.
I also tried using the [Enterprise Policy Generator extension](https://addons.mozilla.org/en-US/firefox/addon/enterprise-policy-generator/) to create a `policies.json` file that included this setting, but that didn't work.
Please advise when this setting is exposed in the policy template, or how this can be done otherwise.
Is this because the setting is not exposed to policy at all? It isn't listed in the [policy templates](https://mozilla.github.io/policy-templates/) documentation.

**Comment by Mikaela** [comment]
This is a duplocate of https://github.com/mozilla/policy-templates/issues/1130 where it's pointed out that disabling telemetry disables that particular option internally regardless of it appearing enabled in the UI. https://github.com/mozilla/policy-templates/issues/1130#issuecomment-2232122261

**Comment by mkaply** [comment]
Yeah, #1130 has the info. We don't currently have a policyl
