### ISSUE TITLE
GPO not applying settings to 64-bit ESR 60.0.1 version 

### ISSUE THREAD

**Issue by Skwazi** [mozilla/policy-templates#114]
I`ve tryed admx files ver 1.0 and Firefox 60.0.1 x64. GPO settings are deployed to computers, i can find them on registry, but not applyed to Firefox.

With 32-bit version Firifox everything is OK.

**Comment by southpaw386** [comment]
To install you simply add the ADMX / ADML files to your central store in their respective spots.  Install Firefox version 60 or higher on the targets.  Configure a GPO.  And that's it right?  Am I missing anything?  I did all the steps I mention and it is not working with Firefox ESR v60.   I recently added Chrome ADMX files and they work fine, but not having luck with Firefox :(

**Comment by sskmadmin** [comment]
Hi,
ADMX / ADML files V1.0 are installed in our central store (Domain)
Windows 7 Client:
Some entries are not pushed througt. Homepage, NoUpdate and any other. Proxy Setting works.
Server 2012 R2:
All GPO entries works very well. 
Has anybody an idea?

Firefox 60.0.1 x64 ESR - Windows 7 Build 1709:SP1

**Comment by mkaply** [comment]
sskmadmin: Are you sure you are using the ESR? The policies you have listed are the ones that don't work on rapid release. Please go to the about dialog and verify it says esr.

**Comment by sskmadmin** [comment]
mkaply: Thank you for the advice. I have used the standard version V60 on Win7.
Everything works fine with the ESR version.

**Comment by mkaply** [comment]
Are you sure you are using the ESR? Some of the problems you are seeing happen if you are not using the ESR.

**Comment by mkaply** [comment]
Can you please turn on logging and see if there are errors in the console?

To do this, go to about:config, add a new strign preference:

browser.policies.loglevel

and set the value to "debug"

**Comment by southpaw386** [comment]
mkkaay, mkaply.  I enabled debugging.  Sorry but I'm not super familiar with where to find those debug logs.

I did discover **about:support**  which you can also get there by going to **Help > Troubleshooting** info.  This is a neat area as you can scroll down to **Important Locked Preferences**  and easily see / verify some of the hard setting that you pushed.

**Comment by mkaply** [comment]
Ctrl+Shift+J will show the browser console which will have logging.

**Comment by tgrisel** [comment]
Even if GPO-setting seems to be correct. If a user sets "do not search for updates" it won't be corrected.
We don't want that a user can switch updates off.

![disableappupdate](https://user-images.githubusercontent.com/39399700/40348680-a6469762-5da4-11e8-922c-8f4d3996eae3.PNG)

**Comment by mkaply** [comment]
It looks like you have DisableAppUpdate set to disable instead of enable? It's showing a 0 in the registry when it should be a 1.

**Comment by tgrisel** [comment]
mkaply: Yes, thats right. I want to prevent users from turning off automtic updates. Normally, a gpo-setting works that way. Is there any possibility to lock this setting?

**Comment by mkaply** [comment]
We didn't anticipate that behavior. I'll see if we can add it.

**Comment by mkaply** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1467603

**Comment by mkaply** [comment]
We have this now. In the Preferences policy, you can lock app.update.auto to true.
