### ISSUE TITLE
GPO Wish - Extension whitelist

### ISSUE THREAD

**Issue by rumpeltizkin** [mozilla/policy-templates#115]
I'm working with GPO's for a week now and they are very nice but I miss something really useful from Chrome policies, a whitelist of extensions that can be installed.

Can it be implemented to allow users to optionally install only a few if they need?, we have different departments at the office and creating this through GPO's is a hell since inside every department there are users that need some extensions and others different ones. It's way easier to allow only the extensions everyone together need and each person installs the ones they need by themselves.

Thank you! :)

**Comment by mkaply** [comment]
This is definitely on the list. Hadn't figured out how to implement yet.

**Comment by rumpeltizkin** [comment]
great! I'm eager to see policies template  v1.1 soon :)

Thank you very much for your work!

**Comment by mattpwhite** [comment]
Hi, just wanted to chime in and say that this is a critical feature for us to switch from autoconfig to policy templates.  We'd actually gone as far as writing our own mechanism using the AddOnManager API to hook extension installation to validate against a whitelist.  We're going to have to downgrade our fleet to the last ESR or remove everyone's extensions until this is implemented with policies.

The comparable Chromium policy is more or less what we're looking for: https://www.chromium.org/administrators/policy-list-3#ExtensionInstallWhitelist

With both Chrome and Firefox with our custom autoconfig we were able to:

- A couple extensions to be automatically installed for everyone.
- A much larger list of extensions that users are allowed to self-service install using the normal extension installation mechanisms (about:addons, addons.mozilla.org).
- Installed extensions automatically update from addons.mozilla.org.
- Existing installed extensions are removed if not present on the force install list or whitelist.

And thanks for all your work to make Firefox usable in the enterprise over the years.

**Comment by rumpeltizkin** [comment]
Yeah, I'm in the same situation, but I made a different mechanism to avoid people installing extensions. I blocked all of them and allowed only manual installation by administrator. Then, I elaborated a script mechanism to push the extension I want to all the configured destinations. They only need to close and open Firefox to have a green popup in the menu bar that a new extension was added. I also disabled part of the internal pages of Firefox through configuration files in order to block the users to disable / enable / update / remove or enter in the options / about page of the extensions, it only shows what extensions are loaded.

Although it is a lot of fun to play with Firefox because it is by far much more customizable than Chrome, I feel the lacking of some critical policies like this one. I hope they arrive sooner than later :)

**Comment by mattpwhite** [comment]
Any update here?  We’re still stuck on ESR 60 and autoconfig due to this issue (and only this issue).

I really don’t want to pull Firefox off of > 5000 machines and become a Chrome only shop.  If this isn’t implemented (and autoconfig is sandboxed in the next ESR), that’s what I’ll have to do.

**Comment by rumpeltizkin** [comment]
I guess no. The last policy updates hadn't had many new features, I think we will have to stick with the "hard" way for a long time.

**Comment by mkaply** [comment]
Autoconfig will not be sandboxed on the next ESR.

And I am working on whitelisting.

And we are actively working on new policies.

**Comment by mattpwhite** [comment]
Thanks, that’s a relief to hear.

**Comment by mkaply** [comment]
FYI, I'm following Chrome's lead here:

https://dev.chromium.org/administrators/policy-list-3/extension-settings-full

This should give all these features. Let me know what you think.

**Comment by mattpwhite** [comment]
Wow, that's a lot more than I was expecting, especially in an initial implementation.  If you implement something that looks like Chrome's extension policy, that would be great and more than cover our requirements.  If it's helpful, here's the minimum we need to move off of autoconfig:

* Specify extensions to be automatically installed by ID.  These extensions are automatically installed from addons.mozilla.org.  This affects new and existing profiles.
* Specify extensions that users can install for themselves from addons.mozilla.org on a whitelist.  If a previously allowed extension is removed from this list, it is removed from existing profiles.
* When users try to install an extension that is not on the whitelist, they get a message saying it's blocked by policy and asking them to contact an administrator.  Bonus points if we can provide a custom string for this.
* Extensions (both the force installed ones and the user installed ones) automatically stay up to date.

This roughly corresponds to Chrome's "legacy" extensions policy.  Their newer system can do all of that too, but it can also do quite a bit more.  The legacy Chrome extensions policy is what we roughly re-implemented in autoconfig with a bunch of callbacks on AddOnManager.  The additional features in Chrome's newer extensions policies are great/useful, but above and beyond the minimum we'd need to make the jump from autoconfig to Firefox policies.

**Comment by cjake2299** [comment]
I'd love to see something along the lines of Chrome's extension policy as well. Following in hopes this is something that is ready to test relatively soon.

**Comment by rumpeltizkin** [comment]
nice!, I hope to be able to test it soon, it seems promising :).

Thank you very much for your effort!

**Comment by linh3301** [comment]
Definitely glad to see this is coming along. It's a big reason we haven't fully deployed FF.

**Comment by mkaply** [comment]
This is now available in beta, but only via JSON. (I'm working on the GPO).

It will be similar to Google where you have to paste a JSON blob.

**Comment by mkaply** [comment]
This is in the new ExtensionSettings policy

https://github.com/mozilla/policy-templates#extensionsettings

**Comment by sjd4** [comment]
Maybe I'm missing something, but is there a GPO policy that we can test with?  The current ones do not contain installation_mode.  I've read there is a bug with Firefox 68 [https://github.com/mozilla/policy-templates#extensionsettings](url).  It just doesn't seem like this issue is resolved yet.  Sorry if I'm bringing this back up if it's truly ready, but I'm itching to use this.  Especially in light of dataspii.

**Comment by mkaply** [comment]
Sorry, the fix made it into 68, but I haven't updates the templates. Doing that now.

**Comment by mkaply** [comment]
Made it into 68.0.1

**Comment by mkaply** [comment]
https://github.com/mozilla/policy-templates/releases/tag/v1.8.1

**Comment by sjd4** [comment]
I tried them and I’m getting an error opening gpedit.msc:

Invalid value ‘1.6.1’ for attribute revision.
File C:\WINDOWS\PolicyDefinitions\firefox.admx, line 2, column 56

________________________________

**Comment by mkaply** [comment]
Sorry about that. I assumed Windows supported that style revisions. New zip is up. Same release
