### ISSUE TITLE
Add "Weather" to FirefoxHome

### ISSUE THREAD

**Issue by corobin** [mozilla/policy-templates#1154]
[FirefoxHome](https://mozilla.github.io/policy-templates/#firefoxhome) has settings for the new tab page content. Firefox 130 added a Weather section. It does not currently have a corresponding policy in FirefoxHome. Thanks.

**Comment by mkaply** [comment]
Who doesn't want the weather? :)

**Comment by mkaply** [comment]
I've opened a bugzilla bug for this.

It will be handled there

https://bugzilla.mozilla.org/show_bug.cgi?id=1919387

**Comment by corobin** [comment]
@mkaply i see that this is targeting  152, but it looks like the new weather widget in 151 is now associated with a different pref:

`browser.newtabpage.activity-stream.widgets.weather.enabled`

and this is not weather, but might as well mention that there's also a new checkbox that doesn't have a policy

`browser.newtabpage.activity-stream.showSponsoredCheckboxes`

<img width="673" height="89" alt="Image" src="https://github.com/user-attachments/assets/03116827-fb97-48c4-b68c-daa793fce469" />
