### ISSUE TITLE
Disable Monitor in Firefox Accounts

### ISSUE THREAD

**Issue by AtomixAlpha** [mozilla/policy-templates#1158]
Need support to disable **identity.fxaccounts.toolbar.pxiToolbarEnabled.monitorEnabled** in **Preferences** section.

![image](https://github.com/user-attachments/assets/57664068-fcb4-4ccd-82e7-ade76cb6d550)

I get the following error when I add it in **Preferences** section. I don't think there is stability reason for this policy.

![image](https://github.com/user-attachments/assets/67069a24-5a6a-481a-afed-56b92c003b69)

**Comment by mkaply** [comment]
Great call out. I've opened a bugzilla bug

https://bugzilla.mozilla.org/show_bug.cgi?id=1922329
