### ISSUE TITLE
`AppUpdatePin` constantly shows error ` -2016281112`

### ISSUE THREAD

**Issue by AnonymousX86** [mozilla/policy-templates#1163]
Recently I've prepared deployment plan for Firefox v131.0.3. I've followed official docs and prepared installer and configuration accordingly.

I'd like to apply minor versions only (do not apply major updates).

Install script:
```cmd
msiexec /i "Firefox Setup 131.0.3.msi" TASKBAR_SHORTCUT=true DESKTOP_SHORTCUT=true START_MENU_SHORTCUT=true PRIVATE_BROWSING_SHORTCUT=false INSTALL_MAINTENANCE_SERVICE=true PREVENT_REBOOT_REQUIRED=true OPTIONAL_EXTENSIONS=false /quiet /log "%TEMP%\Install-MozillaFirefoxEnterprise.log"
```

Microsoft Intune Device Configuration includes:
- `OfferToSaveLogins`
- `WindowsSSO`
- `PasswordManagerEnabled`
- `AppAutoUpdate`
- `AppUpdatePin`

Firefox installs properly, and all policies apply, except for the last one.

## Details:

OMA-URI:

```plaintext
./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox/AppUpdatePin
```
Value:

```xml
<enabled/>
<data id="AppUpdatePin" value="131."/>
```

## Screenshot

![image](https://github.com/user-attachments/assets/8fd838bb-8de6-4610-b188-cd2ec2605353)

**Comment by mkaply** [comment]
Everything I see online says it's an Intune bug that can be ignored.

https://www.reddit.com/r/Intune/comments/fgcx11/bitlocker_intune_2016281112_remediation_failed/

If you go to about:policies, is it set?

**Comment by AnonymousX86** [comment]
Forgot to put that screenshot.
![image](https://github.com/user-attachments/assets/f4b6e949-3b9a-4185-be66-a6688d85c59a)
`AppUpdatePin` is missing,

**Comment by mkaply** [comment]
Can you try changing it to:

```
<enabled/>
<data id="String" value="131."/>
```

**Comment by AnonymousX86** [comment]
Changing the value worked.
![image](https://github.com/user-attachments/assets/0727baa0-7991-4a61-82bd-6aad4a4d7148)
![image](https://github.com/user-attachments/assets/3a1e1a58-430a-4272-a136-3f9307564ebd)
Should I open a PR for this?

**Comment by mkaply** [comment]
I already fixed the docs. Thanks for finding this and sorry that I didn't catch it.
