### ISSUE TITLE
Feature Request: Policy To Disable Firefox Translation Feature For A Certain Website

### ISSUE THREAD

**Issue by niemalsnever** [mozilla/policy-templates#1164]
Hello, 
I'm not quite sure if this request would be better suited in the Bugzilla bug tracker. If so, I'd be willing to post it there instead. 

I would like to kindly ask you to provide a policy that allows specifying websites for which no automatic translation should ocurr. My reason being that just about everyone in my organization uses a certain web app that is falsely detected as English. Unfortunately Firefox fails to translate the (not at all English) website, if our users have automatic translation for English enabled. This leads to rendering issues in the web app. Therefore it would be a huge help, if we were able to centrally tell Firefox not to automatically translate that web app.

We are running Firefox 128.3.1 ESR at the moment.

**Comment by mkaply** [comment]
Most of the time when this happens, it's because the language code in the HTML says it's English when it's not.

I'd love to try to figure out what's actually happening. Would you mind opening a bug here:

https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Translations

**Comment by mkaply** [comment]
I'm going to close this here and we'll handle it in bugzilla. Thanks!

**Comment by mkaply** [comment]
So there is site specific translation enablement, just not in policy.

I added a bug for it here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1927581
