### ISSUE TITLE
ExtensionSettings documentation

### ISSUE THREAD

**Issue by soldevi** [mozilla/policy-templates#1168]
Request to update the documentation to include that you need to provide the extension ID with curly brackets. I could probably do so myself, but I'm not sure how this would reflect on the other parts such as the Intune / MacOS parts. For ADMX Windows it's like this,

example Bitwarden

  "{446900e4-71c2-419f-a6a7-df9c091e268b}": {
    "installation_mode": "allowed",
    "install_url": "https://addons.mozilla.org/firefox/downloads/latest/bitwarden-password-manager/latest.xpi" # using extension ID, needs curly brackets!
  },

I've been pulling my hair out for the last two days trying to figure out why my gpo wasn't working. Curly brackets! For extensions with _normal_ IDs, the curly brackets are not necessary/needed. But for hashed IDs, apparently they do. This addon helped me get stuff right. > https://github.com/mkaply/queryamoid/releases/

**Comment by mkaply** [comment]
Thanks, I updated the docs.
