### ISSUE TITLE
GPO wishlist: Security

### ISSUE THREAD

**Issue by arlt** [mozilla/policy-templates#117]
Please implement the following GPO settings:

lockPref("security.default_personal_cert", "Ask Every Time"); // default
lockPref("security.enable_java", false); // exists?
lockPref("security.enable_md5_signatures", false); // exists?
lockPref("security.enable_ssl2", false);
lockPref("security.enable_ssl3", false);
lockPref("security.enable_tls", true);
lockPref("security.ssl.require_safe_negotiation", true);
lockPref("security.ssl.treat_unsafe_negotiation_as_broken", true);
lockPref("security.ssl3.dhe_rsa_aes_128_sha", false);
lockPref("security.ssl3.dhe_rsa_aes_256_sha", false);
lockPref("security.ssl3.rsa_des_ede3_sha", false);
lockPref("security.ssl3.rsa_aes_128_sha", false);
lockPref("security.ssl3.ecdhe_rsa_aes_128_sha", false);
lockPref("security.ssl3.ecdhe_ecdsa_aes_128_sha", false);
lockPref("security.ssl3.ecdhe_ecdsa_aes_256_sha", false);
lockPref("security.ssl3.ecdhe_rsa_aes_256_sha", false);
lockPref("security.ssl3.rsa_aes_256_sha", false);
lockPref("security.tls.insecure_fallback_hosts.use_static_list", false); // exists?
lockPref("security.tls.unrestricted_rc4_fallback", false); // exists?
lockPref("security.tls.version.min", 3);
lockPref("security.warn_entering_weak", true); // exists?
lockPref("security.warn_submit_insecure", true); // exists?
lockPref("security.warn_viewing_mixed", true); // exists?

lockPref("browser.safebrowsing.enabled", true); // exists?
lockPref("browser.safebrowsing.malware.enabled", true);
lockPref("media.peerconnection.enabled", false);
lockPref("webgl.enable-debug-renderer-info", false);

(I am not sure if all these settings affect something with the newest ESR, but hopefully you can enlighten me :-).)

**Comment by jjurkus** [comment]
lockPref("security.enable_java", false); doesn't exist. Java is a plugin, the setting is^H^Hwas pref("plugin.state.java", 2); with ESR52.

pref("media.peerconnection.enabled", false); (webRTC) is still in, I would like this too for my corporate users.

**Comment by Conan1989** [comment]
chiming in to vote up this request

particularly:
security.ssl.require_safe_negotiation
security.ssl.treat_unsafe_negotiation_as_broken

**Comment by asadotzler** [comment]
for security.tls.version.min see issue #283

**Comment by mkaply** [comment]
At this point, we've made many of these available, so I'm not going to go through the list. If you have specific requirements, open a new issue for the specific pref.

https://github.com/mozilla/policy-templates/blob/master/README.md#preferences
https://github.com/mozilla/policy-templates/blob/master/README.md#disabledciphers
