### ISSUE TITLE
media.eme.playready.enabled

### ISSUE THREAD

**Issue by corobin** [mozilla/policy-templates#1171]
The [EncryptedMediaExtensions](https://mozilla.github.io/policy-templates/#encryptedmediaextensions) affects the `media.eme.enabled` pref.

It does not affect the `media.eme.playready.enabled` pref.

Does that pref also need to be toggled, or does the `media.eme.enabled` pref already disable DRM completely?

**Comment by mkaply** [comment]
media.eme.enabled disables DRM completely.

**Comment by corobin** [comment]
thanks!
