### ISSUE TITLE
GPO wishlist: Extend "Authentication"

### ISSUE THREAD

**Issue by arlt** [mozilla/policy-templates#118]
Please implement the following GPO settings:

pref("network.automatic-ntlm-auth.allow-non-fqdn", true);
pref("network.negotiate-auth.allow-non-fqdn", true);

**Comment by jjurkus** [comment]
Huh?

My autoconfig has these settings:
pref("network.automatic-ntlm-auth.trusted-uris", ".domain.tld");
pref("network.negotiate-auth.trusted-uris", ".domain.tld");
pref("network.negotiate-auth.delegation-uris", ".domain.tld");

I have never needed the settings you name. Can you give me an example when it is needed?

**Comment by arlt** [comment]
It trusts the hostname if it is found in your domain search list. So you can use https://intranet instead of https://intranet.domain.tld

**Comment by EvilerBetty** [comment]
Yes, just ran into this today.  Without this setting, internal websites that are not configured with a FQDN will not authenticate (pop-up for credentials).

Does the policy exist today via the registry (just missing from the ADMX), or is this something not yet implemented?

**Comment by mkaply** [comment]
This is being implemented here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1471651

Pull request for GPO Changes is here:

https://github.com/mozilla/policy-templates/pull/180

**Comment by mkaply** [comment]
This was fixed in Firefox 62/Firefox ESR 60.2.
