### ISSUE TITLE
Homepage GPO

### ISSUE THREAD

**Issue by amaccuish** [mozilla/policy-templates#12]
The homepage GPO is confusing, it provides a textbox to enter one URL, but this is not sufficient, you then have to go into the list provided and write it in again. Is there a reason for this duplication? Cheers

**Comment by mkaply** [comment]
You shouldn't have to put any URLs in the list. That's only if you have more than one URL you want to use for a start page.

Just putting a URL in the textbox should be enough. Is that not working for you?

**Comment by amaccuish** [comment]
No. Trying to exit the dialog displays an error. I've looked through the admx and don't see anything immediately wrong...

![bildschirmfoto 2018-03-14 um 22 49 23](https://user-images.githubusercontent.com/9434795/37427274-f7b5c196-27d9-11e8-8ce7-75e8341d063d.png)
![bildschirmfoto 2018-03-14 um 22 49 14](https://user-images.githubusercontent.com/9434795/37427276-fa919f84-27d9-11e8-8245-64c7ffef737e.png)

**Comment by mkaply** [comment]
Odd. It shouldn't be required. I'll take a look.

**Comment by mkaply** [comment]
It looks you can't do what I was trying to do. I'm going to move Homepage to a top level category and make additional pages a separate item. Thanks for letting me know.

**Comment by amaccuish** [comment]
No worries. If I remember correctly, Chrome has one policy in which you decide the homepage url. Then there are two other policies, action on startup where you pick between start with new tab page, restore session, or open list of urls. You then fill in in the last policy the list of urls, where you can just put 1. So there's one policy for the homepage (i.e. the button), and then 2 separate ones controlling startup. :)

**Comment by mkaply** [comment]
I just pushed new files for this.

https://raw.githubusercontent.com/mozilla/policy-templates/master/windows/firefox.admx
https://raw.githubusercontent.com/mozilla/policy-templates/master/windows/en-US/firefox.adml

**Comment by amaccuish** [comment]
Cheers! Works great!

**Comment by mkaply** [comment]
I'm reopening because I should have done a proper branch.

**Comment by sonnenx** [comment]
Hej,

Could you push these files in ZIP file? 
Thanks in advance

**Comment by mkaply** [comment]
I have a version here:

https://github.com/mozilla/policy-templates/releases

I'll work towards pushing regular zip file updates.

**Comment by amaccuish** [comment]
@sonnenx you can download the master or at any commit from the project homepage?

**Comment by sonnenx** [comment]
@amaccuish ,
Files downloaded from https://github.com/mozilla/policy-templates/tree/master/windows
cause an error https://github.com/mozilla/policy-templates/issues/10
Files distributed in .zip work correctly.

**Comment by amaccuish** [comment]
@sonnenx if you look at the homepage of the project (https://github.com/mozilla/policy-templates), click the "Clone/Download" and then "Download ZIP". This enables you to get up to date templates between releases.
