### ISSUE TITLE
GPO wishlist: Reporting

### ISSUE THREAD

**Issue by arlt** [mozilla/policy-templates#121]
Please implement the following GPO settings:

lockPref("extensions.getAddons.cache.enabled", false);
lockPref("datareporting.healthreport.logging.consoleEnabled", false);
lockPref("datareporting.healthreport.service.enabled", false);
lockPref("datareporting.healthreport.service.firstRun", false);
lockPref("datareporting.policy.dataSubmissionEnabled.v2", false);
lockPref("toolkit.telemetry.archive.enabled", false);
lockPref("toolkit.telemetry.server", '');
lockPref("toolkit.telemetry.unified", false);

**Comment by mkaply** [comment]
There's no need to set these individual preferences. We allow turning off telemetry and turning off the addons manager.

**Comment by arlt** [comment]
We had some problem with archive folders from pings - this is what i remember. These where getting bigger and bigger. A quick check showed that toolkit.telemetry.archive.enabled is still true even if telemetry is diabled.

**Comment by zim333** [comment]
Hello,
I agree with @arlt .
We are using roaming profiles and those folder have a negative impact on opening/closing account session.
It have a negative impact too when we must backup the server that store roaming profiles as there are a huge amount of small files (that we do not need) to read.

Anyway, why mozilla do not "move" those folders on "local" (C:\Users\<username>\AppData\Local\Mozilla\Firefox\Profiles\xxxxxx.default\) like "OfflineCache" folder ?

Thank you

**Comment by arlt** [comment]
@zim33 yes, a local folder would be better but no files is the best :-).

**Comment by velosol** [comment]
@mkaply Is there still no need to set individual prefs?  The STIG was updated in July to call for setting & locking things like `toolkit.telemetry.archive.enabled` which doesn't seem to be set/locked by the 'Disable Telemetry' policy.  I'm willing to file change requests with DISA but need a little backup that the preferences they want set & locked are not necessary when using a policy setting.

Current STIG: https://dl.dod.cyber.mil/wp-content/uploads/stigs/zip/U_MOZ_FireFox_V4R29_STIG.zip
Listing of current STIGs: https://public.cyber.mil/stigs/downloads/

**Comment by mkaply** [comment]
We're adding the ability to set a lot more prefs. toolkit.* is not on the list - I'll get it added.

I'm thoroughly confused by the update to the STIG though. I'm literally in the middle of getting the STIG updated and having it be managed by Mozilla (I'm working with DISA)

I'll get this preference added to the telemetry disable as well.

**Comment by mkaply** [comment]
So toolkit.* has too much to add it globally. I'm just adding toolkit.telemetry.archive.enabled to DisableTelemetry:

https://bugzilla.mozilla.org/show_bug.cgi?id=1665670

**Comment by velosol** [comment]
Thank you @mkaply, I appreciate it and wish I could provide any insight into DISA's confusing actions but failing that I'll say you're doing a great job and the resources you have out there for policy management of Firefox are really helpful.

**Comment by mkaply** [comment]
Thanks. I'm in contact with them to figure out. And FYI, that bug went in and will go into the ESR.

I'm going to go ahead and close this since the fix will be in the next Firefox, and these other prefs are in the new PReferences policy.
