### ISSUE TITLE
GPO wishlist: User experience

### ISSUE THREAD

**Issue by arlt** [mozilla/policy-templates#122]
Please implement the following GPO settings:

lockPref("browser.newtabpage.enhanced", false); // exists?
lockPref("browser.newtabpage.introShown", true);
lockPref("browser.rights.3.shown", true);
lockPref("browser.search.showOneOffButtons", false);
lockPref("browser.selfsupport.url", "");
lockPref("browser.slowStartup.maxSamples", 0);
lockPref("browser.slowStartup.notificationDisabled", true);
lockPref("browser.slowStartup.samples", 0);
defaultPref("browser.backspace_action", 0);
lockPref("experiments.enabled", false);
lockPref("extensions.getMoreThemesURL", ""); // exists?
lockPref("general.warnOnAboutConfig", true);
lockPref("network.http.speculative-parallel-limit", 0);
defaultPref("places.history.enabled", true);

See also #88 

(I am not sure if all these settings affect something with the newest ESR, but hopefully you can enlighten me :-).)

**Comment by mkaply** [comment]
Those two newtabpage prefs are no longer needed, nor is the rights.3 shown.

I'm curious as to why you turn off the one off buttons?

browser.selfsupport.url is no longer used.

browser.backspace_action already defaults to 0 on Windows. What patform are you on?

"extensions.getMoreThemesURL" - are you disabling the addons manager?

general.warnOnAboutConfig - Do you disable about:config? I'm curious why you would always show the warning

network.http.speculative-parallel-limit - what's the goal here?

places.history.enabled - we are plannning to add this.

**Comment by arlt** [comment]
>Those two newtabpage prefs are no longer needed, nor is the rights.3 shown.
>browser.selfsupport.url is no longer used.
>places.history.enabled - we are plannning to add this.

Thanks.

>"extensions.getMoreThemesURL" - are you disabling the addons manager?

Yes but as you mentioned in another issue: This is covered with the GPOs.

>general.warnOnAboutConfig - Do you disable about:config? I'm curious why you would always show the warning

Counter question: Why has firefox this option? ;-)

>network.http.speculative-parallel-limit - what's the goal here?

From https://www.privacy-handbuch.de/handbuch_21n.htm:
> Firefox starts loading web pages in some situations when the mouse pointer is over a link, before you actually click. This should speed up the loading of web pages by a few milliseconds. If you want to avoid connections with unwanted web servers, you can disable the feature under "about:config": 

>browser.backspace_action already defaults to 0 on Windows. What patform are you on?

Yes - there where days with other defaults. I will remove it.

>I'm curious as to why you turn off the one off buttons?

Historical, too (https://support.mozilla.org/de/questions/1099139) - i will remove it.

**Comment by arlt** [comment]
after a cleanup these remain:

lockPref("browser.slowStartup.maxSamples", 0);
lockPref("browser.slowStartup.notificationDisabled", true);
lockPref("browser.slowStartup.samples", 0);
lockPref("experiments.enabled", false);
lockPref("network.http.speculative-parallel-limit", 0);
> Firefox starts loading web pages in some situations when the mouse pointer is over a link, before you actually click. This should speed up the loading of web pages by a few milliseconds. If you want to avoid connections with unwanted web servers, you can disable the feature under "about:config":

**Comment by mkaply** [comment]
All the browser and network policies are in the new preferences policy:

https://github.com/mozilla/policy-templates/blob/master/README.md#preferences

experiments.enabled isn't used anymore.
