### ISSUE TITLE
 GPO wishlist: Tools

### ISSUE THREAD

**Issue by arlt** [mozilla/policy-templates#123]
Enable/disable all additional Tools like sync, pocket, screenshots, social*, addons(available), ...

Please implement (e.g.) the following GPO settings:

lockPref("devtools.webide.autoinstallADBHelper", false);
lockPref("devtools.webide.autoinstallFxdtAdapters", false); // exits?
lockPref("devtools.webide.enabled", false);
lockPref("extensions.getAddons.get.url", "");
lockPref("extensions.getAddons.getWithPerformance.url", ""); // exists?
lockPref("extensions.getAddons.search.browseURL", "");
lockPref("extensions.getAddons.search.url", ""); // exists?
lockPref("extensions.getMoreThemesURL", ""); // exists?
lockPref("extensions.webservice.discoverURL", ""); 
lockPref("services.sync.addons.trustedSourceHostnames", "");
lockPref("services.sync.jpake.serverURL", ""); // exists?
lockPref("services.sync.serverURL", ""); // exists?
lockPref("services.sync.statusURL", ""); // exists?
lockPref("services.sync.syncKeyHelpURL", ""); // exists?
lockPref("services.sync.autoconnect", false); // exists?
lockPref("services.sync.engine.addons", false);
lockPref("services.sync.engine.apps", false); // exists?
lockPref("services.sync.engine.bookmarks", false);
lockPref("services.sync.engine.history", false);
lockPref("services.sync.engine.passwords", false);
lockPref("services.sync.engine.prefs", false);
lockPref("services.sync.engine.tabs", false);
lockPref("social.directories", "");
lockPref("social.manifest.facebook", "");
lockPref("social.remote-install.enabled", false);
lockPref("social.toast-notifications.enabled", false);
lockPref("social.whitelist", "");

(I am not sure if all these settings affect something with the newest ESR, but hopefully you can enlighten me :-).)

**Comment by mkaply** [comment]
None of these sync preferences are necessary individually. Disabling sync via the policy disables all sync.
Social has been completely removed.
Disabling devtools means you shouldn't need to disable those specific preferences.
And if you disable about:addons completely, you shouldn't need to disable any of those addon prefs.

**Comment by arlt** [comment]
>None of these sync preferences are necessary individually. Disabling sync via the policy disables all sync.
>Social has been completely removed.
>Disabling devtools means you shouldn't need to disable those specific preferences.

Thanks

> And if you disable about:addons completely, you shouldn't need to disable any of those addon prefs.

The new setting "Allow add-on installs from websites" is deactivated but "Block Add-ons Manager" is deactivated, too. Is this fine to remove all extensions.xyz settings?

**Comment by mkaply** [comment]
> Block Add-ons Manager" is deactivated, too. Is this fine to remove all extensions.xyz settings?

Yes, none of those would apply.

I think I'm going to close this issue, since these are covered or not used anymore.
