### ISSUE TITLE
GPO wishlist: Media

### ISSUE THREAD

**Issue by arlt** [mozilla/policy-templates#124]
Please implement the following GPO settings:

lockPref("media.gmp-eme-adobe.enabled", false); // exists?
lockPref("media.gmp-gmpopenh264.enabled", false); // due to download
lockPref("media.gmp-widevinecdm.enabled", false); // due to download

(I am not sure if all these settings affect something with the newest ESR, but hopefully you can enlighten me :-).)

**Comment by jjurkus** [comment]
lockPref("media.gmp-eme-adobe.enabled", false); doesn't seem to exist.
lockPref("media.gmp-gmpopenh264.enabled", false); I don't see this, but it might be a setting that exists, but not there by default

In ESR52 I have this setting:
pref("media.eme.enabled", false);
This disables widevine, but openh264 is still there.

**Comment by arlt** [comment]
According to https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js the exist.

An extract:

```
// disable Adobe EME "Primetime CDM" (Content Decryption Module)
user_pref("media.gmp-eme-adobe.enabled", false);
// This is the bundled codec used for video chat in WebRTC
user_pref("media.gmp-gmpopenh264.enabled", false); // (hidden pref)
// disable widevine CDM (Content Decryption Module) [SETUP]
user_pref("media.gmp-widevinecdm.enabled", false);
```

**Comment by jjurkus** [comment]
The first one exists, but under the "9999: DEPRECATED / REMOVED / LEGACY / RENAMED" header.

With the rest of those settings you are right, tough.

**Comment by mkaply** [comment]
This has been added with our new Preferences policy in Firefox 68.
