### ISSUE TITLE
GPO wishlist: CAPS

### ISSUE THREAD

**Issue by arlt** [mozilla/policy-templates#125]
We use e.g.:

lockPref("capability.policy.policynames", "internal");
lockPref("capability.policy.internal.sites", "https://fqdn1 ...");
lockPref("capability.policy.internal.checkloaduri.enabled", "allAccess");

Nice would be an unlimited list of policynames, sites with the ability to configure checkloaduri, Window.open, ... - see https://www-archive.mozilla.org/projects/security/components/ConfigPolicy.html

**Comment by mkaply** [comment]
The only caps left is checkloaduri (local file access) and that was added in Firefox 68.
