### ISSUE TITLE
GPO Settings problem

### ISSUE THREAD

**Issue by nakwada** [mozilla/policy-templates#131]
As soon as I open the GPO settings panel, I get an error message saying resource $(string.mozilla) was not found in mozilla.admx file, line 8 column 66. See attached file (in french)

![mstsc_2018-05-23_10-28-44](https://user-images.githubusercontent.com/1219791/40412755-76a7a2c8-5e74-11e8-9f19-238f36e65cd2.png)

**Comment by mkaply** [comment]
You need to grab both the mozilla*.adm files and the firefox*.adm files and install them.

Did you use the zip file?

**Comment by mkaply** [comment]
Is this working for you now?

**Comment by dark-swordsman** [comment]
I don't speak whatever language that is, but I'm guessing this would be the same error?:
```
An appropriate resource file could not be found for file %windir%/PolicyDefinitions/firefix.admx (error = 2): The system cannot find the file specified.
```
Same thing with mozilla.admx.

As @jakieu suggested, the en-US files need to be copied to the en-US folder under PolicyDefinitions. That will solve it, and then it will be available in any GPO you edit from then on.

That solved my issue, which I hope this is the same one.

**Comment by mkaply** [comment]
@nakwada Is this working for you?

**Comment by mkaply** [comment]
This should all be working.
