### ISSUE TITLE
GPO Text correct for "Allows Pop-ups from websites" ?

### ISSUE THREAD

**Issue by sskmadmin** [mozilla/policy-templates#132]
Possible value:
If this policy is disabled, pop-up windows are allowed from websites by default.
If this policy is not configured or enabled, popups are not allowed from websites.

GPO means "Allow..."
if disable, pop-ups are allowed ??

Normally it should be called "if enable, pop-ups are allowed ..."

**Comment by mkaply** [comment]
The name of the policy is PopupBlocking so the text is correct.

In hindsight we probably could have named this bettter so we didn't have "negative" policies.
