### ISSUE TITLE
Lock Preferences

### ISSUE THREAD

**Issue by cedricbrx** [mozilla/policy-templates#133]
There should be a possibility for an Adminsitrator to overwrite the preference of the user or prevent the user to change it. I changed the proxy-settings, but the user can still change to something else. It would be nice to get the "lockPref" Option back, like:
 "Proxy": {
      "AutoLogin": true,
      "Mode": "system",
      "SOCKSVersion": 4,
      "UseHTTPProxyForAllProtocols": true,
      "UseProxyForDNS": false,
      **"Locked": true**
}
or for the SearchBar
"SearchBar":  {
   "type": "unified"
   "Locked": "true"
}

**Comment by mkaply** [comment]
This is exactly how it works. The Proxy entry supports adding Locked exactly as you specified and they cannot be changed.

As far as the SearchBar goes, we investigating completely preventing Customizing. That would accomplish what you want. It's not a pref, so locking it doesn't make sense.
