### ISSUE TITLE
GPO | Extensions | help me extension URL

### ISSUE THREAD

**Issue by mbbinh** [mozilla/policy-templates#141]
I use Firefox Quantum 60 and Windows Server 2012 Standard deploy GPO.
I want to deploy add-on NoScript Security Suite.
In policy "Extension to install", what is extension URL add-on NoScript Security Suite ?
Help me find it.
![image](https://user-images.githubusercontent.com/39734390/40663362-abb4d932-6382-11e8-8be3-d6013cd34e5c.png)
![image](https://user-images.githubusercontent.com/39734390/40663428-d7a8de26-6382-11e8-96cd-44b92d8abefd.png)

**Comment by mkaply** [comment]
It's the URL to the XPI. If you right click on the button and copy the URL, you'll get

https://addons.mozilla.org/firefox/downloads/file/940138/noscript_security_suite-10.1.8.1-an+fx.xpi

If you want to install that specific version.

You can also replace the version number with "latest" and always get the latest version

https://addons.mozilla.org/firefox/downloads/file/940138/noscript_security_suite-latest-an+fx.xpi

**Comment by mbbinh** [comment]
@mkaply 
Thanks for reply.
I try your link but unsuccessful. 
I copy this link then paste&go in Firefox Quantum 60 >>> could not download. I think that is the cause. Is it right?
![image](https://user-images.githubusercontent.com/39734390/40755733-d2b37138-64a9-11e8-9a71-5a1f32399515.png)

**Comment by mbbinh** [comment]
@mkaply
Can you help me, pls !!!

**Comment by mkaply** [comment]
When I use this URL

https://addons.mozilla.org/firefox/downloads/file/972162/noscript_security_suite-latest-an+fx.xpi

I do not see that error.

Do you see any errors on the browser console?

**Comment by mbbinh** [comment]
@mkaply
Why error ? I don't know.
I want to question more about policy "URL for homepage"
I configured in below picture but unsuccessfull. 
![image](https://user-images.githubusercontent.com/39734390/40870188-32faaed4-6654-11e8-84d4-675a8dde2f48.png)
