### ISSUE TITLE
GPO wishlist: do not ask user about search engines

### ISSUE THREAD

**Issue by jjurkus** [mozilla/policy-templates#143]
```
// Do not ask about search suggestions
pref("browser.urlbar.userMadeSearchSuggestionsChoice", true);
```
This is a setting we have in our autoconfig file. A reason to have this setting: we don't have roaming profiles, people change computers, and don't need to see this every time they logon to a new desktop.

**Comment by mkaply** [comment]
This is available via the new preferences policy:

https://github.com/mozilla/policy-templates/blob/master/README.md#preferences
