### ISSUE TITLE
GPO For not autorize the extenssions to installe on Firefox by Users

### ISSUE THREAD

**Issue by ljbili** [mozilla/policy-templates#144]
hello,

how can i do to creat a gpo to forbid the user to install extenssion in firefox?

please i need your help

best regards.

**Comment by Pierrux** [comment]
Hi,

You can activate the "**Block Add-ons Manager**" policy:
![image](https://user-images.githubusercontent.com/25585341/41086887-99b6ac0a-6a3b-11e8-9d11-4cee0e5dcb75.png)

You should either activate the "**Allow add-on installs from websites**" policy:
![image](https://user-images.githubusercontent.com/25585341/41087102-16dac5e0-6a3c-11e8-896f-c5fe30550921.png)

This way, users won't be able to access Add-ons manager and to install add-ons from other websites (such as uBlock for example).

Be careful, **those policies **don't uninstall already existing add-ons.****

Best regards,

**Comment by ljbili** [comment]
thank you  Pierrux  for your reply, i will tested this policy soon,

and what i need to do for "uninstall already existing add-ons" ? have you any idea for this plz?

thanks,

best regards,
Lokmane JBILI.

**Comment by mkaply** [comment]
There is a policy to uninstall addons.

Extensions->Uninstall.

You list the extensions by ID.

**Comment by ljbili** [comment]
thanks for your reply mkaply,

but i have many users on my domain, every user have many different extenssion on his firefox,
i need to uninstall all this extenssions which are installerd on all computers.

thanks,
