### ISSUE TITLE
GPO Wishe : some policy to add if possible

### ISSUE THREAD

**Issue by zim333** [mozilla/policy-templates#145]
Hello Mike,
We are still using some settings in the cfg file in our Government administration

**extensions.autoDisableScopes** = 7
We need some system add-on to be "always" enabled (example Trend Micro Osprey Firefox Extension). 

**extension.shownSelectionUI**
In order to not let users to "easily" disable system addons

**Services.perms.add(NetUtil.newURI("https://www.asscap.agents-ctae.ants.gouv.fr"), "install", 1)**
We have some URL to add in order to let them to install extension. I have tried policy "Extensions to Install" but it does not add this URL to the list of authorized URL.

**lockPref("security.insecure_field_warning.contextual.enabled", false);**
**lockPref("signon.autofillForms.http", true);**
We have some VIP that do not want to see this warning on internal web servers (not https)  and they want autofill too...   We are aware that this is not best practice for security but we had to do this.

We want to know if you are planning to release a MSI version of installer. This is IMHO a feature that is very long awaited by organizations/administrations.

Thank you.
Lulzim KELMENI

**Comment by bastien30** [comment]
> extensions.autoDisableScopes = 7
> We need some system add-on to be "always" enabled (example Trend Micro Osprey Firefox Extension).

+1, very usefull parameter

> lockPref("security.insecure_field_warning.contextual.enabled", false);
> lockPref("signon.autofillForms.http", true);
> We have some VIP that do not want to see this warning on internal web servers (not https) and they want autofill too... We are aware that this is not best practice for security but we had to do this.

Same as you, many of our users does not want to see this warning on internal webui, and autofill is kind of indispensable.

I really hope theses parameters will be added (or similar others).

Thanks.

**Comment by charleslatham** [comment]
> **lockPref("security.insecure_field_warning.contextual.enabled", false);**
> **lockPref("signon.autofillForms.http", true);**
> We have some VIP that do not want to see this warning on internal web servers (not https) and they want autofill too... We are aware that this is not best practice for security but we had to do this.

I'd also like to see this for the same reason.

**Comment by mkaply** [comment]
security.insecure_field_warning.contextual.enabled has been added

All of the signon preferences were just made available in Firefox 83 and Firefox ESR 78.5 via the Preferences policy.

As far as autoDisableScopes, that won't be added to policy. You'll have to use autoconfig or force_install the extension via the ExtensionSettings policy.
