### ISSUE TITLE
Problem with policy "proxy setting"

### ISSUE THREAD

**Issue by zim333** [mozilla/policy-templates#146]
Hello Mike,
We want to configure policy "Proxy setting" but we have a warning that prevent us to apply this settings : 

When we set "Automatic proxy configuration" and fill the filed "Automatic proxy configuration URL" with an URL, we have a warning that says (in french) 
"Aucune valeur n'a été entrée pour ce champ. Vérifiez que vous entrez un valeur".

It's look like an other field must be fill in order to validate settings.

Thank you.
Lulzim KELMENI

**Comment by mkaply** [comment]
Because of a bug in Microsoft GPO, all dropdowns must have a value. So you need to set the SOCKS version even though it isn't used. This is indicated in the description of the policy.
