### ISSUE TITLE
GPO Wish : Delete search engines

### ISSUE THREAD

**Issue by redm5** [mozilla/policy-templates#148]
Hello,

i would like to be able to delete the search engines which are already present in firefox like amazon, etc.

Thanks

**Comment by HeiHei90** [comment]
Is there a ways to achieve this, until it is supported via GPO?

**Comment by redm5** [comment]
I found a way but it is more like a workaround... 

in your firefox profile folder

C:\Users\USERNAME\AppData\Roaming\Mozilla\Firefox\Profiles\XXXXXXXX.default

is a file called **search.json.mozlz4** it contains all the search engines. You can delete them on one machine and then copie this file to each machine if you want to delete the search engines. But as you can see on the path each profile is generated automatically when you install Firefox so you need to write a script which retrieves the right path. Personnaly i defined a default search engine for now and it works greate like this.

**Comment by HeiHei90** [comment]
T.hanks for that. Gonna try it as soon as I can.
Yeah that path should not be a problem. I need to make changes in every profile anyways, in my installation package. 
I defined a default search engine via GPO but it seems no longer to work.

**Comment by havx** [comment]
The ESR-only restriction for removal of search engines and specifying the default search engine should be lifted. Those policies should be extended to the normal client.

**Comment by mkaply** [comment]
> The ESR-only restriction for removal of search engines and specifying the default search engine should be lifted. Those policies should be extended to the normal client.

I appreciate that, but unfortunately we have a major search hijacking problem on Firefox and until we have better support for only allowing these policies only when connected to an Active Directory server, it's going to stay like that.

**Comment by mkaply** [comment]
Removing search engines was added which is what this bug was originally about.
