### ISSUE TITLE
Disable to Install Addons

### ISSUE THREAD

**Issue by luciano-work** [mozilla/policy-templates#15]
I'm trying to block Addons but the policy InstallAddons don't work.
I want to block any Addons from (https://addons.mozilla.org)

All the best.

**Comment by mkaply** [comment]
We haven't implemented that policy yet. There will be a policy to completely block installing addone.

https://bugzilla.mozilla.org/show_bug.cgi?id=1429131

**Comment by mkaply** [comment]
This policy is implemented.
