### ISSUE TITLE
GPO Wish: Disable DNS over HTTPS

### ISSUE THREAD

**Issue by moshekaplan** [mozilla/policy-templates#154]
Please create an option to enable/disable DNS over HTTPS. In an enterprise environment, it can be important for all DNS requests to go through centralized infrastructure for monitoring and protection.

Thanks!

**Comment by mkaply** [comment]
There will definitely be a policy to turn this off. I've opened a bug

https://bugzilla.mozilla.org/show_bug.cgi?id=1484843

Which you can follow.

**Comment by fantuz** [comment]
why closing ??

DoH is not in ESR but will probably be anytime soon...

**Comment by mkaply** [comment]
Because it's being handled in a bugzilla bug, I'll reopen for now.

**Comment by mkaply** [comment]
This landed in Firefox 64 and will be uplifted with the DNS over HTTPS support.

https://bugzilla.mozilla.org/show_bug.cgi?id=1484843
