### ISSUE TITLE
Not working on macOS, troubleshooting process?

### ISSUE THREAD

**Issue by ygini** [mozilla/policy-templates#157]
Hi folks,

I'm trying to rely on policies to autoconfigure new profiles with our default corporate setup (each consultant create one Firefox profile on its own session per customer we've to not leak any informations between each of them).

Here the content of `/Applications/Firefox.app/Contents/Resources/dictionaries/policies.json`, and it does absolutely nothing.

```
{
	"policies": {
		"FlashPlugin": {
			"Default": true
		},
		"PopupBlocking": {
			"PopupBlocking": false
		},
		"Extensions": {
			"Install": [
				"https://app-updates.agilebits.com/download/OPX4?browser=firefox&alt=true"
			]
		},
		"DisableAppUpdate": true,
		"DisableFeedbackCommands": true,
		"DisableFirefoxAccounts": true,
		"DisableFirefoxStudies": true,
		"DisableProfileImport": true,
		"DisableTelemetry": true,
		"DisplayBookmarksToolbar": true,
		"DontCheckDefaultBrowser": true,
		"OfferToSaveLogins": true,
		"OverrideFirstRunPage": "https://www.abelionni.com/",
		"OverridePostUpdatePage": ""
	}
}
```

This is a valid JSON from jsonlint point of view, POSIX rights are `rw-r--r--`.

Do you see any error? 

What should be the troubleshooting process here? How can I get logs specific to this feature?

I'm using Firefox ESR 60.0.2.

**Comment by ygini** [comment]
Damned! Thanks a lot, relying too much on TAB to autocomplete path can be an issue.

It work now.

Can't wait to see this feature on macOS ported to MDM based management!

**Comment by mkaply** [comment]
I've done the exact same thing :).
