### ISSUE TITLE
Referencing the last version of a plugin?

### ISSUE THREAD

**Issue by ygini** [mozilla/policy-templates#158]
Hi folks,

I'm trying to rely on policies to autoconfigure new profiles with our default corporate setup (each consultant create one Firefox profile on its own session per customer we've to not leak any informations between each of them).

Part of our profile is:

```
		"Extensions": {
			"Install": [
				"https://app-updates.agilebits.com/download/OPX4?browser=firefox&alt=true"
			]
		},
```

Where we use the static URL provided by AgileBits for the 1Password extension (the server will redirect then to the XPI).

Not all extension provide this kind of URL.

For example, I would also like to install by default SAML Tracer (https://addons.mozilla.org/en-US/firefox/addon/saml-tracer/).

The main website for this project is on Github where we cannot reference via a static URL the link to the last release artefacts.

How could we use the policy system to ask Firefox to install the last version available on the addons.mozilla.org catalog for a specific extension ID? Documentation tend to say that's only URL and local path are supported for the install part feature. This seems to lead to un updated extension… No?

**Comment by mkaply** [comment]
The secret is to right click on the install button and copy the URL. You'll get something like this:

https://addons.mozilla.org/firefox/downloads/file/972487/saml_tracer-1.5-an+fx-mac.xpi?src=dp-btn-primary

then replace the version with "latest"

https://addons.mozilla.org/firefox/downloads/file/972487/saml_tracer-latest-an+fx-mac.xpi

(I also removed the extra stuff at the end)

**Comment by ygini** [comment]
Thanks a lot! That's awesome!

**Comment by SecT0uch** [comment]
@mkaply Thanks for this answer, it is working as expected.

However, I've noticed that for some extensions the url changed (972487, in your example).
For example, for uBlock origin I had https://addons.mozilla.org/firefox/downloads/file/1672871/ublock_origin-latest-an+fx.xpi a few months ago. 
The file is still there but it links to the version 1.18.4 while the last one is 1.19.6, available here : https://addons.mozilla.org/firefox/downloads/file/2990453/ublock_origin-latest-an+fx.xpi

I've noticed the the xpi can be accessed via https://addons.mozilla.org/firefox/downloads/ublock_origin-1.19.6-an+fx.xpi, which bypasses the issue, but https://addons.mozilla.org/firefox/downloads/ublock_origin-latest-an+fx.xpi doesn't work.

Do you have any idea how this could be bypassed/fixed ?

**Comment by mkaply** [comment]
Does 

https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/

Work for you?

**Comment by mkaply** [comment]
You can also use:

https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi

**Comment by SecT0uch** [comment]
Awesome, thanks !

**Comment by SecT0uch** [comment]
After testing, I confirm that only this one works propely :

> https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi

**Comment by mkaply** [comment]
Thank you. I'll make sure the documentation makes this clear. I'm also going to build an add-on that lets you get the ID of an extension easily from AMO.
