### ISSUE TITLE
GPO Wish: New tab customization. 

### ISSUE THREAD

**Issue by blewis123** [mozilla/policy-templates#159]
Please add a options for opening a specific page when a new tab is opened.  We would prefer to see something on our new tabs besides the links for Face Book and Twitter for example.

Thanks

**Comment by havx** [comment]
Agreed. The ability to set the default for "New tabs" should be added. We can already dictate the homepage so we should be given the ability to dictate new tabs.

**Comment by Coros** [comment]
adding my wish to have new tab customization.  I need to be able to disable all the top sites, recommended by pocket (I've already disabled pocket but this still shows on Mac), and Highlights for our school devices.  I'd prefer it open a blank page.

**Comment by jscher2000** [comment]
> I need to be able to disable all the top sites, recommended by pocket (I've already disabled pocket but this still shows on Mac), and Highlights for our school devices. I'd prefer it open a blank page.

Through Autoconfig, you can set these preferences:

````
// At startup, set new tab to blank page
pref("browser.newtabpage.enabled", false);
// Disable specific sections of about:newtab in case user enables it
// - Top Sites
pref("browser.newtabpage.activity-stream.feeds.topsites", false);
// - Recommended by Pocket
pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
// - Highlights
pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
````

More on Autoconfig files, including how to prevent user choice (lockPref) or honor user choice (defaultPref): 
https://support.mozilla.org/kb/customizing-firefox-using-autoconfig

**Comment by mkaply** [comment]
We've added this in Firefox 68. You can turn it off or remove sections.
