### ISSUE TITLE
GPO Wishlist: downloads and favourites

### ISSUE THREAD

**Issue by vitormfgoncalves** [mozilla/policy-templates#160]
It's a bummer that some settings only work with ESR.
Will these features eventually come to mainstream installations?

Anyway, my wishlist:
- force users to always chose where to save downloaded files;
- automatically maintain favourites synchronized with another browser (edge-like GPO)
- better documentation :)

**Comment by sshowers** [comment]
+1 for control over the "Downloads" options (specifically "ask where to save").

**Comment by asadotzler** [comment]
For bookmarks sync with another browser see issue #270

**Comment by mkaply** [comment]
We now can force users to choose where to download.

https://github.com/mozilla/policy-templates/blob/master/README.md#promptfordownloadlocation
