### ISSUE TITLE
RSoP Error - Encountered an error while parsing

### ISSUE THREAD

**Issue by rosskoes05** [mozilla/policy-templates#162]
Receiving this error when viewing RSoP on my Windows 10 machine.
![image](https://user-images.githubusercontent.com/40174419/41249712-d3524308-6d82-11e8-8ba9-e6423fcc7cc3.png)

**Comment by rosskoes05** [comment]
Yes.  I followed the link on Mozilla's website which took me here:
https://github.com/mozilla/policy-templates/releases

It looks like I downloaded the same release (1.0)

**Comment by mkaply** [comment]
This should all be fixed. Versions are matching.
