### ISSUE TITLE
GPO Wish: Make Firefox the default browser

### ISSUE THREAD

**Issue by davehope** [mozilla/policy-templates#164]
These ADM template are helping to move us closer to a position where we may be able to make Firefox the default browser for at least some of our staff.

What they don't do is allow for Firefox to be set as the default browser.

For Windows 10, Microsoft allow this to be set via GPO ( Computer Configuration > Policies > Administrative Template > Windows Components > File Explorer -> Set a default associations configuration file ) and then creating an XML file with the desired associations.

AFAICT, Microsoft do not provide an equivalent Windows 7. This leaves administrators needing to manually tweak HKEY_CLASSES_ROOT, or use a login script to launch helper.exe/ SetAsDefaultAppGlobal

**Comment by davehope** [comment]
IMO, The GPO should support any current Microsoft Operating system in mainstream/extended support. 

So Windows 7 and later.

**Comment by davehope** [comment]
The hash Microsoft use to protect the registry keys for Windows 10 has been reversed, for further details see here:

https://kolbi.cz/blog/2017/10/25/setuserfta-userchoice-hash-defeated-set-file-type-associations-per-user/

From my perspective, It only makes sense implementing this if preferences can be implemented for both OS's.

**Comment by mkaply** [comment]
That post still requires us to do the actual reverse engineering which we cannot. So unfortunately, there isn't anything we can do on Windows 10.

But I could make a Windows 7 only policy.

**Comment by mkaply** [comment]
This isn't something we are going to be able to do. You'll have to do this via Microsoft GPO.
