### ISSUE TITLE
GPO block installation of addons issue

### ISSUE THREAD

**Issue by CLiX90** [mozilla/policy-templates#165]
I enabled the „Allowed Site“ GPO and add one URL to this.
I disabled the „Allow add-on install from websites“ GPO.
So I would block the installation of all addons except the one defined in „Allowed Site“, but I can install every addon from every site.
![a566501a-86aa-484b-b56c-71dc20da53d4](https://user-images.githubusercontent.com/39278813/41429863-a7277aee-700e-11e8-9a20-1e70f7d0aa37.jpeg)

**Comment by mkaply** [comment]
You can't allow a specific addon that way. You can only allow a domain.

**Comment by CLiX90** [comment]
Ok, thanks!

Is another way possible to allow only specific addons?

**Comment by mkaply** [comment]
> Is another way possible to allow only specific addons?

No, we don't allow whitelisting/blacklisting of addons.

**Comment by CLiX90** [comment]
Ok.
