### ISSUE TITLE
Block add-on install wrong landing page

### ISSUE THREAD

**Issue by CLiX90** [mozilla/policy-templates#169]
If you disable the policy "Allow add-on installs from websites", then the page that you see the first time on "about:addons" is only this page (German):
![addonlandingpage](https://user-images.githubusercontent.com/39278813/41602288-c67b441e-73da-11e8-9ef0-7b986bc715e2.PNG)

If you click on extensions, restart Firefox and go again to "about:addons, you will see extensions.

Maybe set "extensions.ui.lastCategory" to "addons://list/extensions" with this policy.

**Comment by mkaply** [comment]
This should be working now.

It was broke in ESR, but I fixed it there. And there is a specific fix in Firefox:

https://searchfox.org/mozilla-central/source/toolkit/mozapps/extensions/content/extensions.js#2049
