### ISSUE TITLE
Question about 'DisableProfileImport' policy

### ISSUE THREAD

**Issue by bastien30** [mozilla/policy-templates#170]
Hi,

Do the policy 'DisableProfileImport' disable also the profil migrator ?

I used to deploy an override.ini file in 'browser' directory with 'EnableProfileMigrator=false' inside.
Do I still need to deploy it ?

Thanks.

**Comment by mkaply** [comment]
The profile migrator isn't enabled by Firefox anymore, so you shouldn't need to deploy override.ini.

**Comment by bastien30** [comment]
You're faster than light ! :laughing:
Thanks, I will remove it.
