### ISSUE TITLE
GPO wishlist: Disable Updates and Authentication for non ESR Version

### ISSUE THREAD

**Issue by Alex-L-ander** [mozilla/policy-templates#171]
We are currently deploying the RR of Firefox with Updates disabled and Authentication Settings for network.negotiate-auth.trusted-uris, network.negotiate-auth.delegation-uris and network.negotiate-auth.allow-non-fqdn by using a gpo-extension and CCK2. With the current Version of FF these settings do not work, only the ESR Version seems to read the Registry Keys. Can this be changed?

**Comment by Alex-L-ander** [comment]
Wow that was quick! That sounds perfect. Thanks!

**Comment by mkaply** [comment]
This was fixed. We allow these options in RR.
