### ISSUE TITLE
Popups/Allowed sites = Invalid parameters specified for PopupBlocking.

### ISSUE THREAD

**Issue by Tsmith-noc1** [mozilla/policy-templates#174]
Trying to add sites to allowed for pop ups list, ADMX templates imported, GPO created and applying to a PC successfully and the registry keys exist, but the desired sites do not show up when accessing the browser setting GUI for pop up blocker excluded sites list, and popups are still blocked (hence the "popuptest.com" url being included for testing.)
Client device is a W7 Pro x64 OS with FF version 60.0.2 64 bit

=========

>HKEY_CURRENT_USER\Software\Policies\Mozilla\Firefox\PopupBlocking\Allow
KeyName: 1
Key value: google.com
Key name: 2
Key value: popuptest.com

=========
Turned on debug via about:config, added value for "browser.policies.loglevel"="debug".
Result shown in the console when opening Firefox:

=========

> GPOParser.jsm:{
  "PopupBlocking": {
    "Allow": [
      "google.com",
      "popuptest.com"
    ]
  }
}  WindowsGPOParser.jsm:40
PoliciesValidator.jsm:checking @[object Object]@ for type object  PoliciesValidator.jsm:39
PoliciesValidator.jsm:in object, checking
    property: Allow
    value: google.com,popuptest.com
    expected type: array  PoliciesValidator.jsm:77
PoliciesValidator.jsm:checking @google.com,popuptest.com@ for type array  PoliciesValidator.jsm:39
PoliciesValidator.jsm:in array, checking @google.com@ for type origin  PoliciesValidator.jsm:58
PoliciesValidator.jsm:checking @google.com@ for type origin  PoliciesValidator.jsm:39
Enterprise Policies:Invalid parameters specified for PopupBlocking.  EnterprisePolicies.js:134
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox”  browser.xul

**Comment by Tsmith-noc1** [comment]
Michael,
Confirmed, changing to include the protocol prefix does fix.
Should I have been able to find that requirement in documentation for the GPO templates somewhere?

Thanks,
Tim

**Comment by mkaply** [comment]
I agree I did not specify this well. The problem is there is no good terminology for describing this. It's not a URL because you can't have anything after the domain name.

I'll update the docs to have an example.

I'll leave this open to fix the ADML

**Comment by mkaply** [comment]
The term I should have used in the docs was "origin":

https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#Definition_of_an_origin

**Comment by mkaply** [comment]
I've updated the docs to use the term "origin" instead of URL.
