### ISSUE TITLE
Duplicates Bookmarks

### ISSUE THREAD

**Issue by bastien30** [mozilla/policy-templates#177]
Hi,

It seems that the bookmarks policy add duplicates bookmarks if they already exists.

Couldn't he merge the existing bookmarks with those configured by policy ?

Thanks.

**Comment by mkaply** [comment]
Unfortunately our bookmarks policy left a lot to be desired.

We've added a ManagedBookmarks policy that works better

https://github.com/mozilla/policy-templates/#managedbookmarks
