### ISSUE TITLE
GPO wish: Firefox startup behaviour

### ISSUE THREAD

**Issue by CLiX90** [mozilla/policy-templates#179]
Please add a policy to define the startup behaviour.

browser.startup.page

http://kb.mozillazine.org/Browser.startup.page

**Comment by Almi14** [comment]
Hi there,

same here, we would need this within the GPO.

Thanks!

**Comment by CLiX90** [comment]
I would like to set a policy that opens a blank screen at Firefox startup (browser.startup.page = 0) and not the defined home page and not the last visited pages.

**Comment by mkaply** [comment]
FYI, this can be done today by setting the homepage to about:blank

**Comment by CLiX90** [comment]
Yes, this is a workaround.

**Comment by mkaply** [comment]
Startpage support was added in Firefox 64/60.4
