### ISSUE TITLE
I think Bookmarks GPO doesn't work with ESR 60.1

### ISSUE THREAD

**Issue by xstelios** [mozilla/policy-templates#182]
I think Bookmarks GPO doesn't work with ESR 60.1. I have set three bookmarks in the GPO and they doesn't appear to my clients. The method that i deployed ESR 60.1 to my clients was by Windows GPO Software Installation which was set to uninstall any previous versions. Can someone confirm it with ESR 60.1??

**Comment by mkaply** [comment]
Can you see if there are any errors on the console? Can you export your registry entries so we can verify them?

**Comment by TPISC** [comment]
Hi mkaply, same problem here. I am using the example entry from README.md . When I start Firefox ESR for the first time after installation, the console shows no error at all. Only after another start the console shows

> Enterprise Policies: Invalid Parameters specified for Bookmarks

**Comment by mkaply** [comment]
In the example, for placement, I specify:

"Placement": ["toolbar", "menu"],

Which means use "toolbar" or "menu"

Is that possibly the problem?

Can you post your bookmarks here?

**Comment by xstelios** [comment]
No. This is not the problem. I have tried both "toolbar" and "menu" for placement with no success. There is also another problem with "Do not display default bookmarks" policy. It doesn't seems to work ether.

**Comment by mkaply** [comment]
xstelios: Can you export your registry entries so I can see what they look like?

**Comment by xstelios** [comment]
Can you specify which registry entries you want me to export?

**Comment by xstelios** [comment]
[FirefoxPoliciesRegEntries.zip](https://github.com/mozilla/policy-templates/files/2169146/FirefoxPoliciesRegEntries.zip)
Here are the Firefox Policies Registry Entries of a Client Computer. It seems that the bookmarks are OK but actually it doesn't appear in browsers.

**Comment by mkaply** [comment]
@xstelios The problem is this entry:

"URL"="mail.culture.gr"

This is not a URL. It has to be:

https://mail.culture.gr

**Comment by xstelios** [comment]
OK. I got the answer myself... "Note: this policy is only effective if used before the first run of the profile."
Thank you anyway..
