### ISSUE TITLE
Feature Request: Make all ESR-only policies available to Release Channel

### ISSUE THREAD

**Issue by gregneagle** [mozilla/policy-templates#185]
It seems completely arbitrary to limit some policies to ESR-only. Please remove that restriction and make them available to the Release Channel Firefox as well.

**Comment by gregneagle** [comment]
I don't want to have to choose between managing a feature for a better end-user experience in my organization and offering an up-to-date release of Firefox.

**Comment by mkaply** [comment]
This will be fixed in Firefox 62 (assuming there is uplift). I never meant it to apply to Mac anyway.

Going forward, some policies will be machine GPO policy on Windows, but on Mac/Linux all policies will be available on RR except for the search engine policy (We're concerned about hijacking).

https://bugzilla.mozilla.org/show_bug.cgi?id=1463895

I understand the search thing will annoy people for now. I'm trying to find a better solution.

**Comment by gregneagle** [comment]
I can live without the search engine. Of more concern (in moving away from CCK2/autoconfig) is supporting internal CAs. Getting Firefox on macOS to honor the macOS keychains, and a policy to turn that on would address that. I don't think anyone really wants to import internal CAs multiple times, one for each product vendor. Import into the macOS System keychain and let all third-party software use _that_, please.

**Comment by mkaply** [comment]
> Of more concern (in moving away from CCK2/autoconfig) is supporting internal CAs. Getting Firefox on macOS to honor the macOS keychains, and a policy to turn that on would address that.

Absolutely. I'm pushing on that one, and we're getting some movement, but I'm not there yet.

> I don't think anyone really wants to import internal CAs multiple times, one for each product vendor. Import into the macOS System keychain and let all third-party software use that, please.

I'm planning to get some sort of policy together for 62 that will at least to do some level of import on Mac. I'm still trying to figure out what they will look like (URL to cert path, read certs from some location, etc.).

Do you have any preference?

**Comment by gregneagle** [comment]
If we can't jump right to macOS keychain support, then a mechanism as similar as possible to autoconfig's mechanism would be my preference. It's not great to have to continually change how we manage one single (replaceable!) piece of software. Admins have to manage dozens or maybe hundreds of software titles for their organization. Any vendor/title that 

1. Deviates from platform standards, and 
2. Changes how they deviate from platform standards over and over, is

is likely to get on the admin's s**t list, leading to either lack of support, advocation to "get rid of" the product, or foot-dragging on upgrades to avoid dealing with the constant annoying changes.

If Mozilla wanted to move away from autoconfig, they should have moved _directly_ to Group Policy (Windows) and Managed Preferences (macOS) support. Telling admins "we're breaking the old way, here's a new way, oh in the future there will be yet another way" is not a great message.

**Comment by gregneagle** [comment]
"So the closest to autoconfig would probably be putting the certs in a directory (maybe under distribution) and then specifying the name via the policy. Is that acceptable for now?"

Yes, I'd think so. With autoconfig we're copying files into the Firefox bundle; this is basically the same thing -- we'd be copying in a json file and some certs.

**Comment by Clickbaitcake** [comment]
It would be great for both channels to have the same GPO capabilities!

**Comment by mkaply** [comment]
> It would be great for both channels to have the same GPO capabilities!

That's being changed in the next release (62). ESR only policies will now be machine only policies (except for adding/changing the search enginewhich will still be ESR only).

And @gregneagle I have really good news for you - https://bugzilla.mozilla.org/show_bug.cgi?id=1300420#c12

**Comment by mkaply** [comment]
This has been fixed. Everything except search is available on rapid release on Mac.

On Windows, we've moved some things to machine GPO only
