### ISSUE TITLE
Uninstall add-ons feature seem not working

### ISSUE THREAD

**Issue by hungitpro** [mozilla/policy-templates#186]
{
  "policies": {
    "Extensions": {
      "Install": ["https://addons.mozilla.org/firefox/downloads/somefile.xpi", "//path/to/xpi"],
      "Uninstall": ["addon_id@mozilla.org"],
      "Locked":  ["addon_id@mozilla.org"]
    }
}

It's seem uninstall add-ons not working.
Can someone help me using this feature via GPO? I'd tried but it was not working.

**Comment by mkaply** [comment]
Can you provide the exactly what you specified in each section?

**Comment by hungitpro** [comment]
Hi Mkaply,

Local computer policy>administrative templates>Mozilla>Firefox>Extensions>Extensions to Uninstall
I specified a list of extension IDs that will be uninstalled but it's not working. There is no extension has been uninstalled. https://ibb.co/dNLae8
Even if I created a policies.json files like above in this folder C:\Program Files\Mozilla Firefox\distribution. It's not working.

**Comment by mkaply** [comment]
Are you on ESR or rapid release?

**Comment by hungitpro** [comment]
It seem I using rapid release, cause the policies are not working.

**Comment by hungitpro** [comment]
I've tried ESR version, the policies are working well. Thank you for your support.

**Comment by mkaply** [comment]
FYI, we are planning to allow these on rapid release soon, but they will be machine only policies.
