### ISSUE TITLE
GPO wish: Whitelist for Local File Links

### ISSUE THREAD

**Issue by derco0n** [mozilla/policy-templates#188]
It would be very usefull if there would be an GPO that defines sites, from which links to localfiles are accepted.

At the moment they have to be defined in prefs.js like this:
user_pref("capability.policy.localfilelinks.checkloaduri.enabled", "allAccess");
user_pref("capability.policy.localfilelinks.sites", "https://intranet.mysite.com");
user_pref("capability.policy.policynames", "localfilelinks");

**Comment by mkaply** [comment]
I think allAccess is the only option here now.

I wonder if I could simplify this with just a policy for domains that can have local file links?

**Comment by pierre-guillot** [comment]
Hello @mkaply 
First, I take advantage of this issue to say "thank a lot" for your cck plugin. I use it on the hospital where I work (with Firefox 45.9) and it's very usefull.
Now, the goal is to migrate to ESR 60 and we have the same problem with our intranet site : few links uses "file uri" and need a user.js to continu to work on ESR 60.
@derco0n seems to not respond to your question, but for me, YES, if you can add a policy for "just" listing domains where you can open "file uri", it will be perfect.

**Comment by mkaply** [comment]
FYI, I've added a policy for this. It will be in 68.

**Comment by pierre-guillot** [comment]
Thank you! 👍

**Comment by mkaply** [comment]
This is in Firefox 68.
