### ISSUE TITLE
Extension installation

### ISSUE THREAD

**Issue by jjurkus** [mozilla/policy-templates#189]
Is there a way to force firefox to redo the installation of extensions, without having to change the registry key [HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox\Extensions\Install]?

This change detection isn't always very handy, and after deploying a newer version I want to force a reload. The Uninstall key is similarly affected. It is now filled with "1" = "uBlock0@raymondhill.net"
Firefox does not want to uninstall this extension. I have to change it to "2" = "uBlock0@raymondhill.net" and then it does something.

This is rather a nuisance when you're making a deployment script. In another case you might want to force an uninstall.

**Comment by mkaply** [comment]
That's a usecase I hadn't really thought about. I'm not sure what the best way to implement it is. I guess with a new parmeter to force install/uninstall?

Ideas welcome.

**Comment by jjurkus** [comment]
Or not force an install/uninstall, but a list of extensions that should be installed, and a list of extensions that should not be installed.
For instance: I list three extensions. I want them to be installed, and probably keep them installed. Update them when the version is newer than the one in the user directory.
With uninstall: make sure that addon-id is not installed.

The current solution is to use a deployment script that installs the extensions, but users have to enable those themselves.

**Comment by mkaply** [comment]
Another option is to use the version in the filename. Then when the extension name changes, we will reinstall it. I'm continuing to look at other options.

**Comment by jjurkus** [comment]
I have found a workaround, somewhat.

The install script (OPSI) is copying the extensions to all user profiles and to the browser\defaults\profile\extensions directory.

**Comment by asadotzler** [comment]
see also #115 for whitelist of extensions that can be installed.

**Comment by mkaply** [comment]
This is now supported via the ExtensionSettings policy.

If an addon located on the local file system is updated, the policy installs the new version.

**Comment by mkaply** [comment]
https://github.com/mozilla/policy-templates/blob/master/README.md#extensionsettings
