### ISSUE TITLE
Issues with auth_fqdn

### ISSUE THREAD

**Issue by ChrisNbg** [mozilla/policy-templates#190]
Hello,

i tested the branch with auth_fqdn and got some issues while testing:
- the german translation is missing the strings in the adml for the changes made in admx (the gpm at the server blame this) 
- at the client the rsop.msc blames minRequiredRevision differs between firefox.adml and firefox.admx
- the firefox.adml at en-us folder uses UTF8-BOM encoding and at the de-de Version uses UTF8 without BOM

Thank you
Christian

**Comment by ChrisNbg** [comment]
I registred another thing with auth_fqdn:
- the rule gets applied at the clients (checked with rsop.msc) but in about:config the both "fqdn" settings are not changed
I tested it with Firefox 60.1.0esr(64bit) on a Win10 Client
Other Settings like trusted uris does work here! is there an updated "future" client necessary to use the new feature of the admx?

thank you

**Comment by mkaply** [comment]
This setting is going in to the next version of Firefox and the ESR, so it's not available yet.

**Comment by mkaply** [comment]
This should be fixed now in ESR 60.2 and Firefox 62
