### ISSUE TITLE
Naming in the GPO of authentication

### ISSUE THREAD

**Issue by ChrisNbg** [mozilla/policy-templates#191]
Hello,

we are using the new admx Templates for Firefox ESR which are working pretty good sofar. I wanted to ask why the naming of the settings sometimes differ so far from that what is used in the about:config-files of FF?

It took me some testings to figure out that SPNEGO configures the value "network.negotiate-auth.trusted-uris" which was important for some kerberos based SSO-Intranet-Pages.

perhaps you can adjust the names so it matches better to the "config names" or you places the hints in the description of the adml-files. 
The linked page at the descriptions (https://developer.mozilla.org/en-US/docs/Mozilla/Integrated_authentication) doesn't help here.

Thank you so far for the good work!
Christian

**Comment by mkaply** [comment]
I'm working on documentation that better associates the pref names with the policies.

**Comment by mkaply** [comment]
I've updated the documentation so you can look for specific prefs and see what policies are affected.
