### ISSUE TITLE
GPO Wish: Prevent Profile Manager From Being Used to Create/Switch Profiles

### ISSUE THREAD

**Issue by derekdata** [mozilla/policy-templates#198]
Prevent the Profile Manager from being used from the command line to create new profiles.

I realize that GPO work across profiles, but in my case I am installing specific addons and then locking about:addons from users.  Therefore, I do not want them to create another profile and work around being able to use Firefox without the installed addon.  

Another way to do this would be to force-install extensions on new profiles.  I see there is a feature for this but it only supports ESR versions of Firefox.  If this were extended to work on all Firefox versions it could also work to solve my problem; however having a policy that prevents the Profile Manager across the board would still be useful.

**Comment by mkaply** [comment]
I would think in this situation, you wouldn't want your users to have access to the command line.

As far as extensions goes, in Firefox 62, we will be making that policy available via a machine GPO, not just the ESR, so you can use it.

**Comment by asadotzler** [comment]
Users can create new profiles without the command line. Simply visiting about:profiles gives you a nice creation and switching tool.

**Comment by mkaply** [comment]
All versions of Firefox supporting using policy to force install extension.

We also allow blocking of about:profiles.

We have no plans to remove access to profile manager via policy.
