### ISSUE TITLE
Better Policy Documentation

### ISSUE THREAD

**Issue by mkaply** [mozilla/policy-templates#203]
We need better documentation

Basically what I was trying to do (and haven't finished) was put together documentation similar to Chrome:

https://www.chromium.org/administrators/policy-list-3

This is how it was looking:

https://mozilla.github.io/policy-templates/

which is based on:

https://github.com/mozilla/policy-templates/blob/master/index.html

Chrome's stuff is all strings and bools, though so I wasn't sure it all mapped nicely into the format I was trying...

**Comment by jeffreymcclain** [comment]
This is my 1st time working with html, but hopefully my pull request is ok. I only changed the section order, added indentation, and added couple short sections for "Certificates" and "Cookies" so the links in the table at the top of the page would work properly.

**Comment by jeffreymcclain** [comment]
I also have a few questions:

- What does "CCK2 Equivalent" mean and where would I find this information?
- How do I check whether "Preferences modified" is N/A or changes a particular value?

**Comment by mkaply** [comment]
> What does "CCK2 Equivalent" mean and where would I find this information?

I did a product called CCK2 that did Firefox enterprise customization. 

https://github.com/mkaply/cck2wizard

You can leave those blank and I'l resolve them.

As far as preferences modified, easiest place is the source code:

https://searchfox.org/mozilla-central/source/browser/components/enterprisepolicies/Policies.jsm#132

You can search on a policy name (in this case, ImportEnterpriseRoots), and see that it changes the prefererence "security.enterprise_roots.enabled".

I can help with this one as well.

**Comment by jeffreymcclain** [comment]
@mkaply , I just submitted a pull-request with a skeleton table for all the policies, based on the source code you linked in your last comment. I will work on populating the linked table entries with details in the following weeks.

**Comment by mkaply** [comment]
This is finally done.
