### ISSUE TITLE
use CA from windows certificate store

### ISSUE THREAD

**Issue by LHService** [mozilla/policy-templates#208]
We use self created ca in our organisation for internal web services.

I can see them in the Windows certificate store on the clients.

We use cck2 in the past - but this method is no longer working.

We enabled the setting "Import Enterprise Roots" for Firefox. 

I can see the registry DWORD
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox\Certificates,ImportEnterpriseRoots has the value "1", and the browser log with policy log set to debug, shows no error messages and the correct settings for all policys.

But its not working - we get "your connection is not secure" messages

What did we wrong ?

Settings for bookmarks, homepage, update... are working fine.

FF Version 60.1.0esr

**Comment by mkaply** [comment]
Do you see the preference 

security.enterprise_roots.enabled

set to true in about:config?

Were you explicitly adding the cert in the CCK?

**Comment by LHService** [comment]
> Do you see the preference

Yes, its locked and set to true

------------------------------------------------------

![grafik](https://user-images.githubusercontent.com/42406820/44249692-503a7a00-a1f1-11e8-8db4-353849e46c36.png)

We deployed it via autoconfig, working fine with rapid releases until Version 61.x...

Because of that we started with the GPOs and the 'esr' version.

**Comment by mkaply** [comment]
Your autoconfig method should still be working on Firefox 61. What problem did you run into?

We are investigating adding certificate import support to the policy manager.

**Comment by LHService** [comment]
Sorry for the late reply,

and I am now unable to reproduce the problem with autoconfig. I recreated the whole config from scratch, and its working fine. The only explanation (besides the layer 8) for me would be a problem with importing a existing config file, change it, and deploy the changed config via autoconfig.

Thank you for your support and that great addon!
