### ISSUE TITLE
DisableAppUpdate were extended to non-ESR - please modify README.md

### ISSUE THREAD

**Issue by gitoss** [mozilla/policy-templates#209]
According to https://bugzilla.mozilla.org/show_bug.cgi?id=1460082 the DisableAppUpdate policy is now enabled for non-ESR builds, too - please modify README.md

The code https://hg.mozilla.org/releases/mozilla-beta/rev/e28ce913332a was merged on 21 Jun 2018, i.e. it should arreive with Firefox 63 builds.

**Comment by bytesized** [comment]
I filed [PR 192](https://github.com/mozilla/policy-templates/pull/192) to address exactly this.

**Comment by mkaply** [comment]
Yes. I'm behind on docs for the new update. I'll be working on that this week.

**Comment by mkaply** [comment]
This was done. Thanks for the reminder.
