### ISSUE TITLE
Proxy port

### ISSUE THREAD

**Issue by logikv** [mozilla/policy-templates#210]
The template nothing have port section for proxy.
If proxy set proxy:port, firefox doesn't parse port, only address
Thank you!

**Comment by mkaply** [comment]
What specific setting are you referring to?

And yes, the port is specified with a colon:

http://url.com:PORT

**Comment by mkaply** [comment]
Did this work for you?

**Comment by Welshyuk** [comment]
I can confirm that url.com:PORT works
