### ISSUE TITLE
GPO Wish: Change Cache Directory Path

### ISSUE THREAD

**Issue by PhilippvK** [mozilla/policy-templates#212]
In our organization the UNIX `/home/$USER` folders are mounted from NAS.

To have a better performance and less quota problems, we changed the path from `/home/$USER/.cache/firefox` to `/tmp/firefox/$USER`

This requires this line in the `Prefs.js` file at the moment:
```
user_pref("browser.cache.disk.parent_directory", "INSERT_PATH_HERE");
```

Permission handling is very important (sticky bit) but should be handled by firefox like it is at the moment.

I would really appreciate to see this feature. Thank you.

**Comment by mkaply** [comment]
Fixed in Firefox 68.

https://bugzilla.mozilla.org/show_bug.cgi?id=1491046

I'll close when I do the policy.

**Comment by mkaply** [comment]
This is in Firefox 68 with the new Preferences policy.
