### ISSUE TITLE
Firefox Sync add-ons

### ISSUE THREAD

**Issue by CLiX90** [mozilla/policy-templates#213]
If you set the policy "Allow add-on installs from websites" to disabled to block the add-on installation, then it is always possible to install add-ons over the Firefox Sync automatically.

So if a user has a Firefox with no policies at home and installs add-ons to this, then these add-ons are synchronized and are also available in the firefox with policies in the company.

**Comment by mkaply** [comment]
I've opened

https://bugzilla.mozilla.org/show_bug.cgi?id=1487529

for this. I would say that I think it would be odd to not disable Sync in any lock down of Firefox, but I agree we should handle this case.

**Comment by mkaply** [comment]
I fixed this and forgot to mark this.
