### ISSUE TITLE
Flash Allowlist doesn't prevent user from enabling Flash on other pages

### ISSUE THREAD

**Issue by annabaum** [mozilla/policy-templates#214]
I am trying to block flash on all websites, excluding the ones on the Allow List.
As I understand the Allow List setting, enabling this should prevent Flash from being running on any website that is not on this list.
However I get the Click to run option when browsing to a site that is not on the list (FF 61.0.2, Win 10 64bit).
Browsing to a whitelisted site runs Flash automatically (as expected).

**Comment by mkaply** [comment]
Did you change the default behavior of Flash to be disabled?

**Comment by annabaum** [comment]
![image](https://user-images.githubusercontent.com/11655481/44789908-1fb5f100-ab9e-11e8-9d40-c6438c1c6858.png)
I have left "Activate Flash on websites" as not configured as the description states that it will override the Allow List. Or do you mean a different setting?

**Comment by mkaply** [comment]
I'll double check, but I think the way it's supposed to work is that you disable flash by default and then allow it on specific sites. I'll make sure the text is clearer.

**Comment by annabaum** [comment]
When I disable Flash generally the whitelist also doesn't work. The disable setting actually seems to override the whitelist. If it worked the way you describe it that would be ideal. Thanks for your quick reply and for looking into it!

**Comment by mkaply** [comment]
Unfortunately, I couldn't make it work the way I suggested, but this is moot at this point.

firefox is disabled by default and you enable it on the sites you want (and flash is going away at the end of the year)
