### ISSUE TITLE
German localization troubble

### ISSUE THREAD

**Issue by GMBU** [mozilla/policy-templates#215]
I implement the german localization, but I run in a lot of errors, most of them of type " ..this is not a valid xml sign "  ( ö,ä,ü ). I upgrade .xml files , but it does not help. No pproblems if I use only the en-Us adml files.

**Comment by mkaply** [comment]
I'm able to use the German files in Windows/PolicyDefinitions. Can you provide a little more information as to where you are seeing this problem?

**Comment by GMBU** [comment]
Am 30.08.2018 um 20:52 schrieb Michael Kaply:
> I'm able to use the German files in Windows/PolicyDefinitions. Can you 
> provide a little more information as to where you are seeing this problem?

Hello Michael,

everything fine, please close it. I copyed the code, put it in a empty 
file and run into a UTF-8 interpretation problem.

After download the .adml files corretly it works fine, thank you !

Sirko


-- 
Dipl.-Ing.(FH) Sirko Poehlmann

Tel: 03641 3667 43         Fax: 03641 3667 77
GMBU e.V. - Fachsektion Photonik und Sensorik
Felsbachstraße 7                D- 07745 Jena
poehlmann@gmbu.de                 www.gmbu.de
