### ISSUE TITLE
policies marked as "machine only" doesn't work as expected in latest Firefox 62.0 build

### ISSUE THREAD

**Issue by kulmegil** [mozilla/policy-templates#216]
> As of Firefox 62, these policies are available outside of the ESR, but only via JSON file or a Local Machine-based Group Policy.

That's how it's working in Firefox 62.0 b20 when using policies.json file.
But in latest build 20180823143155 from auto update, marked as 62.0 
I'm getting error thrown in browser console:

> Enterprise Policies: Policy SearchEngines is only allowed on ESR

**Comment by mkaply** [comment]
The Search Engine policy will continue to be an ESR only policy. I'm considering making only setting the default engine as ESR only.

The reason the search engine policy is special is because we are a target for hijackers.

**Comment by kulmegil** [comment]
Btw.. Is there any other way to create search engines along with assigned keyword?

Addind xml's to distribution\searchplugins is still working fine, but there is no way to assign keywords to engines.

**Comment by mkaply** [comment]
I've opened a bug for that.

https://bugzilla.mozilla.org/show_bug.cgi?id=1491930

I can't promise that distribution/searchplugins will continue to work.

**Comment by michalrus** [comment]
Okay, since Tor Browser is not ESR, so this policy doesn’t work, how can I pre-configure its search engines *with keywords* on my own machine?

**Comment by mkaply** [comment]
The Tor browsers are all ESR based.
