### ISSUE TITLE
Install\uninstall Addon policy work only once with policies.json

### ISSUE THREAD

**Issue by 6bIBAET** [mozilla/policy-templates#224]
In 60.1.0esr 32bit Install and uninstall policy work only once.  If you delete the add-on that installed through policy and install an add-on that is deleted through policies, then in subsequent FF launches install\uninstall policy not work.

**Comment by mkaply** [comment]
Yes, that is how it works today. It's not designed to keep force installing an addon. If you allow a user to remove an addon (by not marking it as not removable), it won't be reinstalled.

As far as deletion goes, you're probably correct that we should check delete at every startup (until we have a blocklist)

**Comment by mkaply** [comment]
The new ExtensionSettings policy does all of this much better and should fix this issue

https://github.com/mozilla/policy-templates#extensionsettings
