### ISSUE TITLE
Enable Sub-Folders in Bookmarks Policy

### ISSUE THREAD

**Issue by moop2000** [mozilla/policy-templates#226]
Cannot create sub-folders for bookmarks when setup via policies.json file. Trying to organize company-wide bookmarks via folders, and would be willing to supply them by going "PartFolderName\SubFolder1" for each bookmark as needed.

**Comment by mkaply** [comment]
We've added a new ManagedBookmarks policy that gives subfolders.

https://github.com/mozilla/policy-templates/#managedbookmarks
