### ISSUE TITLE
Request: Plist and mobileConfig Files for MacOS

### ISSUE THREAD

**Issue by jeffreymcclain** [mozilla/policy-templates#232]
If possible, I'd appreciate if there was support for configuring these policies via JamF on macOS. I realize that this can currently be done via a JSON file, but I'd prefer a plist and mobileconfig file if possible.

For reference: [Chrome: create a configuration profile](https://support.google.com/chrome/a/answer/9020077?hl=en&ref_topic=7650028l)

Ideally I'd like something similar to Chrome's implementation, where I can modify a plist file template and then convert it to a mobileConfig file.

**Comment by ygini** [comment]
+1

This is the standard management solution on macOS (just like GPO for Windows), it would be a better way to support managed settings for this platform.

**Comment by mkaply** [comment]
See:

https://bugzilla.mozilla.org/show_bug.cgi?id=1445943

This is being actively worked on. We have a test build you can try:

https://queue.taskcluster.net/v1/task/fcqeRaj-SmOTMBRd7SJIMg/runs/0/artifacts/public/build/target.dmg

To enable Enterprise Policies, set `EnterprisePoliciesEnabled` as bool to `YES` for org.mozilla.nightly, i.e. `defaults write org.mozilla.nightly EnterprisePoliciesEnabled -bool YES`
you can then set all "flat" types of policies via `defaults write`. More complex policies using nested types (dictionary of arrays and similar) can be set via configuration policies.
See comment 22 and comment 23 in the bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1445943#c22, https://bugzilla.mozilla.org/show_bug.cgi?id=1445943#c23

**Comment by mkaply** [comment]
We have mac configuration profiles.

**Comment by mkaply** [comment]
https://github.com/mozilla/policy-templates/tree/master/mac
