### ISSUE TITLE
RR to ESR

### ISSUE THREAD

**Issue by vartaxe** [mozilla/policy-templates#233]
Hi,

is there a way to migrate from RR to ESR using a Firefox GPO?maybe for instance perhaps using a Custom Update URL?

thanks

**Comment by vartaxe** [comment]
maybe using app.update.channel and app.update.url ?

**Comment by hheinen** [comment]
Hey @vartaxe, what are you trying to achieve?
You only want to change app.update.url, if you are running your own update server (e.g. inside your organization).

**Comment by mkaply** [comment]
You really need to change channel prefs for this to happen.

This document should still apply

https://mike.kaply.com/2017/02/02/plugin-support-in-firefox-52/

**Comment by vartaxe** [comment]
nice link but can this be done through gpo?

**Comment by mkaply** [comment]
No, this is something that would need to be done via manual changes to the file.

**Comment by vartaxe** [comment]
is there a chance we can see this implemented through gpo?

**Comment by mkaply** [comment]
Not likely. This change can be potentially dangerous if done with the wrong versions (backleveling to ESR).

So I would want admins to understand exactly what they are doing.

**Comment by mkaply** [comment]
I'm going to wontfix this. This would not be something we can do easily via policy.
