### ISSUE TITLE
Request: Policies/GPOs that focus on compliance requirements

### ISSUE THREAD

**Issue by brentil** [mozilla/policy-templates#234]
I work in an environment where I have systems that have to comply with either CIS or DoD STIG configuration requirements.  It's nice I can do some of this through GPO now because honestly dealing with file based configuration for management is not fun or efficient and is more error prone.  However, currently with the existing GPOs I can only configure 3 of the 23 existing STIG requirements.  I haven't delved into how many I can cover with CIS but they're typically not too far away from the STIG.

It would be very helpful if the policy templates covered all of the items needed for audit compliance then which would make them a lot more useful for Gov & DoD along with corporate audit requirements.

[Browser STIGs](https://iase.disa.mil/stigs/app-security/browser-guidance/Pages/index.aspx)

[CIS for Firefox](https://www.cisecurity.org/benchmark/mozilla_firefox/)

**Comment by hheinen** [comment]
Sounds interesting but also like a lot of work. I didn't even find "rules" in that STIG-PDFs. The document itself is complecated. 
Maybe it would be helpful if you could identify all the Firefox-Configs that needed to be configured.
What do you think?

**Comment by brentil** [comment]
That's something I can definitely work on, I'll start gathering the configuration required by these audit bodies.

For reference the PDFs only provide information about the STIG but not the details themselves.  THe rules defining a STIG are in the XCCDF XML files which are formatted XML for browser viewing and also the definition files for audit compliance scanning tools.  For example from the latest STIG this is the actual rules of the STIG.

U_Mozilla_Firefox_V4R22_STIG\U_Mozilla_Firefox_V4R22_Manual_STIG\U_Mozilla_Firefox_STIG_V4R22_Manual-xccdf.xml

**Comment by turtlexiv** [comment]
For quick reference, stigviewer.com is handy: https://www.stigviewer.com/stig/mozilla_firefox/

**Comment by brentil** [comment]
STIG configuration requirements from the latest v4r22 release.

**Items existing Firefox GPO handle**

- V-6318 - The DOD Root Certificate is not installed.
     In a Windows environment, use of policy setting "security.enterprise_roots.enabled=true" will point Firefox to the Windows CA and is allowed.
- V-15774 - Firefox formfill assistance option is disabled.
     Ensure the preference “browser.formfill.enable" is set and locked to the value of “False”.
- V-15776 - FireFox is configured to use a password store with or without a master password.
     Ensure the preference “signon.rememberSignons“ is set and locked to the value of “false”.

**Items not covered by existing GPOs**
- V-15768 - FireFox is configured to ask which certificate to present to a web site when a certificate is required.
    Fix Text: Set the value of "security.default_personal_cert" to "Ask Every Time". Use the Mozilla.cfg file to lock the preference so users cannot change it.
- V-15771 - Network shell protocol is enabled in FireFox.
    Fix Text: Procedure: Set the value of "network.protocol-handler.external.shell" to "false" and lock using the Mozilla.cfg file.
- V-15772 - Firefox not configured to prompt user before download and opening for required file types.
    Fix Text: Ensure the following extensions are not automatically opened by Firefox without user confirmation. Do not use plugins and add-ons to open these files. Use the "plugin.disable_full_page_plugin_for_types" preference to set and lock the following extensions so that an external application rather than an add-on or plugin will not be used. (PDF, FDF, XFDF, LSL, LSO, LSS, IQY, RQY, XLK, XLS, XLT, POT PPS, PPT, DOS, DOT, WKS, BAT, PS, EPS, WCH, WCM, WB1, WB3, RTF, DOC, MDB, MDE, WBK, WB1, WCH, WCM, AD, ADP)
- V-15775 - Firefox is configured to autofill passwords.
    Fix Text: Ensure the preference " signon.prefillForms " is set and locked to the value of “False”.
- V-15777 - History retention must be enabled.
    Fix Text: Ensure the preference "places.history.enabled" is set and locked to the value of “true”.
- V-15778 - FireFox is not configured to block pop-up windows.
    Fix Text: Ensure the preference "dom.disable_window_open_feature.status " is set and locked to the value of “true”.
- V-15779 - FireFox is configured to allow JavaScript to move or resize windows.
    Fix Text: Ensure the preference "dom.disable_window_move_resize" is set and locked to the value of “true”.
- V-15983 - Firefox must be configured to allow only TLS.
    Fix Text: Configure the following parameters using the Mozilla.cfg file:
    LockPref "security.enable_tls" is set to "true".
    LockPref "security.tls.version.min" is set to "2".
    LockPref "security.tls.version.max" is set to "3".
- V-15985 - Firefox is configured to allow JavaScript to raise or lower windows.
    Fix Text: Ensure the preference "dom.disable_window_flip" is set and locked to the value of “true”.
- V-15986 - Firefox is configured to allow JavaScript to disable or replace context menus.
    Fix Text: Ensure the preferences "dom.event.contextmenu.enabled" is set and locked to "false".
- V-15987 - Firefox is configured to allow JavaScript to hide or change the status bar.
    Fix Text: Ensure the preference "dom.disable_window_status_change" is set and locked to the value of “true”.
- V-15988 - Firefox is configured to allow JavaScript to change the status bar text.
    Fix Text: Ensure the preference "dom.disable_window_open_feature.status" is set and locked to the value of “true”.
- V-15989 - Firefox is not configured to provide warnings when a user switches from a secure (SSL-enabled) to a non-secure page.
    Fix Text: Ensure the preference “security.warn_leaving_secure" is set to “true” and locked on this setting.
- V-19741 - Firefox application is set to auto-update.
    Fix Text: Ensure the preference "app.update.enable" is set and locked to the value of “False” or that a trusted server is used.
- V-19742 - Firefox automatically updates installed add-ons and plugins.
    Fix Text: Set the preference “extensions.update.enabled” value to "false" and lock using the Mozilla.cfg file.
- V-19743 - Firefox required security preferences cannot be changed by user.
    Fix Text: Ensure the required settings in "about:config" are locked using the "mozilla.cfg" file.
- V-19744	- Firefox automatically checks for updated version of installed Search plugins.
    Fix Text: Ensure the preference "browser.search.update" is set and locked to the value of “False”.
    
    
**Items not currently covered and I'm unsure if they can be**
- V-15770 - Firefox automatically executes or downloads MIME types which are not authorized for auto-download.
    Check Text: Use Method 1 or 2 to check if the following extensions are listed in the browser configuration: HTA, JSE, JS, MOCHA, SHS, VBE, VBS, SCT, WSC. By default, most of these extensions will not show up on the Firefox listing. 
    Criteria: 

    Method 1: In about:plugins, Installed plug-in, inspect the entries in the Suffixes column. 
    If any of the prohibited extensions are found, then for each of them, verify that it is not associated with an application that executes code. However, applications such as Notepad.exe that do not execute code may be associated with the extension. If the extension is associated with an unauthorized application, then this is a finding.
    If the extension exists but is not associated with an application, then this is a finding. 

    Method 2: 
    Use the Options User Interface Applications menu to search for the prohibited extensions in the Content column of the table.
    If an extension that is not approved for automatic execution exists and the entry in the Action column is associated with an application that does not execute the code (e.g., Notepad), then do not mark this as a finding. 
    If the entry exists and the "Action" is 'Save File' or 'Always Ask', then this is not a finding.
    If an extension exists and the entry in the Action column is associated with an application that does/can execute the code, then this is a finding.
- V-15773 - FireFox plug-in for ActiveX controls is installed.
    Fix Text: Remove/uninstall the Mozilla ActiveX plugin

**Comment by Ericos65** [comment]
To echo the above request this would be amazing for us in the Federal space that need to harden Firefox via the DISA STIGS. Below is the sample file which summarizes the preferences above posted by brentil if this is easier to follow.  A few others that I think would be nice would be disabling the "Welcome Page" (unless I just did not see this option already).

V-19743 Firefox Preferences - Lock settings
Sample file:
//
lockPref("browser.download.dir", "N:");
lockPref("browser.download.downloadDir", "N:");
lockPref("app.update.enabled", false);
lockPref("extensions.update.enabled", false);
lockPref("browser.shell.checkDefaultBrowser", false);
lockPref("browser.search.update", false);
lockPref("browser.formfill.enable", false); 
lockPref("signon.prefillForms", false);
lockPref("dom.disable_open_during_load", true);
lockPref("dom.disable_window_move_resize", true); 
lockPref("dom.event.contextmenu.enabled", false);
lockPref("dom.disable_window_status_change", true); 
lockPref("dom.disable_window_flip", true);
lockPref("dom.disable_window_open_feature.status", true); 
lockPref("security.warn_leaving_secure", true); 
lockPref("security.default_personal_cert", "Ask Every Time"); 
lockPref("signon.rememberSignons", false);
lockPref("xpinstall.whitelist.required", true);
lockPref(“network.protocol-handler.external.shell”,false); 
lockPref("security.tls.version.min" ,"2"); 
lockPref(“security.tls.version.max", "3");
lockPref("plugin.disable_full_page_plugin_for_types", "application/pdf,application/doc,application/xls,application/bat,application/ppt,application/mdb,application/mde,application/fdf,application/xfdf,application/lsl,application/lso,application/lss,application/iqy,application/rqy,application/xlk,application/pot,application/pps,application/dot,application/wbk,application/ps,application/eps,application/wch,application/wcm,application/wbi,application/wb1,application/wb3,application/rtf,application/wch,application/wcm,application/ad,application/adp,application/xlt, application/dos, application/wks");
lockPref("privacy.item.history", false)

**Comment by mkaply** [comment]
Do default options have to be locked? For instance, dom.disable_open_during_load is already set to true.

FYI, A number of items in this list don't apply anymore. Anything plugin related for instance.

**Comment by brentil** [comment]
> Do default options have to be locked? For instance, dom.disable_open_during_load is already set to true.
> 
> FYI, A number of items in this list don't apply anymore. Anything plugin related for instance.

Only specific ones have to be locked, this entry defines the ones that have to be.  It's pretty much just the list of items being set by the STIG.

[https://www.stigviewer.com/stig/mozilla_firefox/2018-04-02/finding/V-19743](https://www.stigviewer.com/stig/mozilla_firefox/2018-04-02/finding/V-19743)

STIGs lag behind product development so at some point there will be a revision of the STIG that will catch up with changes.  Until then though if an auditor looks at a systems configuration and doesn't find the setting set it's a down check unless we document it.  So whichever ones aren't supported anymore we'll just have to put in our SSPs and checklists to keep them happy.

**Comment by brentil** [comment]
DISA has released an updated Firefox STIG v4r23 which has two additional settings that need to be set for compliance.

- V-64891 - Extensions install must be disabled.
Fix Text: Set the preference “xpinstall.enabled” to “false” and lock using the “mozilla.cfg” file. The “mozilla.cfg” file may need to be created if it does not already exist.

- V-79053 - Background submission of information to Mozilla must be disabled.
Fix Text: Ensure the preferences "datareporting.policy.dataSubmissionEnabled" is set and locked to "false".

**Comment by asadotzler** [comment]
for history locking, see also #181

**Comment by asadotzler** [comment]
For STIG, see also issue #94

**Comment by mkaply** [comment]
Firefox 68 policy contains everything current from the STIG.

**Comment by brentil** [comment]
Excellent news, thank you!
