### ISSUE TITLE
"Disable Pocket" policy does not work

### ISSUE THREAD

**Issue by havx** [mozilla/policy-templates#235]
I have tested the "Disable Pocket" policy with the GPO on a domain-joined machine and with the policies.json file on a local-workgroup machine, in both cases Pocket remains enabled.

Please let me know what additional information you need to assist with investigating the issue further.
```
Policy version is 1.1 and browser version is 62.0 (64-bit)
Client OS: Win7, Win10, Server2012R2, Server2016
Domain Controller OS: Server2016
```

**Comment by mkaply** [comment]
This is working for me. It disables pocket integration in the browser.

Were you expecting it to disable pocket on the new tab page?

**Comment by havx** [comment]
Ahh, yes. I see that now. I guess I was expecting it to also be disabled in the "Firefox Home Content" options.

**Comment by asadotzler** [comment]
The other Firefox Start Page content section options are covered in issue #82 (which claims extensions.pocket.enabled already disables the Pocket content)

**Comment by havx** [comment]
I can confirm that the latest GPO templates (v1.4) and policies.json do not disable Pocket content on the Start Page.
![image](https://user-images.githubusercontent.com/23101303/50043067-4f94e180-0033-11e9-8333-895302f3d734.png)
![image](https://user-images.githubusercontent.com/23101303/50043083-8834bb00-0033-11e9-9761-9a77bc842f16.png)

**Comment by jscher2000** [comment]
For the time being, you can use Autoconfig files to hide various sections of the new tab page. For example:

````
// Disable specific sections of about:newtab (user can re-enable)
// - Top Sites
pref("browser.newtabpage.activity-stream.feeds.topsites", false);
// - Recommended by Pocket
pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
// - Highlights
pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
````

More on Autoconfig files, including how to prevent user choice (lockPref) or honor user choice (defaultPref): 
https://support.mozilla.org/kb/customizing-firefox-using-autoconfig

**Comment by mkaply** [comment]
We've added policies for this in Firefox 68. It's called FirefoxHome
