### ISSUE TITLE
"Bookmarks" GPO 5 through 20 mirroring one another

### ISSUE THREAD

**Issue by havx** [mozilla/policy-templates#236]
Configuring the GPOs for Bookmarks 01 through 04 work as intended but that can't be said for 05 through 20. Configuring any of those policies changes the rest (excluding 01 through 04); replicating its settings to the others, overriding whatever the policy state was (enabled or disabled). I can also note that only 01 through 05 are actually added to the registry even though the remaining polices are technically enabled and configured.

Please let me know what additional information you need to assist with investigating the issue further.

I will also add that editing a configured bookmark (for example updating only the URL) changes the order that the bookmarks are listed in the browser. I believe order should be maintained regardless of what's changed with the bookmark.
```
Policy version is 1.1 and browser version is 62.0 (64-bit)
Client OS: Win7, Win10, Server2012R2, Server2016
Domain Controller OS: Server2016
```

**Comment by mkaply** [comment]
This is fixed. Sorry for the delay.

https://github.com/mozilla/policy-templates/releases/tag/v1.2

**Comment by havx** [comment]
Thanks Mike!
