### ISSUE TITLE
JavaScript link does not work

### ISSUE THREAD

**Issue by LordNicon79** [mozilla/policy-templates#239]
Hi there, 
I'm trying to open a JavaScript Link at my Exchange2013 but nothing happens. 
I tried FF ESR 60/60.1.0/60.2.0 managed by GPOs, but always the same Problem.
I logged on at the ManagementConsole (ECP) went into a Account and want to see the last two detail links. If i click the link, nothing happens. If i click the link in Chrome or IE there starts a second window with all details i wanna know.
The problemlink looks like:
javascript:__doPostBack('ctl00$ctl00$ResultPanePlaceHolder$Mailbox$MailboxFeatures$contentContainer$MessageSizeRestriction_button','')

There is another link (even a javascript) that works fine:
javascript:__doPostBack('ctl00$ctl00$ResultPanePlaceHolder$Mailbox$MailboxFeatures$contentContainer$ctl07$enableArchivePopup_button','')

The second link works fine! 
As I see this, the first link tries to open a second windows and the second link just chang a single setting. 

My question/problem is the missing second window, staret by a javascript link. 
There is no popupblocker or thometing else. 

![unbenannt](https://user-images.githubusercontent.com/43130300/45283569-8b715580-b4de-11e8-9db5-9057c89bdcf1.jpg)

Can someone help me, please.

**Comment by mkaply** [comment]
Those NTLM values are incorrect. They must be domains, not just protocols.

**Comment by LordNicon79** [comment]
like https://mail.mydomain.de/ecp  ?
ok, i covered it, but the problem is still there.

is there anything to enable, that was standard disabled bevor version 60.1.0(even 60.0.1/60.2.0) ?

**Comment by mkaply** [comment]
Were you setting values before in Autoconfig or something else in order to get this to work?

Is this something that has worked in older versions of Firefox?

I'm not sure this is GPO related

**Comment by LordNicon79** [comment]
We jumped from Version 52.7.3 to 60.1.0. 
With version 52.7.3 everything was ok and the only thing we changed was the switch from ....
Mozilla.cfg
######
pref("browser.rights.override", true);
pref("browser.shell.checkDefaultBrowser", false);
pref("toolkit.telemetry.enabled", false);
pref("datareporting.healthreport.uploadEnabled", false);
pref("datareporting.policy.dataSubmissionEnabled", false);
pref("security.tls.version.min", 1);
pref("network.automatic-ntlm-auth.trusted-uris", "https://sharepoint.mydomain.de, http://sharepoint.mydomain.de, http://web01sharepoint.mydomain.de");
pref("extensions.autoDisableScopes", 11);

//Seit dem 26.04.2018
// Disable password manager
// unlockPref("signon.rememberSignons", false);
// unlockPref("pref.privacy.disable_button.view_passwords", false);

// Deaktiviert den Updater
lockPref("app.update.enabled", false);

// Stellt sicher dass er tatsächlich abgestellt ist
lockPref("app.update.auto", false);
lockPref("app.update.mode", 0);
lockPref("app.update.service.enabled", false);

// Versteckt 'Was ist neu?' beim ersten Start nach jedem Update
pref("browser.startup.homepage_override.mstone","ignore");

// Verhindert die Frage nach der Installation des Flash Plugins
pref("plugins.notifyMissingFlash", false);

// Deaktiviert das 'plugin checking'
pref("plugins.hide_infobar_for_outdated_plugin", false);
pref("plugins.update.url");

// Deaktiviert den 'health reporter'
lockPref("datareporting.healthreport.service.enabled", false);

// Disable all data upload (Telemetry and FHR)
pref("datareporting.policy.dataSubmissionEnabled", false);

// Deaktiviert den 'crash reporter'
lockPref("toolkit.crashreporter.enabled", false);
// Components.classes["@mozilla.org/toolkit/crash-reporter;1"].getService(Components.interfaces.nsICrashReporter).submitReports = false;
pref("browser.tabs.crashReporting.emailMe", false);
pref("browser.tabs.crashReporting.requestEmail", false);
pref("browser.tabs.crashReporting.sendReport", false);
pref("privacy.trackingprotection.enabled", true)
pref("datareporting.policy.dataSubmissionEnabled", false);
pref("datareporting.healthreport.uploadEnabled", false); 
pref("toolkit.telemetry.unified", false); 

// Seit dem 23.05.2018
// drop the Cache to 150 MB
lockPref ("browser.cache.disk.capacity", 153600);
pref("autoadmin.append_it-service@mydomain.de", true); 
###
and local-settings.js
###
pref("general.config.obscure_value", 0);
pref("general.config.filename", "mozilla.cfg");
###
to "managed by GPOs".

Thats why i thought this could be a gpo Probleme.

**Comment by mkaply** [comment]
So based on that, the values for the NTLM GPO should be

https://sharepoint.mydomain.de
http://sharepoint.mydomain.de
http://web01sharepoint.mydomain.de
