### ISSUE TITLE
policy "Don't Check Default Browser" does not work as expected in Firefox ESR 60.2

### ISSUE THREAD

**Issue by github-kh2018** [mozilla/policy-templates#240]
- add Firefox GPO templates version 1.1 from GitHub to your domain policy store
- create GPO with "Don't Check Default Browser" set to "disabled" and apply it to a OU
- install Firefox ESR 60.2 on a computer in that OU
- set Internet Explorer as the default browser
- run "gpupdate /force" on that computer
- Check registry for existence of DWORD
    HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox\DontCheckDefaultBrowser
  and notice it has the value 0, which looks right to me.
- restart Firefox and notice that it does NOT suggest to change the default browser
- check Firefox about:config for boolean attribute "browser.shell.checkDefaultBrowser"
  and notice that it is locked with value "false" instead of "true"

- in the GPO, set "Don't Check Default Browser" to "enabled"
- run "gpupdate /force"
- in the registry, the value of "DontCheckDefaultBrowser" changed to 1
- restart Firefox and notice that it does NOT suggest to change the default browser
- check Firefox about:config for boolean attribute "browser.shell.checkDefaultBrowser"
  and notice that it is still locked with value "false"

- in the GPO, set "Don't Check Default Browser" to "not configured"
- run "gpupdate /force"
- in the registry, the value of "DontCheckDefaultBrowser" has disappeared
- restart Firefox and notice that it DOES suggest to change the default browser
- check Firefox about:config for boolean attribute "browser.shell.checkDefaultBrowser"
  and notice that it is NOT locked with value "true"

  I would have expected the following to happen

    GPO "Don't Check Default Browser" set to "enabled" => "DWORD DontCheckDefaultBrowser" = 1 => "browser.shell.checkDefaultBrowser" = false
    GPO "Don't Check Default Browser" set to "disabled" => "DWORD DontCheckDefaultBrowser" = 0 => "browser.shell.checkDefaultBrowser" = true

**Comment by Chartman123** [comment]
Are there any news on this one? We're also facing this problem.

**Comment by mkaply** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1529312

Although I am curious why you want to lock it to true?

**Comment by Chartman123** [comment]
I want to lock it to true so that the browser always checks for "default browser" as we're switching from IE to FF at the moment.

**Comment by mkaply** [comment]
> I want to lock it to true so that the browser always checks for "default browser" as we're switching from IE to FF at the moment.

I can't complain about that :). I'll get this into the next Firefox release and ESR.

**Comment by mkaply** [comment]
This did make it in.
