### ISSUE TITLE
Search engine - wrong codepage?

### ISSUE THREAD

**Issue by Darlord** [mozilla/policy-templates#242]
I have a problem with setting search engine via GPO. According to settings file (http://search.skydns.ru/opensearch.xml):
URL Template: http://poisk.skydns.ru/search/?query={searchTerms}&r=1

When I enter in address field "йцу" (russian language), i've got:
String in address field of browser "https://poisk.skydns.ru/search/?query=%26%231081%3B%26%231094%3B%26%231091%3B&r=1"
String in search field of site page `"&#1081;&#1094;&#1091;"`

**Comment by mkaply** [comment]
This is bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1463684

I'll add this to the list to get fixed asap.

**Comment by Darlord** [comment]
This bug have been fixed in firefox 63, but not in esr 60.3, can you tell, when fix for this bug is tentatively scheduled in esr?

**Comment by mkaply** [comment]
I'll get this scheduled for the next ESR.
