### ISSUE TITLE
GPO Wish: Define key-value pairs for arbitrary preferences

### ISSUE THREAD

**Issue by kedia990** [mozilla/policy-templates#244]
Would it be possible to implement a policy setting that allows us to define key-value pairs to set arbitrary preferences, which then gets set via `pref()` (and maybe one each similarly for `lockPref()`, `defaultPref()` etc.)?

While I really appreciate the work that's gone towards creating bespoke policy settings for various preferences so far, there are going to be cases when we need the flexibility to enforce arbitrary preferences. By way of example, uBlock settings can be defined using the `extensions.ublock0.adminSettings` preference, and it strikes me as unreasonable that Mozilla's stock policy templates could foresee and provision for all of those. At the same time, they provide a lot of value.

Thanks!

**Comment by mkaply** [comment]
Already looking at it. The ublock stuff wouldn't work in a WebExtensions world, though. It can't read arbitrary preferences.

We're looking at managed chrome storage for that purpose.

**Comment by kedia990** [comment]
Got it - Thanks Mike! Appreciate the prompt response.

**Comment by mkaply** [comment]
We've started adding specific preferences in the new Preferences policy. If there are ones you need, 
please open a specific issue.

https://github.com/mozilla/policy-templates#preferences

And I've added support for chrome.storage.managed. You should check with the ublock folks to see if they plan to support that.

**Comment by mkaply** [comment]
FYI, I've added many more prefs

This is settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences
