### ISSUE TITLE
Block Gmail consumer accounts

### ISSUE THREAD

**Issue by rumpeltizkin** [mozilla/policy-templates#245]
I'm using policies for Firefox since the first day and I'm very happy, but there's one thing I really really miss from Chrome, to be able to block gmail consumer accounts, allowing only some corporate domains. At the moment we are using our firewall to accomplish that task, but it would be superb to transfer the task to the browser itself to relieve resources within the firewall.

Is it possible to do that in Firefox? I guess so, but maybe it needs a little work to be done.

Thanks.

**Comment by mkaply** [comment]
Chrome's documentation says you do this via a proxy server as well:

https://support.google.com/a/answer/1668854?hl=en

What policies does Chrome to allow this?

Based on that doc, a WebExtension could probably be easily written to do this.

**Comment by rumpeltizkin** [comment]
Yeah, the "standard" way to accomplish this is by using a proxy with SSL deep inspection, but Chrome has a plain policy that adds that header when it detects you're trying to login into gmail. It does not use any proxy configuration, it's the browser itself in charge of managing this.

**Comment by mkaply** [comment]
This will be in the release of Firefox that's coming out next week (esr and regular).

I implemented the AllowedDomainsForApps policy.
