### ISSUE TITLE
POP-up Allowed sites

### ISSUE THREAD

**Issue by Rukicc** [mozilla/policy-templates#253]
In group policy under POP-up  section under Allowed sites are option to white list all domain including subdomains.
This not work 100% as expected, because if site contains custom port numbers (for example http://example.com:8082 and http://example.com:8081 and http://example.com:8085) I must make record with domain name for each custom port number.

**Comment by mkaply** [comment]
This is working as designed. Firefox has the same behavior. 

Allowing popups is based on the origin and different port numbers are different origins.
