### ISSUE TITLE
GPO Wish:  Disable Browser session resume from crash

### ISSUE THREAD

**Issue by srt86** [mozilla/policy-templates#255]
It would be great to have a GPO to not restore a previous tab or session after a browser crash.

**Comment by jbostoen** [comment]
Also needing this. Used to do it with mozilla.cfg, which is now ignored?

**Comment by mkaply** [comment]
Can I ask the reason for wanting this?

> Also needing this. Used to do it with mozilla.cfg, which is now ignored?

You need to set an additional pref for mozilla.cfg to work now.

https://www.mozilla.org/en-US/firefox/62.0/releasenotes/

AutoConfig is sandboxed to the documented API by default. You
can disable the sandbox by setting the preference
general.config.sandbox_enabled to false. Our long term plan is to
remove the ability to turn off the sandboxing. If you need to
continue to use more complex AutoConfig scripts, you will need to use
Firefox Extended Support Release (ESR).

**Comment by jbostoen** [comment]
For a script, FireFox exits through JavaScript code. Therefore, a setting also needs to be adjusted ( dom.allow_scripts_to_close_windows ). Do I need to disable the sandbox if I just push this with a registry setting?

Anyhow, we noticed a lot of users who keep getting 'restore from crash' option rather than the intranet homepage. We've had quite a few remarks about this. That's why I want to disable it and push it.

**Comment by mkaply** [comment]
> For a script, FireFox exits through JavaScript code. Therefore, a setting also needs to be adjusted ( dom.allow_scripts_to_close_windows ). Do I need to disable the sandbox if I just push this with a registry setting?

That setting can only be pushed be mozilla.cfg, so yes, you would need to use the sandbox.

> Anyhow, we noticed a lot of users who keep getting 'restore from crash' option rather than the intranet homepage. We've had quite a few remarks about this. That's why I want to disable it and push it.

OK, I'll make a note.

**Comment by mkaply** [comment]
This should be settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences
