### ISSUE TITLE
Computer Group Policy Addons/Allowed Sites

### ISSUE THREAD

**Issue by jwillis44** [mozilla/policy-templates#259]
I'm having problems whitelisting through group policy. I am able to force install using a URL but not whitelist. 
What I would like to do is build a list of "approved" add on's that users can install but not let them install anything else and not force them installed if they do not require them.

For Example, I want to whitelist uBlock Origin, using URL: **https://addons.mozilla.org/firefox/downloads/file/1086463** (found URL from copying add to Firefox button link and stripping out the end?) I Enable the **Allowed Sites**, add that URL to the list and enable **allow add-on installs from websites**.
Once that is done I can install add-ons from anything I find in http://addons.mozilla.org . 

For grins I tried these settings under user configuration also with the same result.
Am I doing something wrong or is this not intended to do what I think it is?

I absolutely love that group policy support has been added. Thank you so much for the great work!
Joe

edit: I should mention version is 62.0.3 64 bit on Windows 10 1803 (17134.320)

**Comment by mkaply** [comment]
So the whitelist is about origins (like https://addons.mozilla.org) not URLs. So you can't whitelist a specific addon like that.

We've been asked to add whitelisting of addons and I'm looking at that.

**Comment by mkaply** [comment]
This is in the new ExtensionSettings policy. The GPO doesn't work on Windows yet (will in the next week), but you can test the functionality with policies.json,

https://github.com/mozilla/policy-templates#extensionsettings
