### ISSUE TITLE
FF 60 ESR GPO v1.2  - Allow Pop-Ups : Confusing Title/Description

### ISSUE THREAD

**Issue by 314ns** [mozilla/policy-templates#261]
In the ADMX templates version 1.2 for FF 60 ESR,  the "Allow Pop-ups for websites"  description states:

> If this policy is **disabled**, pop-up windows are **allowed** from websites by default.
> 
> If this policy is not configured or **enabled**, popups are **not allowed** from websites.

You would expect _disabling_ a setting that _allows_ something would _not allow_ such thing.  Therefore, either the title or the description is wrong.

**Comment by mkaply** [comment]
Finally fixed this. Sorry.

https://github.com/mozilla/policy-templates/commit/a5e0c5982d4f273eb04e14ef91c988575b2a9f95#diff-7109322a9280a0903013b42129b89b13
