### ISSUE TITLE
Add Support for "Advanced preferences"

### ISSUE THREAD

**Issue by basti12203** [mozilla/policy-templates#262]
Hello,
please add support for Advanced preferences so that we can set all possible preference values like "pref.privacy.disable_button.view_passwords" via GPO.
I have add this to firefox.admx and firefox.adml like (https://mozillagpo.sourceforge.io). The Values are created in the registry but firefox ignore this.

When i add the files from the link above to Firefox Installdir it works.
So please add the Support for "Advanced preferences" to the default Firefox GPO functionality or add the files from mozillagpo.sourceforge.io to the default installer to support this.

An other advantage of the last option would be that Thunderbird is also supported.

Rest Regards,

**Comment by UsoSka** [comment]
Definitely agree. With mozillagpo.sourceforge.io you were able to set every settings of about.config by GPO, wich was extremely useful !

**Comment by StFIT** [comment]
In this case could you please also consider of making it possible that users are forced to use a master password?
That would be a great benefit security-wise

**Comment by mkaply** [comment]
There are now policies for disabling viewing the password manager (and just disabling the viewing of saved passwords)
