### ISSUE TITLE
Use windows certificate store

### ISSUE THREAD

**Issue by vartaxe** [mozilla/policy-templates#264]
Hi,

The policy for using the windows certificate store doesnt seem to be working because i still have to manually import the certificate and check websites option though it works using the cck2 tool https://wiki.mozilla.org/CA:AddRootToFirefox

**Comment by mkaply** [comment]
If you go to about:config, is the preference security.enterprise_roots.enabled  set to true?

**Comment by vartaxe** [comment]
hi, yes it is set to true

**Comment by mkaply** [comment]
We're adding support for importing certificates. It should be in Firefox 64.

**Comment by vartaxe** [comment]
Thank god :D

**Comment by mkaply** [comment]
We have importing now. Client certificate is not a policy thing.
