### ISSUE TITLE
Windows example for install path in Extension policy

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/policy-templates#267]
Could you please expand the documentation for the Extension policy?
https://github.com/mozilla/policy-templates#extensions-machine-only

I am interested in an example of what the install path should look like on Windows. Usually a Windows path looks like:

`C:\Program Files\Mozilla Firefox\distribution\extension.xpi`

I know that backslashes has to be escaped in JSON so I expected the following as valid path:

`C:\\Program Files\\Mozilla Firefox\\distribution\\extension.xpi`

A user of my Enterprise Policy Generator add-on has reported that this does not work. He said that four (!) backslashes are necessary:

`C:\\\\Program Files\\\\Mozilla Firefox\\\\distribution\\\\extension.xpi`

I don't have a Windows system so I can't verify this. It would be great if the correct way to write Windows pathes in policies.json could be clarified in the documentation because I guess it's a common source of errors.

Thank you.

**Comment by mkaply** [comment]
Double backslashes work fine for me on Windows. There should be no reason to have four backslashes.
