### ISSUE TITLE
Extensions User Consent (Another Program on your computer)

### ISSUE THREAD

**Issue by Clickbaitcake** [mozilla/policy-templates#269]
_One again; thank you to Mike for all of this beautiful work. You are making Firefox in the enterprise possible._

I am trying to install uBlock Origin across my domain via the Extensions GPO. It seems to be installing just fine _but_ pops a message to the user asking for thier permission to **enable** it. 

`Another program on your computer installed an add-on that may affect your browser. 
Please review this addon's permissions requests and choose to Enable or Cancel `

**Is there anyway to force the installation of the addon without any user interaction?**

**Comment by mkaply** [comment]
That's odd. That message should only happen if you are installing via sideloading (registry or some other mechanism).

Is it possible you have some old code around that's installing the addon a different way?

In the mean time, I'll do some testing.

**Comment by Clickbaitcake** [comment]
@mkaply Your dead right. Old CCK2 file dropping the uBlock Origin in and triggering the warning. Thanks for the nudge. This can be closed.

**Comment by mkaply** [comment]
And thanks for the kind words.

**Comment by SecT0uch** [comment]
For the last update of UBlock Origin, it requires User Consent to update. (because of new permissions of the extension). Would it be possible to force updates even if it requires new permissions ?

**Comment by mkaply** [comment]
> For the last update of UBlock Origin, it requires User Consent to update. (because of new permissions of the extension). Would it be possible to force updates even if it requires new permissions ?

Did you force install uBlock origin?

**Comment by SecT0uch** [comment]
Yes, via the GPO

**Comment by mkaply** [comment]
> Yes, I forced the install across my domain via the GPO (it was a previous version), but to update to the new version it requires user consent on every computer.

I'll check into what we can do about that.
