### ISSUE TITLE
GPO Wish: Allways Sync Bookmarks from IE / Use Windows Bookmarks

### ISSUE THREAD

**Issue by hheinen** [mozilla/policy-templates#270]
Story time:
In corporate business environments it may be typical to work with a two browser strategy (main browser and fallback).
In this situations it would be helpful, if you could tell firefox, that it should use the "Bookmarks" under 'C:\User\bob\Favorites' and import them into firefox own bookmark system (and maybe even export them after firefox closeing into windows bookmark format and location).

Benefit for User:
The user always have the same bookmarks in both browsers.

Could we get this on the agenda or should I or anyone write a Addon for this? 
I know that we need to make changes on firefox itself, to achieve the goal.
Is there a chance we could convince the developers to get this done?

**Comment by mkaply** [comment]
We actually have this now. You can use preferences to import HTML bookmarks and save on exit:

browser.bookmarks.autoExportHTML
browser.bookmarks.file
browser.places.importBookmarksHTML
