### ISSUE TITLE
GPO Wish: Option to clear Cache only on exit.

### ISSUE THREAD

**Issue by TheCondor** [mozilla/policy-templates#276]
Is it possible to add an new option to clear the Cache only or separate all the options in "Clear all data when browser is closed"?
The use case is a terminal server, with a lot of user profiles.
But if I enable the "Clear all data when browser is closed" option, our users will trying to get us with pitchforks.

**Comment by tintinlu** [comment]
Hi, +1 ... Pleeeaazz ;))

**Comment by mkaply** [comment]
This is fixed in Firefox 68.

**Comment by TheCondor** [comment]
Thanks @mkaply :)
