### ISSUE TITLE
 "Disable System Add-on Updates" policy is not disabling update

### ISSUE THREAD

**Issue by amasresha** [mozilla/policy-templates#28]
Steps to reproduce:
1-  Enable the  "Disable System Add-on Updates" policy 
2-  Start Firefox
3- Go to about:config and set extensions.systemAddon.update.url to 
     http://felipc.github.io/blankupdate/update.xml
4- In to about:config set extensions.logging.enabled;true
    and restart the browser
5- Open browser console and verify the following script returns "false":
 Cu.import("resource://gre/modules/AddonManager.jsm").AddonManagerInternal.systemUpdateEnabled()

6-Run the following script again and check the string like "Starting system add-on update check"
Cu.import("resource://gre/modules/AddonManager.jsm"); AddonManagerPrivate.backgroundUpdateCheck()

Actual result:
It does not disable sys addon update

Expected Result:
It should disable sys addon update

**Comment by mkaply** [comment]
I just tested this and I do see false in step 5, but for step 6 I see lots of information on the console related to the update.

But I see the same behavior when I use the policy instead of the ADM template...

**Comment by amasresha** [comment]
Yes, this is working as intended. It is disabling sys addon update  We can close this issue.
