### ISSUE TITLE
Change granularity of BlockAboutAddons

### ISSUE THREAD

**Issue by StFIT** [mozilla/policy-templates#281]
Using BlockAboutAddons results not only in not being able to explore new addons as it was with cck2 but also not seeing any addons that are installed.
Is it possible to change this?

**Comment by mkaply** [comment]
Can you be more specific as to what you want? YOu want to block explore new addons but still show about:Addons?

**Comment by mkaply** [comment]
The new Preferences policy allows blocking just the explore pane.
