### ISSUE TITLE
GPO Wish: Prevent accessibility servies from accessing your browser

### ISSUE THREAD

**Issue by cypherstream** [mozilla/policy-templates#284]
We are in desperate need to find a way to mark a check in "Prevent accessibility services from accessing your browser" which is located in the Firefox Privacy & Security section.

Without this checked off, Firefox is extremely slow on Windows 7 machines with our screen recording software.

**Comment by mkaply** [comment]
this was added in firefox 70/ESR 68.2 in Preferences

accessibility.force_disabled
