### ISSUE TITLE
"component is not defined"components.utils.import don't working

### ISSUE THREAD

**Issue by pedroexpo** [mozilla/policy-templates#285]
In firefox 57 and firefox 60 version with the custom configuration file firefox.cfg this method worked correctly, however, when updating to version 61 does not work, is there any substitute to components.utils.import("resource://gre/modules/Services.jsm");
Through this method I managed to add exceptions for emerging elements and cookies.

 I would greatly appreciate your response. Thank you very much.

**Comment by mkaply** [comment]
Set the preferences:

general.config.sandbox_enabled

to false

In the JS file in your defaults/pref directory

**Comment by pedroexpo** [comment]
Thank you very much, for the great speed with which you have answered my question, it works perfectly.
I have added it to the JS file and it adds all the exceptions correctly.
Regards

**Comment by mkaply** [comment]
This won't work on rapid release forever. We are sandboxing Autoconfig. Can you give me more detail on exactly what you are doing and if it needs to be in policies? Otherwise you'll need to switch to ESR.

**Comment by pedroexpo** [comment]
Good, Sorry for answering so late, this setting is a policy crossing
through the use of configuration settings, configuration of the
autoconfig.js function as you told me it works perfectly. Many thanks.
Regards
