### ISSUE TITLE
Development Tool to test responsive design don't works

### ISSUE THREAD

**Issue by CLiX90** [mozilla/policy-templates#287]
If you apply one of the following policies, then it is not possible to use the dev tool to test screen sizes (Toggle Responsive Design Mode [ Ctrl + Shift + M ]). If you apply one of these policies and open the dev tool, then you will see only a blank screen.

Here are the policies I found out:
_Addons > Allow add-on installs from websites (disabled)
Block about:config (enabled)
Block about:profiles (enabled)
Disable Telemetry (enabled)_

I tested it with the actual firefox 63.0.1 and the policy pack v1.3. The issue exists also with the firefox ESR 60.3.0.

It sounds like a bug.

**Comment by mkaply** [comment]
I fixed this but unfortunately it was too late to make it into 63. The fix will be in 64 (and I'll get it on the ESR as well).

**Comment by CLiX90** [comment]
Good to hear. When it will be released?

**Comment by mkaply** [comment]
Early December. I'll try to get it in earlier.

**Comment by CLiX90** [comment]
Do we need to upgrade the Firefox Version or only the admx files? We have some internal release cycles and it would be great, if we could just update only the .admx files and use it with the Firefox ESR 60.3.
