### ISSUE TITLE
ImportEnterpriseRoots not working in one of our locations 

### ISSUE THREAD

**Issue by Clickbaitcake** [mozilla/policy-templates#288]
My company have been applying these great GPOs across our environment with _great success!_ Until today.

For some reason Firefox in this location refuses to import our root cert and is therefore not allowing our HTTPS inspection to work. (We MiTM our staff to stop data leakage) The setting works perfectly fine in our other offices. 

Under about:policies the browser shows **"Certificates	ImportEnterpriseRoots	true"** 

Is there anyway I can enable a debug or read a log to find out why Firefox is failing to import the cert? 

Thanks!

**Comment by mkaply** [comment]
So in our testing, the primary reason certain certs don't import is because they are missing an intermediate.

Is this a cert that is working everywhere else?

**Comment by Clickbaitcake** [comment]
Hi @mkaply I checked the thumbprint for the cert on a machine that is working and one that is not. I am quite certain the cert is the same and yes working everywhere else.

**Comment by Clickbaitcake** [comment]
Error from Firefox: **MOZILLA_PKIX_ERROR_MITM_DETECTED**

**Comment by Clickbaitcake** [comment]
I have not reported issues properly here and it turns out our lab is tainted. I have re-submitted my issue [291](https://github.com/mozilla/policy-templates/issues/291)
