### ISSUE TITLE
Configuring ADMX policies using Intune, certain settings not working

### ISSUE THREAD

**Issue by lilfurbal** [mozilla/policy-templates#289]
Hello,

I'm trying to using these ADMX templates to deploy to Azure AD joined machines through Microsoft Intune via the custom OMA-URI settings process.  Most of the settings I am trying to set work but some I don't understand what the expected value is supposed to be.

I first have the ADMX injecting into a Windows 10 machine just fine.  This setting gives an error every time the policy tries to apply:

```
URI - 
./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~Certificates\Certificates_ImportEnterpriseRoots

string value of "<enabled/>"
```

It seems the only valid values for this setting would be enabled or disabled yet this isn't working and don't know what it is expecting.  I can manually create a registry entry at HKEY_LOCAL_MACHINE\Software\Policies\Mozilla\Firefox\Certificates\ImportEnterpriseRoots with a dword value of 1 and it enables the cert import in the browser but would prefer to set this with the actual policy.

Likewise, I also cannot figure out how to set the policy 'Authentication_NTLM'.  Looks like it's expecting a list element.  For this I'd enter a value like this:

```
<enabled/><data id="Authentication" value="1&#xF000;https://inside.com&#xF000;2&#xF000;https://2inside.corp"/>
```

With the idea that it'll create registry entries in HKEY_LOCAL_MACHINE\Software\Policies\Mozilla\Firefox\Authentication\NTLM labeled by number and then URL.  Entering these registry keys manually works but trying to set this using the ADMX policy just gives errors.  The error is vague, just as though the expected format isn't correct.  

What is the correct OMA-URI based value these settings are expecting?

I also get an error trying to set this two policies:
OverrideFirstRunPage
OverridePostUpdatePage

Using this line:
```
<enabled/><data id="OverridePage" value="https://inside.com"/>
```

I do have a number of policies applied in this manner that are working correctly, such as the homepage URL, DisplayBookmarksToolbar, DisplayAppUpdate and Bookmarks.  

Like for example, this bookmark entry is formatted correctly and sets perfectly (for reference):

```
URI:
./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~Bookmarks/Bookmark02


Value:
<enabled/><data id="BookmarkTitle" value="Office 365 Login"/><data id="BookmarkURL" value="https://www.office.com/?auth=2"/><data id="BookmarkFolder" value="Managed Bookmarks"/><data id="BookmarkFavicon" value=""/><data id="BookmarkPlacement" value="toolbar"/>
```

I haven't really found any guides online covering setting Firefox settings using Intune, so I've been trying to figure it out based on Google Chrome ADMX guides which do exist.  Any guidance would be greatly appreciated, I feel these can all work if I know what values to enter.  Thanks

**Comment by mkaply** [comment]
ImportEnterpriseRoots should just be a DWORD 1 or 0.

Authentication NTLM expects an array of URLs. In the registry, they are 0 with a value of URL1, 1 with a value of URL2

I haven't done any investigation into InTune yet.

**Comment by lilfurbal** [comment]
Yeah, I have got it working with those values if entered as manual registry entries.  But can't get them to set using Intune admx ingestion specifically.  

Here's some information regarding how Intune actually does this:

https://docs.microsoft.com/en-us/windows/client-management/mdm/understanding-admx-backed-policies

https://blogs.technet.microsoft.com/senthilkumar/2018/05/21/intune-deploying-admx-backed-policies-using-microsoft-intune/

The google chrome intune management guide I was using as a general reference for the FF management:
https://blogs.technet.microsoft.com/ukplatforms/2018/05/30/google-chrome-gpo-via-intune/

As was mentioned several of the FF polices do work as expected, whereas the ones I discussed I found do not for some reason.  As a workaround for the time being I can just send a powershell script to these machines that directly set registry keys for the values I can't get to work through normal policy assignment.  If/when you guys are able to review how this works with Intune I'll be up for giving any possible solutions a go.  

Thank you! 

> ImportEnterpriseRoots should just be a DWORD 1 or 0.
> 
> Authentication NTLM expects an array of URLs. In the registry, they are 0 with a value of URL1, 1 with a value of URL2
> 
> I haven't done any investigation into InTune yet.

**Comment by mkaply** [comment]
It sounds like the ones that aren't working are the ones that are nested whereas the ones that work are top level.

Can you explain the underscore thing?

Certificates_ImportEnterpriseRoots

We're looking for Certificates\ImportEnterpriseRoots

**Comment by lilfurbal** [comment]
I got the _ by actually looking inside the firefox.admx in notepad++.  Such as this section:

```
    <policy name="Certificates_ImportEnterpriseRoots" class="Both" displayName="$(string.Certificates_ImportEnterpriseRoots)" explainText="$(string.Certificates_ImportEnterpriseRoots_Explain)" key="Software\Policies\Mozilla\Firefox\Certificates" valueName="ImportEnterpriseRoots">
      <parentCategory ref="Certificates"/>
      <supportedOn ref="SUPPORTED_FF60"/>
      <enabledValue>
        <decimal value="1"/>
      </enabledValue>
      <disabledValue>
        <decimal value="0"/>
      </disabledValue>
    </policy>
```

I refer to its policy name in the URI, the URI is also represented in this registry location after the ADMX is successfully injected:

```
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\AdmxDefault\(GUID)\Firefox~Policy\firefox\Certificates\Certificates_ImportEnterpriseRoots
```

Likewise the NTLM shows up as 'Authentication\Authentication_NTLM'.  I think I tried removing the repeated text before the _ already but that was also unsuccessful.

**Comment by mkaply** [comment]
Certificates_ImportEnterpriseRoots is the internal name, not how it is represented in the registry in Firefox.

n the registry, it's a DWORD value called "ImportEnterpriseRoots" that's inside the 

Software\Policies\Mozilla\Firefox\Certificates

key.
![import](https://user-images.githubusercontent.com/345868/48080429-42bedb80-e1b3-11e8-800b-523fbb0d36a7.JPG)

I'm not sure how Intune works, but it sounds like it's not creating the correct registry key.

**Comment by lilfurbal** [comment]
Ahhh, ok, it appears I kept continuously messing this up.  The URI is supposed to reference the actual policy name, so 'Certificates_ImportEnterpriseRoots' is correct.  What I just now finally noticed is that, as shown in the original post even, I had a \ in place where there should have been a /...

Firefox~Policy~firefox~Certificates\Certificates_ImportEnterpriseRoots

Should be:

Firefox~Policy~firefox~Certificates/Certificates_ImportEnterpriseRoots

with a string value of '<enabled/>'

Policy finally applied successfully.  Same issue with NTLM.  And everything else for that matter that wasn't working.  Hah, ok, nevermind then, there appears to be no issues after all.  Thanks much for reviewing this anyway :)

**Comment by mkaply** [comment]
Actually, it's great that you are doing this. IS there anything we can write up about Intune based on what you've discovered?

**Comment by lilfurbal** [comment]
Potentially a guide basically saying it can be done and referencing some of Microsoft's technet documentation as I shared above would be good, along with some actual examples that applies to Firefox specifically.  Especially some of the more complex settings that I figured out with some trial and error, such as the bookmarks.  Let's see...

From Intune, creating a new Windows 10 custom configuration profile, you'd first inject the firefox.admx.

```
The OMA-URI would be:

./Vendor/MSFT/Policy/ConfigOperations/ADMXInstall/Firefox/Policy/FirefoxAdmx

Data Type - String
Value:
Copy and paste contents of entire .admx file from notepad.

```

Adding a new OMA-URI setting you can then add policy settings, such as the HomepageURL, looks like this:


```
OMA-URI:
./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~Homepage/HomepageURL

Data Type - String
Value:
<enabled/><data id="HomepageURL" value="https://www.office.com"/><data id="HomepageLocked" value="false"/>
```

That sets the homepage and the value for whether or not it's locked for editing by the end user.

A bookmark entry looks like this:

```
OMA-URI:
./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~Bookmarks/Bookmark02

Data Type - String
Value:
<enabled/><data id="BookmarkTitle" value="Office 365 Login"/><data id="BookmarkURL" value="https://www.office.com/?auth=2"/><data id="BookmarkFolder" value="Managed Bookmarks"/><data id="BookmarkFavicon" value=""/><data id="BookmarkPlacement" value="toolbar"/>
```

That one has a lot of different values that need to be set for it to be accepted, even if the value is blank for an item.

Setting the Authentication_NTLM URLs:

```
OMA-URI:
./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~Authentication/Authentication_NTLM

Data Type - String

Value:

<enabled/><data id="Authentication" value="1&#xF000;http://URL1&#xF000;2&#xF000;http://URL2&#xF000;3&#xF000;http://URL3"/>
```

The formatting of that value is important.  Since the entries are written to the registry as 1 = URL, for this type of entry to be entered correctly here it requires a &#xF000; be entered between each entry.  

So it reads **1** &#xF000; **URL1** &#xF000; **2** &#xF000; **URL2** &#xF000; **3** &#xF000; **URL3**

This would probably be enough information to get people started with setting these up, would have saved me some time, that's for sure.  

Thanks!
