### ISSUE TITLE
Feature Request: certificate in the Firefox certificate  store

### ISSUE THREAD

**Issue by FGAGwendalG** [mozilla/policy-templates#29]
Hello,

One feature that will be greatly appreciated would be the ability to import certificates into the Firefox certificate store. Indeed, Firefox does not use the Windows store

Regards,

**Comment by mkaply** [comment]
Firefox does have this ability by adding a new preference:

security.enterprise_roots.enabled 

and setting it to true.

We will have the ability to change this pref in group policy.

**Comment by FGAGwendalG** [comment]
Hello,
Do you mean that with this setting, Firefox uses Windows certificate stores?

**Comment by mkaply** [comment]
Yes.

**Comment by wesdonohue** [comment]
I'd like to second this request. I'm aware of the preference, but have been waiting for these management capabilties to be able to enable it through gpo. The single reason we haven't been able to do SSL decryption in our company is because of all of the users using firefox. Glad to hear it's going to be added. Any ETA?

**Comment by mkaply** [comment]
We're targeting our enteprise features for Firefox 60

https://www.mozilla.org/en-US/firefox/enterprise/

**Comment by wesdonohue** [comment]
I'm aware of that and have 60 installed. Based on the release notes for the beta these are the gpo templates to use with it. Is that correct or is there a different set of admx files somewhere?

**Comment by amaccuish** [comment]
@wesdonohue this has already been requested in #11, and a bug filled https://bugzilla.mozilla.org/show_bug.cgi?id=1446477. This is a work in progress.
