### ISSUE TITLE
GPO Wish List : Add Security policies to Comply with NIST

### ISSUE THREAD

**Issue by ttaylor1on** [mozilla/policy-templates#290]
Here is the contents of my config file. It would be great to be able to do the with a GPO instead.

// IMPORTANT: Start your code on the 2nd line
//DTBF030 - Firefox must be configured to allow only TLS
LockPref (“security.enable_tls”, true);
LockPref (“security.enable_ssl2”, false);
LockPref (“security.enable_ssl3”, false);
LockPref (“security.tls.version.min”, 2);
LockPref (“security.tls.version.max”, 3);

//DTBF050 - FireFox is configured to ask which certificate to present to a web site when a certificate is required. 
lockPref(“security.default_personal_cert”, “Ask Every Time”);

//DTBF070 - Firefox required security preferences cannot be changed by user. - app.update.enabled 
lockPref(“app.update.enabled”, false);

//DTBF070 - Firefox required security preferences cannot be changed by user. - browser.download.dir
lockPref(“browser.download.useDownloadDir”, true);

//DTBF070 - Firefox required security preferences cannot be changed by user. browser.formfill.enable
lockPref(“browser.formfill.enable”, false);

//DTBF070 - Firefox required security preferences cannot be changed by user. browser.search.update
lockPref(“browser.search.update”, false);

//DTBF070 - Firefox required security preferences cannot be changed by user. browser.shell.checkDefaultBrowser
lockPref(“browser.shell.checkDefaultBrowser”, false);

//DTBF070 - Firefox required security preferences cannot be changed by user. dom.disable_open_during_load
lockPref(“dom.disable_open_during_load”, true);

//DTBF070 - Firefox required security preferences cannot be changed by user. dom.disable_window_flip
lockPref(“dom.disable_window_flip”, true);

//DTBF070 - Firefox required security preferences cannot be changed by user. dom.disable_window_move_resize
lockPref(“dom.disable_window_move_resize”, true);

//DTBF070 - Firefox required security preferences cannot be changed by user. dom.disable_window_open_feature.status
lockPref(“dom.disable_window_open_feature.status”, true);

//DTBF070 - Firefox required security preferences cannot be changed by user. dom.disable_window_status_change
//I do not see this parameter in the about:config file

//DTBF070 - Firefox required security preferences cannot be changed by user. dom.event.contextmenu.enabled
lockPref(“dom.event.contextmenu.enabled”, false);

//DTBF070 - Firefox required security preferences cannot be changed by user. extensions.update.enabled
lockPref(“extensions.update.enabled”, false);

//DTBF070 - Firefox required security preferences cannot be changed by user. - network.protocolhandler.external.shell
lockPref(“network.protocol-handler.external.shell”, false);

//DTBF070 - Firefox required security preferences cannot be changed by user. plugin.disable_full_page_plugin_for_types
lockPref(“plugin.disable_full_page_plugin_for_types”, “application/pdf,application/doc,application/xls,application/bat,application/ppt,application/mdb,application/mde,application/fdf,application/xfdf,application/lsl,application/lso,application/lss,application/iqy,application/rqy,application/xlk,application/pot,application/pps,application/dot,application/wbk,application/ps,application/eps,application/wch,application/wcm,application/wbi,application/wb1,application/wb3,application/rtf,application/wch,application/wcm,application/ad,application/adp,application/xlt,application/dos,application/wks”);

//DTBF070 - Firefox required security preferences cannot be changed by user. - privacy.item.history
//I do not see this parameter in the about:config file

//DTBF070 - Firefox required security preferences cannot be changed by user. security.warn_leaving_secure
//I do not see this parameter in the about:config file

//DTBF070 - Firefox required security preferences cannot be changed by user. - signon.prefillForms
//Ensure the preference ' signon.prefillForms ' is set and locked to the value of 'False'.
lockPref(“signon.autofillForms”, false);

//DTBF070 - Firefox required security preferences cannot be changed by user. signon.rememberSignons
lockPref(“signon.rememberSignons”, false);

//DTBF070 - Firefox required security preferences cannot be changed by user. xpinstall.whitelist.required
lockPref(“xpinstall.whitelist.required”, true);
lockPref(“signon.autofillForms.http”, false);

//DTBF080 - Firefox application is set to auto-update.
lockPref(“app.update.auto”, true);

//DTBF085 - Firefox automatically checks for updated version of installed Search plugins.
lockPref(“browser.search.update”, false);

//DTBF090 - Firefox automatically updates installed add-ons and plugins.
lockPref(“extensions.update.enabled”, false);

//DTBF130 - Firefox is not configured to provide warnings when a user switches from a secure (SSLenabled) to a non-secure page.
//Ensure the preference 'security.warn_leaving_secure' is set to 'true' and locked on this setting.
//I do not see this parameter in the about:config file

//DTBF170 - History retention must be enabled.
lockPref(“places.history.enabled”, true);

//not on scan but recommended
lockPref(“security.enterprise_roots.enabled”, true);
lockPref(“datareporting.policy.dataSubmissionEnabled”, false);

**Comment by asadotzler** [comment]
for security.tls.version.min see issue #283

**Comment by EricSP2** [comment]
Spaaaaaaamm... Can you please send all in one message

**Comment by mkaply** [comment]
What is the document that these come from? These only partially correspond to the DOD STIG.

I ask because many thing in here don't apply anymore and I'd like to talk to the author of this spec.

**Comment by mkaply** [comment]
The relevant prefs in this have been added with Firefox 68.
