### ISSUE TITLE
GPO Wish: Configure Print defaults

### ISSUE THREAD

**Issue by PhilippvK** [mozilla/policy-templates#292]
We really want to migrate our CCK2 config to GPO.

One feature missing on the list is setting the default print settings.

We especially need to change `print.print_paper_name` in our configuration.

Thank you. I would really appreciate this feature.

**Comment by buchser** [comment]
Agree! We need to set the paper formats Letter or A4 in our environement... If this could be solved, we could use the integrated PDF viewer and would no more depend on Adobe Acrobat

**Comment by mkaply** [comment]
All these preferences are now available via the Preferences policy:

https://github.com/mozilla/policy-templates/blob/master/README.md#preferences
