### ISSUE TITLE
GPO Wish List: Add a few missing features

### ISSUE THREAD

**Issue by Legion87** [mozilla/policy-templates#293]
Hi Mike, hope you're well. 

First of all thank you for all the effort you invest, otherwise it wouldn't be possible to use the Firefox in an Enterprise environment. Really appreciated!

As I'm also a huge fan of your CCK, I miss some features at the new GPOs, of course most of the old settings are already available. So it would be great if you could have a short look at the following options, maybe you could add a few to the new GPO admx files:

Options | General | Files and Applications | Downloads | Always ask you where to save files
`"browser.download.useDownloadDir",false`

Options | General | Firefox Updates | Allow Firefox to | Automatically install updates (recommended)
`lockPref("app.update.auto", true)`

Options | Privacy & Security | History | Firefox will | Never remember history
`"browser.privatebrowsing.autostart", true`

Options | Privacy & Security | Permissions | Warn you when websites try to install add-ons
`lockPref("xpinstall.whitelist.required", true)`

Options | Privacy & Security | Firefox Data Collection and Use | Allow Firefox to send backlogged crash reports on your behalf
`lockPref("browser.crashReports.unsubmittedCheck.autoSubmit2, false)`

Options | Privacy & Security | Security | Deceptive Content and Dangerous Software Protection
```
lockPref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", true)
lockPref("browser.safebrowsing.downloads.remote.block_uncommon", true)
lockPref("browser.safebrowsing.downloads.enabled", true)
lockPref("browser.safebrowsing.malware.enabled", true)
lockPref("browser.safebrowsing.phishing.enabled", true)
```

Add-ons Manager | Extensions | Tools for all add-ons | Update Add-ons Automatically
```
lockPref("extensions.update.autoUpdateDefault", true)
lockPref("extensions.update.enabled", true)
lockPref("extensions.blocklist.enabled", true)
```

New Tab Preferences (like about:blank) - Remove Search, Top Sites, Highlights, Snippets
```
"browser.newtabpage.activity-stream.feeds.section.highlights", false
"browser.newtabpage.activity-stream.feeds.snippets", false
"browser.newtabpage.activity-stream.showSearch", false
"browser.newtabpage.activity-stream.showTopSites", false
"browser.newtabpage.activity-stream.prerender", false
```

Always automatically open new tab if you hit enter in search bar:
`"browser.search.openintab", true`

Possibility to change the session store from 15 up to 120 sek. 
http://kb.mozillazine.org/Browser.sessionstore.interval
`"browser.sessionstore.interval", 60000`

Don't show the rights notification
`lockPref("browser.rights.3.shown", true)`

Prevent accessibility services from accessing your browser
`"accessibility.force_disabled", 1`

Additional Requests:

Options | General | General | Startup | "Make Default..."
Please lock that item, to prevent the user from clicking on the button.

Options | Privacy & Security | Browser Privacy | Forms & Passwords | "Saved Logins..."
Please lock that item, to prevent the user from clicking on the button.

Possibility to add commands for installed extensions like "uBlock Origin":
`"extensions.ublock0.adminSettings", "{\"timeStamp\":1507709780405,\"version\":\"1.14.14\",\"userSettings\":{\"advancedUserEnabled\":false,\"alwaysDetachLogger\":false,\"autoUpdate\":true,\"cloudStorageEnabled\":false,\"collapseBlocked\":true,\"colorBlindFriendly\":false,\"contextMenuEnabled\":true,\"dynamicFilteringEnabled\":false,\"externalLists\":\"https://mirror1.malwaredomains.com/files/immortal_domains.txt\\nhttps://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt\\nhttps://www.fanboy.co.nz/r/fanboy-ultimate.txt\",\"firewallPaneMinimized\":true,\"hyperlinkAuditingDisabled\":true,\"ignoreGenericCosmeticFilters\":false,\"largeMediaSize\":50,\"parseAllABPHideFilters\":true,\"prefetchingDisabled\":true,\"requestLogMaxEntries\":1000,\"showIconBadge\":true,\"tooltipsDisabled\":false,\"webrtcIPAddressHidden\":false},\"selectedFilterLists\":[\"https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt\",\"https://mirror1.malwaredomains.com/files/immortal_domains.txt\",\"DEU-0\",\"plowe-0\",\"fanboy-social\",\"fanboy-cookiemonster\",\"fanboy-thirdparty_social\",\"fanboy-annoyance\",\"adguard-annoyance\",\"spam404-0\",\"disconnect-malware\",\"malware-1\",\"malware-0\",\"disconnect-malvertising\",\"fanboy-enhanced\",\"easyprivacy\",\"adguard-spyware\",\"easylist\",\"adguard-generic\",\"awrl-0\",\"ublock-unbreak\",\"ublock-abuse\",\"ublock-privacy\",\"ublock-badware\",\"ublock-filters\",\"user-filters\",\"https://www.fanboy.co.nz/r/fanboy-ultimate.txt\"],\"hiddenSettingsString\":\"assetFetchTimeout 30\\nautoUpdateAssetFetchPeriod 120\\nautoUpdatePeriod 7\\nignoreRedirectFilters false\\nignoreScriptInjectFilters false\\nmanualUpdateAssetFetchPeriod 2000\\npopupFontSize unset\\nsuspendTabsUntilReady false\\nuserResourcesLocation unset\",\"netWhitelist\":\"behind-the-scene\\nchrome-extension-scheme\\nchrome-scheme\\nmoz-extension-scheme\\nnewtab.about-scheme\\nopera-scheme\\nvivaldi-scheme\\nvts.inxpo.com\",\"dynamicFilteringString\":\"behind-the-scene * 3p-frame noop\\nbehind-the-scene * 3p noop\",\"urlFilteringString\":\"\",\"hostnameSwitchesString\":\"\",\"userFilters\":\"\",\"filterLists\":{\"https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resource-abuse.txt\":{\"off\":false},\"https://mirror1.malwaredomains.com/files/immortal_domains.txt\":{\"off\":false},\"https://easylist-downloads.adblockplus.org/easylistgermany.txt\":{\"off\":false},\"assets/thirdparties/pgl.yoyo.org/as/serverlist\":{\"off\":false},\"https://easylist-downloads.adblockplus.org/fanboy-social.txt\":{\"off\":false},\"fanboy-cookiemonster\":{\"off\":false},\"https://www.fanboy.co.nz/fanboy-antifacebook.txt\":{\"off\":false},\"https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt\":{\"off\":false},\"adguard-annoyance\":{\"off\":false},\"https://raw.githubusercontent.com/Dawsey21/Lists/master/adblock-list.txt\":{\"off\":false},\"https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt\":{\"off\":false},\"assets/thirdparties/mirror1.malwaredomains.com/files/justdomains\":{\"off\":false},\"assets/thirdparties/www.malwaredomainlist.com/hostslist/hosts.txt\":{\"off\":false},\"https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt\":{\"off\":false},\"https://www.fanboy.co.nz/enhancedstats.txt\":{\"off\":false},\"assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt\":{\"off\":false},\"adguard-spyware\":{\"off\":false},\"assets/thirdparties/easylist-downloads.adblockplus.org/easylist.txt\":{\"off\":false},\"adguard-generic\":{\"off\":false},\"https://easylist-downloads.adblockplus.org/antiadblockfilters.txt\":{\"off\":false},\"assets/ublock/unbreak.txt\":{\"off\":false},\"ublock-abuse\":{\"off\":false},\"assets/ublock/privacy.txt\":{\"off\":false},\"assets/ublock/badware.txt\":{\"off\":false},\"assets/ublock/filters.txt\":{\"off\":false},\"assets/user/filters.txt\":{\"off\":false},\"https://www.fanboy.co.nz/r/fanboy-ultimate.txt\":{\"off\":false},\"assets/ublock/experimental.txt\":{\"off\":true}}}"`

Prevent Discovering Add-ons in the Add-ons Manager - seems to be removed, is there another way to not block the whole Add-ons Manager?
`lockPref("extensions.getAddons.showPane", false)`

Thank you. 

Kind regards
Rob

**Comment by asadotzler** [comment]
for Prevent accessibility services from accessing your browser see #284

**Comment by asadotzler** [comment]
For downloads location, see also issue #160

**Comment by MCHuijgen** [comment]
I'm in favor for browser.crashReports.unsubmittedCheck.autoSubmit2 as well

And also a new one: extensions.autoDisableScopes

**Comment by mkaply** [comment]
Most of these are available as of tomorrow:

https://github.com/mozilla/policy-templates#preferences

The scopes stuff will not be available.
