### ISSUE TITLE
Extensions uninstall only runs once

### ISSUE THREAD

**Issue by wykydtron253** [mozilla/policy-templates#294]
Configuring a policy to uninstall an extension via ID only appears to run once unless the extensions field was edited again.  Is it not intended behavior to uninstall a specific extension at every app startup?

Example:
1 Install extension
2 Apply extension policy, upon launch firefox will remove the extension
3 Reinstall extension, re launch firefox. The extension does not get removed again.

In testing, I added another extension ID to the policies.json, and relaunched firefox. It uninstalled the originally scoped policy that was reinstalled in step3.

Running the debugger produces this output if I do not edit the policy file.
"Policies.jsm: Not running action extensionsUninstall again because the policy's value is unchanged"

**Comment by RakeshUP** [comment]
I am also facing the same issue. Is this the default behaviour??

**Comment by mkaply** [comment]
This is resolved with the new ExtensionSettings policy.

We uninstall at every startup.

https://github.com/mozilla/policy-templates#extensionsettings
