### ISSUE TITLE
A clear instruction is needed to configure extensions.

### ISSUE THREAD

**Issue by IRainman** [mozilla/policy-templates#295]
For example, I want this extension to be installed automatically and so that it cannot be turned off and removed:
https://addons.mozilla.org/ru/firefox/addon/h264ify/
How to do it?

{
  "policies": {
    "Extensions": {
      "Install": ["https://addons.mozilla.org/firefox/WHAT????", "//path/to/xpi"],
      "Locked":  ["WHY_ID???@mozilla.org"]
    }
  }
}

**Comment by mkaply** [comment]
I agree. I'll put an article together on this.

**Comment by mkaply** [comment]
The quick answer to your question is:

Install:

https://addons.mozilla.org/firefox/downloads/file/1085396/h264ify-latest-an+fx.xpi

Extension ID:

    jid1-TSgSxBhncsPBWQ@jetpack

I'll write an article as to how I got there.

**Comment by mkaply** [comment]
The new ExtensionSettings policy is much better documented and provides the features you need:

https://github.com/mozilla/policy-templates#extensionsettings
