### ISSUE TITLE
GPO policies disable all options defined in  local policies.json file  even if they are not defined in GPO

### ISSUE THREAD

**Issue by beware-of-froggy** [mozilla/policy-templates#296]
Hello 

Is this by design ?

GPO policies disable all options defined in  local policies.json file  even if they are not defined in GPO if only one option is defined by GPO.

 I  inject the policies.json file into a Firefox windows installer repackaged as I usually do to have a package with basic initial lock options that I could later change GPO options to business use and changes to the information system.

I do this with many programs like Microsoft Office to distribute a corporate basic lock package whether the computer is managed by GPO or not to lock the package.

I use the enterprise-policy-generator extension developed by Sören Hentzschel https://github.com/cadeyrn to create de inital policies.json file. 

I then inject it with the usual procedure into a repackaged windows firefox installer.

All is working fine and the lock options defined in policies.json are respected.

but if I change just one option per GPO it disable all the other parameters defined locally. Which is unfortunate. It is normal business operation that an option set by GPO overrides a locally defined option, but not that undefined or disabled options on the GPO override other locally defined options. An option defined locally should remain so if it is undefined or disabled by GPO by doing a merge of parameters which is the usual operation of GPOs

**Comment by mkaply** [comment]
Yes, policies.json and GPO cannot coexist.

GPO is read and policies.json is ignored.

This is so a local user cannot use a policies.json to override corporate policies.

**Comment by beware-of-froggy** [comment]
Hello M MKAPLY,

Thank you for your answer.

It's not possible for futur version to first read local policy.json, and then the GPO override the parameters defined locally ? (if parameter present in GPO is also present in local policy.json)

( thank you also for your work for years for the management of firefox in business, great help for me :-)

**Comment by mkaply** [comment]
> It's not possible for futur version to first read local policy.json, and then the GPO override the parameters defined locally ? (if parameter present in GPO is also present in local policy.json)

I'm thinking about it. I've had other requests for this.

**Comment by mkaply** [comment]
This was fixed a while ago. policies.json now augments GPO but cannot override it.
