### ISSUE TITLE
GPO Wish: Force Full Screen / Disable URL Bar

### ISSUE THREAD

**Issue by zeeter82** [mozilla/policy-templates#298]
We are trying to create a locked down Firefox ESR that operates in "kiosk" mode.  We definitely would like the URL/address/search bars hidden and launching in full screen would be nice too.  CCK2 and policies don't seem to be able to accomplish this yet.

Thanks!

**Comment by asadotzler** [comment]
See also #247

**Comment by mkaply** [comment]
I'm going to close this for now as it's not really policy related, but we have kiosk mode on our roadmap for 3Q this year.
