### ISSUE TITLE
GPO New search engine and accent

### ISSUE THREAD

**Issue by Izanagi52** [mozilla/policy-templates#305]
Hello,
I want to add Qwant Lite as default search engine in Firefox 60.3.0 ESR with GPO. I have succefully done it, but there is a problem when I make a research with any character with accent (é, è, à, ...)
Example : testé
Become : test%E9

I have tested with the Qwant Lite Extension, which have exactly the same parameters than my GPO, and there is no problem, so I don't understand why... 

Thanks !

![gpo](https://user-images.githubusercontent.com/21294450/49793212-f415db80-fd34-11e8-90fe-6b9d63f152bc.png)

**Comment by mkaply** [comment]
This is fixed in the 60.4 ESR which is released today.

**Comment by Izanagi52** [comment]
Thanks !
