### ISSUE TITLE
Set policies for new installs only

### ISSUE THREAD

**Issue by ArjenBalfoort** [mozilla/policy-templates#310]
Now, every time I update policies.json existing users find their configuration changed. In a corporate environment I can understand that but as a Linux distribution maintainer, that is not something I want my users to be bothered with.

Is it possible to implement the policies for new installs only, leaving existing user configuration as-is?
Possibly disabling runOncePerModification?

**Comment by mkaply** [comment]
You shouldn't be using policies for a distro. That's not what they are intended for.

What exactly are you trying to do?

**Comment by ArjenBalfoort** [comment]
That's fast!

I just set some default things for the new user: homepage, bookmarks, addons, etc. I did that first with placing the needed files in /etc/skel but that is cumbersome to maintain.

Here's the source: https://github.com/SolydXK/firefox-solydxk-adjustments/blob/master/usr/share/solydxk/firefox/policies.json

**Comment by mkaply** [comment]
I would suggest doing that via distribution.ini. That's how current distros do it:

https://mike.kaply.com/2012/03/26/customizing-firefox-distribution-ini/

**Comment by mkaply** [comment]
No, you'll have to use a policies.json file for that one thing.

**Comment by ArjenBalfoort** [comment]
I've been unable to implement these changes with distribution.ini (please, correct me if I'm wrong):

- DisableAppUpdate: as mentioned by ilu33.
- DisplayBookmarksToolbar: always show the bookmarks toolbar.
- NoDefaultBookmarks: remove the default bookmarks.
- SearchEngines: set the default search engine and remove unwanted search engines.

Neither distribution.ini nor policies.json can set userContent.css and userChrome.css. I couldn't place these files in the defaults directory because that was dropped which forced me to put these files in /etc/skel forcing the user's Firefox directory to a fixed name.

Thunderbird (60.3) was even worse: distribution.ini and policies.json are not yet implemented but the distribution/extensions and distribution/searchengines directories work properly.

All in all this has been a steep learning curve and I'm a bit disappointed that I ended up with a less than ideal solution.

If you're interested, here's the source:
https://github.com/SolydXK/firefox-solydxk-adjustments
https://github.com/SolydXK/thunderbird-solydxk-adjustments

**Comment by mkaply** [comment]
I didn't realize you were a Linux distro. You cannot make these changes to Firefox and redistribute it without an agreement with Mozilla.

See:

https://www.mozilla.org/en-US/foundation/trademarks/distribution-policy/

Please send an email to trademark-permissions@mozilla.com to make this.

**Comment by mkaply** [comment]
That sounded harsh and I didn't mean it to. We allow some limited customizations for Linux distros, but not to this degree (especially not search engines). If you have companies/individuals that want to make these customizations, you can provide them information on how to do that, but you cannot redistribute Firefox with these changes yourself without our permission.

Do you support Flatpaks or Snaps? We're working on providing official Firefox distros via those distribution mechanisms.

As far as disabling app update goes, how are you ensuring users have the latest version of Firefox?

**Comment by ArjenBalfoort** [comment]
>     SearchEngines: set the default search engine and remove unwanted search engines.
> 
> Why would you need to do that?

I aim to create a an environment that respect our user's privacy as much as possible. 

I interpreted the Firefox Distribution Policy that I cannot change Firefox itself. It doesn't mention external packages that make those changes. Therefor we download and package Firefox without any changes. The above mentioned configuration will be available in a separate package and can be removed by the user.

I will send them an e-mail to see if my interpretation was correct.

> As far as disabling app update goes, how are you ensuring users have the latest version of Firefox?

A cron job checks for a new version every day and is automatically packaged and uploaded to the repository when there is a new version.

> Do you support Flatpaks or Snaps? We're working on providing official Firefox distros via those distribution mechanisms.

There has been some discussion in our community but I haven't looked at it yet. Probably because the workload maintaining this distribution is manageable (I'm the only developer).

Thanks again for all your help and don't worry about the tone of your posts: I'm Dutch and directness is very much appreciated :)

**Comment by ilu33** [comment]
I would appreciate it if Mozilla would rethink its design decision regarding updates or, better even, introduce a Linux-repository-friendly configuration option.

Every decent Linux distro serves an unaltered firefox via their repository. So do we. Updates are only served via the repository, that's what the repository is for. The nag popup is completely useless and only confusing for the user. A running Firefox technically *cannot* update itself without root privileges, no matter what the user clicks. And whenever a new version is available it takes only a short time until the repo serves the update anyway.
A well cared for repository is the best way to ensure that a system is always up-to-date.

As you said, a policy is not the correct way to remedy this situation. But the regular nag popup we can't remove any other way confuses our users, especially the elders among them.

**Comment by mkaply** [comment]
Well, what I'd rather have is that every Linux distro stops shipping Firefox and users our official builds once we have Flatpak/Snaps.

The core problem is that there are a ton of different Firefox builds out there.

When you say "unaltered" do you mean you are actually using the build from Mozilla? Or are you compiling it?

**Comment by ilu33** [comment]
Quoting Arjen: "Therefor we download and package Firefox without any changes. " 

Flatpak/Snaps have a lot of issues regarding support and reliability. I don't think Debian (which we rely on) will embrace that concept. We have the repository as "single point of trust" and I'd like that to stay. That's the main Linux selling point. One of the problems with MS Win is that users get their software from who-knows-where on the internet. Flatpak/Snap is extending that problem onto Linux - a very bad idea.

So no, Flatpak/Snap will not solve anything.

**Comment by mkaply** [comment]
I guess the question would be how to mark Firefox as "This gets updates from somewhere else" without also providing a vector for malware to turn off Firefox updates (which is the problem we were trying to solve).

What do you see as an issue with using policies.json to turn off updates at the OS level (packaging a policies.json with your Firefox)

**Comment by mkaply** [comment]
> Yes, that would be a better formulated question and to ask the obvious: do you know how to set this behavior other than by setting DisableAppUpdate?

No. We specifically removed the ability to do this via prefs.

> No problem at all. It's just that I would have preferred a single method to configure Firefox instead of three (distribution.ini, policies.json and files in /etc/skel).

policies.json is the only way to DisableAppUpdate, so you will always be stuck with that. That was a deliberate choice.

Can you explain the files in /etc/skel?

**Comment by ArjenBalfoort** [comment]
> Can you explain the files in /etc/skel?

This is needed for userContent.css and userChrome.css.

**Comment by mkaply** [comment]
> This is needed for userContent.css and userChrome.css.

Why are you making these changes:

https://github.com/SolydXK/firefox-solydxk-adjustments/blob/master/etc/skel/.mozilla/firefox/user.default/chrome/userContent.css

These seem completely arbitrary.

And you're removing our search and logo?

**Comment by ArjenBalfoort** [comment]
Text fields and input boxes were hard to read when using a dark Gtk+ system theme (white text on a white text field background). These changes make sure that forms are still usable when using a dark Gtk+ system theme.

We found the search bar in the new tab confusing. The address bar is used by most users but others prefer to have the separate search bar in the toolbar. Together with the new tab search bar would make three different ways of searching in one glance. To have a fixed place for searching (or anything really) is preferable. A logo without the search bar would only take a lot of space without adding something useful to the user experience.

**Comment by mkaply** [comment]
> Text fields and input boxes were hard to read when using a dark Gtk+ system theme (white text on a white text field background). These changes make sure that forms are still usable when using a dark Gtk+ system theme.

You should open a bugzilla bug so we can investigate.

As far as the search box goes, that's not something that you get to decide. You're modifying our product without our consent.

**Comment by ArjenBalfoort** [comment]
I have sent a request for distribution to Mozilla.
