### ISSUE TITLE
GPO Wish: CFR policy

### ISSUE THREAD

**Issue by Nemerensis** [mozilla/policy-templates#315]
https://blog.mozilla.org/blog/2018/12/11/latest-firefox-release-available-today/
Having the option to enable/disable recommendation notifications via gpo would be appreciated

**Comment by mkaply** [comment]
That already exists. If you set DisableFirefoxStudies, you won't see them

**Comment by Nemerensis** [comment]
@mkaply Just checking, but I was under the impression that this made it out of the firefox study phase and into ff64

**Comment by mkaply** [comment]
Even though it's in 64, it's still accomplished as a study, so disabling studies will disable it (at least that's my understanding)
