### ISSUE TITLE
How to add saved login exceptions

### ISSUE THREAD

**Issue by Skinny-Phat** [mozilla/policy-templates#320]
Hi Guys,

Im not sure if this is a genuine issue, but I need to be able to add in the saved logins exception sites without using the GUI as im hosting firefox in a docker container and this configuration will be volume mounted in and consistent.

I have been able to enable this functionality to save passwords in general via policies.json but I need to go a step further and specify the blacklisted sites.

Many Thanks,

**Comment by mkaply** [comment]
We don't have support for this right now. I'll add it to our list.

**Comment by nasura90** [comment]
Hi all!

Is there any update for this issue ?

Thanks.

**Comment by kinop112365362** [comment]
@mkaply when you support this right?

**Comment by mkaply** [comment]
Working on it  now. Should be 79 or 80 (will be backported to 78 ESR)

https://bugzilla.mozilla.org/show_bug.cgi?id=1520913

**Comment by mkaply** [comment]
This will be in Firefox 101. Sorry it took so long.
