### ISSUE TITLE
template versions compatible?

### ISSUE THREAD

**Issue by ldlx** [mozilla/policy-templates#322]
Can I "upgrade" template version 1.3 to template version 1.4 without having to recreate my group policy?

Is it supported to use template version 1.4 with Firefox versions older than 64?

Will you change/remove settings in new versions? (which would lead to not being able to change/remove settings of an older version) It would maybe be better to never remove deprecated settings, add a prefix for deprecated settings in the setting's name string or description and only adding new settings.

**Comment by mkaply** [comment]
Yes, you can upgrade the template without recreating policy. The template will work on older versions, but some features will just be ignored.

If we deprecate something, we definitely won't remove it for the reason you specify.

We've been working to maintain compatibility.
