### ISSUE TITLE
Unable to block manual extension installation

### ISSUE THREAD

**Issue by angryfirefox** [mozilla/policy-templates#324]
The GPO does its job to block the extension installation. However I found that users can easily get around it by manually copying their favorite extensions (ie: xpi files) to the extensions folder (\appdata\roaming\mozilla\firefox\profiles\*.default\extensions) as seen below:

1) download their favorite xpi files
2) copy the files to the extensions folder
3) launch Firefox and enable the "manually installed" extensions

Am I missing something or is Firefox still end-user friendly? Enabling the "Prevent extensions from being disabled or removed" policy isn't an option for us because we need our employees to be able to disable any extensions that are automatically installed by the policy.

**Comment by mkaply** [comment]
I don't really consider that end-user friendly. That's a lot of work to get an extension installed :).

I think our thought was that if Firefox was locked down, the system would probably be locked down as well to prevent the user from even opening a command prompt.

Are you installing some extensions via policy and not allowing other extensions?

i'll add this to our list of requirements.

**Comment by mkaply** [comment]
I understand your frustration. I'll look at what I can do solve this.

**Comment by mkaply** [comment]
FYI, this was fixed in Firefox 66. Can you give it a try?

**Comment by mkaply** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1525357

**Comment by mkaply** [comment]
I'm going to mark this as fixed.
