### ISSUE TITLE
Configuring Certificates

### ISSUE THREAD

**Issue by blackberryhell** [mozilla/policy-templates#325]
Should imported certificates show up in Certificate manager? I am not seeing the one I am trying to import.

**Comment by blackberryhell** [comment]
On Mac using 60.4.0esr (64-bit) and Enterprise Policy Generator to create JSON file.

**Comment by mkaply** [comment]
When you say imported, do you mean imported from the Mac keychain?

**Comment by blackberryhell** [comment]
Hi Mike

Thanks for getting back to me, I am actually based in Saudi Arabia and I'm
out mountain biking for our weekend (Friday and Saturday) so don't have all
my info to hand.

Essentially what I'm trying to do is replace cck2 with enterprise policy
generator and where I am falling down is while trying to configure it to
import certificates from the default location, my json file looks correct.

{
  "policies": {
    "Certificates": {
      "ImportEnterpriseRoots": true
    }
  }
}


Put I don't see the desired cert under Authorities, I am sure it is
something simple but just not seeing it.

Regards

Alex

**Comment by mkaply** [comment]
import enterprise roots is probably not the best name.

While the certificates are read and used, they don't show up in the Firefox UI.

We are discussing if we should show temporary certificates in the certificates UI.

Let me know if the certificates don't work. That would be an issue.

**Comment by hunterp12** [comment]
To piggy back off of this open issue, it doesn't appear to let you specify a location such as %systemdrive%\Company\cert3.der. When I do specify a location, I get this error in the debug: NS_ERROR_FILE_UNRECOGNIZED_PATH. If I copy the cert in to the appdata certificate folder, it works no issue. This is all because it looks like setting the import enterprise roots doesn't import/chain to associated subordinate certs

**Comment by mkaply** [comment]
> To piggy back off of this open issue, it doesn't appear to let you specify a location such as %systemdrive%\Company\cert3.der.

Are you using the ESR or rapid release? specifying a fully qualified path isn't available until the next ESR

**Comment by hunterp12** [comment]
This is in the rapid release 64.0.2 (64-bit)

**Comment by mkaply** [comment]
Ah, You were actually using the variable %systemdrive%. IT doesn't support those substiution values.

**Comment by hunterp12** [comment]
In my testing, I tried using c:\\tmp\\cert3.cer and was getting the same error.

**Comment by mkaply** [comment]
Should be two backslashes. I hadn't put this in the docs yet because it's not supported on ESR.

**Comment by hunterp12** [comment]
Sorry for all the trouble and thanks for your work. I edited my last post. My policies file does have the two backslashes in the path, just when I post here it changes them to one

**Comment by mkaply** [comment]
That's odd. In our testing, we were able to install the files. I'll test some more.

**Comment by hunterp12** [comment]
Thanks. I'll keep at it as well. Maybe I'm missing something dumb. Here is what debugging flags when I run it with the path specified, if it helps:

NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.append] Policies.jsm:163

Which highlights the line:
certfile.append(certfilename);

**Comment by mkaply** [comment]
Are you still seeing this?

**Comment by hunterp12** [comment]
I think you can close this. This seems to be fixed in 67. It now imports the enterprise roots CAs and sub CAs correctly.

**Comment by mkaply** [comment]
Thanks!
