### ISSUE TITLE
About:config settings

### ISSUE THREAD

**Issue by Mimicracra97** [mozilla/policy-templates#327]
Hello all,
We use mac os with firefox esr.
I want to know, how to change this setting in aboutconfig with by default value false to true with policies :

network.auth.force-generic-ntlm
network.auth.force-generic-ntlm-v1

Thanks in advance
This setting was possible with cck2.

**Comment by mkaply** [comment]
You shouldn't need to use those.

From the documentation:

Using generic NTLM authentication can expose the user to reflection attack vulnerabilities.

Does native NTLM not work for you?

**Comment by mkaply** [comment]
@Mimicracra97 Can you provide more info on why you need these?

**Comment by Mimicracra97** [comment]
Hi Mike,
Sorry for my late response.
I can close this issue cause we have change the way to connect to the web in my enterprise.
We don't need now to change network.auth.force-generic-ntlm and network.auth.force-generic-ntlm-v1

Thanks for your interest in my problem.
