### ISSUE TITLE
Feature Request: Version Pinning

### ISSUE THREAD

**Issue by churc169** [mozilla/policy-templates#328]
I manage desktop applications for my company. We have Firefox auto-updates disabled. We use a deployment tool to push out new versions of Firefox after we have tested that it doesn't break any business processes.

I want to update Firefox more quickly, and it would be super nice if I could use group policy or a registry key to control what version the Firefox client should update to and stay on.

For Google Chrome this is called "version pinning" and it's very convenient to just update group policy to allow all clients to update themselves to a version that we have verified works in our environment. The process of downloading, packaging, testing, and deploying new versions of Firefox takes forever so it ends up not being updated often enough because of time. Controlling the version via policy super cuts down on admin time.

This also allows me to create beta groups in group policy. I can have certain machines update to a new version, and after we deem it business ready, I can allow the whole fleet of machines to update themselves.

I think this would be a great enterprise feature. Some admins are stuck in the world of not being able to allow auto-updates, but wanting to be able to update more quickly.

**Comment by kedia990** [comment]
+1 - this would be incredibly useful to have, and would also allow us to move to a fully GPO-controlled solution to managing automatic updates for Firefox, like we can for Chrome.

**Comment by mkaply** [comment]
So this is happening in Firefox, the work is tracked there.

https://bugzilla.mozilla.org/show_bug.cgi?id=1529943

**Comment by mkaply** [comment]
This has shipped in Firefox 102 and I just added the policy.
