### ISSUE TITLE
Firefox nags about updates - won't go away

### ISSUE THREAD

**Issue by cubetronic** [mozilla/policy-templates#329]
firefox is bugging me about updates. i can't turn it off. i want to turn it off.

apparently the ability to turn it off is gone. i'm very unhappy about that. the current behavior of checking for updates when i do not want it to, and bothering me when i do not want it to, is, in my view, mal-ware, anti-user, anti-feature, whatever you want to call it.

it's extremely narcissistic of the developers to think that every update they have is absolutely more important than _anything_ i'm doing.

and it's bewildering to see an option that people used _removed_

1. i do not want updates installing automatically in the background because i consider what i'm doing at the moment more critical than an update, and performing an update may interfere with what i'm doing, like slow down my computer, even a fraction of a second.

2. i do not want to be bothered out of the blue about updates. i may be trying to concentrate on something important. or i may just not want to be bothered.

3. i know from experience that there are certain computers out there (i.e., no SSE2) where an update causes COMPLETE FAILURE of the program. i remember depending on the ability to disable updates before even running firefox -- because even at that time, firefox developers decided to make auto-updates default, meaning that i had to change that option either before running the program or right away before CERTAIN DOOOMM.

there are some forums about people with my exact concern... the "solution" was: "no, you can't do that"... really?  one authoritative comment even said "don't post comments as bug reports"... well... in that case.. this is not a comment. this is a bug report.

thanks for firefox. please fix this.

**Comment by mkaply** [comment]
We provide a mechanism for disabling updates via policy.

{
  "policies": {
    "DisableAppUpdate": true
  }
}

You can get more info on how to use policies.json here:

https://github.com/mozilla/policy-templates/blob/master/README.md

**Comment by cubetronic** [comment]
thank you..
it would be better if this were available through about:config

**Comment by mkaply** [comment]
We removed it from about:config because it was too easy to turn off updates and end up with an insecure Firefox.

Using the policies file is the only way to completely remove updates.
