### ISSUE TITLE
Feature request : Accepted languages

### ISSUE THREAD

**Issue by benoitdelmelle** [mozilla/policy-templates#330]
Hello,
I see policies evolving quite quickly. This is very nice. Keep up with the good work !
One feature that would be very nice to see is a policy to fill the "intl.accept_languages" field the same way as it is for the "intl.locale.requested" field. This field is used for displaying most websites in the preferred language of the user.

![accept_languages](https://user-images.githubusercontent.com/47031567/51748474-d6b28c00-20ac-11e9-9632-299cc2c5ce28.jpg)

**Comment by mkaply** [comment]
I did add this field in Firefox 70/ESR 68.2 as a preference.
