### ISSUE TITLE
GPO Wish List: Bookmark backup redirection

### ISSUE THREAD

**Issue by MrDanielFrey** [mozilla/policy-templates#331]
Microsoft has pushed a new Windows Update that makes any attempt at redirection of AppData fail. I was using this in testing to backup bookmarks to a server share for users.

I see that it is possible to create backups in HTML in Firefox that would suit our backup needs.

These are configured under browser.bookmarks.*, most notably:

browser.bookmarks.autoExportHTML
browser.bookmarks.file
browser.bookmarks.overwrite

Which will configure Firefox to automatically save a backup of bookmarks in the specified HTML location.

It would be nice to have this configurable via GPO.

**Comment by shthead** [comment]
I too would like this, with Chrome I can use the "roaming profile" option, it will create a database file at a location of your choosing and it will sync from/to that.

**Comment by MrDanielFrey** [comment]
Two other items that would be useful for the bookmarks backup/import are:

browser.places.importBookmarksHTML
browser.bookmarks.restore_default_bookmarks

**Comment by JasonNVSD** [comment]
I would like this as well, but even better would be synchronization without a Firefox account.  Ideally the developers could just tie into the existing Firefox Sync components, but add some GPOs that would include a local network location.

It sounds like @shthead is interested in the same thing, what about @MrDanielFrey?

**Comment by shthead** [comment]
> It sounds like @shthead is interested in the same thing, what about @MrDanielFrey?

Yes exactly right for me. The chrome roaming profiles option will use the same sync internals as if you were syncing it to a Google account but instead it will do it to a flat file.

To give some more background of why I want this feature:

A GPO is applied to PC's for folder redirection of the users 'Documents' folder. We don't redirect the app data. If the user switches to a new PC obviously they will then lose any of their FF configuration (bookmarks is the only thing that is important).

To solve this for Chrome we use the [admx files](https://support.google.com/chrome/a/answer/187202?hl=en) that Google provides. We then use the [roaming profile](https://support.google.com/chrome/a/answer/7349337?hl=en) policy and set the sync location to "${documents}\Applications\Chrome". When the user goes to a new PC and starts Chrome it will sync from the database file created at that location (if it doesn't exist a new one will be created) and they will retain their settings.

I wasn't actually aware of the auto export/import feature for bookmarks for FF until I saw this request (I actually found this when trying to find if FF can support roaming profiles in the same method as Chrome). While not ideal, the auto export/import settings should be working for my environment so I will start rolling out a preferences file with those configured. It would be nice if the settings could be configured directly from the admx files. Ideally, if there was a way to sync in the same method as Chrome (use the FF sync internals, configure a policy to sync to a file at a custom location) that would be perfect. I can imagine for enterprise environments being able to sync to a file at a custom location would be something that is very very useful.

**Comment by MrDanielFrey** [comment]
Yes that would work as well. We need to have some way of putting only the bookmarks and not the cache etc onto a server share.

We use Documents redirection but we also map a home drive that has a drive letter (same for all users) so redirecting to it would be fairly simple.

Simply being able to redirect places.sqlite to a network location would also work for our organization.

I was testing redirecting AppData and Microsoft is getting famous for breaking stuff with updates. I don't really want to rely on that method anymore if I can avoid it.

The problem with redirecting places.sqlite is that there would have to be some checks of some sort to make sure the network share is available and not just crash (as an example) if it's not found.

**Comment by mkaply** [comment]
I had added these already and now all these prefs are available

This is settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences
