### ISSUE TITLE
Zoom function in policies.JSON

### ISSUE THREAD

**Issue by reedie91** [mozilla/policy-templates#332]
We are using Firefox on Mac OS and need to configure the zoom percent to a permanent value.
We used to do this via AutoConfig and CFG files using
lockPref("zoom.maxPercent", 100);
lockPref("zoom.minPercent", 100);
I can't seem to find If there's an equivalent configuration for the policies.JSON.

If this is the wrong place please close or delete.

**Comment by mkaply** [comment]
I'm not clear why you would do this as this creates a very serious accessibility issues for users with vision problemsthat need to zoom the page.

That being said, you'll need to continue to do this via Autoconfig. I'm going to add a policy for this.
