### ISSUE TITLE
GPO for default Browser on different Windows OS

### ISSUE THREAD

**Issue by TThelpdesk** [mozilla/policy-templates#333]
I just can see a Policy to disable Firefox default browser check.
How can I set Firefox as default Browser on different Windows Systems?
We use Win7, some Win8.1, Win10 and Win Server 2012 R2. In the Future we want to switch to Win Server 2019.
Is there a way to set Firefox as default browser in every Win OS we use?
The most important would be Win Server 2012 R2, because we use this with ThinClients for Remotedesktop and the serverprofiles often do not safe the setting. With a GPO we hope it will be done.
I'm german sysadmin, open for answers ins german.

Thank you for the policy-templates anyway! They are great!

**Comment by charleslatham** [comment]
That's not a Firefox issue -- it's handled through a Microsoft policy. There may be other/better ways but I achieve this by using a **Computer** policy under _Policies / Admin Templates / Windows Components / File Explorer: Default Associations Configuration File._
First, you'll want to get on a computer that already has Firefox as default and run a Dism command to export the current values to a text file: Dism.exe /Online /Export-DefaultAppAssociations:C:\AppAssoc.txt
Next, pick out the htm, html, http and https associations and keep their formatting. This is what I use:
[firefox-default.txt](https://github.com/mozilla/policy-templates/files/2824797/firefox-default.txt)
Next, save your modified text file somewhere accessible on your network and point your clients to it through the above policy.

**Comment by TThelpdesk** [comment]
What if firefox has a different "ProgID" on the different servers?
Can I just change this? If I write it without this ID, it does not work...
any idea?

**Comment by TThelpdesk** [comment]
Got it.
Had to reinstall firefox on some older servers, because some had no ProgID and some others had a different one (maybe because of x86 version from "the past"). After installing new the ID was everywhere the same and the policy worked.

**Comment by mkaply** [comment]
So can I close this issue?

**Comment by charleslatham** [comment]
I don't see why not -- wasn't really something to do with Firefox policy.
