### ISSUE TITLE
Cannot set "use Systemlanguage"

### ISSUE THREAD

**Issue by hermann1514** [mozilla/policy-templates#336]
I wanted to set the value of "intl.locale.requested" with the current GPO. 
If no value is set, the system language should actually be adopted. But if I did not set a value for this entry, a message comes that a value must be set.

What must be entered so that the system language is adopted?

**Comment by mkaply** [comment]
This was an oversight in our implementation. I'm creating a new version of this policy to solve this.

**Comment by alexhass** [comment]
Have I missed that Firefox has a multilingual installer now? How can this work if I'm not able to deploy an MUI package to thousands of computers?

**Comment by mkaply** [comment]
> Have I missed that Firefox has a multilingual MSI installer now? How can this work if I'm not able to deploy an MUI package to thousands of computers?

You can deploy the language XPIs via policy.

**Comment by mkaply** [comment]
This is being fixed here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1528068

I'll close this once I update the ADMX

**Comment by MichaelWie** [comment]
I'am interested in, where the setting "intl.locale.requested" is hidden in the GPO. Didn't found an entry where I could set the language. But these option sound nice to me.

**Comment by mkaply** [comment]
It's the RequestedLocales policy

**Comment by MichaelWie** [comment]
So it's not existing in the GPO at the moment and will be implemented in the future? Please excuse any misunderstandings I am relatively new to the Firefox configuration.

**Comment by mkaply** [comment]
> So it's not existing in the GPO at the moment and will be implemented in the future? Please excuse any misunderstandings I am relatively new to the Firefox configuration.

It's an existing GPO that is implemented and works fine for selecting a specific language.

The bug is that on Windows in particular, you can't set the value to empty via group policy which means "use the same language as the operating system"

That is being fixed in Firefox 68.

**Comment by alexhass** [comment]
Are you guys at Mozilla making progress on MUI packages?

**Comment by MichaelWie** [comment]
> 
> 
> > So it's not existing in the GPO at the moment and will be implemented in the future? Please excuse any misunderstandings I am relatively new to the Firefox configuration.
> 
> It's an existing GPO that is implemented and works fine for selecting a specific language.
> 
> The bug is that on Windows in particular, you can't set the value to empty via group policy which means "use the same language as the operating system"
> 
> That is being fixed in Firefox 68.

I see, that would be a great thing. And now I found it, it's name is "Firefox/Requested locale". Thank you so far.

**Comment by mkaply** [comment]
This is fixed in Firefox 68. There is a new string based policy that lets this be set to blank.

**Comment by lohitashwa2020** [comment]
Sorry for replying on a closed topic but issue that I am facing the related.
I am installing Firefox 68.4 English installer with multiple language packs. My goal is to manage all configuration with GPO and not use Autoconfig.
I want firefox to follow system language, I can get this working well with Autoconfig file but not with GPO.
My understanding is that I need to set Firefox/Requested locale to empty and that should work. I can't get this to work by putting '''' or ""
Am I missing something?
