### ISSUE TITLE
Bookmark group policy processing

### ISSUE THREAD

**Issue by ghost** [mozilla/policy-templates#337]
Windows 10 Version 1607 Build 14393.2724
Firefox 60.4.0esr (32-bit)
policy_templates_v1.4.zip
Forest functional level: 2012 R2, 2012 R2 Domain Controllers

Added several bookmarks using policy templates, including multiple folders. Not all bookmarks are applied on initial group policy sync (logon). Using the same session forcing another policy check using gpupdate /force adds only 1 bookmark. Every time I re-run a gpupdate it adds a single bookmark after closing and re-opening firefox. This is an issue because I cannot reasonably require my users to stay logged on for 30+ background policy refreshes to get all the bookmarks.

If this is a misconfiguration on my end or an incompatibility with something please advise.

**Comment by DarkGhost368** [comment]
I figured it out, it looks like it you specify an invalid Favicon URL it causes this behavior. I just set all of the bookmarks to be a blank Favicon URL and the issue no longer occurs. I am not sure if this is the desired behavior though.

**Comment by felipc** [comment]
@DarkGhost368, can you give more details about what was invalid in your Favicon URL?  Was it simply a URL that didn't exist? Or was it a malformed URL?

**Comment by mkaply** [comment]
We did have a problem where an invalid favicon caused an issue. It was fixed.
