### ISSUE TITLE
GPO wishlist: Confirm close

### ISSUE THREAD

**Issue by paul-cossey** [mozilla/policy-templates#338]
Would it be possible to add the ability to manage the "Confirm close" dialogue box when closing Firefox? On our macOS computers we log students out automatically after 30 mins of inactivity, as they have a tendency to just walk away when they're finished. If Firefox is open the "Confirm close" pop up will stop macOS from auto logging out. 

Apologies if it's been logged already, and thanks for everyones work on this, it's going to make my life a lot easier! 

Paul

**Comment by mkaply** [comment]
This was added in Firefox 68. The new preferences policy.
