### ISSUE TITLE
Debian/Ubuntu issues

### ISSUE THREAD

**Issue by liquidoshin** [mozilla/policy-templates#339]
The certificate installation portion still doesn't seem to work on debian/ubuntu.  The reason I say "still" is because I filed an issue regarding certificates not working with firefox based on the current implementation at the time.  The old implementation was to copy the mozilla.cfg file which contained the following contents:
var Cc = Components.classes;
var Ci = Components.interfaces;
var certdb = Cc["@mozilla.org/security/x509certdb;1"].getService(Ci.nsIX509Cert$
var certdb2 = certdb;
try {
   certdb2 = Cc["@mozilla.org/security/x509certdb;1"].getService(Ci.nsIX509Cert$
} catch (e) {}
cert = "CertContentsHere"
certdb.addCertFromBase64(cert, "C,C,C", "");

to the /usr/lib/firefox(firefox-esr) folder

And to also add the autoconfig.js file which contained the following contents:
pref("general.config.obscure_value", 0);
pref("general.config.filename", "mozilla.cfg");

to the /usr/lib/firefox(firefox-esr)/defaults/pref folder.  

However this didn't work on .deb systems so I filed a ticket with firefox.  I'm emailed a link to this solution which still does not work on .deb systems.  

I create the policies.json file, putting the necessary certificate information in said file, and put this file inside /usr/lib/firefox/distribution (the location on ubuntu 16).
I then put my certificate inside the appropriate directory, restart firefox, and try to navigate to our internal ssl url and no luck.

First off there is no /usr/lib/mozilla, /usr/lib/mozilla/certificates, or ~/.mozilla/certificates directories.  If these directories including any missing parent directories are manually made and the certs put in those directories, it still doesn't work.

Is this an issue with .deb systems?  If so, this should be worked out between you two since they are a major linux distribution.  Any help would be great.

**Comment by liquidoshin** [comment]
BTW I forgot to mention that the new implementation works with .rpm systems such as RHEL 6 and 7 and Centos 6 and 7 so far.

**Comment by mkaply** [comment]
What version of Firefox is it?

**Comment by liquidoshin** [comment]
63.0.3 .  Is that the latest? When I do an apt-get update there are no packages marked for updating.

**Comment by mkaply** [comment]
No 65 is the latest and the certificate stuff didn't go in until 64.

**Comment by liquidoshin** [comment]
Ah!  Sorry, for some reason my apt-get update was reading old metadata I guess and not updating.  65 does actually work.  Thank you.  Sorry for the inconvenience.

**Comment by mkaply** [comment]
No problem! Glad it's working!

**Comment by liquidoshin** [comment]
One additional thing.  I think you may have a typo with the latest package name for .rpm systems.  When updating to the latest firefox package, for instance, on rhel 7, doing a firefox --version shows:
Mozilla Firefox 60.5.0 instead of 65.x.x . This confused me because it kept telling me I have the latest version.  I verified I do have the latest version by the implementing the new policies technique that we've been going over so unless by some accident version 60.5.0 also got some pieces of code from 65, then the package name is off.

**Comment by mkaply** [comment]
That's the ESR version. On RHEL, they use the ESR Firefox, not release.

It has the same policy functionality as Firefox 65.
