### ISSUE TITLE
xpi from local web server downloaded instead of installed

### ISSUE THREAD

**Issue by red-erik** [mozilla/policy-templates#340]
Hi,
I'm trying to distribute an .xpi using GPO but nothing happens. If i try to manually connect to the server (IIS with AddType application/x-xpinstall .xpi) FF (60.4 ESR) asks me where to save the file instead of installing it. If I drag'drop the file in the add-on tab, the .xpi installs fine (Cisco Webex meetings taken from here https://collaborationhelp.cisco.com/article/en-us/9q0glab).
Any help on how to use GPO to distribute .xpi would be greatly appreciated.
Regards.

Red.

FF 60.4 ESR on Windows 7 64 bit

**Comment by mkaply** [comment]
You'll need to put the XPI file on a server somewhere and specify the path via GPO.

What Cisco is distributing is a ZIP, not the XPI

**Comment by red-erik** [comment]
Hi,
I did it. it's on virtual directory on IIS server. Cisco let you download a zip file witch contains the .xpi file.
As mentioned above, I put the .xpi file on IIS (I can access the virtual directory and any anonymous user can) and I used the GPO but...nothing happens.
Opening manually the link, FF ask me tyo save the .xpi instead on installing it

**Comment by mkaply** [comment]
Ah, sorry. Missed that. Can you go to about:config and create a string preference "browser.policies.loglevel" and set the value to "debug"?

And then see if there are any errors on the JS console?

**Comment by red-erik** [comment]
Done but I don't see anything...only a get with 200 code. FF only ask to save the file . Is there a way to debug GPO processing for FF ?

**Comment by mkaply** [comment]
Setting browser.policies.loglevel to the string "debug" is how you debug policies.

You should see detailed policy information in the console (mapping of the GPO to JSON)

**Comment by mkaply** [comment]
Would you be willing to try in a more current version of Firefox for testing only? (non ESR).

We have a new URL - about:policies - that gives more info

**Comment by red-erik** [comment]
We can't . In Enterprise environment only FF60.4 ESR is permitted. I can't install a different version
![xpi](https://user-images.githubusercontent.com/10245160/52489397-78180280-2bc2-11e9-9fff-823be707d2c5.JPG)

**Comment by mkaply** [comment]
Can you try on an https server? I'll test locally.

**Comment by red-erik** [comment]
I did a "trick" and installed FF65. Now I have about:policy with the error section
![xpi](https://user-images.githubusercontent.com/10245160/52489731-50756a00-2bc3-11e9-81d8-b32f9cb4d8c9.JPG)
It seems that the policy should install it only 1 time and if the user remove it, nothing happens anymore. Is there a way to force the policy to be applied or to have the extension as "required" (reinstalled every time if missing) ?

**Comment by mkaply** [comment]
In about:config, right click and reset the pref.

I'm wondering if that's the problem you were having on 60. It wasn't trying to install the extension again.

**Comment by red-erik** [comment]
We have 60.4 ESR that should be equivalent on 64. Tryed right now with 60.5 ESR and 65...same result with the difference that in 60.5 ESR we don't have about:policies.
FF alway try to download and not install

**Comment by red-erik** [comment]
Ok...with your suggestion is now more clear to me.
I open about:config and reset the preference, close and open FF and I found the xpi correctly installed and enabled.
Now, it should be great to have the xpi "always installed if missing" or some other trick to be sure to have the extension installed and enabled for ALL users.
Thank you for your time and support.
Great work, as usual.

Red.

**Comment by mkaply** [comment]
> Now, it should be great to have the xpi "always installed if missing" or some other trick to be sure to have the extension installed and enabled for ALL users.

I'm seeing what we can do there. You should add the ID to the list so users can't remove it once it is installed.

**Comment by red-erik** [comment]
Thank You.
Sorry for the question but how can I find the xpi ID ?!? 
Regards

**Comment by red-erik** [comment]
For reference, this is the quick way to find the ID of an installed XPI
https://stackoverflow.com/questions/48056506/get-add-on-id-of-extensions-in-firefox
Red.
