### ISSUE TITLE
Locked extensions via GPO not locking extensions in V65

### ISSUE THREAD

**Issue by br-sn** [mozilla/policy-templates#343]
Hi,

We're able to push out extensions using GPO but the setting "Prevent extensions from being disabled or removed" doesn't seem to work. We've set it up in our test environment and can't get it to work, the user (both administrators and unprivileged accounts) can simply right click on the extension and select "Remove Extension"

Details: 

Domain functional level: 2012R2 (Test environment)
Group policy settings applied via Computer Configuration, not User
Firefox v65.0.1 (both 32 and 64bit)
Operating Systems: Win7 Pro (64bit) // Win8.1 Pro (64bit) // Win10 Pro (64bit)

Extensions tested with:
uBlock Origin (ID: uBlock0@raymondhill.net)
Multi-Account Containers (ID: @testpilot-containers)

The extensions deploy without issues, but aren't "locked" even though the GPO is configured to do so.

I've tested it in Firefox ESR (v 60.5.1esr 64-bit) and it does seem to work - is this currently not supported for non-ESR builds?

**Comment by mkaply** [comment]
Are you referring to the icon itself? Can it be removed via the addons manager?

Unfortunately this feature was added and we didn't know to turn it off. We've fixed it in Firefox 66.

https://bugzilla.mozilla.org/show_bug.cgi?id=1522820

**Comment by br-sn** [comment]
Hi,

I'm referring to the extension itself. Despite locking it in Group Policy using the "Prevent extensions from being disabled or removed" setting, the extension itself can be removed by the user:

![firefox_gpo1](https://user-images.githubusercontent.com/39455110/53310921-b1c95880-38a6-11e9-800e-84418be0eb9f.png)

![firefox_gpo2](https://user-images.githubusercontent.com/39455110/53310943-c1e13800-38a6-11e9-9c16-c78401065130.png)

This is in Firefox Quantum v65.0.1 (32-bit)

**Comment by mkaply** [comment]
Is this working for you in Firefox 66?

**Comment by mkaply** [comment]
There was a bug but has since been fixed.
