### ISSUE TITLE
PopupBlocking - Allowed sides not working on macOS FF ESR 60.5.2

### ISSUE THREAD

**Issue by Coros** [mozilla/policy-templates#345]
I've been unable to control the popup blocker on macOS through a configuration profile. 

Here's my xml excerpt:
`<key>PopupBlocking</key>
	<dict>
		<key>Allow</key>
		<array>
			<string>https://lisd.net/</string>
			<string>https://lhub.lisd.net/</string>
			<string>https://encoresso.lisd.net/</string>
		</array>
		<key>Default</key>
		<true/>
		<key>Locked</key>
		<false/>
	</dict>
`

I've tried enabling and disabling the Popup blocker, neither worked.  The sites in the allow array are not populating in the UI of allowed sites either.  I've tried the URLs without the trailing / to see if that was the problem as well.

Any ideas?  Is this a bug with the mac version of FF?

**Comment by mkaply** [comment]
What version of Firefox?

Can you create a string value in about:config called:

browser.policies.loglevel

and set the value to "debug"

and see if there is any output on the JAvascript console?

**Comment by Coros** [comment]
I have no idea why but now it is working.  I made no changes to my configuration profile besides re-enabling about:config so I could do what you asked and now the settings are applied correctly.  I've disabled about:config again and the popup settings are still applied.
