### ISSUE TITLE
Proxy settings not applied via GPO

### ISSUE THREAD

**Issue by sorchaa** [mozilla/policy-templates#346]
Hello all,
I don't arrive to configure my firefox 60.5.2 ESR 32bits with proxy settings sent by GPO.
I tried in the user configuration, the registry is correctly updated (HKCU\software\policies\Mozilla\...), and I arrive to modify my homepage but never any proxy settings.
I tried in Machine configuration and same problem, the proxy settings are correctly written in the registry but are not "read" by firefox.

For that, I used the last template.
Thk

**Comment by mkaply** [comment]
So to be clear, homepage works, but proxy doesn't?

Did you set the network type policy?

Can you go to about:config and add a new string preference called "browser.policies.loglevel" and set it to "debug" and see if there are any errors on the console?

**Comment by sorchaa** [comment]
Thk for your reply,
So, I did what you asked. But I didn't understand "network type Policy", maybe you would like to say "mode" of proxy ?

I paste my registry config , it's ascreen from the key HKEY_CURRENT_USER, there is nothing in the local machine:
![proxy](https://user-images.githubusercontent.com/37829781/53866789-ab4b8700-3ff2-11e9-898d-d44867038e09.png)

The log via browser.policies.loglevel :
![logfirefox](https://user-images.githubusercontent.com/37829781/53866936-05e4e300-3ff3-11e9-945e-26b0b5112c15.png)

And if I see the options of my firefox 60.4.0esr (32 bits) (I changed since yesterday to test with another version):
![proxyf](https://user-images.githubusercontent.com/37829781/53867109-67a54d00-3ff3-11e9-96a9-0a6151e092cd.png)

**Comment by sorchaa** [comment]
I dont know if it will help you but when I put the value "1" to the option "locked", it works nice :
![proxok](https://user-images.githubusercontent.com/37829781/53868474-69244480-3ff6-11e9-96df-50ab7ffcce99.png)

Now, if I put 0 to the same option, my proxy conf disepears  and comes back with the option "no proxy" selected

**Comment by mkaply** [comment]
You can't configure proxy and autoproxy. They are mutually exclusive.

You have mode set to Autoconfig.

**Comment by sorchaa** [comment]
If I understand, I must put mode to unconfigured ? and AutoConfigURL with my address ?

**Comment by mkaply** [comment]
You would set the mode that corresponds to what you are trying to do.

The modes are:

      "Mode": ["none", "system", "manual", "autoDetect", "autoConfig"],

and if you want to set a proxy, you would use "manual".

If you want an autoconfig script, you would use "autoConfig"

**Comment by sorchaa** [comment]
But If I use autoConfig  mode and the autoConfigURL, I need to use "locked" if I want to see my settings written in firefox.
If I don't use Locked the configuration is not modified by the settings in the registry.

**Comment by mkaply** [comment]
Ah, I see what you are saying. That is expected behavior. If you don't lock the preferences, you are only setting the default values, so the values you are setting via preferences or about:config are overriding those preferences.

You either force preferences by locking them, or a user can change them.

**Comment by sorchaa** [comment]
ok! thk for the answer. So, the "locked" is necesseray to have configure the autoconfig mode and URL.
Maybe, it should be interesting to explain that in the description of the GPO no ?

Thanks for all

**Comment by mkaply** [comment]
The locked is only necessary if you want to force the settings on the user. Otherwise it uses whatever you have configured in Firefox.

**Comment by sorchaa** [comment]
Ok thk for all
