### ISSUE TITLE
Extension reinstall

### ISSUE THREAD

**Issue by mdedeboer** [mozilla/policy-templates#347]
I think this is related to some of the other issues surrounding extension installations and uninstalls.

**Partially Related issues:**
https://github.com/mozilla/policy-templates/issues/189
https://github.com/mozilla/policy-templates/issues/294

**Summary**
Repeat uninstalls/installs do not appear to be processed

**Steps to Reproduce**
1. Add policy to force install an addon (such as uBlock origin)
2. Restart Firefox (addon is installed)
3. Remove policy
4. Add policy to force uninstall addon
5. Restart Firefox (addon is removed)
6. Add policy to force install an addon (such as uBlock origin)
7. Restart Firefox (addon is NOT installed)

Another variation also seems to have an issue
1.  Add policy to force install an addon (such as uBlock origin)
2. Restart Firefox (addon is installed)
3.  Manually remove addon.
4. Restart Firefox (addon is NOT reinstalled....this is expected based on the other bug reports)
5. Manually reinstall addon 
6. Restart Firefox
7. Remove force install policy
8. Add force uninstall policy
9. Restart Firefox (addon is NOT removed)

Note:  All my testing has been on 60.5.2 ESR x64

**Suggestions**
I am NOT a Firefox developer, so I have no idea if this is practical.

When processing the Install key:
It should be possible to pragmatically parse which addons are currently installed.  If it is not possible within the Firefox browser, it could be possible by checking the extensions directory of the current profile.  The filename there could be matched with the filename in the policy.  If you can parse this pragmatically, you also should be able to trigger the install only if the addon is not currently installed.  Then you can parse the install key on each launch of Firefox.

When processing the Uninstall key:
It seems that there is a method to match the ID of the addon with the currently installed addons.  As a result, it should be fairly trivial to check if the addon is installed and only trigger the uninstall if needed.  Again, then you can parse the uninstall key on each launch of Firefox.

My apologies if I am being unrealistic :-)

**Comment by mkaply** [comment]
That's an interesting idea. In hindsight, I wish I'd required people to put the ID of the extension being installed which would make it easier.

Your second scenario is just a bug. It should have been uninstalled.

We are looking to solve scenario one by resetting the internal preference when addons are uninstalled.

**Comment by mdedeboer** [comment]
Thanks for the very quick response!

I look forward to the improvements :-)

**Comment by xaverdh** [comment]
On a related note, could there be a more declarative interface, i.e. an option which says that the extensions specified through policies is exhausting. This would block the user from installing extensions by other means, and ensure that precisely the given extensions are installed.

**Comment by mkaply** [comment]
My plan is to follow Chrome's model:

https://dev.chromium.org/administrators/policy-list-3/extension-settings-full

Very declarative and allows much better control.

**Comment by Gor3t3x** [comment]
@mkaply Same problem for us, any ETA on a solution?

**Comment by mkaply** [comment]
This has landed and will be in Firefox 68.

**Comment by mkaply** [comment]
This is in Firefox 68. Extensions should work much better

https://github.com/mozilla/policy-templates#extensionsettings
