### ISSUE TITLE
GPO Wishlist: PDFJS browser controls such as default zoom value

### ISSUE THREAD

**Issue by cypherstream** [mozilla/policy-templates#349]
We would love the ability to customize Firefox internal PDF viewer, which preferences are all prefixed with pdfjs.

One important aspect that we want to change sis pdfjs.defaultZoomValue to "page-width" so that cuts back on thousands of clicks with all employees in our organization changing this view upon opening pdfs in firefox.  

I have been unable to set this via autoconfig.js , or cck2 for Firefox 60.5.2esr 64-bit, so an ADMX template would be a godsend.

You could create a whole category for Firefox PDF viewer in the ADMX templates and have all of the preference values toggleable.

pdfjs.curserToolOnLoad
pdfjs.defultZoomValue
pdfjs.disableAutoFetch
pdfjs.disableFontFace
pdfjs.disablePageLabels
pdfjs.disablePageMode
pdfjs.disableRange
pdfjs.disableStream
pdfjs.disabled
pdfjs.enablePrintAutoRotate
pdfjs.enableWebGL
pdfjs.enabledCashe.initiaized
pdfjs.enabledCache.state
pdfjs.externalLinkTarget
pdfjs.firstRun
pdfjs.migrationVersion
pdfjs.pdfBugEnabled
pdfjs.previousHandler.alwaysAskBeforeHandling
pdfjs.previousHandler.preferredAction
pdfjs.renderInactiveForms
pdfjs.renderer
pdfjs.showPreviousViewOnLoad
pdfjs.sidebarViewOnLoad
pdfjs.textLayerMode
pdfjs.useOnlyCssZoom

**Comment by mkaply** [comment]
I'm surprised you are using pdf.js. Most people just turn it off :).

Can you be more specific as to which other prefs you would need? Many of these are true internal preferences.

**Comment by cypherstream** [comment]
Yeah our core financial system runs in Firefox and they support and use the built in PDF viewer for reports.  The thing is that since the way the page is laid out in certain frames or tables, the PDF looks best when set to page-width.

I could see other users possibly wanting to disable pdfjs, and I think that is pdfjs.disabled.
Forcing (or not) the sidebar with pdfjs.sidebarViewOnLoad.  Possibly disabling page labels with pdfjs.disablePageLabels, and then maybe specifying pdfjs.enablePrintAutoRotate to open landscape documents in landscape.

**Comment by mkaply** [comment]
FYI, These will all be available in the next version of Firefox in December.

**Comment by Deutschi** [comment]
Even though this issue is kinda old, I am still looking forward for better pdfjs control via Windows GPO. So far, there are only two options available in the most recent admx files (v2.10). I'd also like to add the option **pdfjs.enableScripting** to this list.

**Comment by mkaply** [comment]
All of the pdfjs preferences are now available via the Preferences policy (rather than adding them all individually to the PDF policy).

For the Windows GPO case, you use a JSON that specifies the preferences (in the new top level Preferences items).

see:

https://github.com/mozilla/policy-templates/blob/master/README.md#preferences

**Comment by Deutschi** [comment]
Thank you for the hint. Although pasting JSON in a GPO setting doesn't feel very Windows-like, it works at least ;-)

**Comment by mkaply** [comment]
>Although pasting JSON in a GPO setting doesn't feel very Windows-like, it works at least ;-)

Chrome started this and even Microsoft is switching to it with some Edge policies.

Unfortunately when you need deep dictionaries, there's just no good way to get it with ADMX templates.

I will say we do better than Chrome and Edge though - they make you put all the JSON on one line :).
