### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by vF360** [mozilla/policy-templates#35]
I've made the policies.json file & placed it inside C:\Program Files (x86)\Mozilla Firefox, yet it does not seem to work....

**Comment by vF360** [comment]
I placed the policy.json file in C:\Program Files (x86)\Mozilla Firefox, the firefox.admx + mozilla.admx files in C:\Windows\PolicyDefinitions & the firefox.adml + mozilla.adml files in C:\Windows\PolicyDefinitions\en-US

Here is what is inside the policy.json file: { "policies": { "BlockAboutSupport": true }

I didn't change the .admx & .adml files, I just copied them from the template. If I'm suppose to modify them, can you tell me how I would do that?

The part I'm looking to modify in the mozilla.admx file looks like this: </policy> <policy name="BlockAboutSupport" class="Both" displayName="$(string.BlockAboutSupport)" explainText="$(string.BlockAboutSupport_Explain)" key="Software\Policies\Mozilla\Firefox" valueName="BlockAboutSupport"> <parentCategory ref="firefox"/> <supportedOn ref="SUPPORTED_WINXPSP2"/> <enabledValue> <decimal value="1"/> </enabledValue> <disabledValue> <decimal value="0"/> </disabledValue>

The mozilla.adml file part I probably might need to change looks like this: <string id="BlockAboutSupport">Block About Support</string>

**Comment by felipc** [comment]
Oh but btw, the policies.json file needs to be placed in "C:\Program Files (x86)\Mozilla Firefox\distribution".  If that folder doesn't exist, you can create it.

The admx files are meant to be loaded through the "Windows Policy Editor" program available from Microsoft. You don't need to edit them manually.

(You don't need to use both techniques, you should choose between the json file or the admx templates)

**Comment by vF360** [comment]
I got it to work now but there still seems to be a way around the settings that I set, I can just refresh Firefox or use it in safe mode via the help tab. Even disabling safe mode doesn't solve the problem: https://i.imgur.com/InihWu6.png

**Comment by donaldv77** [comment]
Any idea where the create the distribution directory on MacOS? I tried /Applications/Firefox.app/Contents/MacOS/distribution and dropped a sample policies.json inside but not being honored by Firefox (v60 beta)

**Comment by mkaply** [comment]
It actually goes in Contents/Resources/distribution

**Comment by mkaply** [comment]
I'll update the docs.

**Comment by vF360** [comment]
Is there anyway to fix the issue I have?

**Comment by felipc** [comment]
The DisableSafeMode policy just landed on Firefox Beta yesterday. It will be available on the next beta (beta 7 I believe)

**Comment by vF360** [comment]
So the one that is in the group policy editor won't work until I update? https://i.imgur.com/jWtcFHr.png
Also, even if I could disable safe mode, there still isn't a way of disabling the refresh option......

**Comment by felipc** [comment]
Right, because that was created in advance to test it with Nightly. 
The DisableProfileRefresh policy is still being worked on, and will probably be available for testing early next week: https://bugzilla.mozilla.org/show_bug.cgi?id=1429157
