### ISSUE TITLE
"file://" URLs not recognized in popup whitelist

### ISSUE THREAD

**Issue by mangstadt** [mozilla/policy-templates#354]
I want to allow popups for certain "file://" URLs.  However, when I add them to the "Popups > Allowed Sites" GPO setting, it is not picked up by Firefox.

"http://" and "https://" URLs are detected, but not "file://" URLs.

Please see the screenshots below.  Thank you! 😁 

**Group policy setting:**

![Allowed Sites GPO setting](https://user-images.githubusercontent.com/700174/54760376-5862f980-4bc6-11e9-834e-e3737b660b60.png)

**List of popup exceptions in Firefox Options screen:**

![Firefox Settings](https://user-images.githubusercontent.com/700174/54760377-5862f980-4bc6-11e9-9b97-249f81e04c47.png)

**Comment by mkaply** [comment]
Are you able to do this in Firefox? (independent of policies)

**Comment by mangstadt** [comment]
Yes, I can manually add exceptions from within Firefox (using the dialog box shown in the second screenshot). However, the URLs that I add go away when I close and reopen Firefox.

**Comment by mkaply** [comment]
I opened a bug for this:

https://bugzilla.mozilla.org/show_bug.cgi?id=1542895

Come to find out, some code we have to do origin checking doesn't handle file URIs.

**Comment by mkaply** [comment]
This will be fixed in Firefox 68.

**Comment by mangstadt** [comment]
Thanks Michael

**Comment by mkaply** [comment]
This is fixed in Firefox 68.
