### ISSUE TITLE
DisableAppUpdate no longer works after update to FF 66

### ISSUE THREAD

**Issue by Madeupname722** [mozilla/policy-templates#356]
The DisableAppUpdate policy was working in v65, after updating FF V66 it no longer works.

**Comment by mkaply** [comment]
Can you be more specific?

I verified that when I go to the about dialog, updates are disabled.

What platform are you on?

**Comment by Madeupname722** [comment]
After your reply I removed the policy and let FF update (to 66.0.2). I replaced the policy and it works fine now. Apparently it was a glitch on my PC. Thanks for the reply.

Removed = moved json file from distribution folder to desktop. Replaced= Moved it back
