### ISSUE TITLE
Enterprise Policy support for macOS via configuration profiles

### ISSUE THREAD

**Issue by aimnfires** [mozilla/policy-templates#361]
I installed esr 60.6.1 and followed the steps from comment 22 and comment 23 in the (closed) bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1445943#c22 
https://bugzilla.mozilla.org/show_bug.cgi?id=1445943#c23

Under mac system preferences / profiles I see 2 profiles, one for chrome (which works...edited the plist file with xcode) and one for firefox (org.mozilla.nighly) which does not work.

The homepage for org.mozilla.night.plist is about:polices . I changed that to https://www.yahoo.com  and the policy still does not work.

The about:polices also returns a window that states "Hmm. that address doesn't look right. Please check that the URL is correct and try again." It does this with or without the firefox policy installed.

**Comment by mkaply** [comment]
Can you post your plist here please?

Also about:policies doesn't work on the ESR.

**Comment by aimnfires** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnterprisePoliciesEnabled</key>
	<true/>
	<key>Homepage</key>
	<dict>
		<key>Locked</key>
		<true/>
		<key>URL</key>
		<string>https://www.yahoo.com</string>
	</dict>
</dict>
</plist>

**Comment by aimnfires** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnterprisePoliciesEnabled</key>
	<true/>
	<key>Homepage</key>
	<dict>
		<key>Locked</key>
		<true/>
		<key>URL</key>
		<string>https://www.yahoo.com</string>
	</dict>
</dict>
</plist>

**Comment by aimnfires** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnterprisePoliciesEnabled</key>
	<true/>
	<key>Homepage</key>
	<dict>
		<key>Locked</key>
		<true/>
		<key>URL</key>
		<string>https://www.yahoo.com</string>
	</dict>
</dict>
</plist>

**Comment by aimnfires** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnterprisePoliciesEnabled</key>
	<true/>
	<key>Homepage</key>
	<dict>
		<key>Locked</key>
		<true/>
		<key>URL</key>
		<string>https://www.yahoo.com</string>
	</dict>
</dict>
</plist>

**Comment by mkaply** [comment]
You'll need to attach it as a file.

**Comment by aimnfires** [comment]
tried to drag file org.mozilla.nightly.plist into comment box. received message "we don't support that file type. I then converted the plist file to xml and opened into text editor ... and tried copy and paste. didnt format correctly.

**Comment by aimnfires** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnterprisePoliciesEnabled</key>
	<true/>
	<key>Homepage</key>
	<dict>
		<key>Locked</key>
		<true/>
		<key>URL</key>
		<string>https://www.yahoo.com</string>
	</dict>
</dict>
</plist>

**Comment by aimnfires** [comment]
[org_mozilla_nightly.txt](https://github.com/mozilla/policy-templates/files/3040541/org_mozilla_nightly.txt)

**Comment by mkaply** [comment]
So the plist file must be called org.mozilla.firefox.plist for Current Firerfox

org.mozilla.nightly was for testing,. Sorry for the confusion.

I've verified that mcxToProfile.py is able to convert your file properly when named org.mozilla.firefox.plist

**Comment by jeffreymcclain** [comment]
> The about:polices also returns a window that states "Hmm. that address doesn't look right. Please check that the URL is correct and try again." It does this with or without the firefox policy installed.

@aimnfires "about:policies" isn't supported in the current ESR version (60.6.1), it was only added in Firefox 63 (stable). It likely won't be added to ESR until the next major version bump (68), scheduled for July 9th.
