### ISSUE TITLE
NTML through proxy

### ISSUE THREAD

**Issue by red-erik** [mozilla/policy-templates#363]
Hello,
it would be nice to be able to set (force and lock) this preference
network.automatic-ntlm-auth.allow-proxies
otherwise is a really a pain to manage it in an enterprise environment.

Regards.

Red.

**Comment by mkaply** [comment]
This pref is already set to true. Do you need to set it to false?

**Comment by red-erik** [comment]
Hi,
we are in the middle of updates from FF 50.2 with CCK2 to FF 60.4 with GPO (both ESR)  and we found a lot of browser with this setting to FALSE and LOCKED. It seems that some information from cck2 has been "imported" in the 60.4 profile. (really I don't know how)
It would be nice to be sure to have the possibility to SET and configure all NTLM parameters in FF 60.4

Regards.

Red.

**Comment by mkaply** [comment]
> a lot of browser with this setting to FALSE and LOCKED.

If it is locked to false, it's being explicitly set that way by an autoconfig or CCK2. Locked prefs do not persist across invocations.

> It would be nice to be sure to have the possibility to SET and configure all NTLM parameters in FF 60.4

We provide the basics, but I would rather not provide option that users don't need to change. That being said, I'll look at adding this one.

Are there other NTLM preferences you need?

**Comment by red-erik** [comment]
Hi,
I don't see any other requirements because you already have provided
"Allow non FQDN"
"Delegated"
"NTLM" and "SPNEGO"
Thank you very much for your work.
Regards.

Red.

**Comment by mkaply** [comment]
This preference was added Firefox 70/68.2.

**Comment by mkaply** [comment]
https://github.com/mozilla/policy-templates/blob/master/README.md#authentication
