### ISSUE TITLE
ADMX Options for new Tab

### ISSUE THREAD

**Issue by leebrand** [mozilla/policy-templates#364]
Hello Guys,

i miss options for new tabs:

![grafik](https://user-images.githubusercontent.com/49483694/55878961-d1d68200-5b9d-11e9-9e2d-4ef4bd3075cb.png)

Thanky

**Comment by mkaply** [comment]
The new tab is in some flux right now, so for now I'm adding a policy to simply turn it off. Once the design is finalized for 68, there will be policies for everything.

**Comment by mkaply** [comment]
These are in the new FirefoxHome policy in Firefox 68.
