### ISSUE TITLE
ADMX: Clear cache only

### ISSUE THREAD

**Issue by jechange** [mozilla/policy-templates#365]
Hi, is it possible to have a GPO to clear only the cache when we close firefox ? 
Beside the GPO whose clear all data when Firefox is close.

**Comment by mkaply** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1545592

**Comment by mkaply** [comment]
This is fixed in Firefox 68. SanitizeOnShutdown supports each individual property.
