### ISSUE TITLE
GPO Wish: Control of gfx.webrender.all setting

### ISSUE THREAD

**Issue by smpettit** [mozilla/policy-templates#366]
We would like to control the rollout of gfx.webrender.all setting (GPU rendering) in our organisation and customer organisations.

It provides significant performance benefits for some hardware and has issues on other hardware. So a GPO control for this would be great!

**Comment by mkaply** [comment]
After discussion with developers, they don't want to allow folks to flip this. We should be doing the right thing in Firefox. If you run into specific issues on hardware, please open a bugzilla bug.
