### ISSUE TITLE
FEATURE REQUEST: obfuscated extensions GPO

### ISSUE THREAD

**Issue by red-erik** [mozilla/policy-templates#369]
Hello,
since new policy in FF to ban obfuscated extensions, it would be great to manage the preference
xpinstall.signatures.required through GPO to force some extension to work (eg. Cisco Webex).
Thank you very much for your help.

Regards.

Red.

**Comment by mkaply** [comment]
Why do you think you'll need to turn off signatures to get Cisco Webex to work? It's distribution on AMO. Do you think they won't update it to be unobfuscated?

**Comment by red-erik** [comment]
Hello,
What I see is that suddenly all our Extensions STOPPED working and the only workaround is to update FF for all users or change xpinstall.sigatures.required on every browser. As you know, not always software company are quick in response to manage changes and so Mozilla rolled back this configuration with 60.6.2/3.
In enterprise environment, with Firefox Updates disabled, it's a pain to redistribute FF to all users while it would enough to manage this setting through GPO.

Regards.

**Comment by mkaply** [comment]
That was completely unrelated to the obfuscation.

See:

https://blog.mozilla.org/blog/2019/05/09/what-we-do-when-things-go-wrong/

Normally that preference should never need to be changed.
