### ISSUE TITLE
Certificates documentation

### ISSUE THREAD

**Issue by dosfx** [mozilla/policy-templates#370]
The documentation for the Certifiates/Install policy is a little conflicting and I believe the examples are incorrect.

It mentions requiring a double backslash for UNC paths but then the example is simply `\SERVER\CERTS\CERT5.PEM` Looking at the raw, I guess markdown is swallowing the `\\` in the display so I would suggest the example be wrapped in code backticks.

Which brings us to the json example. On our system we were only able to get this to work if we escaped the backslashes in the json strings. So I would again suggest the example json be updated to:
`"Install": ["cert1.der", "cert2.pem", "%SYSTEMDRIVE%\\Company\\cert3.der", "/Library/Company/cert4.pem", "\\\\server\\certs\\cert.pem"]` with double backslashes in all the windows paths, and the glorious quadruple backslash for the UNC path

**Comment by mkaply** [comment]
Done. Thanks!
