### ISSUE TITLE
Custom Update Url

### ISSUE THREAD

**Issue by red-erik** [mozilla/policy-templates#371]
Hello,
I'm trying to update FF from internal server but GPO setting Custom Update Url does not override 
preference app.update.url
am I missing something ?

Regards.

**Comment by red-erik** [comment]
Something related to this ?
https://bugzilla.mozilla.org/show_bug.cgi?id=1468948
We are using ESR too.

Red.

**Comment by hheinen** [comment]
Maybe this will help you:
https://github.com/mozilla/policy-templates/issues/77

**Comment by mkaply** [comment]
The policy should work. What version of Firefox?

**Comment by red-erik** [comment]
FF 60.2 ESR and the Bugzilla link seems to be relevant.

**Comment by mkaply** [comment]
> FF 60.2 ESR 

Support for this was added in the 60.3 ESR (and Firefox 63).
