### ISSUE TITLE
Install / read personal certificate from windows store

### ISSUE THREAD

**Issue by redm5** [mozilla/policy-templates#372]
Hello,

i have a personal certificate for every user in cour company that i to be able to access a webpage. Unfortunately Firefox is unable to read the personal store of each user and that's why i need to install the certificate manually.

I can copy the cert9.db and key4.db files but for me this is a workaround and not a real solution to my problem.

Is there a comand to install certificates or is there an option which allows this ?

best regards

**Comment by mkaply** [comment]
We do not support reading client certificates from the Windows story, but you can explicitly install them using the Install policy under Certificates in group policy.

**Comment by CLiX90** [comment]
Is it planned for future releases to access personal user certs from the windows cert store (like chrome)?  Install with the existing group policy isn‘t realy a practical solution.

**Comment by mkaply** [comment]
We are looking at support for client certs.

**Comment by CLiX90** [comment]
Is there a roadmap? Our boss thinks about migration to google chrome because of this missing cert support.

**Comment by CLiX90** [comment]
We have another issue with client certificates. We use Microsoft Conditional Access to allow only access the Microsoft Cloud with managed devices. Microsoft uses a client certificate to check this. Firefox cannot access this certificate and the access is not possible.

**Comment by mkaply** [comment]
We're actively working on this and it's working in Nightly right now.

I'm putting together a plan to get it on ESR, earlier Firefox.

**Comment by mkaply** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1592111

**Comment by mkaply** [comment]
Client certificates are in release and will be in Firefox 78.

You can flip the pref

security.osclientcerts.autoload

or use the policy to flip it.
