### ISSUE TITLE
ImportEnterpriseRoots does not import Untrusted (revoked) certificates

### ISSUE THREAD

**Issue by R-Adrian** [mozilla/policy-templates#373]
this issue is related to:
https://bugzilla.mozilla.org/show_bug.cgi?id=1553233
and
https://forum.avast.com/index.php?topic=227348.0

tl;dr version: Root CA certificates that are revoked via the Certificate Manager are still imported and considered as valid by Firefox even if the operating system properly considers them as revoked.

![avast_root_ca_2](https://user-images.githubusercontent.com/16319504/58121018-1c243780-7c0f-11e9-95f9-875d15150b05.png)

![avast_root_ca_3](https://user-images.githubusercontent.com/16319504/58121020-1c243780-7c0f-11e9-89a0-4e175e5152c7.png)

![avast_root_ca_4](https://user-images.githubusercontent.com/16319504/58121022-1c243780-7c0f-11e9-9572-c815a01edc85.png)

**Comment by mkaply** [comment]
This policy simply maps to the preference, so the bugzilla bug is sufficient here.
