### ISSUE TITLE
documentation for Certificates / ImportEnterpriseRoots is incomplete

### ISSUE THREAD

**Issue by mozkeeler** [mozilla/policy-templates#375]
`The ImportEnterpriseRoots key will cause Firefox to import from the system certificate store.` 
We should probably include that it only imports 3rd party certificates that have been added by a user or administrator (people seem to think we're saying it imports the entire default Windows certificate store).

**Comment by Dark345** [comment]
definitely

**Comment by mkaply** [comment]
Done. Thanks!
