### ISSUE TITLE
Add-on/Extension enforcement issue

### ISSUE THREAD

**Issue by KingBluto** [mozilla/policy-templates#379]
Using Firefox ESR along with GPO Templates. Since the issue with with a Firefox update we have not been able to force enable addons. Adding them in the correct group policy template will place them in the addons menus however it does not automatically enable them anymore.

The key is successfully created in this location HKCU\Software\Policies\Mozilla\Firefox\Extensions\Install

And in HKCU\Software\Policies\Mozilla\Firefox\Extensions\Locked

I was only able to make the addon visible by manually creating the registry value in HKLM\SOFTWARE\Mozilla\Firefox\Extensions

Has anyone seen similar behavior or have a possible workaround?

Windows 10 x64 Enterprise Mozilla Firefox 60.7.0 x64

**Comment by mkaply** [comment]
Were the addons installed disabled? they should be enabled by default?

**Comment by KingBluto** [comment]
The Add-ons are installed disabled. I can go in an enable them manually, but I need to enable them for multiple users.

**Comment by mkaply** [comment]
> The Add-ons are installed disabled. I can go in an enable them manually, but I need to enable them for multiple users.

If we are installing them, they won't be disabled. Are they possibly being installed by some other mechanism besides Extensions/Install? Have the been installed and disabled before?

We actually have code in 60.7 ESR that explicitly enables addons which makes me think something else is going on:

https://searchfox.org/mozilla-esr60/source/browser/components/enterprisepolicies/Policies.jsm#568

**Comment by KingBluto** [comment]
I am installing them using the Group Policy Templates. One of which is an in house extension which worked previously and now doesn't.

**Comment by etsmi** [comment]
Having the same issue, system msi deployment, the extension installs but you have to manually enable it for every user. Tried adding the extension path also to the gpo templates, no luck.

**Comment by mkaply** [comment]
A couple things.

1. If you add the extension to HKLM\SOFTWARE\Mozilla\Firefox\Extensions it will be disabled by default. That's a third party extension.

2. I think I know why extensions aren't installing. Are you specifying a path on Windows like C:\foo\bar.xpi?

Can you change it to file:///c:/foo/bar.xpi and see if that works?

**Comment by mkaply** [comment]
Were you able to test this?
