### ISSUE TITLE
InstallAddonsPermission not blocking installation from domains that are not set

### ISSUE THREAD

**Issue by H-ISO** [mozilla/policy-templates#380]
Hello,
we have set InstallAddonsPermission with "Allow": ["https://addons.mozilla.org/"] in order to limit add-on installations from just this trusted domain, but we were still able to install add-ons from other sites, e.g. [https://my.jdownloader.org/apps/](url) or [https://1password.com/de/browsers/beta/firefox/](url). Is there any other settings that needs to be set in order to make this work? Or is the thing that we are trying to achieve not possible with this setting?
Thank you in advance and keep up the great work with Firefox policies :)

**Comment by mkaply** [comment]
That's going to be in Firefox 68. I've basically implemented Chrome's ExtensionSettings:

https://dev.chromium.org/administrators/policy-list-3/extension-settings-full

I should have docs on it soon so folks can test in beta.

**Comment by H-ISO** [comment]
> 
> 
> That's going to be in Firefox 68. I've basically implemented Chrome's ExtensionSettings:
> 
> https://dev.chromium.org/administrators/policy-list-3/extension-settings-full
> 
> I should have docs on it soon so folks can test in beta.

Looking forward to v68 then :)
