### ISSUE TITLE
ADMX V1.7 RSOP ISSUES

### ISSUE THREAD

**Issue by Electricavenues** [mozilla/policy-templates#381]
Hi since deploying this 1.7 ADMX set we are getting RSOP error saying the firefox.adml has a revision of 1.5 which does not meet the minRequiredRevision specified in the ADMX file.

Please could you advise on resolution?

![image](https://user-images.githubusercontent.com/51994063/59756732-3f7bea00-9282-11e9-968f-660b727cb090.png)

**Comment by mkaply** [comment]
I'm very sorry. I changed one place and forgot another. I've updated the template release.

**Comment by Electricavenues** [comment]
Hi Michael
Thank you for your prompt response and resolution on this greatly appreciated!



Daniel James - IT Technician
T:  01245 235485
M:
E: daniel.james@bew-elec.co.uk
[cid:BEWLogo2CROPPED_649bf9ba-4995-41bf-9f9c-a36429e1147b.jpg]  [cid:elektrack_51f7e013-9ec0-42a0-808c-26deb31b9549.png]
BEW Electrical Distributors Ltd,
Unit 5 Northumberland Court,
Dukes Park Industrial Estate,
Chelmsford, Essex,
CM2 6UW Chelmsford (Head Office):
T: 01245 495757
F: 01245 496178
http://www.bewdirect.co.uk
[cid:Facebook_1e2b09bb-f8b5-4a0f-b289-8b13770154fd.png]<http://www.facebook.com/BEWelectrical><http://www.facebook.com/BEWelectrical>   [cid:Twitter_da4559ae-eb56-4e48-803f-328053547316.png] <https://twitter.com/BEW_ELECTRICAL> <https://twitter.com/BEW_ELECTRICAL>        [cid:LinkedIn_64f6a95d-4930-4dcd-8e17-f43687430537.png] <https://www.linkedin.com/company/bew-electrial-distributors-ltd> <https://www.linkedin.com/company/bew-electrial-distributors-ltd>

The information in this message is confidential. It is intended only for use of the named recipient. If you are not the intended recipient, please notify the sender immediately. You should not disclose the information to any person or take any copies. The use, dissemination or taking any action in reliance on the contents of this message is prohibited and unlawful. If you have received this e-mail in error, please return the original message to BEW ELECTRICAL DISTRIBUTORS LTD. By e-mail to enquiries@bew-elec.co.uk.
