### ISSUE TITLE
GPO Wish: Enforce primary homepage while allowing user to add additional homepages

### ISSUE THREAD

**Issue by jeffreymcclain** [mozilla/policy-templates#383]
Currently it is possible to enforce a primary homepage as well as additional homepages using group policy. However, it is NOT possible to enforce a "primary" homepage while simultaneously allowing users to add their own additional homepages.

Related forum posts for other browsers: 

- https://community.spiceworks.com/topic/306774-setting-our-intranet-page-as-home-page-on-chrome-already-done-on-ie?page=2

- https://community.spiceworks.com/topic/225684-how-to-enforce-a-primary-home-page-in-ie-and-allow-users-to-select-secondary

- https://www.reddit.com/r/sysadmin/comments/c2oanw/use_group_policy_to_set_homepage_across_all_major/

- https://serverfault.com/questions/777727/how-to-set-an-enforced-ie-homepage-whilst-allowing-additional-user-defined-tabs

**Comment by mkaply** [comment]
Unfortunately with the way homepage UI is done in pretty much every browser, I don't see an easy way to do this. Multiple homepages on Firefox in the same entry field with a | as a delimiter...

**Comment by mkaply** [comment]
I appreciate the request, but there's no good way to do this and no other browser supports it.
