### ISSUE TITLE
request inclusion of "security.insecure_connection_*" settings

### ISSUE THREAD

**Issue by Conan1989** [mozilla/policy-templates#384]
Hi,
Request the following settings to be controllable via Group Policy.
Thank you

security.insecure_connection_icon.enabled
security.insecure_connection_icon.pbmode.enabled
security.insecure_connection_text.enabled
security.insecure_connection_text.pbmode.enabled

can test with
http://http.badssl.com/

**Comment by Conan1989** [comment]
Hi,
just following up. The intention is to turns those settings one, achieve something like the following

before: 
![image](https://user-images.githubusercontent.com/6946596/81881416-a469be00-957f-11ea-9511-ff62fa448573.png)

after:
![image](https://user-images.githubusercontent.com/6946596/81881423-a764ae80-957f-11ea-8750-c52f16ca9aba.png)

**Comment by mkaply** [comment]
So the icons are already enabled, you're just looking to add the text?

**Comment by Conan1989** [comment]
yes please.
Thinking is, the more obvious and scary looking we can make non-https stuff the better. Helps to get corp to approve cutting over internal sites to https too

**Comment by mkaply** [comment]
This is settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences

**Comment by Conan1989** [comment]
I'm not able to find this change in the updated .ADML / .ADMX

![image](https://user-images.githubusercontent.com/6946596/95177822-2d42f980-07ae-11eb-847d-13d546643f6b.png)

**Comment by Conan1989** [comment]
my mistake, sorry. Didn't read the part about the new JSON method
