### ISSUE TITLE
feature request: layout.spellcheckDefault

### ISSUE THREAD

**Issue by Conan1989** [mozilla/policy-templates#386]
Hi,
the current default for "layout.spellcheckDefault" is 1, which enables spellcheck for multiline text boxes only.
A group policy option to set that value as 2, which enables spellcheck for single and multiline text boxes would be useful.

Thanks

http://kb.mozillazine.org/Layout.spellcheckDefault

**Comment by mkaply** [comment]
This is settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences

**Comment by Conan1989** [comment]
I'm not able to find this change in the .ADML / .ADMX or in the README.md

**Comment by Conan1989** [comment]
my mistake, sorry. Didn't read the part about the new JSON method
