### ISSUE TITLE
gpo parametre is not change

### ISSUE THREAD

**Issue by aurelgodin** [mozilla/policy-templates#389]
Hello,

Sorry for my English.

I installed Firefox 60.7.2esr with policy templates.

I realized that if you change the proxy settings or homepage the settings do not update at Firefox restart.

Is this normal?

**Comment by mkaply** [comment]
If the user has changed the values, then settings them won't change them for the user.

Can you try locking them and see if the change?

**Comment by aurelgodin** [comment]
Before using GPO for Firefox, when a user made a change it was overwritten by the settings of the GPO.
This feature does not exist ?

**Comment by mkaply** [comment]
The GPO sets the default value unless you lock it.

**Comment by aurelgodin** [comment]
thank you for your answers
