### ISSUE TITLE
Will this be available for Linux anytime soon...?

### ISSUE THREAD

**Issue by vF360** [mozilla/policy-templates#39]

**Comment by mkaply** [comment]
Any beta build will already have the policy engine.

See.

https://github.com/mozilla/policy-templates/blob/master/README.md

Most linux distros already have a distribution directory that Firefox is already using.

**Comment by vF360** [comment]
Oh ok. Is it possible for you to add some sort of timer to the template so I can only open Firefox at a certain time?

**Comment by mkaply** [comment]
> Oh ok. Is it possible for you to add some sort of timer to the template so I can only open Firefox at a certain time?

That's not really in scope for enterprise policies. I would look for some application that could do that.
