### ISSUE TITLE
DisableSafeMode via policies.json

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/policy-templates#391]
Hi and thank you for the great new documentation.

The new documentation says that the DisableSafeMode policy can be set via policies.json but according to https://bugzilla.mozilla.org/show_bug.cgi?id=1496869#c5 it can't be set via policies.json. I tested on macOS and the menu item to start in safe mode is disabled but you can still start with safe mode enabled. So maybe it should be made clear in the documentation that it only affects the menu item.

**Comment by mkaply** [comment]
I will definitely update the documentation to make this clear. Thanks!

**Comment by mkaply** [comment]
I've updated the docs. Please let me know what you think.
