### ISSUE TITLE
GPO Wish: bool browser.fixup.dns_first_for_single_words || bool keyword.enable 

### ISSUE THREAD

**Issue by Vodochnik** [mozilla/policy-templates#392]
Need this like a hell for intranet addresses :)
Thanks in advance, you make a great job for hundred thousands of admins!

**Comment by mkaply** [comment]
You'll get browser.fixup.dns_first_for_single_words in firefox 68.

**Comment by Vodochnik** [comment]
Wow, thanks for quick response! I need it in Firefox ESR 60.7.2 and later... 
tried policies.json on it (32-bit) on my local machine, but it does not work somehow...
{"policies": {"Preferences": {"browser.fixup.dns_first_for_single_words": true}}}

It would be nice if i could deploy this setting via GPO :)))

**Comment by mkaply** [comment]
The new ESR comes out tomorrow and it will be available there.

You will be able to deploy it via GPO on Windows, but again, Firefox 68 only. (firefox 60 end of life is in 12 weeks)"

**Comment by Vodochnik** [comment]
Do i understand it correct, i have to wait for ESR 68 for this setting? We don't have "regular" Firefox in the enterprise, only ESR... and it can take ages before ESR 68 comes out, right?

**Comment by mkaply** [comment]
ESR 68 actually comes out tomorrow. So your company can choose to switch as soon as they are ready.

It has a lot of great new features for enterprises.

You can see our release calendar here:

https://wiki.mozilla.org/Release_Management/Calendar

Support for Firefox 60 ESR officially ends on October 22.

**Comment by Vodochnik** [comment]
I have seen your commits for Preferences, waiting for tomorrow :joy: 
Hope, this repo will be updated too:)

**Comment by mkaply** [comment]
This is in Firefox 68. All docs are updated.
