### ISSUE TITLE
"Create Master Password" policy does not work with the ADMX file

### ISSUE THREAD

**Issue by amasresha** [mozilla/policy-templates#4]
Steps to reproduce:
Screen capture- https://testing-1.tinytake.com/sf/MjQxNDc2N183MzE4Mzcy

1- Enabled or disable "Create Master Password" policy in Group Policy Editor
2- Go to about:preferences#privacy  and check "use a master password" is unchecked and greyed out

Actual Result:
No change to the browser by using this

Expected Result:
Should disable the create master password option

**Comment by mkaply** [comment]
I forgot to remove false from the enum:

https://bugzilla.mozilla.org/show_bug.cgi?id=1443650

In addition, this should be a "Disable" policy, not an enable policy. Need to make sure it works that way.

**Comment by mkaply** [comment]
This is ready to test in the latest nightly. Fixes were there. Policy didn't change.
