### ISSUE TITLE
Ungültiger Wert "                    Portal" für Eigenschaft "id" .

### ISSUE THREAD

**Issue by drlellinger** [mozilla/policy-templates#400]
Ungültiger Wert "                    Portal" für Eigenschaft "id" .
Datei C:\windows\PolicyDefinitions\de-DE\firefox.adml, Zeile 80, Spalte 26

when opening gpedit.msc.
Firefox Policy Defintions are not available to user to set.

**Comment by mkaply** [comment]
I assume you were using the brand new policies? I have fixed the issue you were seeing, but these are still being completed for Firefox 68. They'll be done by end of day.
