### ISSUE TITLE
GPO startPage and URL not working on ESR68 64bits

### ISSUE THREAD

**Issue by urbanspike** [mozilla/policy-templates#408]
Hello,

in french environnement :
I test GPO in RDS Environment. I Have add ADMX and ADML on PolicyDefinition on my domain.
I want to set default page for all user to www.google.fr for example.
 In registy, Gpo are OK :
Key Homepage with Locked to 1 , StartPage to homepage and URL to www.google.fr

But when user lauch firefox, it's not working.

For test , i have blocked about:config and this is OK for that.

Any ideas why Homepage parameters not working ?

Thank's

**Comment by mkaply** [comment]
You have to put http:// or https:// in front of the URL.

**Comment by urbanspike** [comment]
With http:// or Https:// in front, it's OK !
Thank you so much !
