### ISSUE TITLE
Feature request browser.download.skipConfirmLaunchExecutable

### ISSUE THREAD

**Issue by Blank-Vcf** [mozilla/policy-templates#410]
Have updated do esr 68 at work and .jnlp file are lock on execution from internal app usage.
Found information there: https://support.mozilla.org/fr/questions/1260307
The key is working but doesn't exist by default, i try to add it manually to registry in HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox\Preferences like browser.tabs.warnOnClose but it's not created on new profile.

Don't know if it could be possible or add exception for only specified url.

**Comment by Blank-Vcf** [comment]
I have try 68.1.0 still same "problem".

**Comment by mkaply** [comment]
The fix is in 68.2

https://bugzilla.mozilla.org/show_bug.cgi?id=1576616

Is this sufficient for you?

**Comment by Blank-Vcf** [comment]
Yes, it would be ok.
