### ISSUE TITLE
GPO Extension Whitelist limitation, search engines and themes disappear

### ISSUE THREAD

**Issue by sjd4** [mozilla/policy-templates#416]
I downloaded the GPO templates from https://github.com/mozilla/policy-templates/issues/115, but my JSON gets truncated.  It looks like GPO will only accept 1024 characters.  While blocking * that means I can only allow about 4 plugins.

**Comment by sjd4** [comment]
I can manually set the REG_SZ at:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox
ExtensionSettings

to:
{"policies": {"ExtensionSettings": {"*": {"blocked_install_message": "Please contact your administrator to install plugins.","install_sources": ["https://addons.mozilla.org/"],"installation_mode": "blocked"},"uBlock0@raymondhill.net": {"installation_mode": "allowed","install_url": "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"},"jid1-MnnxcxisBPnSXQ@jetpack": {"installation_mode": "allowed","install_url": "https://addons.mozilla.org/firefox/downloads/latest/privacy-badger17/latest.xpi"},"CanvasBlocker@kkapsner.de": {"installation_mode": "allowed","install_url": "https://addons.mozilla.org/firefox/downloads/latest/canvasblocker/latest.xpi"},"ciscowebexstart1@cisco.com": {"installation_mode": "allowed","install_url": "https://addons.mozilla.org/firefox/downloads/latest/cisco-webex-extension/latest.xpi"},"jid1-BoFifL9Vbdl2zQ@jetpack": {"installation_mode": "allowed","install_url": "https://addons.mozilla.org/firefox/downloads/latest/decentraleyes/latest.xpi"},"@testpilot-containers": {"installation_mode": "allowed","install_url": "https://addons.mozilla.org/firefox/downloads/latest/multi-account-containers/latest.xpi"},"https-everywhere@eff.org": {"installation_mode": "allowed","install_url": "https://addons.mozilla.org/firefox/downloads/latest/https-everywhere/latest.xpi"},"smart-referer@meh.paranoid.pk": {"installation_mode": "allowed","install_url": "https://addons.mozilla.org/firefox/downloads/latest/smart-referer/latest.xpi"}}}}

but it doesn't seem to work.  I can still install new add-ons.

**Comment by mkaply** [comment]
I figured out the limitation thing. ADMX defaults to 1023 for some reason. I'll up the maxLength for that. Researching the search problem.

**Comment by sjd4** [comment]
Michael,

I’d just like to say, you are extremely responsive.  I really appreciate the work your are putting into this.

Shawn

**Comment by mkaply** [comment]
I've pulled the releases for now because the search issue is not recoverable. I'll be working on a Firefox fix and then hope to have an update soon. Thanks for finding this.

**Comment by sjd4** [comment]
I clicked Restore Default Search Engines in about:preferences#search and it brought them back , but they don’t have favicon and are probably not exactly the same, but DuckDuckGo is working fine for me so I can’t complain for now.

**Comment by sjd4** [comment]
Also, it disabled the dark theme I was using and the light theme, but I was able to enable it again.

**Comment by sjd4** [comment]
I might be complicating things further with an unrelated problem, but I now get mmc.exe crashing with ntdll.dll errors.  I wouldn't mention it if it was only one computer, but now it's happened on two.  I'm not sure exactly what has caused it, but removing the mozilla and firefox adml, admx files don't help get gpedit.msc to open again.  I even deleted the reg keys for mozilla in Policies.  You haven't experienced anything like this?

**Comment by mkaply** [comment]
FYI, There should be a fix for the original problem in the next Firefox update in a couple days.

**Comment by sjd4** [comment]
Awesome.

**Comment by mkaply** [comment]
Unfortunately the fix got pushed out. Sorry about that. It's going to be in 69 and the next ESR update in a few weeks.

**Comment by sjd4** [comment]
Btw, I was able to protect the themes and search providers by adding this to the JSON:
"firefox-compact-dark@mozilla.org": {"installation_mode": "allowed"},"firefox-compact-light@mozilla.org": {"installation_mode": "allowed"},"ddg@search.mozilla.org": {"installation_mode": "allowed"}

**Comment by sjd4** [comment]
So is the fix in Firefox 69.0?  It seems like it's working.  I reset my search engines and they all came back with the little favicons.  Does the GPO accept more than 1023 characters?  I'll do some more testing if it's supposed to be ready now.

> 
> 
> I figured out the limitation thing. ADMX defaults to 1023 for some reason. I'll up the maxLength for that. Researching the search problem.

**Comment by mkaply** [comment]
> So is the fix in Firefox 69.0? It seems like it's working. I reset my search engines and they all came back with the little favicons. Does the GPO accept more than 1023 characters? I'll do some more testing if it's supposed to be ready now.

Yep. I'll be uploading the official release templates today. And the new GPO does do more than 1023. As a bonus, it uses a multiline field in the GPO so it's much easier to use.

**Comment by sjd4** [comment]
So I downloaded the latest release and am trying it in Windows Sandbox, but it doesn't seem to block plugins from installing.  The policy says it's active in about:policies.  Here is my testing JSON I've posted in the group policy for Extension Management exactly:
{
   "policies":{
      "ExtensionSettings":{
         "*":{
            "blocked_install_message":"Please contact your administrator to install plugins.",
            "install_sources":["https://addons.mozilla.org/"],
            "installation_mode":"blocked"
         },
         "uBlock0@raymondhill.net":{
            "installation_mode":"allowed",
            "install_url":"https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"
         },
         "jid1-MnnxcxisBPnSXQ@jetpack":{
            "installation_mode":"allowed",
            "install_url":"https://addons.mozilla.org/firefox/downloads/latest/privacy-badger17/latest.xpi"
         },
         "CanvasBlocker@kkapsner.de":{
            "installation_mode":"allowed",
            "install_url":"https://addons.mozilla.org/firefox/downloads/latest/canvasblocker/latest.xpi"
         },
         "ciscowebexstart1@cisco.com":{
            "installation_mode":"allowed",
            "install_url":"https://addons.mozilla.org/firefox/downloads/latest/cisco-webex-extension/latest.xpi"
         },
         "jid1-BoFifL9Vbdl2zQ@jetpack":{
            "installation_mode":"allowed",
            "install_url":"https://addons.mozilla.org/firefox/downloads/latest/decentraleyes/latest.xpi"
         }
      }
   }
}

**Comment by sjd4** [comment]
That was it.  Here is the correct format:
```
{
   "*":{
      "blocked_install_message":"Please contact your administrator to install plugins.",
      "install_sources":["https://addons.mozilla.org/"],
      "installation_mode":"blocked"
   },
   "uBlock0@raymondhill.net":{
      "installation_mode":"allowed",
      "install_url":"https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"
   },
   "jid1-MnnxcxisBPnSXQ@jetpack":{
      "installation_mode":"allowed",
      "install_url":"https://addons.mozilla.org/firefox/downloads/latest/privacy-badger17/latest.xpi"
   },
   "CanvasBlocker@kkapsner.de":{
      "installation_mode":"allowed",
      "install_url":"https://addons.mozilla.org/firefox/downloads/latest/canvasblocker/latest.xpi"
   },
   "ciscowebexstart1@cisco.com":{
      "installation_mode":"allowed",
      "install_url":"https://addons.mozilla.org/firefox/downloads/latest/cisco-webex-extension/latest.xpi"
   },
   "jid1-BoFifL9Vbdl2zQ@jetpack":{
      "installation_mode":"allowed",
      "install_url":"https://addons.mozilla.org/firefox/downloads/latest/decentraleyes/latest.xpi"
   }
}```

**Comment by mkaply** [comment]
I'll see what I can figure out.

**Comment by sjd4** [comment]
> 
> 
> I'll see what I can figure out.

Michael,

See my edited post.  It looks like the JSON example doesn't work for the GPO.  I referred to the Windows registry example.  Now it works, but you may need to update the documentation on:
https://github.com/mozilla/policy-templates#extensionsettings

**Comment by linh3301** [comment]
I feel like I'm missing something, but is there any easy way to find the extension ID?

**Comment by mkaply** [comment]
After installing the extension go to about:support in the URL bar. There's a section called Extensions that shows the extensions and their ID.

**Comment by linh3301** [comment]
Ah, so we have to install it to get the ID? No way to grab it elsewhere?

**Comment by mkaply** [comment]
In many cases, you can unzip the XPI and view it. I have a plan to build a WebExtension to help get this information from AMO, but haven't had a chance to do that.

**Comment by sjd4** [comment]
Maybe you should close this out.  The Windows example/doc just needs a little cleanup since it takes a REG_MULTI_SZ in the registry or multi-lined string in the GPO.  I swear I'm not trying to be nitpicky, but maybe the extension ID issue should be a separate issue?

**Comment by mkaply** [comment]
good call. I'll update the docs.
