### ISSUE TITLE
Local Extension install via GPO debugging

### ISSUE THREAD

**Issue by masaykh** [mozilla/policy-templates#417]
Installed profiles.
Put UNC location of corporate extension ( //someplace/somefolder/file.xpi )
One time it installed.
So i removed an extension and tried to restart firefox to see if it will install an extension again but nothing happening 

I opened about:policies#active and do see policies.
about:policies#errors - are empty

Is there any log files I can trace extension installation?
Or some debugs to turn on?

**Comment by masaykh** [comment]
Checked browser console:
Only found that Firefox looking for InstallDir/distribution/extensions/proper_package_name.xpi to install

Looks like he don`t look for policies.json if registry is filled - this is expected behavior?

**Comment by mkaply** [comment]
Yes, GPO and policies.json are mutually exclusive right now. I'm working on a solution that allows policies.json as long as they don't override GPO.

**Comment by masaykh** [comment]
So, is there way to force extension reinstall?
Any specific log file i can trace installation with?

**Comment by mkaply** [comment]
Easiest way to force a reinstall is to change the name of the XPI in the policy.

What version of Firefox are you using? We fixed a bug where we clear the install policy when we uninstall an extension.

**Comment by masaykh** [comment]
Firefox Quantum 67.0.4

**Comment by masaykh** [comment]
Updated to 68.0.1

**Comment by mkaply** [comment]
We have a new policy that will make this much easier. It should be ready to use in Firefox 68.0.2 next week.

**Comment by mkaply** [comment]
Were you able to check out the new policy?
