### ISSUE TITLE
DownloadDirectory path platform-specific

### ISSUE THREAD

**Issue by extra808** [mozilla/policy-templates#424]
In [DownloadDirectory](https://github.com/mozilla/policy-templates/blob/master/README.md#downloaddirectory), `${home}` maps to the native home directory but the path separators are platform-specific, preventing policies.json from being platform-agnostic. The example value, `"${home}/Downloads"` is ignored on Windows, escaped backslashes are required, i.e. `"${home}\\Downloads."` In turn, the escaped backslash value is ignored on macOS (and I assume on Linux).

I assume [DefaultDownloadDirectory](https://github.com/mozilla/policy-templates/blob/master/README.md#defaultdownloaddirectory) is the same.

Is addressing this within the scope of policies? Since `${home}` is doing work to handle platform differences, I hope not. If it's not in-scope, perhaps a Windows JSON example could be added to the README.

**Comment by mkaply** [comment]
My thought was that most folks would have platform specific policies, so I wouldn't handle it in policies.

I'll add the example.

**Comment by mkaply** [comment]
I've updated the examples.
