### ISSUE TITLE
GPO wishlist

### ISSUE THREAD

**Issue by joandriessen** [mozilla/policy-templates#425]
Please implement the below list of preferences in the FireFox GPO:
(Updated: 09.16.2019)

app.normandy.enabled
app.shield.optoutstudies.enabled
app.update.service.enabled
app.update.staging.enabled
beacon.enabled
browser.cache.disk_cache_ssl
browser.cache.memory.enable
browser.cache.offline.enable
browser.fixup.alternate.enabled
browser.formfill.expire_days
browser.library.activity-stream.enabled
browser.newtab.preload
browser.ping-centre.telemetry
browser.privatebrowsing.autostart
browser.safebrowsing.downloads.remote.enabled
browser.send_pings.require_same_host
browser.sessionstore.max_tabs_undo
browser.sessionstore.max_windows_undo
browser.sessionstore.privacy_level
browser.ssl_override_behavior
browser.tabs.remote.autostart
browser.urlbar.autoFill
browser.urlbar.maxRichResults
browser.urlbar.speculativeConnect.enabled
device.sensors.enabled
dom.battery.enabled
dom.enable_performance
dom.event.clipboardevents.enabled
dom.gamepad.enabled
dom.ipc.plugins.flash.subprocess.crashreporter.enabled
dom.vr.enabled
dom.webnotifications.enabled
dom.webnotifications.serviceworker.enabled
extensions.blocklist.enabled
extensions.formautofill.addresses.enabled
extensions.formautofill.available
extensions.formautofill.creditCards.enabled
extensions.formautofill.heuristics.enabled
extensions.getAddons.cache.enabled
extensions.lastAppVersion
extensions.screenshots.upload-disabled
extensions.update.autoUpdateDefault
geo.enabled
gfx.direct2d.disabled
gfx.font_rendering.opentype_svg.enabled
identity.fxaccounts.auth.uri
javascript.options.asmjs
javascript.options.wasm
keyword.enabled
layout.css.visited_links_enabled
media.getusermedia.screensharing.enabled
media.gmp-manager.url
media.navigator.enabled
media.peerconnection.enabled
media.peerconnection.ice.default_address_only
media.peerconnection.use_document_iceservers
media.video_stats.enabled
network.automatic-ntlm-auth.allow-proxies
network.cookie.thirdparty.sessionOnly
network.http.referer.XOriginPolicy
network.http.spdy.enabled
network.http.speculative-parallel-limit
network.predictor.enabled
network.prefetch-next
plugin.default.state
plugin.defaultXpi.state
privacy.donottrackheader.enabled
privacy.popups.disable_from_plugins
reader.parse-on-load.enabled
security.cert_pinning.enforcement_level
security.dialog_enable_delay
security.mixed_content.block_display_content
security.ocsp.require
security.pki.sha1_enforcement_level
security.ssl.treat_unsafe_negotiation_as_broken
services.settings.server
services.sync.engine.addons
services.sync.engine.bookmarks
services.sync.engine.history
services.sync.engine.passwords
services.sync.engine.prefs
services.sync.engine.tabs
signon.autofillForms
signon.rememberSignons.visibilityToggle
toolkit.telemetry.bhrPing.enabled
toolkit.telemetry.firstShutdownPing.enabled
toolkit.telemetry.hybridContent.enabled
toolkit.telemetry.newProfilePing.enabled
toolkit.telemetry.shutdownPingSender.enabled
toolkit.telemetry.unified
toolkit.telemetry.updatePing.enabled
webgl.disabled

**Comment by drlellinger** [comment]
Some of these settings are already implemented in the GPOs

**Comment by drlellinger** [comment]
For the list of already implemented policies check https://github.com/mozilla/policy-templates/blob/master/README.md

**Comment by joandriessen** [comment]
Updated the list by removing already implemented GPO settings

**Comment by AfroThundr3007730** [comment]
Not sure if this is the right place to ask, but if we're collecting a pref wishlist, I'd like to add these to allow for compliance with DISA STIG guidance:
```
network.protocol-handler.external.shell
plugin.disable_full_page_plugin_for_types
signon.autofillForms
```
Although I wonder if it would be easier in the long run to just allow Firefox to parse arbitrary preferences applied through the enterprise policy, which I've opened a bug for [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1612253).

**Comment by mkaply** [comment]
So I've added a lot of arbitrary prefs now.

https://github.com/mozilla/policy-templates#preferences

If you have specific needs, please open separate issues.

I'm going to add signon.* as well.

As far as STIG goes, I'm updating that.
