### ISSUE TITLE
Add Preferences by ourself

### ISSUE THREAD

**Issue by aurelgodin** [mozilla/policy-templates#428]
is there an option to add preference in GPOs, So we can do this actions by ourself

Example add the preference "toolkit.healthreport.service.enabled" or "security.mixed_content.block_active_content"

Thanks

**Comment by mkaply** [comment]
No, right now if you need to add custom preferences, you need to use Autoconfig. You can request preferences (as you have done here).

Note that toolkit.healthreport.service.enabled is no longer used in Firefox.

As far as security.mixed_content.block_active_content goes, I'll check into this, but note this is a security risk if you turn this off.

**Comment by aurelgodin** [comment]
This reference is still available in firefox "toolkit.healthreport.service.enabled", I see it in about: config.

For "security.mixed_content.block_active_content" I want you to confirm me.

I have 2 other preferences to propose:
"datareporting.healthreport.uploadEnabled"
"browser.rights.3.shown"

Thanks

**Comment by mkaply** [comment]
What version of Firefox are you using?

**Comment by aurelgodin** [comment]
I am using version 68.0.2 esr

**Comment by mkaply** [comment]
If you have the preference toolkit.healthreport.service.enabled, it's because it's being set by autoconfig or something. It's not used by Firefox anymore.

datareporting.healthreport.uploadEnabled is controlled by the DisableTelemetry polici

Although the browser.rights.3.shown pref still exists in about:config, it's not used by Firefox.

**Comment by aurelgodin** [comment]
Thank you very much for your return.

**Comment by aurelgodin** [comment]
Hello,

Could you check for the preference "security.mixed_content.block_active_content"?

**Comment by mkaply** [comment]
This is settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences
