### ISSUE TITLE
"Extensions to Install" GPO no longer functions

### ISSUE THREAD

**Issue by jackdouglas** [mozilla/policy-templates#433]
Commit ce7da214486f45c98ac36f116b77d33808e27288 seems to have introduced a bug. The list of extensions is now ignored.

The keys are added to the registry at [HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox\Extensions\Install] as REG_EXPAND_SZ rather than REG_SZ — manually setting the registry entries back to REG_SZ fixes the issue.

**Comment by mkaply** [comment]
You should be using the officially released policies with the current version of Firefox:

https://github.com/mozilla/policy-templates/releases/

That change is to support the next version of Firefox which will be out next week.
