### ISSUE TITLE
REQUEST - thunderbird 68 template creation?

### ISSUE THREAD

**Issue by Solwayuk** [mozilla/policy-templates#434]
Can the firefox policy files be adapted to support thunderbird version 68 ESR?

currently no resources from thunderbird developers are working on this.
even though new policy engine feature has been released in version 68.

https://bugzilla.mozilla.org/show_bug.cgi?id=1578669

**Comment by mkaply** [comment]
I don't have the bandwidth to do this, but anyone from the community can feel free to do this.

As far as I know, no actual policies were implemented in TB 68, were they?

**Comment by Solwayuk** [comment]
Spoken about this on irc with a thunderbird developer. Apparently your policy engine was ported into thunderbird 68. And mentioned in the release notes as a feature. 
They didn't know any more info about it. Nor where the admx files. Apparent the ff admx can be used?? 
Is there a way to progress this feature. I couldn't find any more info on the engine or API

**Comment by Solwayuk** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1578669

**Comment by mkaply** [comment]
This should be a very straightforward thing to do based on looking at the policy code that is in Thunderbird. They should be able to take the Firefox policy files and make a couple changes and that's it.

**Comment by Solwayuk** [comment]
They said they don't have the resources.
I'm willing to progress this (if I can)
Can you put me towards policy code?

Would this policy code support all settings, including email account prefs?

**Comment by mkaply** [comment]
You can see what policies were implemented for Thunderbird here:

https://searchfox.org/comm-central/source/mail/components/enterprisepolicies/schemas/policies-schema.json

Right now they only have copied over some Firefox policies. There is nothing unique for thunderbird.

The policies themselves are created by adding the schema to that file and then implementing the policy code in:

https://searchfox.org/comm-central/source/mail/components/enterprisepolicies/Policies.jsm

**Comment by drlellinger** [comment]
Is anyone already on it? I would do it

**Comment by Solwayuk** [comment]
Feel free, don't think I can help much. Took a look last night. But bit Past my level of expertise. 

Happy to test though. Or at least some sort of help. 

Can we redirect this over to 

https://bugzilla.mozilla.org/show_bug.cgi?id=1578669

**Comment by drlellinger** [comment]
https://github.com/drlellinger/thunderbird-policies created

**Comment by mkmelin** [comment]
For reference, https://github.com/thundernest/policy-templates is now created and we can adjust the documentation there to be Thunderbird specific, for the small parts that differs (like non-applicable policies)

**Comment by drlellinger** [comment]
First two policies were implemented - found a program bug on the way. [#1579019](https://bugzilla.mozilla.org/show_bug.cgi?id=1579019)
