### ISSUE TITLE
GPO wish : network.http.response.timeout

### ISSUE THREAD

**Issue by YoannPERCHET** [mozilla/policy-templates#437]
Hello

do you think it will be possible ton implement this patameter on you GPO ADMX ?

**Comment by mkaply** [comment]
I'm wondering why you are changing this value? Are you lowering it?

**Comment by YoannPERCHET** [comment]
We set it to 0 for IT user's. It is for launch some treatment like API rest who can be very long for response.

**Comment by mkaply** [comment]
This is settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences
