### ISSUE TITLE
Feature request: lockPref - ask to save files xls, xlsx, doc, docx

### ISSUE THREAD

**Issue by wdiatlee** [mozilla/policy-templates#442]
I did see Prompt for download location but that doesn't work under User or Computer configurations using 68.0.2 ESR MSI.

If we could lock it down so it always asks the question what to do with the file, open or save and disable the do this automatically would help majorly in this situation.

I also do not want to copy the handlers.json file into everyone's profile. The whole point of a Group Policy is being able to control things without leaving a mess behind i.e files or registry.

The main files we deal with and I'm guessing majority of the corporate world also do:

If the user ticks "Save File" and also Click "Do this automatically for files like this from now on" and they forget then the user is left to sometimes think nothing is happening.

PDF, I can disable the built-in viewer but then it auto downloads without notifying the user.
XLS - asks the question, what would you like to do.
XLSX - asks the question, what would you like to do.
DOC - asks the question, what would you like to do.
DOCX - asks the question, what would you like to do.

**Comment by mkaply** [comment]
> I did see Prompt for download location but that doesn't work under User or Computer configurations using 68.0.2 ESR MSI.

Are you saying that the   PromptForDownloadLocation policy isn't working for you?

It should do exactly what you are saying when set to true - always ask for a location.

**Comment by wdiatlee** [comment]
Let me play around with this some more, Is there a way this feature can also work for the "Open File" option if the user accidentally ticks do this automatically??? Because if there is MS Office and another office program on the same computer it would be beneficial to also lock that option down so the user cannot tick that box?

**Comment by mkaply** [comment]
Yeah, that's an interesting point. Basically prevent users from setting a permanent setting for any helper apps.

**Comment by wdiatlee** [comment]
Is this possible to implement? so Save File and Open File are always prompted and the do this automatically tick box is grayed out so the user cannot select it?

**Comment by mkaply** [comment]
It is possible. I'm investigating.

**Comment by wdiatlee** [comment]
Thank you

Sent from my iPhone

On 14 Sep 2019, at 6:52 am, Michael Kaply <notifications@github.com> wrote:

﻿

It is possible. I'm investigating.

**Comment by AfroThundr3007730** [comment]
Isn't this behavior normally controlled by `plugin.disable_full_page_plugin_for_types`? If so, adding it to the Preferences list in group policy would solve this problem, I think.

**Comment by mkaply** [comment]
> Isn't this behavior normally controlled by `plugin.disable_full_page_plugin_for_types`? If so, adding it to the Preferences list in group policy would solve this problem, I think.

That preference only affects full screen plugins (and isn't used anymore now that plugins aren't supported)

**Comment by sidescraper** [comment]
We would also be interested in this feature

PDF, MP3, XSPF

**Comment by mkaply** [comment]
I think the new handlers policy will do this for you now.

https://github.com/mozilla/policy-templates#handlers

**Comment by mkaply** [comment]
Handlers policy does what is requested here.
