### ISSUE TITLE
Cannot load security device

### ISSUE THREAD

**Issue by zim333** [mozilla/policy-templates#445]
Hello,
I am trying to load a security device on firefox with GPO but it doesn't work.
This is my configuration :

- windows 7 (64 bits)
- firefox 60.9.0 ESR (32bits)
- policy templates v1.9

We deployed a msi called "Cryptolib CPS" ( https://esante.gouv.fr/services/espace-cps/telechargements-libres/cryptolib-cps-windows) 

A security device must be loaded on firefox, so i have configured a GPO to load the pkcs11 file.

On client computer; i have the correct key in registry : 

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox\SecurityDevices]"CPS"=hex(2):43,00,3a,00,5c,00,57,00,69,00,6e,00,64,00,6f,00,77,00,73,00,5c,00,\
  53,00,79,00,73,00,57,00,4f,00,57,00,36,00,34,00,5c,00,63,00,70,00,73,00,33,\
  00,5f,00,70,00,6b,00,63,00,73,00,31,00,31,00,5f,00,77,00,33,00,32,00,2e,00,\
  64,00,6c,00,6c,00,00,00

Unfortunately, the device is not loaded "automatically".
Additionaly, when i try to load it "manually" via menu, its works.

Best regards,
Lulzim KELMENI

**Comment by mkaply** [comment]
Do you have it as a string? I'm not sure why you posted as Hex. Should be:

https://github.com/mozilla/policy-templates/blob/master/README.md#securitydevices

**Comment by zim333** [comment]
Hello Mike,
Yes i have it as a string on registry like this : 

NAME       TYPE                            Value
CPS          reg_expand_sz           C:\Windows\SysWOW64\cps3_pkcs11_w32.dll

I have posted the hex value on my original post because this is how it looks like when you "export" the registry key to a reg file.

Best regards.

**Comment by zim333** [comment]
![registry](https://user-images.githubusercontent.com/1705151/65490328-3fa50a80-dead-11e9-8a00-038e9eeefc7b.png)

**Comment by zim333** [comment]
[cps3_pkcs11_w32.zip](https://github.com/mozilla/policy-templates/files/3646685/cps3_pkcs11_w32.zip)


This is the zipped dll i am trying to load as a security module. It works "manually" but not via GPO

**Comment by mkaply** [comment]
I'm still debugging the "why" but it appears that somehow the new REG_EXPAND_SZ is not working on the ESR (even though the code should be there).

If you need this immediately, my suggestion would be to go back to the previous version of the ADM template - https://github.com/mozilla/policy-templates/releases/tag/v1.8.2

I'm actively investigating this and hope to have a definitive answer soon.

**Comment by mkaply** [comment]
Actually, I see the problem.

You should be using these templates:

https://github.com/mozilla/policy-templates/releases/tag/v1.7

This is the last version that works with Firefox 60.

The current templates aren't supported on 60 because of the change to EXPAND_SZ and MULTI_SZ.

**Comment by zim333** [comment]
Hello Mike,
It works perfectly with version 1.7 of policy. I will stay with this version of policy until we jump to firefox 68.x ESR.
Thank you !
