### ISSUE TITLE
Feature Request: Content Blocking url whitelist

### ISSUE THREAD

**Issue by tkimpton** [mozilla/policy-templates#447]
We have a url we would like to be able to turn off for content blocking. Would it be possible to add something for Mac and Windows. On Mac we would like to be able to include this in our config profile and for Windows in a GPO.

Thanks

**Comment by drlellinger** [comment]
I would use a proxy-server for that matter not a policy. You can also use a DNS server but users tend to use other ways to circumvent those kind of barriers.

**Comment by tkimpton** [comment]
A proxy server isn’t something that would work for us and in this case is overkill on something which should be customizable with confit profile for Mac and gpo for Windows.

**Comment by mkaply** [comment]
this will be in the next version of Firefox (73/68.5) via policy.

https://bugzilla.mozilla.org/show_bug.cgi?id=1498691
