### ISSUE TITLE
JNLP files no longer run by default under Firefox 68.x ESR

### ISSUE THREAD

**Issue by FGAGwendalG** [mozilla/policy-templates#448]
Hello,

We have business applications that use JNLP files, instead of the files being started automatically, it offers to download it only (Firefox 68.x ESR version).

![333CB7DC](https://user-images.githubusercontent.com/37629484/65943749-8d32f180-e430-11e9-9aa6-c30d9461d8d5.PNG)

With the Firefox 60.x ESR version, we had the choice to open the file with Java and to do not ask again. It was a good thing.

![2019-10-01_09h51_58](https://user-images.githubusercontent.com/37629484/65944070-3548ba80-e431-11e9-9c68-4162c4978bce.png)

**Is it possible to have a setting to configure exceptions for websites and/or extension files ?**

We have a complicated workaround (we have to do a configuration manually on each computers), like this:

![BFD2FE2D](https://user-images.githubusercontent.com/37629484/65944475-126ad600-e432-11e9-8af1-c85d835e3c98.PNG)

Even with this parameter, we need to accept a warning message when the first JNLP file is executed, that is not good for users point of view.

![A161D64A](https://user-images.githubusercontent.com/37629484/65944571-4c3bdc80-e432-11e9-8856-9cd127c1d107.PNG)

In the absence of granularity to configure this, we will not be able to update Firefox.

Kind regards,

**Comment by mkaply** [comment]
Which version of the Firefox 68 ESR are you using? The latest ESR should have a change that brings back the old behavioor.

**Comment by FGAGwendalG** [comment]
We use 68.1 ESR

I found the reason for the change that was implemented on version 67 :
- https://bugzilla.mozilla.org/show_bug.cgi?id=1392955

 As well as a request to cancel this change which would be effective in version 68.2: 
- https://bugzilla.mozilla.org/show_bug.cgi?id=1392955
- https://bugzilla.mozilla.org/show_bug.cgi?id=1576762

In addition the source of the information has been found on this thread: 
https://support.mozilla.org/de/questions/1260450

So maybe, it's not necessary to add something in template configuration.

**Comment by mkaply** [comment]
I knew we had fixed this, just didn't remember what ESR.

So yes, this will be fixed in ESR 68.2.

**Comment by mkaply** [comment]
I have it on my list to figure out how to do handlers in policy.

Instead of doing handlers.json, I would recommend using some Javascript in an autoconfig file:

https://mike.kaply.com/2013/05/15/setting-default-application-handlers/

Probably less fragile.

**Comment by p1xelshader** [comment]
Thanks Mike, much appreciated 👍

**Comment by FGAGwendalG** [comment]
ESR 68.2 has fixed the problem.
