### ISSUE TITLE
Bookmarks appear to be created one at a time per launch if the Favicon is specified.

### ISSUE THREAD

**Issue by sarlalian** [mozilla/policy-templates#449]
Firefox 68.1.0esr MacOS

Using a policies.json file at `Firefox.app/Contents/Resources/distribution/policies.json

```json
{
    "policies": {
        "Bookmarks": [
            {
                "Title": "Example.com",
                "URL": "https://www.example.com",
                "Favicon": "https://www.example.com/favicon.ico"
            },
            {
                "Title": "Example Email",
                "URL": "https://mail.example.com",
                "Favicon": "https://mail.example.com/favicon.ico"
            },
            {
                "Title": "Example Wiki",
                "URL": "https://wiki.example.com/intranet/links",
                "Favicon": "https://wiki.example.com/img/favicon.png"
            }
        ]
    }
}
```

The first launch results in a bookmark with the name of *Example.com*, the second launch results in a second bookmark with the name of *Example Email* and finally the third launch results in a third bookmark with the name of *Example Wiki*.  Without the Favicon lines, all three bookmarks are created on the initial launch.

**Comment by mkaply** [comment]
Interesting. It appears to only happen if the favicons aren't actually valid. If I put in a working icon like https://www.google.com/favicon.ico, it works.

Either way, definitely a bug and I know what's going on and I'll have a fix in the next ESR/Firefox release.

**Comment by mkaply** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1586453

I'm going to close this because it's not specifically a policy bug. Thanks for reporting!
