### ISSUE TITLE
Global policies.json

### ISSUE THREAD

**Issue by Maeljd** [mozilla/policy-templates#450]
Hi,

Is it possible to centralize policies configuration like Centralize customizing as described [here](https://support.mozilla.org/en-US/kb/customizing-firefox-using-autoconfig#w_centralized-management) ?

Thanks for your help
Maël

**Comment by mkaply** [comment]
What platform?

**Comment by Maeljd** [comment]
Linux and Windows.

**Comment by mkaply** [comment]
On Windows, you centralize via GPO.

On Linux, I'm working on reading policy from etc.

**Comment by Maeljd** [comment]
Yes, i allready doing that for Windows.
But i want centrelize beetween Linux and Windows.
If i can distribute one json file by http for both it's better ;-)
Thanks a lot for your responses.

Sorry for my English..

**Comment by mkaply** [comment]
> Yes, i allready doing that for Windows.
> But i want centrelize beetween Linux and Windows.
> If i can distribute one json file by http for both it's better ;-)
> Thanks a lot for your responses.

We have no plans to provide a way to centralize policies.json on Windows. With GPO on Windows and Configuration profiles on Mac, it's really only needed on Linux.

> Sorry for my English..

Never apologize for being able to speak more than one language. 😄

**Comment by Maeljd** [comment]
OK :-( 
I was imagining something like that

{
  "policies": {
    "GlobalPoliciesConfig": http://server.tld/myglobalpolicies.json }
}

defined in \distribution\policies.json (windows) and /distribution/policies.json (linux).
And it will be able for all Operating System.

Thanks again.
Have a nice day.

**Comment by anatoli26** [comment]
Just came here to ask the same as @Maeljd. There needs to be a centralized unified way of managing policies for all platforms (you may still leave GPO ability on Windows, but enable policies.json for all platforms).

Anyway, the urgent need is to be able to remotely provide policies.json on Linux the same way AutoConfig's Centralized Management is implemented.

What's the status of this feature? If nobody is working on this, would you accept patches?

**Comment by mkaply** [comment]
I've put together a patch to allow policies.json in /etc/firefox/policies

https://bugzilla.mozilla.org/show_bug.cgi?id=1469629

**Comment by anatoli26** [comment]
@mkaply, is there a possibility to make ff to request the policy config from a remote server (e.g. via https) the same way AutoConfig's Centralized Management is implemented? This would allow a dynamic reconfiguration of each ff instance running on the machine as opposed to a static per-machine global policy. The idea is for the admin to be able to reconfigure each user's ff remotely as with AutoConfig's Centralized Management.

It would suffice the AutoConfig's CM, but it can't (AFAIK) indicate what extensions to install and remove.

Anyway thanks for this improvement!

**Comment by mueller-ma** [comment]
You can use Ansible to roll out a new version of your policy.

**Comment by anatoli26** [comment]
@mueller-ma, sure one can find different 3rd-party solutions to deploy things, but the idea is for FF to have a native solution for policies.json distribution the same way the AutoConfig CM is working. I guess its code could be reused, and everything else is already in place.

**Comment by mkaply** [comment]
As @mueller-ma said, various operating systems already have the ability to do this, we're not going to reinvent it.

**Comment by mkaply** [comment]
Support for doing this in Linux has landed:

https://bugzilla.mozilla.org/show_bug.cgi?id=1469629

It will be in Firefox 78 and possibly earlier.

**Comment by anatoli26** [comment]
How should we differentiate the policies for each user on the same machine? If the policies are placed under `~/.mozilla`, the user can overwrite the file.

And there's no reliable way to place files in a home dir of user X under some other user Y with tools like ansible, the user home dir could be mounted over the network or encrypted, being mounted only when the user is logged in, and even at that moment possibly not even root being able to write there.

I don't see how the linked fix allows to centralize policies configurations for each user as was requested by the OP.

The OP has referenced a CM way of retrieving the policies from a remote http server, specifying the user it requests the policies for (and the CM has a well defined mechanism of determining the failures and what to do when certain things are not available). With the global policies in `/etc` IMO there's just no way to set up per-user policies. Am I missing something?

If there could be a way to put policies in `/etc/firefox/policies/<user>/policies.json` (e.g. if the `PREF_PER_USER_DIR` is true), that would at least partially solve the current issue. For now I don't see how the submitted fix solves it.

**Comment by mkaply** [comment]
You can do per user policy using the support we added for fleet commander:

https://bugzilla.mozilla.org/show_bug.cgi?id=1583466

As far as I can tell, they are using a somewhat standard way to do user policies.

The reality is that Linux just doesn't have a good standard way to do this.

**Comment by anatoli26** [comment]
> You can do per user policy using the support we added for fleet commander

So if I understand it correctly, it's possible to define the `PREF_PER_USER_DIR` via the `perUserDir` prop in the global `/etc/firefox/policies.json` as well as the `XREUserRunTimeDir` prop to actually specify the per-user dir and then FF would load the per-user `policies.json` from there, correct? Because the default value of `/run/user/$UID/appname` doesn't suite well the cases outside the FleetCommander.

**Comment by mueller-ma** [comment]
> Support for doing this in Linux has landed

Just to be sure: The filename is `/etc/firefox/polices.json`, right?

**Comment by mkaply** [comment]
> Just to be sure: The filename is `/etc/firefox/polices.json`, right?

Yes

**Comment by mueller-ma** [comment]
Can it be `/etc/firefox-esr/polices.json` as well, depending on the Firefox distribution?

**Comment by mkaply** [comment]
No, it's just firefox.

**Comment by mrandybu** [comment]
So, does the policy work for a specific user? For example (/run/user/`uid`/.. or /etc/firefox/`user`/..).
I tried to launch firefox in different ways, for the user the policy does not work, only the global policy is applied.

**Comment by mkaply** [comment]
No we don't have user specific policy in the etc directory. There was some support added for Fleet Commander:

https://bugzilla.mozilla.org/show_bug.cgi?id=1583466

Honestly, we copied chrome with in this regard and it has no way to do user specific policy on Chrome. You're not the first person to request this, so we probably need to figure out something.

**Comment by mrandybu** [comment]
I just need this for fleet-commander. Tell me, how does support work? What should be done? Something doesn't work for me.

**Comment by mkaply** [comment]
I'll be perfectly honest, I don't exactly know how it works. It was written by someone from RedHat. I would comment in the bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1583466

and ask how the support works in Fleet Commander.
