### ISSUE TITLE
GPO wish : Extension blacklist

### ISSUE THREAD

**Issue by YoannPERCHET** [mozilla/policy-templates#451]
Hello, 

Maybe ia haven't understand how to procede but i don't fin a solution to blacklist all extersion on firefox.

My need's is by default that blacklist for all extension and whitelist the desired extension

as for Chrome GPO

**Comment by drlellinger** [comment]
I think https://github.com/mozilla/policy-templates/blob/master/README.md#extensionsettings is applicable for you

**Comment by YoannPERCHET** [comment]
I have seen this option but by GPO this option can only be implement by registry directly not with the adm files

it is not veryeasy to keep coherence on the GPO

**Comment by drlellinger** [comment]
There is this Windows policy in current master, i think it came with the v1.9 release

```
<policy name="ExtensionSettings" class="Both" displayName="$(string.ExtensionSettings)"  key="Software\Policies\Mozilla\Firefox" explainText="$(string.ExtensionSettings_Explain)"  presentation="$(presentation.ExtensionSettings)">">
      <parentCategory ref="Extensions"/>
      <supportedOn ref="SUPPORTED_FF69"/>
      <elements>
        <multiText id="ExtensionSettings" valueName="ExtensionSettings"  maxLength="2048"/>
      </elements>
    </policy>
```

**Comment by mkaply** [comment]
Yes, Extension Settings is definitely there. You would do something like this as the value

{
    "ExtensionSettings": {
      "*": {
        "blocked_install_message": "Installs are blocked.",
        "installation_mode": "blocked"
      },
      "uBlock0@raymondhill.net": {
        "installation_mode": "force_installed",
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"
      }
    }
  }
