### ISSUE TITLE
GPO - certificates

### ISSUE THREAD

**Issue by Argayle** [mozilla/policy-templates#455]
Hello everyone.

i install the admx for firefox and i trying few of the possibilities.

One is the certificates.
I have one for my countability program, named : count**.p12.

How can i install it with the install certificate ?

Thank in advance for your replies

**Comment by mkaply** [comment]
Assuming you are on macOS or Windows, the easiest way is to install it in to the operating system and use this policy:

https://github.com/mozilla/policy-templates/blob/master/README.md#certificates--importenterpriseroots

If you want to just install it into Firefox, detailed instructions are here as to where to place it or what paths look like:

https://github.com/mozilla/policy-templates/blob/master/README.md#certificates--install
