### ISSUE TITLE
How to hide navigation toolbar for managed application

### ISSUE THREAD

**Issue by red-erik** [mozilla/policy-templates#457]
Hello,
we need to publish a Firefox session on Citrix environment but we need to hide (disable) navigation bar and let users only use the starting web page.
Is the a policy setting to accomplish this?

Regards,

Red.

**Comment by mkaply** [comment]
We currently do not have a way to do app mode which is what you are asking. We do have a kiosk mode coming soon.

**Comment by mkaply** [comment]
Kiosk mode is now available in Firefox. You can start with --kiosk
