### ISSUE TITLE
Feature request: preferences - widget.content.gtk-theme-override

### ISSUE THREAD

**Issue by apoole7** [mozilla/policy-templates#458]
Could you add the preference: widget.content.gtk-theme-override to the supported preferences able to be configured.
This is currently the last preference managed through our mozilla.cfg

Thanks
Andy

**Comment by mkaply** [comment]
That's not one I'm familiar with. Can you provide a summary of what it does? I'll get it added in the next release.

**Comment by apoole7** [comment]
It is to do with fixing issues around foreground and background form field colours when websites do not specify both & the window manager theme being of a dark variant.
There has been a lot of action around it for many a year (from earlier research looks like has been a prob for 16-17 years), latest bug fix (https://bugzilla.mozilla.org/show_bug.cgi?id=1527048) seems to help but the override preference is the "brute force" solution that solves it for us.

**Comment by mkaply** [comment]
This was added in Firefox 68.4 and 72.
