### ISSUE TITLE
ExtensionSettings not applying?

### ISSUE THREAD

**Issue by Bangaio65** [mozilla/policy-templates#459]
Firefox 69.0.3 (64-bit)

I want to install uBlock Origin and block the rest. I followed the instructions from this post:
https://github.com/mozilla/policy-templates/issues/451#issuecomment-539556394

It does get applied to registry in the target machine and I can see it on rsop.msc
But it isn't doing anything... I can still disable the add-on and install others.
The "Prevent extensions from being disabled or removed" GPO does work.

Bonus question: is there a way to lock uBlock Origin options so the user can't change them?

**Comment by Bangaio65** [comment]
I didn't realize you don't need to put the Extension Settings bit in the JSON.
This works:
```
{
"*": {
"blocked_install_message": "Installs are blocked.",
"installation_mode": "blocked"
},
"uBlock0@raymondhill.net": {
"installation_mode": "force_installed",
"install_url": "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"
}
}
```

I'll close this now, thanks.

**Comment by mkaply** [comment]
You're not the first person that had this problem. I'll update the example.

**Comment by PerMalmberg** [comment]
@mkaply He wasn't the last person to have it either, I just spend the better part of the day before I found this thread. Please update the example, it really leads you down the wrong road.

https://discourse.mozilla.org/t/installation-via-policy/48499

**Comment by mkaply** [comment]
I renamed JSON to policies.json and I made the Windows GPO setting for ExtensionSettings more clear.

https://github.com/mozilla/policy-templates/blob/master/README.md#ExtensionSettings

What do you think?

**Comment by PerMalmberg** [comment]
@mkaply  A change for the better. It might be available in the referenced Chrome-docs, but I feel it all should be spelled out clearly in the docs for Firefox. For example, what's the location and name of the file for macOS? What about Linux, can extensions be force-installed there (our customers are asking for it).

As a side note: Do you know the answer my question re. updates of extensions installed this way? How do you make sure a new XPI-file is used by Firefox when self-distributed? This is information that would be really nice to have on that page to, or at least referenced.

**Comment by mkaply** [comment]
> @mkaply A change for the better. It might be available in the referenced Chrome-docs, but I feel it all should be spelled out clearly in the docs for Firefox. For example, what's the location and name of the file for macOS? 

Which file are you referring to?

> What about Linux, can extensions be force-installed there (our customers are asking for it).

ExtensionSettings can be specified via policies.json. The beginning of the document explains where to put it on Linux.

> As a side note: Do you know the answer my question re. updates of extensions installed this way? How do you make sure a new XPI-file is used by Firefox when self-distributed? This is information that would be really nice to have on that page to, or at least referenced.

Once an extension is installed, it updates like a normal Firefox extension would (connecting to an update server and getting an update) unless you've turned off add-on updates.

**Comment by PerMalmberg** [comment]
Ah, yes. I see the note re. Linux it now, thanks.

What about updates when the extension is self-distributed as an xpi-file? Will simply replacing the file cause an update the next time FF is started?

**Comment by mkaply** [comment]
> What about updates when the extension is self-distributed as an xpi-file? Will simply replacing the file cause an update the next time FF is started?

No it will not. I'll get that fixed.

**Comment by PerMalmberg** [comment]
> No it will not. I'll get that fixed.

That'd be great. Is there an issue I can track to get notified of the progress?

**Comment by mkaply** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1596481

I think I'm going to add a version to the ExtensionSettings JSON and if it doesn't match the installed version, we install it.
