### ISSUE TITLE
Extensions_Uninstall and wildcard support

### ISSUE THREAD

**Issue by sveinungre** [mozilla/policy-templates#466]
Please enable * to automatically uninstall all extensions, and then use specific extension IDs for Extensions_Install. The result removing all extensions except the ones you whitelist. I'm using Intune device configuration profile to manage settings, and I can see its successfully set in registry and also reported in Firefox about:policies, but nothing happens. I guess this could be a limitation in Firefox itself for the moment.

**Comment by mkaply** [comment]
The new ExtensionSettings property will do this for you.

https://github.com/mozilla/policy-templates/blob/master/README.md#extensionsettings

**Comment by sveinungre** [comment]
So you don't think its worth to include wild card support just like Chrome uses? Really?

**Comment by mkaply** [comment]
> So you don't think its worth to include wild card support just like Chrome uses? Really?

The new ExtensionSettings policy is a duplicate of the Chrome policy and does include wildcard support (and is much better than the old extension policies).

I'm not going to be updating the old way of installing/controlling extensions.
