### ISSUE TITLE
ExtensionSettings Intune example?

### ISSUE THREAD

**Issue by sveinungre** [mozilla/policy-templates#472]
I'm able to get this working using GPO (copy paste in GPO Editor using firefox.admx)::
{"*":{"blocked_install_message":"Blocked by YOUR CUSTOMER.","installation_mode": "blocked"},"addon@darkreader.org":{"installation_mode":"force_installed","install_url":"https://addons.mozilla.org/firefox/downloads/latest/darkreader/latest.xpi"}}

But do you have an Intune example?
OMA-URI would be: ./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~Extensions/ExtensionSettings

String something like: 

```
<enabled/> <data id="ExtensionSettings" value="something but I'm struggling with formatting"/>
```

But what is the correct formatting for the string? I get into trouble with the { and } characters.

**Comment by sveinungre** [comment]
I will answer this myself in case someone else finds this information useful. If you want to do the same in Intune device configuration profile as the above GPO example, then this is the correct formatting:

<enabled/> <data id="ExtensionSettings" value='{"*":{"blocked_install_message":"Blocked by YOUR CUSTOMER.","installation_mode": "blocked"},"addon@darkreader.org":{"installation_mode":"force_installed","install_url":"https://addons.mozilla.org/firefox/downloads/latest/darkreader/latest.xpi"}}'/>


Note the single quotation at the beginning and end,

**Comment by AlexanderCGKarlsson** [comment]
@sveinungre Did I miss something where you posted this correct formatting? I can only see this

`<enabled/> <data id="ExtensionSettings" value="something but I'm struggling with formatting"/>`

**Comment by sveinungre** [comment]
Not sure what happend here, let me insert code + screenshot to show how it works.

OMA-URI:
`./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~Extensions/ExtensionSettings`

String value:
`<enabled/> <data id="ExtensionSettings" value='{"*":{"blocked_install_message":"Blocked by MY COMPANY for your safety.","installation_mode": "blocked"},"jid1-ZAdIEUB7XOzOJw@jetpack":{"installation_mode":"force_installed","install_url":"https://addons.mozilla.org/firefox/downloads/latest/duckduckgo-for-firefox/latest.xpi"},"ApplicationGuardRel@microsoft.com":{"installation_mode":"force_installed","install_url":"https://addons.mozilla.org/firefox/downloads/latest/application-guard-extension/latest.xpi"}}'/>`

![extensionsettings](https://user-images.githubusercontent.com/49359654/75041121-394aa700-54bc-11ea-8a54-29b2d192f1cc.PNG)

**Comment by AlexanderCGKarlsson** [comment]
> Not sure what happend here, let me insert code + screenshot to show how it works.
> 
> OMA-URI:
> `./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~Extensions/ExtensionSettings`
> 
> String value:
> `<enabled/> <data id="ExtensionSettings" value='{"*":{"blocked_install_message":"Blocked by MY COMPANY for your safety.","installation_mode": "blocked"},"jid1-ZAdIEUB7XOzOJw@jetpack":{"installation_mode":"force_installed","install_url":"https://addons.mozilla.org/firefox/downloads/latest/duckduckgo-for-firefox/latest.xpi"},"ApplicationGuardRel@microsoft.com":{"installation_mode":"force_installed","install_url":"https://addons.mozilla.org/firefox/downloads/latest/application-guard-extension/latest.xpi"}}'/>`
> 
> ![extensionsettings](https://user-images.githubusercontent.com/49359654/75041121-394aa700-54bc-11ea-8a54-29b2d192f1cc.PNG)

Awesome, thanks mate! I was off with just a quotation mark. Hopefully I get it working.
