### ISSUE TITLE
GPO feature: force open FF in incognito mode

### ISSUE THREAD

**Issue by grawerpl** [mozilla/policy-templates#474]
Hello,

i just found out that no one ever asked about this, but this can bee helpful in some cases.
for now to do this you need add command line argument like "-private" but option for this in GPO will be nice.

other is option to force safe browsing in search engine.

**Comment by drlellinger** [comment]
I have a request for the opposite scenario - never thought of it before - can you have a setting to force open in normal mode. Because some users manipulated their about:config in the past and i want to force them to use the normal mode instead of incongnito.

**Comment by drlellinger** [comment]
And for safe search requirements i would suggest you force the usage of https://addons.mozilla.org/de/firefox/addon/sas/ via the Extension GPO

**Comment by mkaply** [comment]
If you set the DisablePrivateBrowsing policy, users can't open private browsing.

**Comment by drlellinger** [comment]
They still can when they configured Firefox to always open in Private Browsing in the first place.

**Comment by grawerpl** [comment]
I think option for both setting is good idea. So if is not configured/disabled then then ff is working how its configured by user locally. If is enable then you can choice between "always open normal mode" or "always open norma mode" and this will be forced no matter what user set or add to shortcut :)

@mkaply i think @drlellinger have point about this and i think maybe add other thing to policy like "force to default about:config before apply other policy" or something like that or add custom about:config policy when we can add other about:config property wit don't have own policy and i thin together with what i suggest can solve @drlellinger problem with about:config.

@drlellinger adding 3party add-on for safe-serach is a pain. its add other problem like cpnstanly checking if is compatible with newer version of ff or there is no other issue or updates. especially this is problematic if you have disabled add-on or auto-updates

**Comment by teknowledgist** [comment]
I need to be able to force private mode for all browser sessions via GPO.  It doesn't make sense to me that there is an option to prevent private browsing, but no option to force it.  

Thanks.

**Comment by mkaply** [comment]
You could set the preferences browser.privatebrowsing.autostart to true (as a user preference) and I think that would do it.

Honestly, it just hasn't been a big request (and I don't think any other browser has it)

**Comment by teknowledgist** [comment]
![image](https://github.com/mozilla/policy-templates/assets/3977744/b4ac86ca-a912-4ea5-b111-c6f9909aef78)

**Comment by mkaply** [comment]
All righty then. I'll see what I can do. It will probably be Windows only.

**Comment by mkaply** [comment]
This will be fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1675077
