### ISSUE TITLE
GPO Wish : Add a subfolder to bookmarks

### ISSUE THREAD

**Issue by AlexandreGPF** [mozilla/policy-templates#475]
Hello,
I don't know if it's possible at the moment but I guess no, without doing it in json.

I would like to create and deploy bookmarks from a Windows GPO.
It seems like we can create some folder but they are directly attached to Toolbar or Menu.

What would be nice : Have the possibility to create a bookmark folder, with subfolder into it.

Example :

>**Bookmarks menu**
>> **Internet**
>>> **Navigate**
DuckDuckGo
Google
**News**
BBC
CNN

I don't know if it's clear enough...

Cheers,
Alexandre

**Comment by robtherobot85** [comment]
We are also looking for this.  Currently Chrome lets you have "Children" folders in their GPO through JSON format.  I actually like the format that Firefox uses for managed bookmarks however subfolder support is a deal breaker for us.  This is a shame since Firefox is the best browser.

**Comment by mkaply** [comment]
I've been trying to figure out the best way to do this.

Would you prefer Chrome's Managed bookmark style?

**Comment by AlexandreGPF** [comment]
That would be a great thing to work this way. 
It's more "complicated" but way more customizable !

**Comment by robtherobot85** [comment]
I completely agree.

**Comment by AlexandreGPF** [comment]
Any update on this point ?
Thank you !

**Comment by mhaymore** [comment]
@mkaply If you are going to follow Chrome's Managed bookmark style, then I'd also ask you follow their JSON format as well. This means I could generate the JSON file just once, and use it with both GPOs.

**Comment by mkaply** [comment]
Question. If these bookmarks were only available on the personal toolbar in the UI, would that be OK? Or do they have to be real bookmarks available in the bookmarks window and sidebar?

**Comment by moop2000** [comment]
@mkaply Unless I am missing something, by default anything on the Bookmark Toolbar shows up in both the Bookmark menu and in the sidebar already.

**Comment by mkaply** [comment]
> @mkaply Unless I am missing something, by default anything on the Bookmark Toolbar shows up in both the Bookmark menu and in the sidebar already.

There was a suggestion internally that instead of making it real bookmarks, I just make it a menu on the toolbar. Was wondering what folks thought of that.

**Comment by NZScottie** [comment]
I am just wondering if this is still progressing?
This is something that I am also looking for and it would be ideal for the JSON format.
Real bookmarks has my vote.

**Comment by drlellinger** [comment]
I foresee that my company wants to have more policy-given bookmarks in the future and our customers rely on them being "real" bookmarks in the bookmark-menu not just a button in the toolbar

**Comment by mkaply** [comment]
My preliminary version is probably going to be toolbar only. The problem is that Firefox doesn't have a concept of temporary bookmarks, and there's no way to exclude them from Sync and other things.

Although now that I think about it, the current method doesn't exclude them from Sync either.

**Comment by drlellinger** [comment]
I dont think that's a problem at all (excluding those bookmarks from sync) because most envoirments that have policies in place will have sync disabled (like us)

**Comment by NZScottie** [comment]
Excluding the bookmarks from Sync would be nice down the track but not a necessity for us.
As an organisation, if it did become something we would like to control, we would just look at blocking the ability to sync.

**Comment by zbcinfoskrm** [comment]
Whats the update on this? 

Is anyone still working on a solution?

**Comment by mkaply** [comment]
Yes. Starting with Firefox 82/Firefox ESR 78.4, we will have a ManagedBookmarks option that works similar to Chrome. Due to limitations in the product, it will only add a button to the personal toolbar and they will function like real bookmarks (copy, drag drop, etc). They won't be added to the bookmark manager.

**Comment by robtherobot85** [comment]
I was looking at the updated policy for 82 but I didn't see a ManagedBookmarks option.  I just wanted to check on this.  We do appreciate your work on this.

**Comment by mkaply** [comment]
So what happened is that I was able to get it into 82, but not the ESR, so I didn't publish it, but it is there. I'll publish it fully with the next release (I do this when I can coordinate things between ESR and RR).

I'm planning to update the templates this week so you'll be able to take a look.

Are you using GPO, macOS or policies.json? Want to make sure I get the right documentation for you.

**Comment by robtherobot85** [comment]
I am using GPO.  Thanks

**Comment by mkaply** [comment]
Here's a pull request with the GPO changes:

https://github.com/mozilla/policy-templates/pull/702

The format is exactly the same as Chrome.

http://www.chromium.org/administrators/policy-list-3#ManagedBookmarks

You can see one of our example files here:

https://searchfox.org/mozilla-central/source/browser/components/enterprisepolicies/tests/browser/managedbookmarks/managedbookmarks.json

I'm planning to get the complete policy update in the next couple days.

**Comment by stroodle96** [comment]
Will these new bookmark policy's only work on Firefox version 82 and above?

**Comment by mkaply** [comment]
> Will these new bookmark policy's only work on Firefox version 82 and above?

They will also be in the next ESR (78.5)

**Comment by mkaply** [comment]
This is now available in the ManagedBookmarks policy

https://github.com/mozilla/policy-templates/#managedbookmarks
