### ISSUE TITLE
XML Document Configuration 

### ISSUE THREAD

**Issue by FGAGwendalG** [mozilla/policy-templates#477]
Hello,

Is it possible to configure the following two parameters via GPO?

- dom.xmldocument.async.enabled
- dom.xmldocument.load.enabled

By default, the settings are in **true** mode and this prevents a business application from working properly.
By passing the parameters to false, no more problems.

The problem is found on version 68.2 ESR (64 bits).
Surprisingly in version 70, the default setting has changed to **false**.

Kind regards,

**Comment by mkaply** [comment]
That's interesting because the values are non standard and the business application shouldn't be depending on them either way

https://www.fxsitecompat.dev/en-CA/docs/2019/xmldocument-load-and-xmldocument-async-have-been-removed/

The reason they are true on the ESR is because we found apps that were broken by having them false.

I'll add them to the preferences policies for the ESR only.

**Comment by FGAGwendalG** [comment]
Thank you for the information.
To understand, here is the code that is used
```
        function loadXml(url) {
            var xmlDoc, xmlhttp;
            try {
                xmlDoc = new window.ActiveXObject("Microsoft.XMLDOM");
                xmlDoc.async = false;
                xmlDoc.load(url);
            } catch (error) {
                try {
                    xmlDoc = document.implementation.createDocument("", "", null);
                    xmlDoc.async = false;
                    xmlDoc.load(url);
                } catch (errorNested) {
                    try {
                        if (navigator.userAgent.indexOf('Firefox') !== -1) {
                            return xmlDoc;
                        }
                        xmlhttp = new window.XMLHttpRequest();
                        xmlhttp.open("GET", url, false);
                        xmlhttp.send(null);
                        if (xmlhttp.responseXML !== null) {
                            xmlDoc = xmlhttp.responseXML.documentElement;
                        }
                    } catch (errorNestedNested) {
                        window.alert(errorNestedNested.message);
                    }
                }
            }
            return xmlDoc;
        }
```
The dev asked us to comment this part:
```
                        if (navigator.userAgent.indexOf('Firefox') !== -1) {
                            return xmlDoc;
                        }
```

also to disable the above-mentioned settings.

I'll wait for your preferences policies.
Thank you for taking into account our concern.

**Comment by FGAGwendalG** [comment]
ESR 68.2 has fixed the problem.

**Comment by FGAGwendalG** [comment]
Hello,
With the 68.3 version, is it now possible to configure the settings?

**Comment by FGAGwendalG** [comment]
> I'll add them to the preferences policies for the ESR only.

Hello,
Happy new year !
Could you please add a setting for the next template 68.4 ?
Kind regards,

**Comment by mkaply** [comment]
I'm sorry for the delay on this. They will be in 68.5.

https://bugzilla.mozilla.org/show_bug.cgi?id=1608123

**Comment by FGAGwendalG** [comment]
> I'm sorry for the delay on this. They will be in 68.5.
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=1608123

Hey, Thanks for modification, it's working well!
I guess you can close the issue.
Kind regards,
