### ISSUE TITLE
Feature request: Allow setting custom top sites

### ISSUE THREAD

**Issue by philipp-sumo** [mozilla/policy-templates#478]
It would be nice to have a way to configure the out-of-the-box experience of the new tab page and to be able to add/pin custom urls as top sites on the new tab page.
This could be used to highlight some often used pages/resources to the userbase in an enterprise environment, as the default bunch of spots there (youtube, facebook ,wikipedia, reddit, amazon, twitter) aren't exactly optimized for producitvity :-)

**Comment by ocdtrekkie** [comment]
I would also very much like this feature. I may have to set our company page to be the home page, but I'd much rather leave the Firefox new tab page intact, but pin our most used external and internal websites to it.

**Comment by mkaply** [comment]
This is available in the preferences policy

browser.newtabpage.activity-stream.default.sites
