### ISSUE TITLE
Issue: Opening Options - Long Delay

### ISSUE THREAD

**Issue by zeeter82** [mozilla/policy-templates#480]
There is a quite a long delay (at least 60 seconds) when opening options while in Firefox ESR 68.2.0  The entire Firefox window is frozen while waiting for the tab to load.  I have minimal policies configured and when the options tab (about:preferences) finally does load, it does show "Your browser is being managed by your organization."  When I click on that link to show the current GPO's, some policies are aren't listed/applied (example: allow certain popups isn't listed).  I've seen this behavior on 2 separate Win7 devices (with clean profiles).  Any ideas?

**Comment by zeeter82** [comment]
-------------------
BEGIN GPO
-------------------







































































*Computer Configuration (Enabled)PoliciesAdministrative TemplatesPolicy
definitions (ADMX files) retrieved from the central
store.Mozilla/FirefoxPolicy Setting Comment Disable Set Desktop Background
Enabled  Override the first run page Enabled  URL:   Policy Setting Comment
Override the upgrade page Enabled  URL:   Policy Setting Comment Support
Menu Enabled  Title:  Edison URL:  https://edison.carilionclinic.org/
<https://edison.carilionclinic.org/> Access key:
 Mozilla/Firefox/AuthenticationPolicy Setting Comment Allow Non FQDN
Enabled  Always allow NTLM on non FQDNs Enabled Always allow SPNEGO on non
FQDNs Disabled  Policy Setting Comment NTLM Enabled   carilion.com
<http://carilion.com>   Mozilla/Firefox/CertificatesPolicy Setting Comment
Import Enterprise Roots Enabled  Mozilla/Firefox/Home pagePolicy Setting
Comment Start Page Enabled   Homepage  Policy Setting Comment URL for Home
page Enabled  URL:  https://www.insidecarilion.org
<https://www.insidecarilion.org> Don't allow the homepage to be changed.
Enabled  Mozilla/Firefox/PopupsPolicy Setting Comment Allowed Sites Enabled
  http://carilion.com <http://carilion.com> https://carilionclinic.org
<https://carilionclinic.org> https://insidecarilion.org
<https://insidecarilion.org> https://jchs.edu <https://jchs.edu>
https://vtc.vt.edu <https://vtc.vt.edu> https://carilion.csod.com
<https://carilion.csod.com> https://member.virginpulse.com
<https://member.virginpulse.com> https://secure.force.com
<https://secure.force.com> https://office.com <https://office.com>
https://perfectserve.com <https://perfectserve.com>   User Configuration
(Enabled)No settings defined.*

---------------
END GPO
---------------




Those are the settings that I have configured in my GPO.  There are no
errors showing in about:policies.  I figured out why my popup exception
URL's weren't loading.  I wasn't including the http/https prefix (they do
successfully load now).  For some reason there is still a delay when
initially opening the options tab though (almost a minute or more).


Thanks!

**Comment by zeeter82** [comment]
After the delay I'm also able to open/re-open the options tab without issue in the same Firefox session.  As soon as I close out and start a new session, the delay issue starts all over again.

**Comment by mkaply** [comment]
I'm at a loss on this one. I'm using your exact policies and it opens fast for me.

Does it happen if you completely disable policies? (easiest way to do that is to rename HKEY_CURRENT_USER\Software\Policies\Mozilla\Firefox to Firefox2 to temporarily.

**Comment by zeeter82** [comment]
I'm not using any of the user policies so I went to HKLM instead (I didn't have any Firefox policies under HKCU).  I renamed key to Firefox2 and launched Firefox.  It opens a default blank page which is good (not seeing homepage policy).  I tried opening settings and it still took over a minute to open the tab.  So might be something going on with ESR 60.2.0 and maybe not GPO's.

**Comment by zeeter82** [comment]
This behavior still exists in ESR version 68.1.0 and I removed all Mozilla profile folders.  Not sure what is causing this.  I've only been testing on Win7 SP1 Enterprise x64 so far.  I'll work on testing with Win10 next week.

**Comment by mkaply** [comment]
So we can profile this

Can you try installing this:

https://profiler.firefox.com/

And capturing a profile?

**Comment by zeeter82** [comment]
[Firefox 2019-10-31 17.49 profile.json.gz](https://github.com/mozilla/policy-templates/files/3795943/Firefox.2019-10-31.17.49.profile.json.gz)

I believe I did this capture correctly.  I'll let you be the judge.

**Comment by mkaply** [comment]
i've opened a bugzilla bug for this.

https://bugzilla.mozilla.org/show_bug.cgi?id=1593137

We'll followup there.

**Comment by mkaply** [comment]
Can you follow the bug?

Question asked:

If they close Firefox, move their handlers.json file out of their profile (or rename it), and reopen Firefox and the prefs, does the problem go away?

Is the profile or the main windows disk on a network drive?

**Comment by zeeter82** [comment]
Done!
