### ISSUE TITLE
Cannot force Firefox to automatically update

### ISSUE THREAD

**Issue by WesleyBranton** [mozilla/policy-templates#481]
The previous `app.update.auto` preference was removed in Firefox 65, along with a ton of update-related preferences (see [bug 1458308](https://bugzilla.mozilla.org/show_bug.cgi?id=1458308)), so it no longer works to enable or lock automatic updates.

**Comment by jamejuan94** [comment]
The value is still deprecated as of 72.0.2, is there any update or workaround?

**Comment by drlellinger** [comment]
Any update on this?

**Comment by mkaply** [comment]
We're working on this policy right now. Should have something soon.

**Comment by mkaply** [comment]
This was done and I forgot to say something.

https://github.com/mozilla/policy-templates/blob/master/README.md#appautoupdate
