### ISSUE TITLE
User Configuration "Prevent extensions from being disabled or removed" doesn't apply

### ISSUE THREAD

**Issue by Bangaio65** [mozilla/policy-templates#482]
If I set `Prevent extensions from being disabled or removed` in `User Configuration`, it doesn't get applied.
Tested on:
68.2.0esr (64-bit)
70.0 (64-bit)

I can see the registry entry at:
`HKCU\Software\Policies\Mozilla\Firefox\Extensions\Locked | Key: 1 | Value: uBlock0@raymondhill.net`

However when I click on `Options > Your browser is being managed by your organization` it doesn't show up, and I can still disable or remove the extension.

It does work if I set it in `Computer Configuration`.

Is this by design or a bug?

**Comment by mkaply** [comment]
That's odd. It's definitely working for me in user configuration.

Does about:policies have an error tab on the left? Do you see any errors on the Javascript console?

The policy itself isn't different between user and computer in the ADMX and we don't do anything different in code.

**Comment by Bangaio65** [comment]
I think I found the issue:
I had set `Extensions to Install`  in `Computer Configuration`.  When I changed it to `Not Configured`, the `Prevent extensions from being disabled or removed` in `User Configuration` policy was applied correctly, and I couldn't remove or disable the extension as intended.

Basically I wanted to install the extension in all computers, but let some users disable it if they wish. Maybe there's a better way to do this but I'm no expert in Group Policy.

**Comment by mkaply** [comment]
Yeah, when a policy exists in both user and computer, computer overrides.

The best way to do what you're trying is to use the ExtensionSettings policy. It lets you install an extension but not make it mandatory. It can be in either User or Computer.

**Comment by Bangaio65** [comment]
I knew about the override, but I though it was a per-policy thing. 
What I wanted to do was install uBlock in every computer (Computer Configuration) but make it only mandatory to certain users (User Configuration). But it's not that important, so I just set both in Computer Configuration. 

I'll close this issue. Thanks.
