### ISSUE TITLE
Hide Recommended Extensions in Add-ons Manager

### ISSUE THREAD

**Issue by MCHuijgen** [mozilla/policy-templates#483]
I would expect the preference extensions.getAddons.showPane would hide the Recommended Extensions section in Add-ons Manager (FF 70.0 and 70.0.1), but it doesn't. It does lock extensions.getAddons.showPane to false but it doesn't lock extensions.htmlaboutaddons.recommendations.enabled to false.

Can this be adjusted or added as a new preference?

**Comment by mkaply** [comment]
I'll add that pref in the next version

1588183

**Comment by MCHuijgen** [comment]
Thanks!

**Comment by mkaply** [comment]
This is available now in the latest version of Firefox and the Firefox ESR.
