### ISSUE TITLE
Add option to prohibit history deletion

### ISSUE THREAD

**Issue by WesleyBranton** [mozilla/policy-templates#489]
There are some circumstances where it may be desirable to stop a user from being able to remove browsing or download history. I could see this function being popular for some enterprise environments.

**Comment by drlellinger** [comment]
I think This is already possible

**Comment by WesleyBranton** [comment]
Apparently there used to be a way to do it, but I believe some UI updates broke it and it could also be bypassed simply by opening the history sidebar and pressing the delete key.

**Comment by mkaply** [comment]
This is being worked on in bugzilla, so moving there:

https://bugzilla.mozilla.org/show_bug.cgi?id=1466882
