### ISSUE TITLE
Proxy "use system proxy system"

### ISSUE THREAD

**Issue by aurelgodin** [mozilla/policy-templates#492]
Hello,

I am having a proxy configuration problem with Firefox
I explain my case, we deploy a wpad from our DHCP with option 252.
When I configure Firefox to use the proxy system settings, it does not work

Do you have any ideas?

**Comment by mkaply** [comment]
This sounds like a bug you should open in bugzilla since it's not policy specific:

https://bugzilla.mozilla.org/home

**Comment by aurelgodin** [comment]
Thank you I will open a ticket

**Comment by mkaply** [comment]
Did you open a bug for this?
