### ISSUE TITLE
Home page GPO don't work on ESR 68.2.0

### ISSUE THREAD

**Issue by tienou** [mozilla/policy-templates#493]
Home page GPO don't work on ESR 68.2.0

All ESR 68.2.0 have the issue

older version is OK

**Comment by drlellinger** [comment]
Cannot verify.
Homepage GPO works as expected with release and master.
It's important to know that you have to specify a URL like _https://mozilla.org_ or _http://mozilla.org_ as URL and not _mozilla.org_

**Comment by tienou** [comment]
> important to know that you have to specify a URL like https://mozilla.org or http://mozilla.org as URL and not mozilla.org
> 
Yes, I did it, but :

**Work with 3 tabs on  70.0.1 :**
![2019-11-20 15_50_40-mRemoteNG - confCons xml - CHA-SRV-VEEAM](https://user-images.githubusercontent.com/57989387/69249201-cb859b00-0bad-11ea-9079-128d5fa208b5.png)
**Don't work on ESR 68.2.0 :**
![2019-11-20 15_51_16-Livéo OnIP _ Plateforme de connexion](https://user-images.githubusercontent.com/57989387/69249232-d8a28a00-0bad-11ea-8496-1cc5624e8939.png)

Thanks for your answer

**Comment by mkaply** [comment]
Can you post a screenshot of about:policies in both cases?

**Comment by drlellinger** [comment]
I see two different operating systems.
What is machine A and machine B?
Have they both updated their GPOs correctly?
Please have a look in the registry if the policies are set according to the specification under HKLM and HKCU:
`Software\Policies\Mozilla\Firefox\Homepage\URL = "https://example.com"`
`Software\Policies\Mozilla\Firefox\Homepage\Locked = 0x1 | 0x0`
`Software\Policies\Mozilla\Firefox\Homepage\Additional\1 = "https://example.org"`
`Software\Policies\Mozilla\Firefox\Homepage\Additional\2 = "https://example.edu"`
`Software\Policies\Mozilla\Firefox\Homepage\StartPage = "none" | "homepage" |  "previous-session"`

**Comment by tienou** [comment]
Thanks for your answers :)

> I see two different operating systems.

Yes
> What is machine A and machine B?

For the screenshot, 2008r2 (works), W10 (don't works), but i manage 200 computers.
> Have they both updated their GPOs correctly?>

Yes
> Please have a look in the registry if the policies are set according to the specification under HKLM and HKCU>

The machines A and B have the same firefox policies in HKLM and HKCU    O_o O_o Strange>

> Can you post a screenshot of about:policies in both cases?

The problem appear, it's the same GPO :
Works :
![2019-11-21 08_33_58-mRemoteNG - confCons xml - CHA-SRV-DC](https://user-images.githubusercontent.com/57989387/69316991-3f6d8500-0c3a-11ea-80c0-a364e395c233.png)

Don't works :
![2019-11-21 08_33_36-Stratégies d’entreprise](https://user-images.githubusercontent.com/57989387/69316994-41cfdf00-0c3a-11ea-98fd-19411142b883.png)

**Comment by drlellinger** [comment]
Can you link the registry for the second machine?
`HKEY\Software\Policies\Mozilla\Firefox\Homepage`
and
`HKCU\Software\Policies\Mozilla\Firefox\Homepage`

**Comment by tienou** [comment]
Of course :)
This is the registry key of the "don't works machine"

`Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Policies\Mozilla\Firefox\Homepage]
"StartPage"="homepage"
"URL"="https://www.google.fr"
"Locked"=dword:00000000
[HKEY_CURRENT_USER\Software\Policies\Mozilla\Firefox\Homepage\Additional]
"1"="https://centrex.liveo.fr/?standardchat"
"2"="http://wps5.triadys.com/login/"

`Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox\Homepage]
"StartPage"="homepage"
"URL"="www.google.fr"
"Locked"=dword:00000000
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox\Homepage\Additional]
"1"="https://centrex.liveo.fr/?standardchat"
"2"="http://wps5.triadys.com/login/"
`

**Comment by tienou** [comment]
I see a mistake on HKEY\Software\Policies\Mozilla\Firefox\Homepage :
"URL"="www.google.fr" --> "URL"="https://www.google.fr"

**Comment by drlellinger** [comment]
I spotted the error the exact moment you saw it

**Comment by tienou** [comment]
It's better, no error, but don't works again :(
![2019-11-21 15_21_40-Stratégies d’entreprise](https://user-images.githubusercontent.com/57989387/69346223-be7eaf80-0c72-11ea-9ace-bcd8f30d27be.png)

**Comment by tienou** [comment]
... it's ok on a machine test, It's smell victory

**Comment by drlellinger** [comment]
Since the homepage setting is not locked by the policy user has the right to change it. To test the effect you either have to force the setting or reset the firefox profile

**Comment by tienou** [comment]
> 
> 
> Since the homepage setting is not locked by the policy, the user has the right to change it. To test the effect you either have to force the setting or reset the firefox profile

Yes, it's ok on 3 machines.
Thanks a lot drlellinger for your help.
Sorry for the stupidity

**Comment by drlellinger** [comment]
No problem nobody starts as a Policy guru ;)

**Comment by mkaply** [comment]
It's not just you, believe me.

I've put in a fix so that the error will now say:

Ignoring parameter "${param}" - scheme (http or https) must be specified.
