### ISSUE TITLE
Disable Banner: Firefox cannot be updated

### ISSUE THREAD

**Issue by CLiX90** [mozilla/policy-templates#496]
We set the Policy DisableAppUpdate to enabled.
This policy works, but we get a banner in Firefox: Firefox cannot be updated to the newest version...
If I check about:policies, then DisableAppUpdate is true.

How can we disable the banner message?

Firefox ESR 68.2.0
Windows Terminal Server 2012 R2

**Comment by drlellinger** [comment]
From my point of view this policy is not possible as a user policy, only as a computer policy.

I will do a PR for this, if this is true.

**Comment by CLiX90** [comment]
Yes, we set the Policy DisableAppUpdate as a Computer Policy.

**Comment by mkaply** [comment]
This just sound like a bug. Firefox should not be trying to update so you shouldn't get the banner. Can you post a screenshot?

**Comment by CLiX90** [comment]
I have only a version in german language.
![1](https://user-images.githubusercontent.com/39278813/69647301-84921c80-1069-11ea-8199-d418d43c906f.JPG)
![2](https://user-images.githubusercontent.com/39278813/69647303-852ab300-1069-11ea-82eb-4a032fdd6008.JPG)
![3](https://user-images.githubusercontent.com/39278813/69647304-852ab300-1069-11ea-9114-e7696b618c39.JPG)

**Comment by mkaply** [comment]
Would you be willing to debug more?

In particular, set the preference app.update.log to true in about:config and check the javascript console for update specific messaging?

In the mean time, I'll see if I can recreate.

**Comment by mkaply** [comment]
also, you mentioned you are using 68.2. This is the latest version so it shouldn't even be offering an update.

Is that the version that is showing this error? If that is the case, can you tell me the value of app.update.channel in about:config?

**Comment by CLiX90** [comment]
![4](https://user-images.githubusercontent.com/39278813/69659864-63d4c180-107f-11ea-8768-3169513161d9.JPG)
![5](https://user-images.githubusercontent.com/39278813/69659865-646d5800-107f-11ea-8343-bfa6d0e264a5.JPG)

**Comment by mkaply** [comment]
And you're getting this update notification on versions that already have 68.2 installed?

**Comment by CLiX90** [comment]
Yes, I get the notification on Firefox 68.2.
Can you give me a little bit more details what I should do with the javascript console?

**Comment by mkaply** [comment]
After setting app.update.log to true, you can press ctrl+Shift+j to see the browser console. (or upper right menu->web developer->browser console)

You should see messages related to application update.

**Comment by CLiX90** [comment]
![6](https://user-images.githubusercontent.com/39278813/69663412-7c94a580-1086-11ea-8572-83cf5cba9382.JPG)

**Comment by mkaply** [comment]
Can you see if there are any more update messages farther down?

Also a few more questions (trying to recreate exactly)

Are you using GPO or policies.json? and do you have the Firefox maintenance service installed?

**Comment by CLiX90** [comment]
I uploaded more information from the Browser-Console. I get the information after I created a new fresh firefox profile.
I reproduce the update notification as fast as possible, if I go to about:support and refresh the firefox profile. After firefox is started, I wait few minutes until I get the notification.

We use GPO. The firefox maintenace service should not be installed, but I need to ask my colleagues tomorrow. The messages in the Browser-Console sounds like the service is installed.

[Browser-Console.txt](https://github.com/mozilla/policy-templates/files/3893664/Browser-Console.txt)

**Comment by mkaply** [comment]
I've opened

https://bugzilla.mozilla.org/show_bug.cgi?id=1599590

for this since this doesn't seem to be policy related, but appears to be a Firefox bug.

**Comment by CLiX90** [comment]
The maintenance service is not installed.

Thank you!

**Comment by mkaply** [comment]
From the bug:

Could you get the permissions of the updates directory using the following command and add it to this bug? Thanks!

cacls C:\ProgramData\Mozilla /t


Can you cc yourself on the bug?

**Comment by pierre-guillot** [comment]
Hello,
I Have the same problem, but for me, I use the "Custom update URL".
So I have many situations 

- Firefox on my computers are up to date : No popup
- Firefox on my computers are not update to date AND there is a new version of Firefox available on Mozilla's servers : Popup even if I setting up "Custome update URl".
- New update availlable on my custom update server : no pop up (and updates are installed)

All tests are with firefox ESR

**Comment by drlellinger** [comment]
I had several Windows Server 2008 R2 servers in the past few weeks that have the same problem as @pierre-guillot

**Comment by pierre-guillot** [comment]
> 
> 
> I had several Windows Server 2008 R2 servers in the past few weeks that have the same problem as @pierre-guillot

For me : Windows 10 and Windows 7

**Comment by mkaply** [comment]
> Firefox on my computers are not update to date AND there is a new version of Firefox available on Mozilla's servers : Popup even if I setting up "Custome update URl".

So we're checking Mozilla's servers to see if there is an update not your servers? Which popup are you seeing?

**Comment by pierre-guillot** [comment]
> 
> 
> > Firefox on my computers are not update to date AND there is a new version of Firefox available on Mozilla's servers : Popup even if I setting up "Custome update URl".
> 
> So we're checking Mozilla's servers to see if there is an update not your servers? Which popup are you seeing?

I configured "AppUpdateURL" in my gpo with value "http://ffupdate/%VERSION%/%BUILD_TARGET%/update.xml" and when I create good folder with good xml file, it work perfectly and update my firefox with MAR file.

But, if a new version is available on firefox server AND if I don't create folder with update in my own update server, many firefox (not all firefox but a great part) shows the banner "cannot update'.

It's like if firefox check AppUpdateURL then firefox server, but because it's not the internal update serveur, they can't apply update.

**Comment by mkaply** [comment]
Can you post a screenshot of exactly what you are seeing? I'm not able to recreate this.

Also, can you set app.update.log to true in about:config and check the javascript console when you see the error? I see something like this:

AUS:SVC Checker:getUpdateURL - update URL: http://localhost/foo.xml
AUS:SVC UpdateService.canCheckForUpdates - able to check for updates
AUS:SVC Checker: checkForUpdates, force: false
AUS:SVC UpdateService.canCheckForUpdates - able to check for updates
AUS:SVC Checker:getUpdateURL - update URL: http://localhost/foo.xml
AUS:SVC Checker:checkForUpdates - sending request to: http://localhost/foo.xml
AUS:SVC Checker:onError - request.status: 2153398258
AUS:SVC getStatusTextFromCode - transfer error: Update XML file malformed (200), default code: 200
AUS:SVC UpdateService:onError - error during background update. error code: 2153398258, status text: Update XML file malformed (200)

**Comment by pierre-guillot** [comment]
Hi, sorry for the delay.

> can you set app.update.log to true in about:config and check the javascript console

You made my day! I didin't know this tools and it's very useful not only for your request!

So, this morning, I launched firefox and have the error : **https://framapic.org/3lOoZc93Ko8R/IYfDQ7AGH43a.jpg**

Because errors are in my client, I have to access to log and JS console, I go to my GPO editor to enable "access to about:config" dans "access to developing tools".

En then... I have no update message anymore! I tested on three differents PC's and no more banner.

I will check if banner appared again and comment this issue.

Regards.

**Comment by pierre-guillot** [comment]
Hi!

Sorry, I was in holiday during 3 weeks and jusrt return to work yesterday. So, the problem is still occuring, but i'm able to get log error via javascript console.

In Summary, my client is a 68.9 and the new ESR (78.1) is available on firefox servers. So, when my client attents to connect to my internal update server, there is no xml file to update firefox.

Then, I have the message as you can see on this screenshot : https://framapic.org/3lOoZc93Ko8R/IYfDQ7AGH43a.jpg

Now, here is the console log ; 


```
UTM:SVC TimerManager:registerTimer - id: xpi-signature-verification
Policies.jsm: Unable to find certificate - \\\\172.22.1.1\\netlogon\\ch-boscamnant.org.crt Policies.jsm:263
AUS:SVC Creating UpdateService
AUS:SVC Logging current UpdateService status:
AUS:SVC UpdateService.canCheckForUpdates - able to check for updates
AUS:SVC getCanApplyUpdates - testing write access C:\ProgramData\Mozilla\updates\308046B0AF4A39CB\update.test
AUS:SVC isServiceInstalled - returning true
AUS:SVC shouldUseService - returning true
AUS:SVC getCanApplyUpdates - bypass the write checks because the Windows Maintenance Service can be used
AUS:SVC isServiceInstalled - returning true
AUS:SVC shouldUseService - returning true
AUS:SVC getCanStageUpdates - able to stage updates using the service
AUS:SVC Elevation required: false
AUS:SVC Update being handled by other instance: false
AUS:SVC Downloading: false
AUS:SVC End of UpdateService status
AUS:SVC getCanApplyUpdates - testing write access C:\ProgramData\Mozilla\updates\308046B0AF4A39CB\update.test
AUS:SVC isServiceInstalled - returning true
AUS:SVC shouldUseService - returning true
AUS:SVC getCanApplyUpdates - bypass the write checks because the Windows Maintenance Service can be used
AUS:SVC isServiceInstalled - returning true
AUS:SVC shouldUseService - returning true
AUS:SVC getCanStageUpdates - able to stage updates using the service
AUS:SVC getCanUseBits - Not using BITS because of proxy usage
AUS:SVC isServiceInstalled - returning true
UTM:SVC TimerManager:registerTimer - id: browser-cleanup-thumbnails
AUS:SVC Checker:getUpdateURL - update URL: http://ffupdate.ch-boscamnant.org/68.9.0/WINNT_x86_64-msvc-x64/update.xml
AUS:SVC UpdateService.canCheckForUpdates - able to check for updates
AUS:SVC Checker: checkForUpdates, force: false
AUS:SVC Creating UpdateService
AUS:SVC Logging current UpdateService status:
AUS:SVC UpdateService.canCheckForUpdates - able to check for updates
AUS:SVC getCanApplyUpdates - testing write access C:\ProgramData\Mozilla\updates\308046B0AF4A39CB\update.test
AUS:SVC isServiceInstalled - returning true
AUS:SVC shouldUseService - returning true
AUS:SVC getCanApplyUpdates - bypass the write checks because the Windows Maintenance Service can be used
AUS:SVC isServiceInstalled - returning true
AUS:SVC shouldUseService - returning true
AUS:SVC getCanStageUpdates - able to stage updates using the service
AUS:SVC Elevation required: false
AUS:SVC Update being handled by other instance: false
AUS:SVC Downloading: false
AUS:SVC End of UpdateService status
AUS:SVC UpdateService.canCheckForUpdates - able to check for updates
AUS:SVC Checker:getUpdateURL - update URL: http://ffupdate.ch-boscamnant.org/68.9.0/WINNT_x86_64-msvc-x64/update.xml
AUS:SVC Checker:checkForUpdates - sending request to: http://ffupdate.ch-boscamnant.org/68.9.0/WINNT_x86_64-msvc-x64/update.xml
Erreur d’analyse XML : erreur de syntaxe
Emplacement : http://ffupdate.ch-boscamnant.org/68.9.0/WINNT_x86_64-msvc-x64/update.xml
Numéro de ligne 1, Colonne 50 : update.xml:1:50
AUS:SVC Checker:onLoad - request completed downloading document
AUS:SVC Checker:onLoad - Getting sslStatus failed.
AUS:SVC Checker:_updates get - unexpected node name!
AUS:SVC Checker:onLoad - there was a problem checking for updates. Exception: Error: Unexpected node name, expected: updates, got: parsererror
AUS:SVC Checker:onLoad - request.status: 404
AUS:SVC getStatusTextFromCode - transfer error: Fichier XML de mise à jour introuvable (404), code: 404
AUS:SVC UpdateService:onError - error during background update. error code: 1404, status text: Fichier XML de mise à jour introuvable (404)
AUS:SVC UpdateService:onError - notifying observers of error. topic: update-error, status: check-attempts-exceeded
Error: Something tried to use the search service before it's been properly intialized. Please examine the stack trace to figure out what and where to fix it:
_ensureInitialized@resource://gre/modules/SearchService.jsm:658:15
get defaultEngine@resource://gre/modules/SearchService.jsm:2496:10
trimURL@resource://gre/modules/BrowserUtils.jsm:831:38
trimValue@resource:///modules/UrlbarInput.jsm:281:55
_setValue@resource:///modules/UrlbarInput.jsm:874:28
set value@resource:///modules/UrlbarInput.jsm:852:17
URLBarSetURI@chrome://browser/content/browser.js:3345:3
onLocationChange@chrome://browser/content/browser.js:5879:7
callListeners@chrome://browser/content/tabbrowser.js:841:31
_callProgressListeners@chrome://browser/content/tabbrowser.js:855:9
_callProgressListeners@chrome://browser/content/tabbrowser.js:5499:46
onLocationChange@chrome://browser/content/tabbrowser.js:5919:14
_callProgressListeners@resource://gre/modules/RemoteWebProgress.jsm:119:32
onLocationChange@resource://gre/modules/RemoteWebProgress.jsm:161:10
receiveMessage@resource://gre/modules/RemoteWebProgress.jsm:286:14
SearchService.jsm:658:15
Error: Something tried to use the search service before it's been properly intialized. Please examine the stack trace to figure out what and where to fix it:
_ensureInitialized@resource://gre/modules/SearchService.jsm:658:15
get defaultEngine@resource://gre/modules/SearchService.jsm:2496:10
_getUrlMetaData@resource:///modules/UrlbarValueFormatter.jsm:117:35
_formatURL@resource:///modules/UrlbarValueFormatter.jsm:206:28
update@resource:///modules/UrlbarValueFormatter.jsm:68:36
formatValue@resource:///modules/UrlbarInput.jsm:290:27
_setValue@resource:///modules/UrlbarInput.jsm:879:10
set value@resource:///modules/UrlbarInput.jsm:852:17
URLBarSetURI@chrome://browser/content/browser.js:3345:3
onLocationChange@chrome://browser/content/browser.js:5879:7
callListeners@chrome://browser/content/tabbrowser.js:841:31
_callProgressListeners@chrome://browser/content/tabbrowser.js:855:9
_callProgressListeners@chrome://browser/content/tabbrowser.js:5499:46
onLocationChange@chrome://browser/content/tabbrowser.js:5919:14
_callProgressListeners@resource://gre/modules/RemoteWebProgress.jsm:119:32
onLocationChange@resource://gre/modules/RemoteWebProgress.jsm:161:10
receiveMessage@resource://gre/modules/RemoteWebProgress.jsm:286:14
SearchService.jsm:658:15
Error: Something tried to use the search service before it's been properly intialized. Please examine the stack trace to figure out what and where to fix it:
_ensureInitialized@resource://gre/modules/SearchService.jsm:658:15
get defaultEngine@resource://gre/modules/SearchService.jsm:2496:10
_getUrlMetaData@resource:///modules/UrlbarValueFormatter.jsm:117:35
_formatURL@resource:///modules/UrlbarValueFormatter.jsm:206:28
update@resource:///modules/UrlbarValueFormatter.jsm:68:36
formatValue@resource:///modules/UrlbarInput.jsm:290:27
formatValue@chrome://browser/content/browser.js:337:19
onSecurityChange@chrome://browser/content/browser.js:6054:20
callListeners@chrome://browser/content/tabbrowser.js:841:31
_callProgressListeners@chrome://browser/content/tabbrowser.js:855:9
_callProgressListeners@chrome://browser/content/tabbrowser.js:5499:46
onSecurityChange@chrome://browser/content/tabbrowser.js:5959:12
_callProgressListeners@resource://gre/modules/RemoteWebProgress.jsm:119:32
onSecurityChange@resource://gre/modules/RemoteWebProgress.jsm:183:10
receiveMessage@resource://gre/modules/RemoteWebProgress.jsm:303:14
SearchService.jsm:658:15
uncaught exception: 2147746065 SessionStore.jsm:1325:22
Unknown category for SetEventRecordingEnabled: fxmonitor
[Exception... "File error: Not found"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: jar:file:///C:/Program%20Files/Mozilla%20Firefox/browser/features/webcompat@mozilla.org.xpi!/experiment-apis/pictureInPicture.js :: getPolicies :: line 70"  data: no] pictureInPicture.js:70:11
Error: An unexpected error occurred undefined:14:57
Error: Incorrect argument types for pictureInPictureParent.setOverrides. picture_in_picture_overrides.js:15:36
Array.forEach is deprecated; use Array.prototype.forEach instead mootools-core.js:38:175
Array.slice is deprecated; use Array.prototype.slice instead mootools-core.js:58:117
L’évènement « key » n’est pas disponible pour certaines dispositions de clavier : key="i" modifiers="accel,alt,shift" id="key_browserToolbox" browser.xul
```

Regards

**Comment by mkaply** [comment]
Interesting. So it looks the XML your custom update server is sending is bad, so the update fails so we tell you to download it from us.

So in the DisableAppUpdate case, we shouldn't show that message. This is very helpful, thanks.

You could also fix this on your end by making sure you always server valid XML.

**Comment by pierre-guillot** [comment]
> This is very helpful, thanks.

You're welcome.

> So it looks the XML your custom update server is sending is bad

My XML is bad because I didn't creat it untile I want to update my clients. So, after clients are updated with last version I choosen to deploy, they "waiting" by checking if an xml is available for it new version : 

`172.22.10.53 - - [31/Jul/2020:08:46:21 +0200] "GET /68.9.0/WINNT_x86-msvc-x64/update.xml?mig64=1 HTTP/1.1" 404 413`

In my example, my client is on version 68.9.0 and check the XML file to know if a new MAR file is available. If not, nothing happen. The only problem is when mozilla realese a new version on his own server : in this case, the banner "New update avaliable" appear.

Beacause i'm curious, I juste test by create a empty update.xml file and there is no effect, the banner is still presents.

> So in the DisableAppUpdate case, we shouldn't show that message

In my GPO editor, I have the parameter " Désactiver la Mise à jour" in the root of Mozilla folder. Is it this parameter you want I edit? Because I tested it and it not change the problem.

Regards,

**Comment by mkaply** [comment]
Your update server should send an empty updates XML file when there are no updates. It shouldn't just send nothing.

But I'll look into fixing this.

**Comment by mkaply** [comment]
This doesn't belong here since it's a Firefox bug.

https://bugzilla.mozilla.org/show_bug.cgi?id=1656535

But if you are writing an update server, you should send empty <updates> in any case where no update is available.

See:

https://mike.kaply.com/2007/03/26/deploying-firefox-2-within-the-enterprise-part-5/ (needs to be rewritten a bit, but still mostly correct)

**Comment by pierre-guillot** [comment]
> See:
> 
> https://mike.kaply.com/2007/03/26/deploying-firefox-2-within-the-enterprise-part-5/ (needs to be rewritten a bit, but still mostly correct)

Thank you so muche for your article! I configured a rewrite rule with a noupdate.xml file at the root of my site and it seem's to work perfectly.

I think it was the best way to avoid this problem.

Regards.
