### ISSUE TITLE
Previously enabled "Display Menu Bar" shows menu bar  even after it is "Disabled"

### ISSUE THREAD

**Issue by amasresha** [mozilla/policy-templates#5]
Steps to reproduce:
Screen capture- https://testing-1.tinytake.com/sf/MjQxNDg0Nl83MzE4NjA0

1.  Enable "Display Menu Bar" 
2.  Restart (open) the browser
3.  Disable "Display Menu Bar" 
4. Restart the browser
5. Check if the menu bar is hidden (default)

Actual Result:
Menu bar still shows after "Display Menu Bar" is set to "Disabled"

Expected Result:
The menu bar should be hidden after "Display Menu Bar" is set to "Disabled"

**Comment by mkaply** [comment]
I think I'm going to just document this better. The Enable Menu bar policy is only going to be able to show the menu bar the first time a user starts the browser. And it won't do anything when it is disabled.

**Comment by amasresha** [comment]
Great. We can close this issue.
