### ISSUE TITLE
Feature request: Set maximum cache size

### ISSUE THREAD

**Issue by drlellinger** [mozilla/policy-templates#503]
I wish for a setting to set the maximum cache size in Megabytes or Kilobytes.

**Comment by mueller-ma** [comment]
It's possible to limit the cache size via `about:config`, but that has to be done on every computer: https://ccm.net/faq/40819-firefox-36-how-to-set-the-maximum-cache-size
I hope we'll see this feature soon.

**Comment by mkaply** [comment]
This is settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences

You might need to set it at a user preference.
