### ISSUE TITLE
allowed_types example missing in README.md

### ISSUE THREAD

**Issue by orbitalchicken** [mozilla/policy-templates#505]
I do not understand how to use `allowed_types` in **policies.json**.
Can someone add an example to README.md ? (If not possible, just reply me with an example)

**Comment by mkaply** [comment]
I've added an example.

**Comment by orbitalchicken** [comment]
Thanks!

**Comment by orbitalchicken** [comment]
I tried **allowed_types**, it's not working:
```
"ExtensionSettings": {
			"*": {
				"installation_mode": "blocked",
                "install_sources": ["https://addons.mozilla.org/"],
                "allowed_types": ["theme", "langpack"]
			}, (... after that, my allowed extensions...)
```
What's wrong I my configuration ? 
If I understand, this should allow  theme and langpack... but it's not. I restarted the browser and my added themes and langpack are disabled and cannot be enabled. 
Is it supposed to work or it's a new feature that nobody tested ?

**Comment by mkaply** [comment]
Because installation_mode is blocked, it blocks all installations. If you remove that, it should work fine.

theme and langpack are allowed and then the extensions you specify are allowed.

**Comment by orbitalchicken** [comment]
@mkaply Thank you, now it works. But is look like the example in README.md is misleading. Because it has **blocked** and **allowed_types** at the same time. If I understand, they are **mutually exclusive** ?
The example in README.md:
```
  "*": {
    "blocked_install_message": "Custom error message.",
    "install_sources": ["https://addons.mozilla.org/"],
    "installation_mode": "blocked",
    "allowed_types": ["extension"]
  },
```

**Comment by mkaply** [comment]
Unfortunately there's no good way to explain this in the sample. I'll see what I can do.
