### ISSUE TITLE
RSOP Error: minRequiredRevision

### ISSUE THREAD

**Issue by AdamC1228** [mozilla/policy-templates#506]
Running an RSOP with the latest policy definitions causes an error stating the the resource file firefox.adml does not meet the minimum required revision defined in firefox.admx.

Firefox.adml revision is 1.11
Firefox.admx minRequiredRevision is 1.10

Changing the Firefox.admx minRequiredRevision to 1.11 corrects the issue.

**Comment by mkaply** [comment]
I'll never understand why Microsoft called it "minRequiredVersion" when that's not what it is :)

This is fixed.
