### ISSUE TITLE
Feature Request: configure exceptions for tracking protection per GPO

### ISSUE THREAD

**Issue by maettle** [mozilla/policy-templates#507]
I need to disable tracking protection for https://teams.microsoft.com as it interferes with the website (e.g. if you open up a Onenote tab in Teams).
I can't do this via GPOs.

**Comment by CLiX90** [comment]
Try to add these URL's to the GPO Firefox > Cookies > Allowed Sites:

- https://login.microsoftonline.com/  
- https://live.com/

**Comment by mkaply** [comment]
I'm doing this in bug 1498691

https://bugzilla.mozilla.org/show_bug.cgi?id=1498691

**Comment by maettle** [comment]
> 
> 
> Try to add these URL's to the GPO Firefox > Cookies > Allowed Sites:
> 
>     * https://login.microsoftonline.com/
> 
>     * https://live.com/

Hi CLiX90, thanks for the replay. Sadly that doesn't work (and it is a different setting too).

**Comment by maettle** [comment]
> 
> 
> I'm doing this in bug 1498691
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=1498691

Thanks Mike!
Another point of view would be to consider it a bug with the Teams website, if that's feasible to add this exception globally? But then again it IS used to track the user...

**Comment by mkaply** [comment]
This has landed and will be in the next version of Firefox and  ESR (73, 68.5)
