### ISSUE TITLE
Feature request: Disable Whats new/Features/AddOns

### ISSUE THREAD

**Issue by reetp** [mozilla/policy-templates#508]
I can't see any policy settings to disable any of these:

browser.messaging-system.whatsNewPanel.enabled
browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features
browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons

Is it that you can't set a policy or you just don't have them documented yet?

**Comment by mkaply** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1608240

**Comment by mkaply** [comment]
This has landed. Will be in the next Firefox update.
