### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by lechardonneret** [mozilla/policy-templates#510]
I have windows 10 computers connected in local network, I want to block access to the file explorer "file: /// c: /" only the old adm files are accepted, the new firefox admx are not recognized by the system localy, I need your help to block this access my firefox version is 71 thanks to you.

**Comment by mkaply** [comment]
We do not have a way to do that at this time. It is being worked on.
We have no plans to support ADM.

**Comment by altonius** [comment]
the file://c:/ is similar to #111

**Comment by htcfreek** [comment]
If I understand you correctly, you want to use the admx/adml files on local gpedit/system.

To do this please copy them to `c:\windows\policydefinitions`.

**Comment by drlellinger** [comment]
If you use Firefox 68 or newer you should not be dependent on ADM files at all because it only runs on Windows 7 or newer which do support ADMX so it makes absolute sense not to have ADM files anymore

**Comment by mkaply** [comment]
We now have blocking of local files via WebsiteFilter

https://github.com/mozilla/policy-templates/#websitefilter
