### ISSUE TITLE
Start Page policy issue

### ISSUE THREAD

**Issue by CLiX90** [mozilla/policy-templates#511]
We use the policy "Start Page" to set the default start page to blank page (none).

Now if you change the start page in Firefox to "Custom URLs..." and add a URL, then this configuration will not be saved.
Instead if you select "Firefox Home (Default)" first and then "Custom URLs...", then it will be saved.

68.3.0esr 64-bit

**Comment by mkaply** [comment]
I am able to recreate this. Can you do me a favor and open a bugzilla bug for this?

https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Enterprise+Policies

My guess is it's related to this:

https://bugzilla.mozilla.org/show_bug.cgi?id=1579418

I'm debugging it.

**Comment by CLiX90** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1611598

**Comment by mkaply** [comment]
This is fixed with my patch here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1635825

I'll try to get it uplifted, but it will definitely be in Firefox 78.
