### ISSUE TITLE
Bookmarks with subfolders

### ISSUE THREAD

**Issue by Andy-Solo** [mozilla/policy-templates#513]
I am using Group Policy templates on Windows. I need Firefox to have bookmarks with subfolders through group policies.

**Comment by Andy-Solo** [comment]
Favorites in Internet Explorer:

You can create a new subfolder for the Favorites by using a backslash e.g. “Corp Shotrcuts\Thom’s HeadSpace”

**Comment by AlexandreGPF** [comment]
I'm also still searching for that feature to be integrated into a Firefox GPO.
TY !

**Comment by Andy-Solo** [comment]
Bookmarks with folders are very necessary!

**Comment by mkaply** [comment]
Question. If these bookmarks were only available on the personal toolbar in the UI, would that be OK? Or do they have to be real bookmarks available in the bookmarks window and sidebar?

**Comment by Andy-Solo** [comment]
It is possible just on the personal toolbar in the user interface.

**Comment by mkaply** [comment]
The ManagedBookmarks policy is now available which gives nested folders via a button on the toolbar.

https://github.com/mozilla/policy-templates/#managedbookmarks
