### ISSUE TITLE
https://github.com/mozilla/policy-templates/blob/3c0d7fcf4ce4aaa7be5f5a3d66fa7c3e2b8487ad/_config.yml#L1

### ISSUE THREAD

**Issue by amir96284** [mozilla/policy-templates#515]
https://github.com/mozilla/policy-templates/blob/3c0d7fcf4ce4aaa7be5f5a3d66fa7c3e2b8487ad/_config.yml#L1

**Comment by amir96284** [comment]
# #``

**Comment by mkaply** [comment]
What exactly are you asking here?
