### ISSUE TITLE
DisplayMenuBar return an error

### ISSUE THREAD

**Issue by WesleyBranton** [mozilla/policy-templates#516]
The `DisplayMenuBar` policy displays the `Invalid parameters specified for DisplayMenuBar` error message when set using Windows Group Policy. It appears to work fine when set with the `policies.json` file.

**Comment by mkaply** [comment]
Argh. I made DisplayMenuBar better in the new version of Firefox but didn't uplift to ESR, so I didn't publish the new GPO.

But I thought I made it so the old one would still work...

**Comment by mkaply** [comment]
Are you on ESR? I know what the problem is. Bug in the schema processor.

**Comment by WesleyBranton** [comment]
Sorry, @mkaply! I thought I had linked this already, but I guess I forgot. Reported this on behalf of someone on the support forums. They are apparently on 72.0.1 and I've also tested the issue on 72.0.1.

Link: https://support.mozilla.org/en-US/questions/1277399

**Comment by mkaply** [comment]
I've opened a bug and put in a fix.

https://bugzilla.mozilla.org/show_bug.cgi?id=1610623
