### ISSUE TITLE
Enterprise Cert Settings

### ISSUE THREAD

**Issue by Petrucci914** [mozilla/policy-templates#518]
Hello,

I'm attempting to get Firefox to read the Windows Certificate Store and I've applied what I believe to be the appropriate Group Policy settings but when I open up Certificates within Options I am not see them being reflected appropriately.

Import Enterprise Roots | Enabled
security.osclientcerts.autoload | Enabled

Am I missing anything?  I'm using Firefox ESR 71.0.1 MSI along with the latest ADMX Templates.

**Comment by mkaply** [comment]
The OS certificates are used, but they won't show in Firefox Options since they are not explicitly imported.

Are you finding things that don't work?

**Comment by Petrucci914** [comment]
Not necessarily but it's good to know that it won't explicitly show there.  Is there another spot to verify it is doing this correctly?  We are moving to a different Web Filter in a few months that relies completely on Certificates so I was just verifying that these settings accomplished what they explained.

**Comment by mkaply** [comment]
@mozkeeler can you offer any advice here on how to verify things are working? Maybe via logging?

**Comment by mozkeeler** [comment]
One way would be to connect to a server with a certificate issued by the certificates you're expecting to import. You could also run Firefox in a console with the environment variable `MOZ_LOG` set to `pipnss:4` - there might be something helpful there.

A more direct way would be to query the implementation directly in the browser console:
* set `devtools.chrome.enabled` to `true` in `about:config`
* open the browser console (ctrl + shift +j)
* run `Cc["@mozilla.org/psm;1"].getService(Ci.nsINSSComponent).getEnterpriseRoots()` and `Cc["@mozilla.org/psm;1"].getService(Ci.nsINSSComponent).getEnterpriseIntermediates()`
Those commands will return arrays of arrays of bytes representing the encoded certificates the implementation imported.

Also, `security.osclientcerts.autoload`only affects *client* certificates, not certificate authorities (i.e. what certificates the browser trusts to issue server certificates)

**Comment by mkaply** [comment]
Were you able to follow the advice above?
