### ISSUE TITLE
Bookmarks are not updated

### ISSUE THREAD

**Issue by Andy-Solo** [mozilla/policy-templates#522]
If you change bookmarks through Group Policy templates on Windows, the bookmarks are not updated.

**Comment by aptvaibhav** [comment]
Can u please share the related code?

**Comment by temx** [comment]
I don't think the Bookmarks policy works anymore even when using policies.json. I had a single bookmark with with just "Title" and "URL", which used to work just fine, and has stopped working recently (maybe in the last month). The rest of the policies (in the same file) are applied correctly.

**Comment by Andy-Solo** [comment]
To change bookmarks to new ones, you need to delete a group of bookmarks in the browser. Then the next time you start the browser, the bookmarks will be updated.

**Comment by Andy-Solo** [comment]
Do auto-update bookmarks.

**Comment by KDGundermann** [comment]
> I don't think the Bookmarks policy works anymore ..
Is this a bug ? 
I have upgraded from policy_templates v2.12 to v3.0 and I can't create any bookmark with the GPO (btw when I create bookmarks in computer settings AND User settings will they both be applied?)
Or is the old setting deprecated/not working with FF90+ and we should use the new "Managed Bookmarks" ?

**Comment by mkaply** [comment]
Nothing changed with regards to bookmarks (and our internal tests are passing), but I do strongly recommend using ManagedBookmarks. It's a much better designed policy.

I'll do some local testing.

**Comment by mkaply** [comment]
I was not able to recreate this. Do you still see it?

**Comment by Andy-Solo** [comment]
> I was not able to recreate this.

This referred to the old version of the policies. I've been using new policies for a long time.
