### ISSUE TITLE
Default search engine GPO

### ISSUE THREAD

**Issue by manoletto** [mozilla/policy-templates#523]
Hello from France ;-)

We use the Policy templates for Firefox 71 and Firefox ESR 68.3 v1.11
and try to set the default search engine by GPO for Firefox ESR 68.3.0.

After gpupdate, the value i set in the client registry key :
HKCU\Software\Policies\Mozilla\Firefox\SearchEngines

But the browser don't use the search engine we set.

How, by GPO, can we set the default search engine ?

Thk ;-)

**Comment by drlellinger** [comment]
Default search engines only work on Firefox ESR. Please have a look in the internal page about:policies and check for errors and applied policies.
If there are errors, please send the set values.

**Comment by mkaply** [comment]
And also, the correct GPO is:

HKCU\Software\Policies\Mozilla\Firefox\SearchEngines

Default with a REG_SZ value that is the name of the engine.

![image](https://user-images.githubusercontent.com/345868/73687045-d1f4c080-468e-11ea-8328-33bab00d00b6.png)

**Comment by manoletto** [comment]
Yes, that is what we've got in the client registry for the "default search engine", we use :
Edu Qwant Junior

We've set the GPO "first search engine" with :
Name : "Edu Qwant Junior"
URL Template : "https://api.qwantjunior.com/api/suggest/?q={searchTerms}&client=opensearch"
Method : POST
Icon URL : "https://qwantjunior.com/favicon.ico"
Suggest URL Template : "https://qwantjunior.com/?q={searchTerms}&t=all"

And ESR do not trigger search when we submit input in the URL input, search input in the new tab page or in search input in the toolbar.

**Comment by mkaply** [comment]
You should be using GET not POST

**Comment by manoletto** [comment]
We've tried with the GET method and after gpupdate the about:policies show it.
However ESR 68.3.0 don't trigger the search ...
May be, we have to remove profiles, but we've got too much to do it manually !

**Comment by manoletto** [comment]
Ok, it was another old GPO that set some policies registry keys that cause some errors in about:policies ! After deleted, ESR search engine work fine ;-)
Thk
