### ISSUE TITLE
README.md DisableAppUpdate Preferences Affected

### ISSUE THREAD

**Issue by robcmo** [mozilla/policy-templates#525]
On the README.md document under DisableAppUpdate it shows "Preferences Affected: N/A".  This should be "app.update.enabled", right?

**Comment by robcmo** [comment]
Unclear, but it seems 'app.update.enabled' may have been changed to 'app.update.auto'.
https://bugzilla.mozilla.org/show_bug.cgi?id=1420514

**Comment by mkaply** [comment]
app.update.enabled was completely removed a while ago. And app.update.auto is a different pref (that's been removed on Windows as well)

**Comment by robcmo** [comment]
Both preferences are deprecated, updates can now only be disabled by policy.
https://support.mozilla.org/en-US/kb/managing-firefox-updates
