### ISSUE TITLE
Ability to configure external protocol handlers

### ISSUE THREAD

**Issue by tresf** [mozilla/policy-templates#532]
This may be better suited as a bug report (**Edit:** found an 8-year old bug report matching  [`Bug #718422`](https://bugzilla.mozilla.org/show_bug.cgi?id=718422)) but currently Firefox will honor external protocol handlers on Windows, but not on MacOS.

Previously through AutoConfig, I was able to register this buy doing the following:

<details>

<summary>Expand AutoConfig code</summary>

```js
// Register the specified protocol to open with the specified application
function registerProtocol() {
    var myProtocol = "foobar"; // without colon
    var myTitle = "My Foo Bar";
    // Only register if platform needs it (e.g. macOS)
    var trayApp = "${trayApp}";
    if (!trayApp) { return; }
    try {
        var hservice = Components.classes["@mozilla.org/uriloader/handler-service;1"].getService(Components.interfaces.nsIHandlerService);
        var pservice = Components.classes["@mozilla.org/uriloader/external-protocol-service;1"].getService(Components.interfaces.nsIExternalProtocolService);

        var file = Components.classes["@mozilla.org/file/local;1"].createInstance(Components.interfaces.nsIFile);
        file.initWithPath(trayApp);

        var lhandler = Components.classes["@mozilla.org/uriloader/local-handler-app;1"].createInstance(Components.interfaces.nsILocalHandlerApp);
        lhandler.executable = file;
        lhandler.name = "myTitle";

        var protocol = pservice.getProtocolHandlerInfo(myProtocol);
        protocol.preferredApplicationHandler = lhandler;
        protocol.preferredAction = 2; // useHelperApp
        protocol.alwaysAskBeforeHandling = false;
        hservice.store(protocol);
    } catch(ignore) {}
}
```
</details>

However, switching to policy templates, I cannot find an equivalent.  I tried following the old preferences guides, but I can't seem to get them working.
* The [new JavaScript policy handling](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/protocol_handlers) seems to be focused around websites, not apps.
* The old technique of [registering values with `about:config` isn't working](http://kb.mozillazine.org/Network.protocol-handler.external.%28protocol%29).  Am I missing something?

It would be great to allow a way to get these URLs to work. Browsing other known-apps, I found the following:
* Roblox uses `roblox-player:/` but to work with Firefox it installs a plugin for launching its own App on MacOS.
* Skype uses `skype:/` and it works out of the box (I'm not yet sure how, I can't find it in `about:config`

**Edit:** I forgot to mention, the protocol handler is registered with the OS using `Info.plist` file and it's working fine with Safari and Chrome.

**Comment by mkaply** [comment]
You should be able to use the old autoconfig method for now and it should work. That macOS bug has been around forever. I have no idea why it hasn't been fixed.

**Comment by tresf** [comment]
> You should be able to use the old autoconfig method for now and it should work.

Thanks.  With the removal of certificate support from AutoConfig, we've taken the liberty to remove all complexities introduced with AutoConfig, as the policy system is much easier to manage and maintain.

Is it a reasonable expectation to eventually control these things with a policy?  Furthemore, how does skype do it?

**Comment by mkaply** [comment]
So you're setting the data in the CFBundleURLTypes? CFBundleTypeRole/CFBundleURLSchemes?

From what I can tell, these are the only things that Skype does (it sets them in the Info.plist)

**Comment by tresf** [comment]
> So you're setting the data in the CFBundleURLTypes? CFBundleTypeRole/CFBundleURLSchemes?
>  From what I can tell, these are the only things that Skype does (it sets them in the Info.plist)

Yes, that's all we're doing too, yet our links don't work. 
Is there a chance Skype is getting special treatment (e.g. whitelisted somewhere?) 

Here's our `Info.plist` file: 

<details>
<summary>QZ Tray Info.plist</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
    <key>CFBundleDevelopmentRegion</key><string>English</string>
    <key>CFBundleIconFile</key><string>${project.filename}</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleGetInfoString</key><string>${project.name} ${build.version}</string>
    <key>CFBundleSignature</key><string>${project.name}</string>
    <key>CFBundleExecutable</key><string>${project.name}</string>
    <key>CFBundleVersion</key><string>${build.version}</string>
    <key>CFBundleShortVersionString</key><string>${build.version}</string>
    <key>CFBundleName</key><string>${project.name}</string>
    <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
    <key>CFBundleURLTypes</key>
        <array>
            <dict>
                <key>CFBundleURLName</key>
                <string>qz-tray</string>
                <key>CFBundleURLSchemes</key>
                <array><string>qz</string></array>
            </dict>
        </array>
</dict></plist>
```
</details>

And for comparison, here's Skype's

<details>
<summary>Skype's Info.plist</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>18G103</string>
	<key>CFBundleDisplayName</key>
	<string>Skype</string>
	<key>CFBundleExecutable</key>
	<string>Skype</string>
	<key>CFBundleIconFile</key>
	<string>Skype.icns</string>
	<key>CFBundleIdentifier</key>
	<string>com.skype.skype</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Skype</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>8.55</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Viewer</string>
			<key>CFBundleURLName</key>
			<string>SKCalltoURL</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>skype</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>8.55.0.141</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTSDKBuild</key>
	<string>10.13</string>
	<key>DTSDKName</key>
	<string>macosx10.13</string>
	<key>DTXcode</key>
	<string>0941</string>
	<key>DTXcodeBuild</key>
	<string>9F2000</string>
	<key>LSApplicationCategoryType</key>
	<string>public.app-category.social-networking</string>
	<key>LSMinimumSystemVersion</key>
	<string>10.10</string>
	<key>NSCameraUsageDescription</key>
	<string>Skype needs access to the camera for your video calls</string>
	<key>NSHighResolutionCapable</key>
	<true/>
	<key>NSMainNibFile</key>
	<string>MainMenu</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Skype needs access to the microphone for your calls</string>
	<key>NSPrincipalClass</key>
	<string>AtomApplication</string>
	<key>NSRequiresAquaSystemAppearance</key>
	<false/>
	<key>NSSupportsAutomaticGraphicsSwitching</key>
	<true/>
</dict>
</plist>
```
</details>

**Comment by tresf** [comment]
... I forgot to mention, the above configuration works just fine in Safari, Chrome, Opera and Edge(ium).

**Comment by mkaply** [comment]
I looked through the code and I don't see any place skype is getting special treatment. I'm still investigating,

**Comment by tresf** [comment]
I looked through the differences and one that stood out to me was `CFBundleIdentifier`, which according to Apple says the following:

> [...] Launch Services uses the bundle ID to locate an app capable of opening a particular file, using the first app it finds with the given identifier.

Adding this to our `Info.plist` seems to have corrected the problem.  Why this doesn't behave the same in other browsers is peculiar, but I believe the issue to specific to my own project and not actually a bug with Firefox.

I've added this property via https://github.com/qzind/tray/pull/590/commits/6c58c19e939435e01036d8224791e719d6791fe6 and it appears to have fixed the issue.  I'll do some more testing to confirm.

<img src="https://user-images.githubusercontent.com/6345473/75185111-870d1c80-5713-11ea-9444-6e2cd6a0c38a.png" width="300px"/>

I still think the original issue is a valid request, right?  It's not much of an inconvenience to click "Remember my choice" although I can still see the original request being useful for enterprise deployments.

**Comment by mkaply** [comment]
FYI, I'm adding handlers support. Should be in for FF78.

https://bugzilla.mozilla.org/show_bug.cgi?id=1577344

I'm going to close this since it's being tracked in bugzilla.

**Comment by tresf** [comment]
@mkaply thanks for the update.  If you happen to remember, could you post a link to the documentation once it hits this repo?

**Comment by mkaply** [comment]
Yes, I will try to remember.

**Comment by mkaply** [comment]
The new handler documentation is here:

https://github.com/mozilla/policy-templates/blob/master/README.md#handlers
