### ISSUE TITLE
GPO Wish: extensions.webextensions.ExtensionStorageIDB.enabled

### ISSUE THREAD

**Issue by jackzone** [mozilla/policy-templates#534]
Hi everybody,

back in 2018 a new backend for storage.local api was introduced (https://blog.mozilla.org/addons/2018/08/03/new-backend-for-storage-local-api/).

As we have to control some extensions globally via storage.js in our enterprise environment it would be really cool to see the "extensions.webextensions.ExtensionStorageIDB.enabled" policy being implemented into the templates. At the moment this is the only policy we still have to set using the config file in the root directory.

Greetings jackzone

**Comment by mkaply** [comment]
So you're saying you still use the old API because you want to modify the storage files?

**Comment by jackzone** [comment]
That's right. As for example, we use a screenshot extension (installed via GPO) and distribute a modified storage.js during logon so that each user gets the same presettings (due to corporate identity).

**Comment by mkaply** [comment]
This should be settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences

**Comment by jackzone** [comment]
Thanks a lot, it works great!
