### ISSUE TITLE
GPO Wish: Ability to maintain multiple policy sets

### ISSUE THREAD

**Issue by kitcho1** [mozilla/policy-templates#535]
I have the need to deliver a unique configuration for a webapp that we are running on the latest Firefox ESR. The crux of the issue is that any policies delivered via the default firefox policy causes  policies.json to be completely ignored.

I like this behaviour in almost all cases as it prevents users from potentially overriding our enterprise policies. However, the ability to exclude (by specifying a directory?) a specific install from our firefox policies or some other type of policy override would be extremely useful. The only way I currently see to set different policies for multiple firefox installs would be to stop using FF GPs entirely and rely on delivering configs via policies.json/mozilla.cfg.

Having policies.json merge instead of being ignored would be an improvement, but wouldn't quite give me the level of customization I'm looking for.

**Comment by mkaply** [comment]
I can give you a custom autoconfig file that causes policy to be ignored for a specific firefox install. You can email me at mozilla@kaply.com for that (I'm not going to post it here).
