### ISSUE TITLE
policies.json doesnt change anything at proxy settings

### ISSUE THREAD

**Issue by batchenr** [mozilla/policy-templates#537]
Hey, Im using firefox 73.0 64bit Mozila firefox for ubuntu 18
canonical 1.0

I have created the file policies.json under /usr/lib/firefox/distribution/, Im tring to set the proxy 
as i would set in in the browser GUI , i only set the "Automatic proxy configuration URL"

my policies.json : 
```
{
"policies": {
   "BlockAboutConfig": true,
   "Proxy": {
           "Mode": "autoConfig",
           "AutoConfiguURL": "http:/myproxt.com:8080/proxy.pac"
      }
 
}
}
```

I did manage to prove this file works as i set the "BlockAboutPage": true" which does blocking me from reaching "about:config"
Proxy settings doesnt apply.

What am i doing wrong ?

**Comment by batchenr** [comment]
Solved after runing "reset\refresh" from truble shoot button . thanks

**Comment by mkaply** [comment]
Also, misspelled autoconfigURL

AutoConfigURL
