### ISSUE TITLE
Management key for `browser.ctrlTab.recentlyUsedOrder`

### ISSUE THREAD

**Issue by ygini** [mozilla/policy-templates#538]
Hello,

Could you add support to manage `browser.ctrlTab.recentlyUsedOrder` settings?

Eventually, the best futur proof improvement would be to have a fully dynamic management framework that can handle all `browser.ctrlTab.recentlyUsedOrder` kind of payload.

**Comment by mkaply** [comment]
Do you want the old behavior for your internal users?

**Comment by ygini** [comment]
@mkaply exactly. I don’t know what led you to that behavior but it’s clearly misleading and kill our productivity. 

I know some people use tab instead of history and signets, but we have a specific work process here with multiple Firefox profile, one per customer, and different tab per service we need to access for the customer, few enough to see the tab name. 

Regular (old) behavior allow us to be performant: we know where we are in the tab list, can quickly see how many jump we have to do and in witch direction. Easy and fast. 

The new behavior has no visual indicator or where we will arrive after each jump, and if we miss the target by one jump, we have to re-do the whole ctrl tab hits with a different number because history has changed. 

This feature is clearly not appropriate for our workflow. We just can’t handle it. And Firefox is important for us. We couldn’t have the same service quality without Firefox profiles. Chrome profile isn’t as good for our workflow for example. 

That’s why we really need better management capabilities for Firefox. 

This one, and all other one. Everything under about:config should be available via MDM. Plus a control to force the profile picker to always be visible at launch. There is no reason for any of those settings to not be manageable via MDM. 

And it will be actually way more easy to maintain for you if the MDM based management framework can offer a direct access to about:config. That will remove a lot of work for you and keep you only focused on managed keys for what is not available in about:config such as bookmarks, plugins, etc.

**Comment by mkaply** [comment]
>This one, and all other one. Everything under about:config should be available via MDM.

There are simply too many of them to manage (and many of them shouldn't be modified at all).

If there are specific preferences you need, let me know and I can look at adding them

> Plus a control to force the profile picker to always be visible at launch.

I'll check into that.

> There is no reason for any of those settings to not be manageable via MDM.

There actually is. People change many of these values and it actually breaks Firefox.

**Comment by ygini** [comment]
@mkaply if you write it as a bridge (same key for MDM payload and about:config) you don’t have to write it one by one. That’s what I would do. 

And regarding the fact it may break Firefox, that’s IT responsibility. We talk about mass fleet management here. There way more risky actions available than breaking Firefox…

If people break Firefox on a whole fleet because they deployed inappropriate settings on MDM, the correct action isn’t to blame Firefox but to remove admin access from the guilty person. 

Anyway, thanks a lot for your work. I can clearly say that Firefox being manageable by MDM from macOS has clearly been a improvement for the hundreds of setup we manage for our customers.

**Comment by mkaply** [comment]
This is settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences

**Comment by ygini** [comment]
Does the new Firefox version offer backward compatibility for legacy managed preferences model?
