### ISSUE TITLE
Cannot get Firefox GPO's extension settings right

### ISSUE THREAD

**Issue by TreeBranches** [mozilla/policy-templates#539]
Using Group Policy, I'm applying the extension settings as documented [here](https://github.com/mozilla/policy-templates/blob/master/README.md#extensionsettings), and using the code for Windows demonstrated there.

Currently the setting has this:

    {
        "*": {
        "blocked_install_message": "Blocked message",
        "install_sources": ["<all_urls>"],
        "installation_mode": "blocked"
    },
        "uBlock Origin@Raymond Hill": {
        "installation_mode": "force_installed",
        "install_url": "https://addons.mozilla.org/firefox/downloads/file/3498086/ublock_origin/latest.xpi"
    },
        "Vue.js@Evan You, Akryum": {
        "installation_mode": "allowed",
        "install_url": https://addons.mozilla.org/firefox/downloads/file/3454607/vuejs_devtools/latest.xpi"
    },
        "Facebook Container@Mozilla": {
        "installation_mode": "allowed",
        "install_url": https://addons.mozilla.org/firefox/downloads/file/3414682/facebook_container/latest.xpi"
    }
}
My aim: Block installation of all addons and extensions *except* for those three listed above.

Result: Despite the above setting being applied, users are able to install any extension they wish. I am able to install Policy Badger as suggested in About:Addons.

I had a look at about:policies, and I can see the following:

BlockAboutAddons = false

I want this, because I want staff to be able to still be able to browse the extension store

Extensions = Install "https://url.to/ublockorigin/latest.xpi"

I want this, because I want uBlock Origin to be force installed on everyone by default.

InstallAddonsPermission = Default = False

I want this, because I don't want people to be able to install any addon/extension they want unless specified in the whitelist (listed in my original post).

The problem is, If I have InstallAddonsPermission set to false, no one can install any addons, even if I specified a list of extensions that I would allow, just not force-installed.

I'm not sure if I'm missing a setting somewhere or not writing the setting in the GPO properly...

**Comment by mkaply** [comment]
Sorry for the delay on this. Had to debug.

First off, you don't need to mess withthe InstallAddonsPermission (Allow add-on installs from websites) at all. the new extension settings policy takes care of everything.

Your JSON had a couple typos, but the main issue was the extension IDs being incorrect.

You can see the IDs by installing them and then going to about:debugging to see the IDs. Alternatively, when the install is blocked (which was happening with your case), it showed the extension ID in the popup. Here's JSON that worked for me.

```
{
	"*": {
		"blocked_install_message": "Blocked message",
		"installation_mode": "blocked"
	},
	"uBlock0@raymondhill.net": {
		"installation_mode": "force_installed",
		"install_url": "https://addons.mozilla.org/firefox/downloads/file/3498086/ublock_origin/latest.xpi"
	},
	"{5caff8cc-3d2e-4110-a88a-003cc85b3858}": {
		"installation_mode": "allowed",
		"install_url": "https://addons.mozilla.org/firefox/downloads/file/3454607/vuejs_devtools/latest.xpi"
	},
	"@contain-facebook": {
		"installation_mode": "allowed",
		"install_url": "https://addons.mozilla.org/firefox/downloads/file/3414682/facebook_container/latest.xpi"
	}
}
```

**Comment by mkaply** [comment]
Oh, and you don't need install_url for things that are just allowed. They will be allowed from anywhere if the ID matches.

**Comment by TreeBranches** [comment]
> but the main issue was the extension IDs being incorrect.
>
> You can see the IDs by installing them and then going to about:debugging to see the IDs.

Ah, this would explain things then. Thank you for the explanation, and your solution worked perfectly!

Is it possible to add this information somewhere to [the documentation?](https://github.com/mozilla/policy-templates) I had no idea that this extra step was needed and thought that that field was just a custom name...

**Comment by mkaply** [comment]
I did have this in the instructions:

"To obtain an extension ID, install the extension and go to about:support. You will see the ID in the Extensions section."

I'm working on an extension to make this easier and I'll try to make it stand out more. Glad it's working for you.
