### ISSUE TITLE
Feature request: Policy to manage autoplay permission

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#540]
Hi everybody.

I mis the policy setting to manage the autoplay permissions for viedo and audio on websites. I want to set the default behavior.

Image of the preference in firefox dialoge:
![image](https://user-images.githubusercontent.com/61519853/75387237-4ebc3880-58e3-11ea-8d8f-938b8d72381f.png)

**Comment by mkaply** [comment]
This will be in the Firefox 74 and the next ESR which release in a couple weeks.
