### ISSUE TITLE
Tracking Protection "Exception list" cannot be empty after first time configuration

### ISSUE THREAD

**Issue by xenothrox** [mozilla/policy-templates#542]
I've set the "Tracking Protection exception list" active to find out how it works. I've added an entry to the list, made some tests and tried to go back to my previous settings (Don't allow tracking protection preferences to be changed. | checked).

Unfortunately it is not possible to apply this GPO afterwards in any possible way - I've tried the following steps:

1. Set "Tracking protection" to "Not configured" -> Apply (to reset the GPO) -> set to "Enabled", "Don't allow...." checked, -> Apply
--> "No entries were added to the list. Make sure that you add an entry to the list." 
---> Should not pop up as the list should be empty after set it to "Not configured"

2. Set "Tracking Protection" to "Disabled" -> Apply (to reset the GPO) -> set to "Enabled", "Don't allow...." checked, -> Apply
--> "No entries were added to the list. Make sure that you add an entry to the list." 

So it seems that the exception list is not empty after setting the GPO to "Not configured", which means that it is necessary to add a dummy entry to the exception list (after the GPO has been set up once).
Workaround would be setting up a Preference that deletes the related Registry value, but I'm pretty sure this behavior doesn't occur at similar GPOs.

I'm not sure if this issue only occurs in my AD or if others can reproduce this as well.

**Comment by mkaply** [comment]
I can reproduce. I don't understand why GPO requires an entry in the list. I haven't made it mandatory.

I'm going to fix this by moving Tracking Protection to its own category with each entry separate.

I think I try to hard to group everything on one entry and it's just not made for that.

**Comment by mkaply** [comment]
I moved tracking protection to its own category. This should take care of all this. You can give it a try early if you want (there are no changes to Firefox)
