### ISSUE TITLE
DNSoverHTTPS force TRR mode

### ISSUE THREAD

**Issue by MichiFr** [mozilla/policy-templates#543]
Hi,

I can set a GPO for DNSoverHTTPS to prevent any changes for e.g. network.trr.mode, however, I'm missing a GPO for network.trr.mode itself. 
According to [https://wiki.mozilla.org/Trusted_Recursive_Resolver](url) I can set several modes myself in config page of FF, however, it would make sense for us admins to set this mode globally.

Any chance to add this setting as a GPO key?

cu,
Michael

**Comment by andygock** [comment]
I would also love to see this feature.

OR if there is any guidance on how to automatically set `network.trr.excluded-domains` for users using other means, but via GPO would be very nice.

**Comment by mkaply** [comment]
FYI, I've added Excluded Domains in the latest GPO.

As far as the other settings go, none of them are really designed to be usable settable.

What specific setting are you looking for of the ones on that page?

**Comment by mkaply** [comment]
This will now be settable via our new Preferences policy

https://github.com/mozilla/policy-templates/blob/master/README.md#preferences
