### ISSUE TITLE
Feature request: disable weak cipher suites

### ISSUE THREAD

**Issue by Conan1989** [mozilla/policy-templates#544]
Hi,
The ability to disable weak cipher suites on the client side would be handy.
A general forward secrecy only would be ideal, or per cipher suits works also

eg.
![image](https://user-images.githubusercontent.com/6946596/75772352-ab847c80-5d43-11ea-86a3-a570d81ffbdb.png)

**Comment by mkaply** [comment]
I'm turning this into a Bugzilla bug since it's a core change. You can follow it there:

https://bugzilla.mozilla.org/show_bug.cgi?id=1621732
