### ISSUE TITLE
50 Bookmarks are too less for us

### ISSUE THREAD

**Issue by ChrisK-fuerth** [mozilla/policy-templates#550]
Hallo,
50 Bookmarks are too less for us. Can i add some more bookmarks?
Thank you

**Comment by mkaply** [comment]
I'm working on better way to do bookmarks, but you can certainly update the ADMX file locally to have more bookmarks.

**Comment by mkaply** [comment]
The ManagedBookmarks policy is now available which gives unlimited bookmarks and nested folders.

https://github.com/mozilla/policy-templates/#managedbookmarks
