### ISSUE TITLE
Where to install template on Linux Firefox

### ISSUE THREAD

**Issue by ineuw** [mozilla/policy-templates#552]
Using FF 73.01 with Linux Mint 19.3, I have conflicting info on where to store the policies.json file. Now, I placed one in each of the following folders but it's not blocking the update.

**/home/ineuw/.mozilla/certificates/policies.json**
**/usr/lib/mozilla/certificates/policies.json**
**/usr/lib/firefox/distribution/policies.json**

**Comment by mkaply** [comment]
As long as Firefox is located in /usr/lib/firefox,  /usr/lib/firefox/distribution/policies.json should work.

I'm working on a patch to allow policies in etc.

**Comment by ineuw** [comment]
Thanks for the help. I also use a certificate in windows 10 and it shows on the **About Firefox**
that updates are blocked. This display doesn't exist in Linux. How can I tell if the updates are blocked?

**Comment by mkaply** [comment]
go to about:policies and it will tell you if the policy is in place.

How is your Firefox installed?

**Comment by ineuw** [comment]
Standard ppa installation in Linux Mint

**Comment by mkaply** [comment]
If it's in an archive, you might not be able to put the JSON in the right place. I'll bump the priority on the Linux change.

**Comment by ineuw** [comment]
@mkaply, much thanks. The policy is listed and active.
