### ISSUE TITLE
enhancement for GPO "Permissions > AutoPlay": setting for default behavior

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#557]
Hello to everybody.

In the issue #540 I asked for an general setting to define the default behavior of media autoplay.
With version 1.14 of the policy-templates we got a setting to define autoplay behavior.

But you can only define the behavior for special web sites in version 1.14.
Is it posible to add a setting for the default behavior on all sites.

Image of the setting that I mean:
![image](https://user-images.githubusercontent.com/61519853/76872371-9f80da80-686c-11ea-8429-8633912951d2.png)

**Comment by mkaply** [comment]
Good call. I'll get that in the next release.

**Comment by htcfreek** [comment]
Will that been with the official menu items:
- allow audio and video
- block audio (As default choosen value if policy gets enabled.)
- block audio and video

It would be very usefull if the menu button in firefox gets automatically disabled if the policy is set. But only the button for default behavior.
Then an admin can define the default behavior and the user cann override taht if necessary with own exception in the list.

**Comment by mkaply** [comment]
Yes, it will get all three options.

**Comment by mkaply** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1623740

You can set the default value and choose to lock it if you don't want the user to change it.

**Comment by htcfreek** [comment]
@mkaply
I have seen in the bug ticket, that esr don't support this setting.
Is there a plan to integrate this feature into the esr?

**Comment by mkaply** [comment]
It just hasn't been merged yet. Esr will support the default value for audio.

the block audio/video functionality doesn't exist on the ESR so the policy won't work for that.

**Comment by htcfreek** [comment]
Okay.

But will the block audio/video functoinally exist in a later esr build?

**Comment by mkaply** [comment]
It will be in the next major ESR which is in a couple months. That functionality was not backported to the ESR (it was a big patch)

**Comment by mkaply** [comment]
This shipped yesterday.
