### ISSUE TITLE
[MacOS] DNSOverHTTPs setting can't be set through policies.json, neither through plist nor through the sudo defaults command

### ISSUE THREAD

**Issue by zpavloudis** [mozilla/policy-templates#559]
MacOS 15.15.3
Firefox 74.0

Hi all,

Have been trying to disable and lock the DNSOverHTTP feature using FF in an enterprise setting.
Things we've tried and have not succeded.

```
sudo defaults write /Library/Preferences/org.mozilla.firefox EnterprisePoliciesEnabled -bool TRUE
sudo defaults write ~/Library/Preferences/org.mozilla.firefox DNSOverHTTPS_Locked -bool TRUE
sudo defaults write ~/Library/Preferences/org.mozilla.firefox DNSOverHTTPS_Enabled -bool False
```

These didn't seem to do the trick. I've then created a `policies.json` under `Firefox.app\Contents\Resources\distribution` with the following contents:

```
{
  "policies": {
    "DNSOverHTTPS": {
      "Enabled":  false,
      "ProviderURL": "URL_TO_ALTERNATE_PROVIDER",
      "Locked": true
    }
  }
}
```

Lastly within `\Users\<user>\Library\Preferences\org.mozilla.firefox.plist` I pasted the following, again with no success.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnterprisePoliciesEnabled</key>
	<false/>
	<key>DNSOverHTTPS</key>
	<dict>
		<key>False</key>
		<false/>
		<key>ProviderURL</key>
		<string>URL_TO_ALTERNATE_PROVIDER</string>
		<key>Locked</key>
		<true/>
	</dict>
</dict>
</plist>
```

It worth noting that the contents of the .plist file before the change was as follows
```
// !!! BINARY PROPERTY LIST WARNING !!!
//
// The pretty-printed property list below has been created
// from a binary version on disk and should not be saved as
// the ASCII format is a subset of the binary representation!
//
{	DNSOverHTTPS_Enabled = :false;
	DNSOverHTTPS_L = :true;
	DNSOverHTTPS_Locked = :true;
	EnterprisePoliciesEnabled = :true;
	NSFullScreenMenuItemEverywhere = :false;
	NSNavLastRootDirectory = "~/Desktop";
	NSNavLastUserSetHideExtensionButtonState = :true;
	NSNavPanelExpandedSizeForOpenMode = "{1140, 738}";
	NSNavPanelExpandedSizeForSaveMode = "{712, 448}";
	NSTreatUnknownArgumentsAsOpen = "NO";
	"NSWindow Frame NSNavPanelAutosaveName" = "270 228 1140 738 0 0 1680 1027 ";
	"PMPrintingExpandedStateForPrint2" = :true;
}
```

It appears that the settings are actually applied but launching FireFox DNSOverHTTP is still enabled and not disabled & locked as required.

Any ideas ? 

Thank you

**Comment by mkaply** [comment]
Going back to the sudo defaults write, those should be double underscores.

https://github.com/mozilla/policy-templates/tree/master/mac

**Comment by zpavloudis** [comment]
Hi mkaply,

Added double underscores on the following commands, still didn't do the trick.
```
sudo defaults write ~/Library/Preferences/org.mozilla.firefox DNSOverHTTPS_Locked -bool TRUE
sudo defaults write ~/Library/Preferences/org.mozilla.firefox DNSOverHTTPS_Enabled -bool False
```

**Comment by mkaply** [comment]
And you still have sudo defaults write /Library/Preferences/org.mozilla.firefox EnterprisePoliciesEnabled -bool TRUE?

**Comment by zpavloudis** [comment]
Hi mkaply,

We've set EnterprisePoliciesEnabled to true followed by the DNSOverHTTPs sudo defaults write - with double underscores.

Then launching FireFox only to be confronted with the setting set to True when it should clearly be disabled.

**Comment by mkaply** [comment]
We you still locking it?

These three commands were successful foe me.

```
Here are the commands that worked for me:
sudo defaults write /Library/Preferences/org.mozilla.firefox EnterprisePoliciesEnabled -bool TRUE
sudo defaults write /Library/Preferences/org.mozilla.firefox DNSOverHTTPS__Enabled  -bool FALSE
sudo defaults write /Library/Preferences/org.mozilla.firefox DNSOverHTTPS__Locked  -bool TRUE
```
What do you see when you go to about:policies?

**Comment by zpavloudis** [comment]
That done it.

We are still not sure why it did not work the first few times we did it.

Thanks.
