### ISSUE TITLE
SanitizeOnShutdown.Sessions - Active Logins not being Cleared - Firefox 74.0 (64-bit) 

### ISSUE THREAD

**Issue by robertatucworkspacedotcom** [mozilla/policy-templates#560]
When I close the Firefox browser and then reopen it the logged in account is not being cleared.
Registry settings file attached.
Image of Firefox attached

![Firefox login not cleared](https://user-images.githubusercontent.com/62448328/77208170-41046800-6ac9-11ea-8289-151e2d818631.png)

[SanitizeOnShutdown_On.zip](https://github.com/mozilla/policy-templates/files/4361877/SanitizeOnShutdown_On.zip)

**Comment by mkaply** [comment]
The Firefox sync account is not considered an active login. That's referring to logins on websites.

Do you want to be logged out of sync every time the browser is closed?

**Comment by robertatucworkspacedotcom** [comment]
... Yessir.. 

We have meeting rooms that run under a single account and we clean them up between meetings.
Being able to bring Firefox back to a base state in the same fashion as we can with Chrome/Edge Chromium Ephemeral mode would be great.

I thought I might get there with SanitizeOnShutdown but leaving a users sync'ed cloud account connected on closing the browser doesn't get them there.

Is there another set of Group Policy settings I should be looking at?

**Comment by mkaply** [comment]
I discussed this with the Firefox team and they strongly recommend against allowing different users to login into Firefox accounts on the same machine. Bookmarks and other things will get combined/lost/added.

I would recommend you use policy to turn off Firefox accounts for this machine.

Sync was not designed for multiple people to use the same browser.
