### ISSUE TITLE
GPO Wish: Manage handlers.json 

### ISSUE THREAD

**Issue by damianfryc** [mozilla/policy-templates#561]
Hi, We have app in our organization that require open generated pdf files in Adobe Reader.
I have disable pdf.js via GPO and it will be absolutely amazing to set default aciton for application/pdf.

I have modified manually handlers.json and it's working. In my case: 
```
	"mimeTypes": {
		"application/pdf": {
			"action": 4,
			"extensions": [
				"pdf"
			]
		}
	}
```

**Comment by mkaply** [comment]
I'm actively doing this,:

https://bugzilla.mozilla.org/show_bug.cgi?id=1577344

It should be in by Firefox 78.

I'm going to close this since it's being tracked in bugzilla.
