### ISSUE TITLE
GPO wish: Force Master password creation

### ISSUE THREAD

**Issue by xenothrox** [mozilla/policy-templates#562]
I'm looking for an option to make the master password creation no longer optional but a 'mandatory'. At the moment I've got a constellation in which it would be necessary to make the users create a master password to prevent their saved passwords (just existing in my network, no general issue). The existing GPO only offers "not able" or "able" to create a master password but I'm sure that not everyone would set a special password if they aren't 'forced' to do so.

At the moment the workaround is to disable the password manager and not offer to save logins in combination with telling the users to delete their saved login information in the browser.

Is there any option to implement this wish?
Thanks in advance!

**Comment by mkaply** [comment]
I've looked into this and unfortunately there is simply no good way to do this.

It would require that the user create a master password the first time the browser came up and also potentially would wipe out any existing passwords.

We are adding a feature that requires the OS password when the user clicks show password. Does that help at all?

**Comment by xenothrox** [comment]
Thank you so much for checking the possibilities at all! It's not that big problem for us, so now I have a valid statement for my co-workers to this constellation. This has to be fixed in a different way by my company.

As far as I'm informed about this topic, this probably doesn't help us in this case (but this function is interesting as well!).
I'd like to tell you more details about our 'problem' in private if that's okay? It's a security relevant topic which I wouldn't like to discuss "in public" because I'm not sure about its potential risk (only relevant in domain networks with a special constellation as far as I'm informed).

**Comment by StFIT** [comment]
I asked for this feature also years ago.
For security reasons we don't want our users to use the 'weak" possibility to store passwords on the machine that could be revealed if s.o. has physical access to this machine.
Will that change with the feature that requires the OS password when the user clicks show password?

**Comment by StFIT** [comment]
I think what could also help is a password backup and restore solution on prem.
Not the whole profile. We had issues with that.

**Comment by mkaply** [comment]
>  Will that change with the feature that requires the OS password when the user clicks show password?

Yes. Passwords can't be revealed without the system password. In addition, I added a policy to completely remove showpassword:

https://github.com/mozilla/policy-templates/blob/master/README.md#disablepasswordreveal

**Comment by xenothrox** [comment]
> We are adding a feature that requires the OS password when the user clicks show password. Does that help at all?

Coming back to this point: It would only help if this affects the encryption of the files "key4.db" or "logins.json" / their content.
In our constellation we have a seperate domain in which every user has local administrator privileges (bad decision in some cases). With this privileges it is somehow possible to collect the content of the key4.db / logins.json of all domain users, decrypt the content with the matching keys and get all the saved login information.

That's the reason why we were looking for the forced master password creation to protect the saved login information. Would your given solution lead to a similar result or does it just affect the password reveal function within the browser but not the files or their content in the user profile?

**Comment by StFIT** [comment]
+1
Same point for us.

**Comment by mkaply** [comment]
This has finally been added. It will be in Firefox 78/Firefox 78 ESR.
