### ISSUE TITLE
GPO wish: browser.fixup.alternate.enabled (domain guessing)

### ISSUE THREAD

**Issue by jbostoen** [mozilla/policy-templates#563]
It would be nice if browser.fixup.alternate.enabled was supported as a policy.

Our intranet is pushed in the settings with its short name (will change that soon but not possible at the moment); FireFox comes up with a different website when users are not connected to our network

**Comment by mkaply** [comment]
This is settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences
