### ISSUE TITLE
GPO wish : install client certificates (p12/pfx)

### ISSUE THREAD

**Issue by he-loop** [mozilla/policy-templates#568]
Hello,

There's already helpful GPOs concerning certificates handling.

I wish it would be possible to install client certificates (p12/pfx) as it is for (pem) and (der).

It would also be great if Firefox could select them automatically (security.default_personal_cert  in 'about:config').

Thank you for what's already done

**Comment by mkaply** [comment]
We already support security.default_personal_cert in policy.

We also support reading client certificates directly from windows by setting security.osclientcerts.autoload via policy

and finally, installing certificates should work for p12/pfx. We've had people use that API to install client certificates.

**Comment by he-loop** [comment]
Hello,

My bad, I messed up during the tests.
After another try, the first two policies you mentioned solved the case.

Thank you
