### ISSUE TITLE
GPO - Proxy Settings

### ISSUE THREAD

**Issue by D-Geismann** [mozilla/policy-templates#576]
I desperately try to set the proxy settings to "Auto-detect proxy settings", but I always get the message "No value was entered for this field. [...]" In the browser itself I don't have to enter any other setting, why in the GPO?

**Comment by mkaply** [comment]
There's a comment in the GPO description about this:

"Due to a bug, you must select a value for the SOCKS proxy version."

I'm considering moving this to a category so this doesn't happen in the future.
