### ISSUE TITLE
Enhancement Request: Local Files Links could provide an option to use system explorer to open links

### ISSUE THREAD

**Issue by bplessis** [mozilla/policy-templates#580]
Hi,

"Local Files links" is huge for us, but we still have to manually set network.protocol-handler.expose.file and network.protocol-handler.external.file to use windows explorer to open the links.

Could it be added somehow as an option to the policy or an extra policy ?

Thanks,
Benoit

**Comment by mkaply** [comment]
Are you linking to directories or files? File should just open with the default handlers, right?

Can you post a screenshot of what you are seeing?

**Comment by bplessis** [comment]
We are linking directory (basically shared files related to a project) and the web application provide a bookmark to the exchange space.

By default firefox open the directory within itself this doesn't allow dropping files to the project or any file management.

**Comment by CLiX90** [comment]
I have a similar question. 

I have a internal site with links to txt files on UNC path (href=“file://///server/share/text.txt“).

I add my URL to the local file policy. Every time I open the link the content is displayed in the firefox browser window. 
What I want is that the file should be open in editor directly from UNC path to make it possible to edit the content of the text file.

**Comment by mkaply** [comment]
So that's tricky with a .txt file. We autodetect that we can display it and do.

You can probably add a mime type handler for text/plain but you would have to do it manually to handlers.json. I don't provide a policy for that (yet)

**Comment by mkaply** [comment]
This is settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences
