### ISSUE TITLE
Policy groups stop working

### ISSUE THREAD

**Issue by KamalMajaiti** [mozilla/policy-templates#587]
Hi I have implemented group policies in my active directory but I have found a bug that occurs when bookmarks have punnycode characters like Ñ, the policies are no longer fully applied in Firefox. 

Firefox 68 ESR 
CCK2 Equivalent: bookmarks.toolbar,bookmarks.menu
Windows (GPO)
Software\Policies\Mozilla\Firefox\Bookmarks\1\Title = "Example"
Software\Policies\Mozilla\Firefox\Bookmarks\1\URL = "https://example.com"
Software\Policies\Mozilla\Firefox\Bookmarks\1\Favicon = "https://example.com/favicon.ico"
Software\Policies\Mozilla\Firefox\Bookmarks\1\Placement = "toolbar" | "menu"
Software\Policies\Mozilla\Firefox\Bookmarks\1\Folder = "FolderName"

**Comment by KamalMajaiti** [comment]
Firefox group policies are no longer applied, stop working and not change browser settings.

**Comment by mkaply** [comment]
You've opened a bugzilla bug for that,. so I'll close this.

https://bugzilla.mozilla.org/show_bug.cgi?id=1634282

This will probably be a core Firefox change.

**Comment by KamalMajaiti** [comment]
Thanks :)
