### ISSUE TITLE
GPO wish - Preferences\dom.successive_dialog_time_limit

### ISSUE THREAD

**Issue by lukeatlook** [mozilla/policy-templates#590]
Setting dom.successive_dialog_time_limit to 0 is necessary for many web-based systems used in numerous workplaces - otherwise a prompt may appear and cause the user to mistakenly disable the popup engine for that web app.

Sorry to bother with such a simple request. Is it possible to just use a policy to apply custom preferences to config?

**Comment by mkaply** [comment]
This is settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences
