### ISSUE TITLE
Windows (Intune): -2016281112 (Remediation failed)

### ISSUE THREAD

**Issue by PeterKlapwijk** [mozilla/policy-templates#594]
We try to deploy a few settings using Microsoft Intune in a Custom configuration profile.
Most of the used work fine, except those for the Proxy and Bookmarks.
In Intune we get the error -2016281112 (Remediation failed)
In the event logs we found Events with Unknown Win32 Error code: 0x82b00001.
I have seen in the description of both policies there is a bug: Due to a bug, you must select a value for the SOCKS proxy version. (for the proxy setting).
Is this causing the issue, even we set the Sock setting?

**Comment by mkaply** [comment]
The socks setting was only related to how the UI works.

The remediation failed error seems random and unexplainable based on my research. 

I've started documented Intune here:

https://github.com/mozilla/policy-templates/pull/581/files

Can you look at the bookmarks example and see if it matches what you are doing? (there is no proxy example yet)

**Comment by PeterKlapwijk** [comment]
Hi Michael,

Thank you for the prompt response.
Bookmarks is exactly the same, I only used the values BookmarkTitle, BookmarkURL and BookmarkPlacement

**Comment by florianviertel** [comment]
Had the same issue (-2016281112 (Remediation failed)) as I forgot to ingest the correct Firefox ADMX template during my first attempt.

**Comment by PeterKlapwijk** [comment]
I have other settings in the same policy which do apply fine, so nothing seems wrong with the ingestion of the ADMX file.

**Comment by mkaply** [comment]
I have published out Intune OMA-URIs here:

https://github.com/mozilla/policy-templates/blob/master/README.md

I'm working on getting our official Intune setup documentation on SUMO.

All of these settings are things I have tested and verified have worked.

From what I've seen on the web, Remediation failed usually means some mistake in the XML, so I would suggest that you verify the XML and that there are no extra characters, formatting errors or anything like that.

**Comment by PeterKlapwijk** [comment]
I see I missed one error in the events which is pretty crucial. As I didn`t have a favicon, I didn`t specify that setting. But I now see all settings are required to get a successful deployment.
So I`m now able to deploy the bookmarks.

**Comment by PeterKlapwijk** [comment]
I see I missed one error in the events which is pretty crucial. As I didnt have a favicon, I didnt specify that setting. But I now see all settings are required to get a successful deployment.
So I`m now able to deploy the bookmarks.

**Comment by mkaply** [comment]
That's really odd. In my testing you didn't need every setting. I'll look some more.

**Comment by Jhedrick1023** [comment]
I know that this issue has been closed, but it seems that I am running into the same remediation error with Intune/Firefox. 
I have other settings that I have pushed that function properly (DisplayBookmarksToolbar and HomepageURL), but Bookmark01 fails every time. I'm trying to add a bookmark for all of our users to access an internal webpage on SharePoint, if that makes a difference.

**Comment by PeterKlapwijk** [comment]
@Jhedrick1023 we have been discussing the same issue on my website (https://www.inthecloud247.com/manage-mozilla-firefox-settings-with-microsoft-intune/) in the comments.
It seems to only work when you specify and use all 5 settings;
BookmarkTitle
BookmarkURL
BookmarkFavicon
BookmarkPlacement
BookmarkFolder

**Comment by mkaply** [comment]
Yeah, this seems to be an annoying thing about Intune. In theory you could remove the things you don't need from the ADMX template before putting into Intune. I don't know of any better way.

Note I'm working on a better bookmarks solution that should solve some of this.

**Comment by Jhedrick1023** [comment]
@mkaply - I'm glad you're working on a better bookmark solution! I've found all of the information related to this code to be extremely helpful.
@PeterKlapwijk - I had already been to your page, but hadn't read too far into the comments! lol. I tried to specify all 5 settings, but must have done something wrong still. I'll re-investigate and let you know what I found.

Thanks for all the help guys!

**Comment by PeterKlapwijk** [comment]
@Jhedrick1023 thought I added Bookmarks to my article as example after figuring out what the issue was, but seem to forgot it. Will add it to my To-Do list 😀

@mkaply curious to that new solution!

**Comment by mkaply** [comment]
It's going to be similar to Chrome's JSON with all the bookmarks, nested.

**Comment by Jhedrick1023** [comment]
I was able to get the bookmarks to work properly! I found an error in the OMA-URI... Somehow it had a space in it.

**Comment by mkaply** [comment]
That's great to know. I'll try that and see if I can recreate the error so I can better explain.

**Comment by Jhedrick1023** [comment]
@mkaply @PeterKlapwijk: I may have missed this in the documentation somewhere, but is there a way to pin the managed bookmarks to the left side of the Toolbar? When users already have bookmarks saved to the toolbar, it drops this managed folder to the end of the list.

**Comment by mkaply** [comment]
There is not at this time.
