### ISSUE TITLE
1.16 Release has Firefox & ESR versions swapped for DisabledCiphers?

### ISSUE THREAD

**Issue by apizz** [mozilla/policy-templates#595]
With latest release (https://github.com/mozilla/policy-templates/releases/tag/v1.16) appears that the Firefox version # is listed as the ESR version and the ESR version # is listed as the Firefox version for the [`DisabledCiphers`](https://github.com/mozilla/policy-templates/blob/master/README.md#disabledciphers) preference.

**Comment by mkaply** [comment]
Fixed. Thank you!
