### ISSUE TITLE
feature request: setting for "plugin.scan.plid.all"

### ISSUE THREAD

**Issue by Conan1989** [mozilla/policy-templates#597]
hi,
May i request a GPO setting for setting "plugin.scan.plid.all" to false

Applications like Adobe Acrobat try to push their browser plugins. Firefox still requires the user the confirm before it loads (good thing) - but being able to hard disable is nice too.

**Comment by mkaply** [comment]
What version of Firefox are you using?

We don't support any plugin but Flash anymore.

**Comment by Conan1989** [comment]
> 
> 
> What version of Firefox are you using?
> 
> We don't support any plugin but Flash anymore.

76.0.1


![image](https://user-images.githubusercontent.com/6946596/81469824-c1e10580-91d6-11ea-8bde-e0a11f393d9e.png)

![image](https://user-images.githubusercontent.com/6946596/81469830-c5748c80-91d6-11ea-9a9d-2bc2e9e03df7.png)

**Comment by drlellinger** [comment]
I support this request. Being able to turn off this notification would be very nice

**Comment by mkaply** [comment]
We've dropped support for sideloading addons, so this shouldn't happen anymore

https://blog.mozilla.org/addons/2020/03/10/support-for-extension-sideloading-has-ended/

**Comment by Conan1989** [comment]
You're right, only seeing it on machines that have previously had it pre-change

**Comment by mkaply** [comment]
I'm going to go ahead and close this then.

**Comment by drlellinger** [comment]
With the release of 78 ESR sideloading will not be possible anymore as well, is this correct?

**Comment by mkaply** [comment]
So when I had them implement this, I had them leave it on for the ESR. I wasn't sure how bad enterprises need sideloading.

We could still turn it off by default if we decided to.

**Comment by drlellinger** [comment]
We don't need it, i asked for curosity
