### ISSUE TITLE
Policies on FF 76.0 in linux do not work

### ISSUE THREAD

**Issue by ineuw** [mozilla/policy-templates#600]
Recommended folders for policies for Linux Mint Cinnamon 19.3 64bit & Firefox 76.0  don't exist and when created, the policy doesn't work. I tested this with root and user ownerships. Created the following folders, and placed a copy of policies.json in each hoping for a positive outcome. 

/usr/lib/mozilla/certificates/policies.json
/usr/lib/mozilla/certificates/policies/policies.json

/usr/lib64/mozilla/certificates does not exist

/home/ineuw/.mozilla/certificates/policies.json
/home/ineuw/.mozilla/certificates/policies/policies.json

about:support "Enterprise Policies" is inactive.

**Comment by mkaply** [comment]
The location for policies.json is in the distribution directory where the executable is installed (per https://github.com/mozilla/policy-templates/blob/master/README.md)

"On Linux, the file goes into firefox/distribution, where firefox is the installation directory for firefox, which varies by distribution."

In the next update, we'll allow putting system wide policies in /etc/firefox/policies.json

Those locations  you indicated are for certificates only.
