### ISSUE TITLE
Detailed Settings for NewTab Page

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#601]
Please allow a detailed definition of what should be shown and what setting should be looked.

A the moment I only can lock all checkboxes. I also can't configure the sub settings of the category "overview".

**Comment by mkaply** [comment]
You can set all the categories and choose whether or not to lock them.

https://github.com/mozilla/policy-templates/blob/master/README.md

As far as the subcategories go, I'm not going to allow configuring them. When we prioritize enterprise features, it's what people commonly need to do and the main requirement is removing sections, not customization.

**Comment by htcfreek** [comment]
> You can set all the categories and choose whether or not to lock them.

You can only look all categories at once and you can't define all sections of the new tab page via gpo.
![image](https://user-images.githubusercontent.com/61519853/82483260-68cb7880-9ad8-11ea-958f-5ef5c2dada84.png)

Please reopen the issue.
Thank you.

**Comment by htcfreek** [comment]
What I wan't to have as result after configure the GPO i s this:

![image](https://user-images.githubusercontent.com/61519853/82484841-cfea2c80-9ada-11ea-9cf3-35601186a5f5.png)

**Comment by htcfreek** [comment]
What I wan't to have as result after configure the GPO i s this:

![image](https://user-images.githubusercontent.com/61519853/82484841-cfea2c80-9ada-11ea-9cf3-35601186a5f5.png)

**Comment by mkaply** [comment]
Our locking is an all or nothing situation, so I don't have a way for some things to be turned off and locked and other things not in this one section.

I'll make that pocket part under Uberblick removed by default if pocket is disabled though.

**Comment by htcfreek** [comment]
> Our locking is an all or nothing situation, so I don't have a way for some things to be turned off and locked and other things not in this one section.

Can you than deselect and lock the sub items of "Überblick" if the "Überblick" section is disabled and the settings are looked? The actual situation could confuse the user.

**Comment by mkaply** [comment]
> Can you than deselect and lock the sub items of "Überblick" if the "Überblick" section is disabled and the settings are looked? The actual situation could confuse the user.

Deselecting them (unchecking) wouldn't make sense because those values would then be changed. I can definitely disable them.
