### ISSUE TITLE
Remove default advertisement and proposals from NewTab page

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#602]
I want to remove the default advertisement and proposal of mozilla from the New Tab page.

**Comment by mkaply** [comment]
Can you post a screenshot please?

**Comment by htcfreek** [comment]
On the NewTab page in a new Firefox profile you see this:
![image](https://user-images.githubusercontent.com/61519853/82482838-bf848280-9ad7-11ea-86b2-e1f4e9dfa0e9.png)

I we wan't to show our users the most used pages we have to remove the advertisements.

**Comment by mkaply** [comment]
You can remove the second part by removing Pocket in the FirefoxHome configuration.

You can change the list of topsites with the Preferences policy browser.newtabpage.activity-stream.default.sites

**Comment by htcfreek** [comment]
I will test this on friday morning at work. Thank you for your help.

**Comment by htcfreek** [comment]
The preferences policy "browser.newtabpage.activity-stream.default.sites" isn't working correctly. Amazon search ist still present.

**Comment by StoyanDimitrov** [comment]
Amazon search probably comes from `browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned`.

**Comment by htcfreek** [comment]
> Amazon search probably comes from `browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned`.

Is there a policy preference for that?

**Comment by mkaply** [comment]
There isn't. We really don't want people messing with all these internals. But you could just remove the Amazon search engine.

**Comment by linuunix** [comment]
Have a look at [FirefoxHome](https://github.com/mozilla/policy-templates#firefoxhome)

**Comment by htcfreek** [comment]
> Have a look at [FirefoxHome](https://github.com/mozilla/policy-templates#firefoxhome)

I know this policy. But the user can't use the pinned websites.

**Comment by mkaply** [comment]
> I know this policy. But the user can't use the pinned websites.

Sorry, not sure what you mean by that statement.

**Comment by htcfreek** [comment]
> > I know this policy. But the user can't use the pinned websites.
> 
> Sorry, not sure what you mean by that statement.

If I disabled the whole "important sites" section, the user can't use it anymore.

**Comment by mkaply** [comment]
Yes. As I said, you can use the Preferences policy to change that list:

> You can change the list of topsites with the Preferences policy browser.newtabpage.activity-stream.default.sites
