### ISSUE TITLE
Address Bar

### ISSUE THREAD

**Issue by red-erik** [mozilla/policy-templates#603]
Hello,
great work as usual. I saw the Kiosk mode but it's really (for us) too locked down.
Is it possible to simply hide "Address Bar" opening FF with a default homepage?
I did not see this setting in all GPO stuff.

Thank you in advance,
Red.

**Comment by mkaply** [comment]
We don't have anything like that right now. You want the tab bar and the bookmarks bar?

There's ways to do this via autoconfig or userChrome.css. Do you want some help with that?

**Comment by red-erik** [comment]
Hello,
I don't need tab or bookmarks but only a "Kiosk like" user interface to publish some web applications in a secure and controlled way, with ability to have "back and forward" surfing buttons. I don't want users be able to put a different address inside what we published

**Comment by mkaply** [comment]
you might take a look at https://openkiosk.mozdevgroup.com/

**Comment by red-erik** [comment]
Thank You.

Red.
