### ISSUE TITLE
Add browser.startup.homepage_override.mstone

### ISSUE THREAD

**Issue by lucamanga** [mozilla/policy-templates#604]
Hello, 

this is useful to have the same beahaviour as this:

```
// Don’t show WhatsNew on first run after every update
pref(“browser.startup.homepage_override.mstone”,”ignore”);
```

**Comment by mkaply** [comment]
Setting this policy to blank does that:

https://github.com/mozilla/policy-templates/blob/master/README.md#overridepostupdatepage
