### ISSUE TITLE
Delete some cookies at browser exit

### ISSUE THREAD

**Issue by lucamanga** [mozilla/policy-templates#605]
Hello, 

I know that there is a preference to remove ALL cookies on browser exit.
But I would like to write domains to delete cookies at browser exit, not all.

**Comment by mkaply** [comment]
I've opened a bug for this:

https://bugzilla.mozilla.org/show_bug.cgi?id=1639945

It should be straightforward and might make it for 78.

Please follow any progress there.

**Comment by lucamanga** [comment]
Sorry, I have a question. This is the:

`Software\Policies\Mozilla\Firefox\Cookies\ExpireAtSessionEnd = 0x1 | 0x0`

Right? But it seems that it is for all coockies, or am I wrong?
I would like to limit it to "accounts.google.com" and to "mail.google.com" domains, is it possible?

**Comment by mkaply** [comment]
Sorry, this will be in Firefrox 79/Firefox ESR 78.1 It landed a few weeks ago.
