### ISSUE TITLE
Policies folder location of FF76.0 on Linux Mint?

### ISSUE THREAD

**Issue by ineuw** [mozilla/policy-templates#606]
Deleting my post of yesterday is not an acceptable behavour, since it was a polite request for help, and didn't transgress any of Github's rules of behaviour.

Please explain the purpose of calling this web page "policy-templates" explaining the location of certificates, but of policies?

Your reaction makes no sense just beause you don't know the answer to my question. You closed the issue with the reply 'in development' as the excuse.

It worked for me in earlier versions of Firefox. Unfortunately, I lost the unsaved info in reinstallation of Linux Mint 19.3.

I created a 'Policies' folder (please note the Uppercase) containing my original policies.json and also pasted the policies.json file alongside the folder in the following locations

And please, don't delete this post as well.

**Comment by drlellinger** [comment]
The location of the policies.json is the same location as the binaries directory

**Comment by ineuw** [comment]
The Firefox 76.0 installation folder for **policies.json** in Linux is **/usr/lib/firefox/distribution/**.
