### ISSUE TITLE
Intune (MDM); proxy setting

### ISSUE THREAD

**Issue by PeterKlapwijk** [mozilla/policy-templates#607]
Hi,

I try to set the proxy settings to use the system proxy. 
I set ProxyLocked to true.
ConnectionType to system.
Because I see via the GPO editor SOCKSversion is needed, I set that to 4.
Now I got an event:
MDM PolicyManager: admx ingestion given payload policy definition element id not found: Id (HTTPproxy).
So I this is probably also a required setting, even if I want Firefox to use the system settings and not specify any further proxy settings in Firefox.

Any thoughts on this?

**Comment by mkaply** [comment]
I assume you are using Intune? Where are you seeing that error?

**Comment by PeterKlapwijk** [comment]
Yes I use Intune.

See the error in the event logs of Intune (DeviceManagement....)

**Comment by PeterKlapwijk** [comment]
Yes, leaving everything blank as much as possible seems to work. At least the policy is applied successful.
Thanks for the info and the documentation you`re creating!
