### ISSUE TITLE
Policy to block 'Clear Browsing History'

### ISSUE THREAD

**Issue by abinpaul1** [mozilla/policy-templates#608]
There doesn't seem to be a policy to enable this. There is a policy to disable 'Forget' option but none to prevent history from being cleared.

**Comment by mkaply** [comment]
That's correct, we don't have a policy for this yet. It's a significant change to the internals of the browser. We'll hopefully have something in the next few months.

**Comment by stoyianov** [comment]
Thought I'd ask, is such a feature still planned?

**Comment by mkaply** [comment]
It's still on my radar, just a lot of other priorities.
