### ISSUE TITLE
wrong bookmarks numbering in firefox.admx

### ISSUE THREAD

**Issue by uniqueit-eu** [mozilla/policy-templates#611]
Bookmark01 creates registry Key Mozilla\Firefox\Bookmarks\1
Bookmark02 creates registry Key Mozilla\Firefox\Bookmarks\10
Bookmark03 creates registry Key Mozilla\Firefox\Bookmarks\11

**Comment by mkaply** [comment]
Yes, this was an unfortunate side effect of some ADMX issues we had.

See:

https://github.com/mozilla/policy-templates/pull/241

I'm working on a new managed bookmarks policy that should make this whole thing much easier.
