### ISSUE TITLE
Firefox ESR and policies.json

### ISSUE THREAD

**Issue by andreiv3103** [mozilla/policy-templates#612]
I'm evaluating (and testing) options for Firefox deployment.
I installed the latest ESR and tried to install 2 language packs using policies.json.
I created the C:\Program Files\Mozilla Firefox\distribution folder and placed the policies.json file there.
I added in it:
{
  "policies": {
    "Extensions": {
      "Install": ["C:\Program Files\Mozilla Firefox\distribution\it.xpi"]
  }
}
}
the it,xpi file is there, in the folder mentioned.
However, when I start Firefox, it doesn't get installed. What am I doing wrong?

**Comment by andreiv3103** [comment]
Just tested. Changed the contents of the policies.json file to:
{ "policies": { "BlockAboutConfig": true } }
and, when opening firefox and trying to get to config, I got blocked:
![image](https://user-images.githubusercontent.com/2743608/83353907-6251c200-a35e-11ea-85d0-8ba00fc5b784.png)
So there must be an error in my policies.json settings...

**Comment by drlellinger** [comment]
When you set BlockAboutConfig to true, about:config is blocked

**Comment by drlellinger** [comment]
I guess your Extension Problem is that the xpi file is on the local file system and the policy engine cannot parse the location correctly.

**Comment by andreiv3103** [comment]
I found the answer. I'll write it here, in case someone else gets into the same issue. This is the correct, working file:
`{
"policies": {
"Extensions": {
"Install": ["C:\\Program Files\\Mozilla Firefox\\distribution\\it.xpi"]
}
}
}`
Apparently, backslashes need to be escaped.

**Comment by andreiv3103** [comment]
> When you set BlockAboutConfig to true, about:config is blocked

Yes, that was a test, to verify that the policy is indeed applied.
