### ISSUE TITLE
Missing Setting: Permissions -> Virtual Reality

### ISSUE THREAD

**Issue by tobiwashere** [mozilla/policy-templates#615]
Would be great to preset the permission for "virtual reality".
Setting: permissions.default.xr

**Comment by mkaply** [comment]
Yeah, that's a good idea. I installed the oculus software on my machine and I get the VR popup everywhere :).

**Comment by tobiwashere** [comment]
Fixed/Added in #671/Release [v2.2](https://github.com/mozilla/policy-templates/releases/tag/v2.2)
