### ISSUE TITLE
Difference between PDFjs and DisableBuiltinPDFViewer?

### ISSUE THREAD

**Issue by apizz** [mozilla/policy-templates#618]
With the most recent release (https://github.com/mozilla/policy-templates/releases/tag/v1.17) a new preference, [`PDFjs`](https://github.com/mozilla/policy-templates/blob/master/README.md#pdfjs).  The purpose of the preference seems remarkably similar to an existing preference [`DisableBuiltinPDFViewer`](https://github.com/mozilla/policy-templates/blob/master/README.md#disablebuiltinpdfviewer).

What is the difference and why would you use one over the other?

**Comment by mkaply** [comment]
I probably should have been clearer about this. I'll update the release notes.

Basically we got a new option for PDFjs (EnablePermissions) and it didn' t make sense to just add a new policy for that so I created the new PDFjs policy for that and included the same function as the old DisableBuiltInPDFViewer. I was originally going to deprecate DisableBuiltInPDFViewer but there didn't seem to be any need to, so you can use either.

**Comment by apizz** [comment]
Got it.  So as of this moment, you can use either, but the additional options w/ `PDFjs` gives a little more control than just enabled/disabled?

**Comment by mkaply** [comment]
> Got it. So as of this moment, you can use either, but the additional options w/ PDFjs gives a little more control than just enabled/disabled?

Yep
