### ISSUE TITLE
Firefox 77.0.1 (64-Bit) ADMX Certificat Import does not work

### ISSUE THREAD

**Issue by therealsatera** [mozilla/policy-templates#622]
Hello,

I copied a .p12 certificate to the %AppData% Path like descriped in the admx. Unfortunately the descriped cert does not get importet after gpupdate /force.

What should i do?

**Comment by mkaply** [comment]
Is there an error when you go to about:policies? Did you restart Firefox?

**Comment by therealsatera** [comment]
No, there is no error displayed. I closed firefox every time before gpupdate

**Comment by mkaply** [comment]
We don't support p12 files. It needs to be the PEM or the DER. If the certificate is in the operating system, you can use the ImportEnterpriseRoots policy and Firefox will read it from there, then you don't need to import it at all.
