### ISSUE TITLE
ImportEnterpriseRoots in Linux (Ubuntu)

### ISSUE THREAD

**Issue by proximous** [mozilla/policy-templates#634]
Either the documentation at https://github.com/mozilla/policy-templates/#certificates--importenterpriseroots needs some clarification or I'm misinterpreting something.

FF 77.0.1 Ubuntu 20.04

I add my certs to /usr/local/share/ca-certificates/\*.crt
I run `update-ca-certificates`
I see the certs in /etc/ssl/certs/*.pem as a link the the files in /usr/local/share/ca-certificates

I have a policy of:
`{
  "policies": {
    "Certificates": {
      "ImportEnterpriseRoots": true
    }
  }
}
`

I'm therefore expecting to have access to all the certificates (.pem files) in the global store (/etc/ssl/certs/*.pem).

Do I understand this setting correctly or am I experiencing a bug?

**Comment by mkaply** [comment]
The ImportEnterpriseRoots policy is Windows and macOS only. 

You can import those certificates individually using the Certificates->Install option.

I don't know exactly why that pref wasn't implemented for Linux except that Linux doesn't have the concept of a true certificate store that we can import from (not just a directory with certs).

**Comment by proximous** [comment]
Thanks for the quick reply. I guess it would be good to clarify that in the docs.

Though it may vary across distributions, I do believe Linux has a certificate store as I use it successfully for other applications in Ubuntu, so it would be great if that could eventually be supported: 

https://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate
https://superuser.com/questions/437330/how-do-you-add-a-certificate-authority-ca-to-ubuntu

Hopefully that's something you can consider.

**Comment by mkaply** [comment]
So it looks like there was discussion of this here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1600509

**Comment by proximous** [comment]
Interesting discussion. Too bad supporting Linux doesn't seem up for consideration, but there is a reference to a potential solution I'll check out: https://askubuntu.com/a/1036637

(I still suggest a quick edit to the README to say Linux is unsupported.)

**Comment by mkaply** [comment]
> (I still suggest a quick edit to the README to say Linux is unsupported.)

I'll do that.
