### ISSUE TITLE
Windows (Intune) OMA-URI security.default_personal_cert

### ISSUE THREAD

**Issue by CLiX90** [mozilla/policy-templates#636]
How can I set the security.default_personal_cert preferences to autoload with Intune OMA-URI?
In the documentation I can find only examples for boolean values.

**Comment by mkaply** [comment]
Sorry about that. Example for a string added to README.md

OMA-URI: (periods are replaced by underscores)
```
./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~Preferences/string_preference_name
```
Value (string):
```
<enabled/>
<data id="Preferences_String" value="string_value"/>
```
