### ISSUE TITLE
Feature request: Extension whitelist? allow but do not install by default

### ISSUE THREAD

**Issue by tastyratz** [mozilla/policy-templates#638]
It would be much easier if the extension whitelist/blacklist/ could be managed without having to write and manage JSON code.

Ideally, a whitelist of extension ID's (like chrome admx's), a behavior field (allow/install/normal/locked), and a description field for each entry (to keep track of what they are)

This is much more approachable and readable across multiple admins if at all possible.

**Comment by mkaply** [comment]
This is exactly what the ExtensionSettings is for, but it does require JSON (as does the Chrome version of this policy).

I understand you prefer the Chrome method (ExtensionInstallWhitelist/ExtensionInstallBlacklist), but they've switched to the JSON method as well (ExtensionSettings is their new preferred policy).

https://github.com/mozilla/policy-templates/blob/master/README.md#extensionsettings

It works exactly as Chrome does and does what you request. You make mark particular extension IDs as "allowed" and then they can be installed from anywhere.

Your idea of a description field is a great idea. I think you could add a description in the JSON today and it would be ignored, but I'll double check and if it isn't, I'll add it.
