### ISSUE TITLE
clipboard events control?

### ISSUE THREAD

**Issue by juju4** [mozilla/policy-templates#639]
Would it be possible to add as an option?
https://rawsec.ml/en/disable-clipboard-events/

Thanks

**Comment by mkaply** [comment]
I'll add it to the potential list but honestly, flipping this prefs breaks a ton of things on the internet.

**Comment by juju4** [comment]
Thanks.
What do you see breaking and legitimate?
I enabled on my side and no impacts but clearly not representative.

malware likely not
blocking password copy/paste same
linkedin getting your whole clipboard neither (that's an app but...)

**Comment by mkaply** [comment]
Per the comments, it breaks Google docs, twitter and others. I'm not saying it's not useful, I just don't know that folks want to encourage this. I agree this is an annoying behavior.

There is an addon for this (the name could be considered offensive) - https://addons.mozilla.org/en-US/firefox/addon/don-t-fuck-with-paste/?src=search

**Comment by juju4** [comment]
Thanks for sharing.
maybe with a block + allow list in this case like cookies and various permission, or chrome block/allow runtime with ChromeGalvanizer (https://github.com/mandatoryprogrammer/ChromeGalvanizer)

**Comment by mkaply** [comment]
This is settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences
