### ISSUE TITLE
Prevent New Tab section "Welcome to Firefox"

### ISSUE THREAD

**Issue by pilgi3** [mozilla/policy-templates#640]
Is there a GPO to prevent the section in 78.0.1esr?

![image](https://user-images.githubusercontent.com/44865075/86575548-c0824e00-bf77-11ea-8883-95ed5d67c3c7.png)

Or what setting i have to modify in about:config?
Thank you!

**Comment by mkaply** [comment]
If you turn off FirefoxAccounts or add an override page, it should turn off. I'm verifying the policy is working correctly. I'll also add this to UserMessaging so it's more explicit.

**Comment by pilgi3** [comment]
We have set this policies:
![image](https://user-images.githubusercontent.com/44865075/86879228-eaa84d00-c0ea-11ea-9bdb-17bcb08d2fcb.png)
![image](https://user-images.githubusercontent.com/44865075/86879237-f0059780-c0ea-11ea-9f71-474907f37f3a.png)

But this does not prevent the "Welcome to Firefox" section.
What policy do you mean exactly?

**Comment by mkaply** [comment]
I was wrong. This apparently broke in Firefox 76. I'll have a fix in the next Firefox update/ESR update

**Comment by pilgi3** [comment]
Should this be fixed with 78.0.2esr? I have tested, but the issue still exists.

**Comment by mkaply** [comment]
No, it should be in the next major update, which will be July 28.

**Comment by mkaply** [comment]
This was fixed the last release.
