### ISSUE TITLE
Feature request: Disable installation of pkcs extensions

### ISSUE THREAD

**Issue by drlellinger** [mozilla/policy-templates#641]
WIth 78esr we get a weird phenomenon that a (Nexus) pkcs module wants to be installed.
My suggestion would be that disabling the policy would disable the installation.

**Comment by mkaply** [comment]
I would need more info as to how nexus is installing their module. There's not an easy way to prevent the installation of modules.

**Comment by drlellinger** [comment]
This occured while testing a Windows Server 2008 R2 Citrix deployed FF 78 x64 - previous versions (68) did not have this phenomenon. It wants to be installed like a software add-on (like Acrobat or McAfee extensions)

**Comment by mkaply** [comment]
PKCS11 support in WebExtension has been there since 58 - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/pkcs11.

So I'm wondering if they (Nexus) switched to using a WebExtension? I would recommend getting the extension ID and just blocking the extension.

**Comment by drlellinger** [comment]
Ok i will do that
