### ISSUE TITLE
Automatic updates only within ESR Major releases

### ISSUE THREAD

**Issue by CLiX90** [mozilla/policy-templates#643]
We need the ability to disable automatic updates from major ESR releases (for example 68 to 78), but allow automatic updates within the major ESR release (68.0 to 68.x).

Major updates should be controlled and deployed with our deploymemt system, but security updates and small changes should be installed automatically.

**Comment by drlellinger** [comment]
Chrome and Microsoft Edge have this feature implemented, this would be very strong for small enterprises without a patch management

**Comment by lucamanga** [comment]
Confirmed here: updated from 68.2 ESR straightly to 78

**Comment by mkaply** [comment]
> Confirmed here: updated from 68.2 ESR straightly to 78

Are you saying that happened automatically? That definitely shouldn't.

**Comment by lucamanga** [comment]
Yes. If the user is the local Administrator, it updates.

**Comment by mkaply** [comment]
I just ran a quick check any my 68.2 ESR updated to 68.10. We are not pushing 78 updates to 68 esr.

**Comment by mkaply** [comment]
This is update pinning and we're implementing it:

https://bugzilla.mozilla.org/show_bug.cgi?id=1529943

**Comment by mkaply** [comment]
This was in Firefox 102 and I just documented the policy.
