### ISSUE TITLE
Import enterprise root

### ISSUE THREAD

**Issue by red-erik** [mozilla/policy-templates#644]
Hello,
I read the story on
https://bugzilla.mozilla.org/show_bug.cgi?id=1473573
but on FF 68.9.0 ESR we have the same problem. FF works correctly only if ALL certificates are in the Root store of Windows and NOT in the Intermediate store.
Is it the default behavior or is it a regression bug? We really would be more happy to be able to correctly populate the windows certificate store with Root CA Cert in the Root Store and Sub CA Certificates in the Intermediate Store.
Regards,

Red.

**Comment by mkaply** [comment]
I would comment in that bug (or open a new bug). We should be importing intermediates from the Windows store.
