### ISSUE TITLE
Typo in releases

### ISSUE THREAD

**Issue by red-erik** [mozilla/policy-templates#645]
Hello,
I think that FF 78 ESR does not exist
https://github.com/mozilla/policy-templates/releases
probably should be FF 68.10 ESR

Regards,
Red.

**Comment by drlellinger** [comment]
Both exist

**Comment by drlellinger** [comment]
https://support.mozilla.org/en-US/kb/firefox-esr-release-cycle

**Comment by red-erik** [comment]
Yes...sorry, my mistake.

Red.

**Comment by red-erik** [comment]
Yes...sorry, my mistake.

Red.
