### ISSUE TITLE
GPO Wish: Whitelist for Third party cookies

### ISSUE THREAD

**Issue by xenothrox** [mozilla/policy-templates#647]
In our company we've set "AcceptThirdParty | _never_" as it was suggested by our IT security team. This works fine in 99% of all cases. For some websites (necessary for daily work) the user has to make manual exceptions to the third party cookie policy to get the website work properly.
This is quite fine and works without any problems, but there is still the possibility that a user can make an exception for the third party cookie policy on websites that might be classified 'critical' by the IT security team.

So I came up with the idea that it might be possible to generate a global whitelist via GPO for websites on which "AcceptThirdParty | never" is not active (for example just like the popup whitelist function). This would increase the security as there are only exceptions to the policy which are approved by the IT security team and it would also be easier to configure this for all users via GPO than using config files which get pushed into the Firefox Profiles.

Is there a possibility to implement this or is this feature "blocked" by technical issues?
Thanks in advnce!

**Comment by Yorgh** [comment]
I agree with you @xenothrox, for Windows users connected to an AD, it would be a great idea.
But you should not forget that the product is multiplatform. This type of features can interest more than Windows users only.
So, according to me, the config files should not be forgotten by the developers.
Maybe both can be taken in consideration if it is not too much work.
Thanks

**Comment by mkaply** [comment]
We already have an Allow option for cookies where you can list domains cookies are always allowed and Block you never want cookies on.

If you add domains to this list, they will allow third party cookies.

**Comment by xenothrox** [comment]
Thank you for your replies to this topic! I didn't realize that the "Allow" policy also affects the third party cookie behavior. I'll use the given policy to configure the whitlist.
