### ISSUE TITLE
placements of policies.json

### ISSUE THREAD

**Issue by ineuw** [mozilla/policy-templates#648]
Two Firefox 78.0.2 en-US standard installation attempts failed on Linux Mint 20.0. Purged the old and Installed a standalone version in /Opt/firefox, but **about:support** Enterprise Policies is "Inactive". I have no clue where to place Policies.json. This is a single user desktop.

**Comment by mkaply** [comment]
Per:

https://github.com/mozilla/policy-templates/issues/606

> The Firefox 76.0 installation folder for policies.json in Linux is /usr/lib/firefox/distribution/.

**Comment by ineuw** [comment]
> Per:
> 
> #606
> 
> > The Firefox 76.0 installation folder for policies.json in Linux is /usr/lib/firefox/distribution/.

:-) That was my previous post you are quoting, and that was true in versions 76.0.0 until 78.0.1. That location is no longer valid in 78.0.2. In another document of this web site, states that now it should be placed in **/etc/firefox** and this doesn't work either. Also please re-read my post of today.

**Comment by mkaply** [comment]
etc/firefox was not a change, it was a new location. You can have system wide policies now. And the location is:

/etc/firefox/policies/policies.json

That is probably easier for you to do.

As far as the /usr/lib/firefox location goes, it depends on where Mint puts Firefox.

**Comment by ineuw** [comment]
Much much thanks. It's working from **/etc/policies/policies.json**, even for this non-Mint installation. Issue closed. :-)
