### ISSUE TITLE
Minor Issue in GP Template Help

### ISSUE THREAD

**Issue by SolarBoy3** [mozilla/policy-templates#649]
There is a missing 'l' in the description text:
- Mozilla\Firefox\User Messaging\Feature Recommendations
Description second paragraph, 11th word is 'wil' should be 'will'

Thank you all for a great product.

**Comment by mkaply** [comment]
Fixed. Thank you!

**Comment by SolarBoy3** [comment]
Glad I could help in some small way. Not being a programmer, all I can do
is testing and proofreading.

    - Steve
