### ISSUE TITLE
issues with the new handlers policy setting for firefox?

### ISSUE THREAD

**Issue by googol13** [mozilla/policy-templates#650]
for the life of me, I tried so many ways for the json to get the settings to apply.

been looking at handlers.json

the format in the readme documentation is much different, but the documentation says it emulates handers.json

the syntax is different

do I need all them? I only see iwl protocol under schemes

if I manually set it under about:preferences to system default, dont ask, then it changes to this under schemes
"iwl":{"action":4}

I dont have any mimetypes or extensions, do I need to include those? i tried both with and without, checked brackets

I look at about:policies, dont ever see it applying, dont see any errors

turned on debugging for policies and looked at the console, nothing about handlers

is the documentation not up to date? is there an example perhaps? the handlers.json has no handler setting, shouldnt need to set a URI and all that I believe.

I tried this
"schemes": {
    "iwl": {
      "action": "useSystemDefault",
      "ask": false,
      }
}

but handlers.json is saying action =4 whatever that means

I am trying to suppress for the iwl protocol when launching it in a link in firefox, dont want the prompt and dont want to click on always do this with the link checkbox, want to push it out via group policy.

please advise

yes Im using firefox 78.0.2 and have uploaded the latest template v2.01

**Comment by googol13** [comment]
![iwlproto](https://user-images.githubusercontent.com/49327352/87842427-41d3bd80-c861-11ea-8ba2-a2dc407dca5a.png)

here is screenshot of the prompt trying to suppress automatically via group policy.

**Comment by mkaply** [comment]
4 is useSystemDefault. So that is working.

That question is why isn't the "ask" false working

I'm checking.

**Comment by googol13** [comment]
what is the proper syntax for the json for the handlers window?

I was trying 4 instead of usesystemdefault just now

{
  "mimeTypes": {
  },
  "schemes": {
    "iwl": {
      "action": "4",
      "ask": false,
    }
  },
  "extensions": {
    }
}

When I go to about:policies, I don't even see handers policy, nothing, no errors. turned on debugging for browser and nothing shows in the console. it should show up there right?

I dont think its processing the new policy and not sure if I have the syntax correctly or can I just focus on one section? I tried both, the full mimetypes, schemes and extensions, or just schemes, tried 4 or usesystemdefault, etc.

thanks for your help, hope we can figure this out

**Comment by mkaply** [comment]
4 definitely won't work. I'm using an enum, so I map useSystemDefault to 4 internally.

**Comment by googol13** [comment]
Thanks..I will switch it back. I already tried with useSystemDefault, wasnt parsing it seems about:policies shows nothing. I also tried it under mimetypes, but looking at my handlers.json, I see it under schemes for the iwl protocol, so thats why I put it under schemes for group policy handlers setting

{
"mimeTypes": {
},
"schemes": {
"iwl": {
"action": "useSystemDefault",
"ask": false,
}
},
"extensions": {
}
}

**Comment by mkaply** [comment]
Is iwl an extension (*.iwl file) or a scheme (iwl:foo)

**Comment by googol13** [comment]
scheme from my understanding, iwl://*

its a special link that application knows, just issue is by default its asking the user, we want to suppress that prompt and make it never ask and just open it with the system default app which is showing up fine in firefox.

definitely not an extension, you can open up any file from the document management system and its all file types

**Comment by googol13** [comment]
iwl shows up in handlers.json under the scheme section as well, adjusts if I manually adjust about:preferences, but thankful you added the handlers policy in the latest updates, updated it and all, but now cant get it working :(

perhaps I just fail with json format required

**Comment by mkaply** [comment]
You've definitely found a bug, but I can't figure out why it's happening. The test we built for this is passing. I'm looking into it...

**Comment by googol13** [comment]
no problem, appreciate you looking into it and responding :)

good luck, keep us posted if you can. I will check release notes for future firefox versions.

**Comment by mkaply** [comment]
It looks like this can happen if we can't find the default handler in the operating system.

I don't have the IWL handler installed, so I can't see exactly what is going on. Is this an app I can install?

**Comment by googol13** [comment]
its part of our document management system

iManage Work Link (IWL)

I unfortunately cannot provide the software nor is it available publicly to my knowledge, but I know we are not the only folks that use it as they are a large company.

It shows up under applications in firefox fine, any thoughts?

![iwlproto](https://user-images.githubusercontent.com/49327352/87995984-d9295280-caa5-11ea-95f9-9624b09aed93.png)

**Comment by googol13** [comment]
![iwlapp-firefox](https://user-images.githubusercontent.com/49327352/87996071-1857a380-caa6-11ea-8751-819a907b7d40.png)

**Comment by devCoder77** [comment]
I was also trying to get the Handlers section to work. I was able to get it working, if I put in policies.json

<code>
{
	"policies": {
		"Handlers": {
			"mimeTypes": {
				"application/something": {
					"action":"useSystemDefault",
					"ask": false
				}
			}
		}
	}
}
</code>

Then I can see the Handlers on the page about:policies.

Maybe the documentation could specify also the levels policies / Handlers as they are described in all other policies.

Otherwise the section Handlers is just what I needed. Thank you!

**Comment by mkaply** [comment]
> Maybe the documentation could specify also the levels policies / Handlers as they are described in all other policies.

Oops. I'll fix that.

And @googol13 I've reached out to iManage to see if they can give me something to test with.

**Comment by googol13** [comment]
Should I try this without mimetypes but schemes?

{ "policies": { "Handlers": { "schemes": { "iwl": { "action":"useSystemDefault", "ask": false } } } } } 

Would this be the correct syntax? but like you said, its not recognizing iwl? Appreciate you reaching out to imanage.

Copy and paste this into the json field in GPO for Handlers under Firefox settings?

**Comment by mkaply** [comment]
No, in the GPO, you only need the inner stuff (the open bracket and schemes)

The outer policies/Handlers is needed when using a JSON file.

@googol13 

I 100% believe that your problem is because we aren't detecting the default handler. We have code that says "if you can't find the default handler, default to asking"

If you want to setup, we can do a WebEx and I can walk you through debugging and we can verify the problem.

**Comment by googol13** [comment]
Sure, I can be available this afternoon around 4pm PT if that works for you. not sure how you can privately message me for info?
If not today, can meet tomorrow at 7am PT or 9-1030am PT, not sure what timezone you are in.

Be happy to debug this with you, appreciate your assistance.

**Comment by mkaply** [comment]
I'm in central. Let's do tomorrow 9 am. Email me at mkaply at mozilla.com

**Comment by googol13** [comment]
We figured it out, the handlers json is working as expected now. not sure what changed, but could have been json formatting. no errors showed up in about:policies, json validation is good check on the free public sites out there.

big thanks to mkaply for his time
