### ISSUE TITLE
Enable extension with GPO

### ISSUE THREAD

**Issue by Rukicc** [mozilla/policy-templates#652]
We use software witch adds extension to firefox, Chrome, but this extension was in disabled state user must manually enable this extension. 
In chrome and Edge Chromium we have option to enable this extension with group policy. 
How to do that with group policy in Firefox?

**Comment by mkaply** [comment]
> We use software witch adds extension to firefox, Chrome, but this extension was in disabled state user must manually enable this extension.

This won't work anymore. We've removed the ability to sideload.

https://blog.mozilla.org/addons/2019/10/31/firefox-to-discontinue-sideloaded-extensions/
https://blog.mozilla.org/addons/2020/03/10/support-for-extension-sideloading-has-ended/

You'll need to install with policy or have the user install it.
