### ISSUE TITLE
Custom Update Url

### ISSUE THREAD

**Issue by red-erik** [mozilla/policy-templates#655]
Hello,
I'm trying to build our internal "Update Server" and I'm testing the update process. Is there a way to have FF looking ONLY the the Custom Update URL and NOT to Mozilla ones ?
FF release 60.x are updating from Mozilla in several step and finally from internal update server. Only FF 78.0.1 is updating to 78.0.2 from my internal server.
Am I missing something? Is there a way to be sure to have updates from my server only ?
If yes, what MAR files I need to publish to have a full working chain of updates from 60.x to 78.0.2 ?

Thank you in advance.
Regards,

Red.

**Comment by drlellinger** [comment]
Easiest setup is to use full .mar update files so all versions get updated to the desired version.

**Comment by red-erik** [comment]
Hello,
yes, but is not working. FF , even if "Custom Update Url" is configured for an internal Webserver, tries (and connect successfully) to Mozilla servers to grab updates.
Any suggestion?

Red.

**Comment by mkaply** [comment]
> yes, but is not working. FF , even if "Custom Update Url" is configured for an internal Webserver, tries (and connect successfully) to Mozilla servers to grab updates.

I've had other folks report this, and I don't really understand.

Are you saying it somehow sends the update request to a Mozilla server or it's download the updates from a Mozilla a server?

What are you serving from your update server?

**Comment by red-erik** [comment]
Hello,
yes, is what I mean. We have FF 60.4.0 ESR and we prepared an update server servicing FF 78.1.0 ESR only (single complete MAR  file). After setting the "custom Update Url" and enabling "updates" I see FF grabbing FF 68.X ESR (for sure from aus5.mozilla.org) and than FF 78.0.2 ESR (again from Mozilla). After that it finally grab FF 78.1.0 ESR from our update server (I see this in "update history" because I set a custom display name) .

Red.

**Comment by red-erik** [comment]
Hello,
to have complete control of the update process, the setting "Check for updates but let you choose to install them" instead of "Automatically install updates (recommended)" should be available as a GPO setting. I did not find it anyway.
Regards,
Red.

**Comment by pierre-guillot** [comment]
For me, I configure "Custome Update URL"  like this : http://ffupdate.ch-boscamnant.org/%VERSION%/%BUILD_TARGET%/update.xml

Then, my clients contacts my web server (apache) to Download "update.xml", depending of version and arch running : 

```
172.22.1.135 - - [31/Jul/2020:12:38:34 +0200] "GET /68.9.0/WINNT_x86-msvc-x86/update.xml HTTP/1.1" 404 413 "-" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
172.22.10.55 - - [31/Jul/2020:12:40:09 +0200] "GET /68.9.0/WINNT_x86_64-msvc-x64/update.xml HTTP/1.1" 200 287 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
172.22.1.135 - - [31/Jul/2020:12:41:04 +0200] "GET /68.9.0/WINNT_x86-msvc-x86/update.xml HTTP/1.1" 404 413 "-" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
172.22.1.148 - - [31/Jul/2020:12:47:03 +0200] "GET /68.9.0/WINNT_x86_64-msvc-x64/update.xml HTTP/1.1" 200 287 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
172.22.1.141 - - [31/Jul/2020:12:49:03 +0200] "GET /68.8.0/WINNT_x86-msvc-x86/update.xml HTTP/1.1" 200 749 "-" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
172.22.1.122 - - [31/Jul/2020:12:54:25 +0200] "GET /68.6.0/WINNT_x86-msvc-x64/update.xml?mig64=1 HTTP/1.1" 200 749 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0"
172.22.3.66 - - [31/Jul/2020:12:57:18 +0200] "GET /68.9.0/WINNT_x86_64-msvc-x64/update.xml HTTP/1.1" 200 287 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
172.22.3.59 - - [31/Jul/2020:13:17:33 +0200] "GET /68.9.0/WINNT_x86-msvc-x86/update.xml HTTP/1.1" 404 413 "-" "Mozilla/5.0 (Windows NT 6.1; rv:68.0) Gecko/20100101 Firefox/68.0"
172.22.3.59 - - [31/Jul/2020:13:20:36 +0200] "GET /68.9.0/WINNT_x86-msvc-x86/update.xml HTTP/1.1" 404 413 "-" "Mozilla/5.0 (Windows NT 6.1; rv:68.0) Gecko/20100101 Firefox/68.0"
172.22.3.59 - - [31/Jul/2020:13:27:48 +0200] "GET /68.9.0/WINNT_x86-msvc-x86/update.xml HTTP/1.1" 404 413 "-" "Mozilla/5.0 (Windows NT 6.1; rv:68.0) Gecko/20100101 Firefox/68.0"
```
Then, I created folder like this in my website root folder : 

```
/home/ffupdate/
├── 60.6.1
│   ├── WINNT_x86-msvc-x64
│   │   └── firefox-60.6.1esr-60.6.3esr.partial.mar
│   └── WINNT_x86-msvc-x86
│       ├── firefox-60.6.1esr-60.6.3esr.partial.mar
│       └── update.xml
├── 60.6.3
│   ├── WINNT_x86_64-msvc-x64
│   ├── WINNT_x86-msvc-x64
│   │   ├── firefox-60.6.3esr-60.9.0esr.partial.mar
│   │   └── update.xml
│   └── WINNT_x86-msvc-x86
│       ├── firefox-60.6.3esr-60.9.0esr.partial.mar
│       └── update.xml
├── 60.7.0
│   ├── WINNT_x86_64-msvc-x64
│   └── WINNT_x86-msvc-x64
│       ├── firefox-60.7.0esr-60.9.0esr.partial.mar
│       └── update.xml
├── 60.7.2
│   ├── WINNT_x86_64-msvc-x64
│   │   ├── firefox-60.7.2esr-60.9.0esr.partial.mar
│   │   └── update.xml
│   └── WINNT_x86-msvc-x64
│       ├── firefox-60.7.2esr-60.9.0esr.partial.mar
│       └── update.xml
├── 60.8.0
│   ├── WINNT_x86_64-msvc-x64
│   │   ├── firefox-60.8.0esr-60.9.0esr.partial.mar
│   │   └── update.xml
│   ├── WINNT_x86-msvc-x64
│   │   ├── firefox-60.8.0esr-60.9.0esr.partial.mar
│   │   └── update.xml
│   └── WINNT_x86-msvc-x86
│       └── update.xml
├── 60.9.0
│   ├── WINNT_x86_64-msvc-x64
│   │   ├── firefox-60.9.0esr-68.2.0esr.partial.mar
│   │   └── update.xml
│   ├── WINNT_x86-msvc-x64
│   │   ├── firefox-60.9.0esr-68.2.0esr.partial.mar
│   │   └── update.xml
│   └── WINNT_x86-msvc-x86
│       ├── firefox-60.9.0esr-68.2.0esr.partial.mar
│       └── update.xml
├── 68.1.0
│   └── WINNT_x86-msvc-x86
│       ├── firefox-68.1.0esr-68.2.0esr.partial.mar
│       └── update.xml
├── 68.2.0
│   ├── WINNT_x86_64-msvc-x64
│   │   ├── firefox-68.2.0esr-68.3.0esr.partial.mar
│   │   └── update.xml
│   ├── WINNT_x86-msvc-x64
│   │   ├── firefox-68.2.0esr-68.3.0esr.partial.mar
│   │   └── update.xml
│   └── WINNT_x86-msvc-x86
│       ├── firefox-68.2.0esr-68.3.0esr.partial.mar
│       └── update.xml
├── 68.3.0
│   ├── WINNT_x86_64-msvc-x64
│   │   ├── firefox-68.3.0esr-68.4.1esr.partial.mar
│   │   └── update.xml
│   ├── WINNT_x86-msvc-x64
│   │   ├── firefox-68.3.0esr-68.4.1esr.partial.mar
│   │   └── update.xml
│   └── WINNT_x86-msvc-x86
│       ├── firefox-68.3.0esr-68.4.1esr.partial.mar
│       └── update.xml
├── 68.4.1
│   ├── WINNT_x86_64-msvc-x64
│   │   ├── firefox-68.4.1esr-68.6.0esr.partial.mar
│   │   └── update.xml
│   ├── WINNT_x86-msvc-x64
│   │   ├── firefox-68.4.1esr-68.6.0esr.partial.mar
│   │   └── update.xml
│   └── WINNT_x86-msvc-x86
│       ├── firefox-68.4.1esr-68.6.0esr.partial.mar
│       └── update.xml
├── 68.6.0
│   ├── WINNT_x86_64-msvc-x64
│   │   ├── firefox-68.6.0esr-68.8.0esr.partial.mar
│   │   └── update.xml
│   ├── WINNT_x86-msvc-x64
│   │   ├── firefox-68.6.0esr-68.8.0esr.partial.mar
│   │   └── update.xml
│   └── WINNT_x86-msvc-x86
│       ├── firefox-68.6.0esr-68.8.0esr.partial.mar
│       └── update.xml
├── 68.7.0
│   └── WINNT_x86_64-msvc-x64
│       ├── firefox-68.7.0esr-68.9.0esr.partial.mar
│       └── update.xml
├── 68.8.0
│   ├── WINNT_x86_64-msvc-x64
│   │   ├── firefox-68.8.0esr-68.9.0esr.partial.mar
│   │   └── update.xml
│   ├── WINNT_x86-msvc-x64
│   │   ├── firefox-68.8.0esr-68.9.0esr.partial.mar
│   │   └── update.xml
│   └── WINNT_x86-msvc-x86
│       ├── firefox-68.8.0esr-68.9.0esr.partial.mar
│       └── update.xml
├── 68.9.0
│   ├── WINNT_x86_64-msvc-x64
│   │   └── update.xml
│   └── WINNT_x86-msvc-x64
│       └── update.xml
└── index.php
```
Get correct version of MAR files here : https://ftp.mozilla.org/pub/firefox/releases/

Last touch is to create the correct update.xml file. here an example for update a firefox 68.8.0 64 bits on windows 64bits to 68.9.0 : 

```
<?xml version="1.0" encoding="UTF-8"?>
<updates>
    <update type="minor" displayVersion="Firefox 68.9.0esr" appVersion="68.9.0esr" platformVersion="68.9.0esr" buildID="20200527211442" detailsURL="https://www.mozilla.org/fr-FR/firefox/68.9.0/releasenotes/">
        <patch type="partial" URL="http://ffupdate.ch-boscamnant.org/68.8.0/WINNT_x86_64-msvc-x64/firefox-68.8.0esr-68.9.0esr.partial.mar" hashFunction="sha512" hashValue="3426ca177bfd6df336d9eb328dec24d8536634e3afef806c15f2c81f392bd34d6979b5c9d3597f9b1facf5908a97910524e25e14b88beb2adc0b8e8015be0b32" size="6945429"/>
    </update>
</updates>
```

use `ls -l `to get the correct size of the MAR file and `sha512` sum to correct sum. Ther is juste one thing I'm not 100% sure : the "Build ID".

last thing : it seems to have bug if a new version is available on Mozilla Server and you don't create folder with the last version on your internal server. See hehre : https://github.com/mozilla/policy-templates/issues/496

**Comment by red-erik** [comment]
@pierre-guillot : Thank you for sharing your configuration, but the problem is to avoid FF from downloading updates from aus5.mozilla.org.
I don't want to have such a complex configuration for every single release of FF but I want to be sure my client get ONLY the MAR file I publish on our internal Webserver.
This way I have to mantain a single .MAR and a single .XML and publish it after an "internal validation" on our infrastructure.
Regards,
Red.

P.S. I have a similar configuration on IIS and is working as expected. The "Build ID" is available in "about:support" and I did not find a public repository with all FF build ID list.

**Comment by pierre-guillot** [comment]
Sorry i skimmed the issue :)

> P.S. I have a similar configuration on IIS and is working as expected. The "Build ID" is available in "about:support" and I did not find a public repository with all FF build ID list.

Thank you for this information.

> I want to be sure my clients get ONLY the MAR

It's strange because I use custom update URL and my client doesn't connect to mozilla server to download newer update (other than there in my local server). In my GPO, "Disable update" is set to "Not Configured"

**Comment by red-erik** [comment]
Hello,
the same for me "not configured" but FF downloads updates from Mozilla too...and this prevent me to have complete control over the update process.
By the way, did you apply GPO to "user" or "computer"  branch ?

**Comment by pierre-guillot** [comment]
> By the way, did you apply GPO to "user" or "computer" branch ?

Yes ; My GPO is configured on "computer" branch.

Currently, I'm configuring new update.xml to download Firefox 68.11.0 on my client.

So, before today, my clients doesn't updates firefox to 68.11.0 or 78esr.

Maybe you can avoid the problem by configuring a rewrite rule on your apache like describe here : https://mike.kaply.com/2007/03/26/deploying-firefox-2-within-the-enterprise-part-5/  ?

**Comment by red-erik** [comment]
Hello,
any news on this topic ? I confirm that a system WITHOUT internet access is upgrading fine from our internal web server while an internet connected machine is downloading and installing updates from Mozilla. We are using the SAME GPO

Off-line machine:
60.6.3--> BuildID:20190507003026
60.9.0--> BuildID:20190901094603
68.2.0--> BuildID:20191016163237
68.5.0--> BuildID:20200206211857
68.9.0--> BuildID:20200527211442
78.1.0--> BuildID:20200722151235

On-line machine:
60.6.3--> BuildID:20190507003026
60.9.0--> BuildID:20190901094603-->From Mozilla
68.11.0-->BuildID:20200720181548-->From Mozilla

All documented in "update history". 
@mkaply : Any suggestion will be greatly appreciated.

Red.

**Comment by red-erik** [comment]
Hello,
finally I solved the problem. The GPO setting "custom Update Url" is available under "User Configuration" and "Computer Configuration". In my company, quite ALL GPO are user based so I configured this one as a "User Configuration" withous succes. As soon I configured it under "Computer Configuration" everything is started working as expected.
Thank you all for the help.

Regards,
red.
