### ISSUE TITLE
Hide first run banner/new tab section?

### ISSUE THREAD

**Issue by Bangaio65** [mozilla/policy-templates#657]
On first run, I get a banner asking to join Firefox. Also in the new tab page there's a "Welcome to Firefox" section on the top that can be closed. (I'm installing it in Spanish so that may not be that exact phrasing in English)

Version: 68.11.0 esr

Is there any way to disable both of these so that they don't show up?

**Comment by mkaply** [comment]
If you turn off the first run page by setting this policy to blank:

https://github.com/mozilla/policy-templates/blob/master/README.md#overridefirstrunpage

It will go away.

**Comment by Bangaio65** [comment]
Great, that worked. Thanks for the quick reply!
