### ISSUE TITLE
v79 Policy Clarification - PrimaryPassword & DisableMasterPasswordCreation

### ISSUE THREAD

**Issue by apizz** [mozilla/policy-templates#658]
2 things:

**1)**

Given the addition in the [2.1 release](https://github.com/mozilla/policy-templates/releases/tag/v2.1) of `PrimaryPassword`, I think it would pertinent when you say ...

> ... If this value is false, it works the same as DisableMasterPasswordCreation and removes the primary password functionality.

... this should also indicate the value of `DisableMasterPasswordCreation` needing to be enabled/true.  Something like:

> If this value is false, it works the same as DisableMasterPasswordCreation _(when set to true)_ and removes the primary password functionality.

Likewise, I think `DisableMasterPasswordCreation` policy description should also include something like the below to reinforce this fact.

> If this value is true, it works the same as PrimaryPassword (when set to false) and removes the primary password functionality.

**2)**

Say an admin includes `PrimaryPassword` and `DisableMasterPasswordCreation` in management and are configured differently.  Which preference is preferred / wins out?  If one does then I think this should be documented as well.

**Comment by mkaply** [comment]
Good comments. Done. Thanks.
