### ISSUE TITLE
UserMessaging (ExtensionRecommendations) not working

### ISSUE THREAD

**Issue by reorx** [mozilla/policy-templates#660]
Hey Guys,

I'm customizing the Firefox (ESR 68.11.0esr Windows 64-bit) in our organization, I want to disable the Recommendations in about:addons page, so I added the UserMessaging rule in policies.json, which I thought should be the solution for it.

Here's my policies and policies.json:

![image](https://user-images.githubusercontent.com/405972/89196460-d1f16100-d5dc-11ea-9231-9d6bea83e8da.png)

[issue-policies.zip](https://github.com/mozilla/policy-templates/files/5016738/issue-policies.zip)

But the addons page is still recommending extensions for me:

![image](https://user-images.githubusercontent.com/405972/89196341-aa9a9400-d5dc-11ea-8fcf-ce0483773ad9.png)

![image](https://user-images.githubusercontent.com/405972/89196412-bede9100-d5dc-11ea-8006-5b7b38b5c767.png)

I confirm that the other rules in policies.json was working as expected, so I don't understand why UserMessaging wasn't, or it's not what I thought of? please help me with this, thank you :)

**Comment by mkaply** [comment]
Yeah, sorry, that's a little confusing. That's disabling a feature where we recommend extensions as you browse.

To disable that page, set the extensions.getAddons.showPane pref in the Preference policies.

**Comment by reorx** [comment]
Got it, thank you very much!

BTW, the description of UserMessage seems to be wrongly copied from somewhere else:
> Prevent installing search engines from webpages.

**Comment by mkaply** [comment]
Fixed the description. Thanks!
