### ISSUE TITLE
GPO Wish: dom.max_script_run_time (Preference)

### ISSUE THREAD

**Issue by xenothrox** [mozilla/policy-templates#662]
Some of our internal web applications have issues with the default value of "dom.max_script_run_time" (not blaming the browser, it's a webapp development issue). As a workaround we increased the default value of the given preference via CCK2. Is it possible to add this preference as a GPO so we can still use this solution in the future?

**Comment by mkaply** [comment]
I've added this to our internal list. We're actively looking at ways to make more prefs available.

**Comment by mkaply** [comment]
This is settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences
