### ISSUE TITLE
feautre request: network.http.http3.enabled

### ISSUE THREAD

**Issue by Conan1989** [mozilla/policy-templates#669]
Hi,
Request a GPO setting for "network.http.http3.enabled"
cheers

**Comment by mkaply** [comment]
This is settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences

**Comment by Conan1989** [comment]
I'm not able to find this change in the .ADML / .ADMX or in the README.md

**Comment by Conan1989** [comment]
my mistake, sorry. Didn't read the part about the new JSON method
