### ISSUE TITLE
Documentation for Tracking Protection Policies

### ISSUE THREAD

**Issue by altonius** [mozilla/policy-templates#674]
The current examples of the TrackingProtection OMA-URIs are not working as expected.  After ingesting the ADMX file the `./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox/TrackingProtection` OMA-URI and the example string values don't work.

Rather you have to use the following OMA-URIs that are not referenced in the README.md, but are present in the ADMX file.
```

./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~TrackingProtection/A_TrackingProtection_Value
./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~TrackingProtection/B_TrackingProtection_Cryptomining
./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~TrackingProtection/C_TrackingProtection_Fingerprinting
./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~TrackingProtection/D_TrackingProtection_Exceptions
./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~TrackingProtection/E_TrackingProtection_Locked
```

**Comment by mkaply** [comment]
Thanks for this. What happened is I moved TrackingProtection to a category and so the Intune is wrong.

Fixing.

**Comment by mkaply** [comment]
To be clear, I left the old in place and added the new. I'm going to document the new in the README.md

**Comment by altonius** [comment]
Thanks for such a quick response and update!
