### ISSUE TITLE
Mixing Policy Templates 1.17 and 2.x

### ISSUE THREAD

**Issue by StFIT** [mozilla/policy-templates#677]
Hi, I'm wondering what does this mean in the release notes:
Note: While these templates will work for Firefox ESR68, they contain new policies that are not in Firefox ESR 68. If you need to manage Firefox ESR 68, you should use v1.17
Especially the last sentence. Does this mean that ESR 68 does not work with policy templates 2.x?
We have a few users testing ESR 78 and want to test 2.x
The policy templates are in a global setting so they will work right away for all users.
What should/can we do?
Thanks.

**Comment by mkaply** [comment]
You can definitely use the 2.x templates with ESR 68.

The only issue is that if you use some of the new policies, 68 will show an error in about:policies (but still work properly).

Nothing has been removed, only added.
