### ISSUE TITLE
Incorrect JSON syntax for ExtensionSettings Intune OMA-URI

### ISSUE THREAD

**Issue by NZSysAdmin** [mozilla/policy-templates#679]
I have been having issues trying to apply a Firefox Extensions policy using the documentation provided. There is an error with the syntax for the Intune OMA-URI value string documentation. I copy and pasted the example and tried to apply it just to see if it would work, the policy applies but if you browse to about:policies in Firefox (80.0.1) it says there is a JSON error.

https://github.com/mozilla/policy-templates/blob/master/README.md#extensionsettings

Here is an example of my working one compared to the documentation, the problem is that the everything between value the ' markers after value= needs to also be wrapped between two curly brackets for the JSON syntax to be correct.

<enabled/> <data id="ExtensionSettings" value='{"*":{"blocked_install_message":"This extension will need to be approved by IT before it can be installed. Please contact your friendly IT team who can review this extension for you.","installation_mode": "blocked"},"webrootsecure@webroot.com":{"installation_mode":"allowed"},"firefox@ghostery.com":{"installation_mode":"allowed"},"jid1-93WyvpgvxzGATw@jetpack":{"installation_mode":"allowed"},"ciscowebexstart1@cisco.com":{"installation_mode":"allowed"}}'/>

**Comment by mkaply** [comment]
Thanks for catching that. Sorry about that.
