### ISSUE TITLE
Question: Cookie AllowSession

### ISSUE THREAD

**Issue by theroch** [mozilla/policy-templates#683]
The description is:
AllowSession is a list of origins (not domains) where cookies are only allowed for the current session. You must include http or https.

If I correctly understand the setting for cookie AllowSession then lifetime for every cookie fof an origin ends if I close the browser!?

But if it so, the feature doesn't work correctly in FF 80.0.1.
I have configured "https://my.site.local". But the session cookie for "https://my.site.local/test" is after closing and starting FF again still active.

Did I do something wrong or did I misunderstand AllowSession?

**Comment by mkaply** [comment]
I  just ran a quick check with Firefox 80 and it's working for me.

I added https://mike.kaply.com to AllowSession and then I visited mike.kaply.com. The cookies were there, but when I restarted, they were gone.

If I didn't have mike.kaply.com in AllowSession, the cookies persisted.

I'm not sure why you are seeing different behavior...

**Comment by theroch** [comment]
Ok, I've added now https://github.com/ to AllowSession but it is the same behavior, the session persist after restarting the browser.
I've tested this with several applications on different sites (nextcloud, open project, confluence) the session persists allways, don't know why?

My browser is configured to reload the last session after restart, maybe this is related to the issue?

**Comment by mkaply** [comment]
> My browser is configured to reload the last session after restart, maybe this is related to the issue?

Just ran a quick test and this does appear to be the case. When you restore the session, you're also restoring the session cookies.

**Comment by theroch** [comment]
But if this is the problem, why takes the setting ExpireAtSessionEnd=1 effect?
If I enable this feature all the cookies are expired after restarting the browser.
I think the behavior of this two options should be the same!?
If ExpireAtSessionEnd is enabled all the cookies should expire (which is actual so) and if AllowSession is enabled, all the cookies of the configured origins should expire after restarting the browser.

So I think, the actual behavior is a bug!?

**Comment by mkaply** [comment]
I think you're right. I'm looking into it.

It's a core Firefox behavior unrelated to policies.

**Comment by mkaply** [comment]
I've opened this bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1666895

We'll see what the answer is.

Worst case, I can add code to clear cookies for the session domains at startup.

**Comment by mkaply** [comment]
So this is being tracked in Bugzilla, there's nothing to do here. Unfortunately there's no movement, but that's the best place for this discussion,

**Comment by mkaply** [comment]
Unfortunately there has been no movement on the bug.

I'm curious how you set this up in Edge/Chrome? Maybe I can use that to justify to the team why we should do it.

**Comment by belsholff** [comment]
It's sad...

I just enable a policy in Windows GPO
https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#cookiessessiononlyforurls - EDGE
https://chromium.googlesource.com/playground/chromium-org-site/+/6cfcc327e21c6a782ee282a4787e308215bd0df8/administrators/policy-list-3/index.md#cookiessessiononlyforurls - Chrome/Chromium

**Comment by mkaply** [comment]
We looked at the code and this should work.

The problem is the definition of a session.

**Comment by mkaply** [comment]
Interesting:

If the “RestoreOnStartup” policy is set to restore URLs from previous sessions this policy will not be respected and cookies will be stored permanently for those sites.

**Comment by theroch** [comment]
Can you reopen this discussion, please, so we have a clear state of this issue.

**Comment by mkaply** [comment]
Yes, I'm working with the team. Looking at the code, it should be working.

**Comment by belsholff** [comment]
> Interesting:
> 
> If the “RestoreOnStartup” policy is set to restore URLs from previous sessions this policy will not be respected and cookies will be stored permanently for those sites.

RestoreOnStartup only affects Edge/Chrome abrupt crashes, isn't?

It does not affect "Open Previous Tabs and Windows", I guess.

**Comment by mkaply** [comment]
> RestoreOnStartup only affects Edge/Chrome abrupt crashes, isn't?

> It does not affect "Open Previous Tabs and Windows", I guess.

Based on the text of the policy, it affects everything.

So essentially if you are set to restore on startup, what you are saying is "everything one session"

When a user restores all previous tabs and windows, they expect sessions to be restored as well.

This policy will only work (on Chrome, Edge and Firefox) is if you do not restore windows/tabs on startup.


I've tested this in Firefox, and this policy is working properly. But the policy has to be active before the cookies are set. It doesn't affect existing cookies. It causes the cookies for a given domain to be set as session only when they are set.

You can test this with this extension:

https://addons.mozilla.org/en-US/firefox/addon/cookie-quick-manager/

Create a new profile, and then go to mozilla.org

Using that extension, you can see that cookies for mozilla.org and www.mozilla.org are set but the are not session cookies.

Then set this policy:

```
{
  "policies": {
    "Cookies": {
      "AllowSession": ["https://mozilla.org", "https://www.mozilla.org"]
    }
  }
}
```
Create a new profile and go to mozilla.org

Then you can use the extension again and see that the cookies that were not session cookies before are now session cookies.

**Comment by belsholff** [comment]
I've been testing here using FF 130 to my Google case.

First, I unselected "Open Previous Tabs and Windows"  in about:preferences. I checked about:config too;
Second, I cleaned all Google's cookies in about:preferences;
Third, I checked 

> ```
> {
>   "policies": {
>     "Cookies": {
>       "AllowSession": ["https://mozilla.org", "https://www.mozilla.org"]
>     }
>   }
> }
> ```
equivalent to Google's case using about:policies and got the same as shown here before.
Fourth, I logged in to my Google Account, did some stuff and then closed my browser.
Fifth, I ran Firefox and my Google Account was logged in.

For me it didn't seems to be a session concept difference. Maybe, we are seeing some inconsistency cause by config garbage or related. Once you are testing and everything works properly, this is a possibility when we isolate "restore windows/tabs on startup" setting.

For instance, I got the last GPO files available to download.

**Comment by mkaply** [comment]
I'll check with a Google account specifically.

**Comment by mkaply** [comment]
Here's my policies.json
```
{
  "policies": {
    "Cookies": {
      "AllowSession": ["https://google.com", "https://accounts.google.com"]
    }
  }
}
```
I verified that if I login to my google account, close the browser, and restart, I'm logged out of google.

All of the google cookies were set to session cookies.

This has to be unchecked for this to work:

![image](https://github.com/user-attachments/assets/1b155263-fdf5-44e9-8870-380716949656)

I definitiely think there is more we can do here to be like Edge/Chrome, but the basics seem to work

**Comment by belsholff** [comment]
Thanks @mkaply for helping and re-testing everything! 
I will reset some firefox installations to factory defaults and check if some garbage seems to be cleaned.

**Comment by mkaply** [comment]
So tab pinning uses the session restore mechanism.

So by pinning it, you've effectively said "this session should persist across Firefox invocations.

I assume Google doesn't do this?

**Comment by belsholff** [comment]
Yeah, Chromium-like behave as I was expecting...

Please allow me some opinion here...
When I pin tabs I'm telling browser this tab should stay at tablist beginning and must be opened at Firefox starts. Here I do not expect a session persistence. This is expected after browser crashes or enabled in about:preferences.

Thanks @mkaply! I know you are not responsible for Firefox session concepts 😉 

Firefox understands can't help me specifically. I going to apply a cookie total cleaning. This is too much, but that what I expect.

**Comment by mkaply** [comment]
Yeah, I think it's just a side effect. I a way, it's similar to the Google thing where they say "restore these URLs at startup"

Does Google clear the cookies for pinned tabs?

**Comment by belsholff** [comment]
> Does Google clear the cookies for pinned tabs?

Yes. Edge and Chrome.
