### ISSUE TITLE
GPO wish: disable about:preferences

### ISSUE THREAD

**Issue by SB97** [mozilla/policy-templates#684]
I would like to disable access to all Preferences to provide a constant experience on all Computers.

**Comment by 3rd3** [comment]
I am also looking for a solution to this. I've tried setting up a filter like this, however, to no avail.

    "WebsiteFilter": {
      "Block": ["about:preferences"]
    }

**Comment by 3rd3** [comment]
I also do not seem to be able to disable access to addon configurations by blocking `moz-extension://*`. Such a website filter is also ignored.

**Comment by mkaply** [comment]
That's correct, the website filter Is mainly about websites.

What exactly is your usecase? If you need to do this, I would recommend using other tools like autoconfig to do this kind of blocking.

**Comment by 3rd3** [comment]
I would like to lock down Firefox as much as possible because it is on a PC used by multiple users. It should **not** run in fullscreen mode, so kiosk mode is not suitable.

It seems tedious to specify all preference items though, especially if they are going to change in future. Simply hiding the settings menu item or access to the settings would be the best solution.

**Comment by SB97** [comment]
> I would like to lock down Firefox as much as possible because it is on a PC used by multiple users. It should **not** run in fullscreen mode, so kiosk mode is not suitable.

My current workaround is to delete the profile folder on logon with a Script. It keeps everything clean, but it's a stupid solution.

**Comment by mkaply** [comment]
We have no plans to provide this level of customizability via policy. You could look into using userChrome.css to do this.

**Comment by 3rd3** [comment]
Then you'd have the "Welcome to Firefox" pages loading each time, or were you able to override that with the Homepage policy item?

**Comment by mkaply** [comment]
We have a policy to stop the first run pages.
