### ISSUE TITLE
Force title bars display?

### ISSUE THREAD

**Issue by lachlan-00** [mozilla/policy-templates#686]
In citrix 2019 i can't get it to load the window without title bars enabled. i was looking for it in your policy list but it doesn't seem to be available?

**Comment by mkaply** [comment]
That's odd because Firefox defaults to not having titlebars, so they shouldn't appear unless customized.

There's no policy for this because no one had requested before :)

**Comment by lachlan-00** [comment]
That's almost surprising! 
I've always enabled them again for myself but now with this bug in Citrix it would be a really good policy to be able to enable/enforce.

**Comment by lachlan-00** [comment]
The bug in Citrix itself I've tracked back to title bars. The window seems to load and disappear randomly and I was able to somehow tab and click into customisation and tick it. (Then I untucked it and can't do it again)

But as a policy it would be really good to have displaytitlebar like the menu bar which is the reason for this issue. :)

**Comment by mkaply** [comment]
Are you going to report the bug to Citrix?

**Comment by lachlan-00** [comment]
yeah, i've got a support ticket with them through our vendor

**Comment by mkaply** [comment]
So with our new Preferences support, you can set this. The preference is:

browser.tabs.drawInTitlebar

See:

https://github.com/mozilla/policy-templates/blob/master/README.md#preferences
