### ISSUE TITLE
[Questions] New Preference Policy behaviour with FF 81 / FF ESR 78.3.0

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#687]
With FF 81 and FF ESR 78.3.0 you have added new preferences policies.

1. Is it necessary to update/change our GPOs when updating to FF ESR 78.3.0?
2. The preferences now can be set to a specific state. I understand that "locked" blocks the setting against changes, "default" sets the default value which can be changed local and "clear" makes the setting empty. But what does the state "user" mean?

**Comment by mkaply** [comment]
> Is it necessary to update/change our GPOs when updating to FF ESR 78.3.0?

Yes, I'll be releasing new GPOs that support the new preferences policies later today.

> But what does the state "user" mean?

It sets the value as if a user had changed the value. This allows these preferences to persist across restarts which is important for preferences that are needed early in startup like setting the cache directory.

**Comment by htcfreek** [comment]
> It sets the value as if a user had changed the value. This allows these preferences to persist across restarts which is important for preferences that are needed early in startup like setting the cache directory.

Here the documentation should be more precise. And I would prefer that such special policies have a extra hint within their description.

Are the preferences locked too, when the state is set to user? For me it makes no sense that locked preferences didn't persist across restarts.

**Comment by mkaply** [comment]
> Here the documentation should be more precise. And I would prefer that such special policies have a extra hint within their description.

I'll update the docs a little more before I release. It does currently say:

"User preferences persist across invocations of Firefox."

> Are the preferences locked too, when the state is set to user? For me it makes no sense that locked preferences didn't persist across restarts.

No. Locked preferences are default prefs and do not persist across restarts. The only prefs that persist are user prefs. The other prefs "persist" in the sense that they are set at startup each time.

But user prefs persist even if the policy is removed (which is why the clear policy exists).

Most of the people that have requested this are people that have had a deep understanding of how preferences work from using Autoconfig which is why I mapped to the existing terminology.

**Comment by htcfreek** [comment]
> > Are the preferences locked too, when the state is set to user? For me it makes no sense that locked preferences didn't persist across restarts.
> 
> No. Locked preferences are default prefs and do not persist across restarts. The only prefs that persist are user prefs. The other prefs "persist" in the sense that they are set at startup each time.

Now I understand that. Thanks for the explanation.


> But user prefs persist even if the policy is removed (which is why the clear policy exists).

This is something important you should mention in the docs to.

**Comment by mkaply** [comment]
> This is something important you should mention in the docs to.

done.

And I just published the new GPOs.
