### ISSUE TITLE
Homepage Setting behaviour changed with 2.3 GPO and FF 78 ESR

### ISSUE THREAD

**Issue by StFIT** [mozilla/policy-templates#690]
We set the Homepage to our Intranet and users should not change this.
So we locked this setting.
Startpage was also set to Homepage.
This worked with FF 68 ESR but not with FF 78 ESR.
Is it because the new option for locking the homepage, but still allowing the user to choose whether or not they want to restore their session?
How can we get back to the old behaviour?

**Comment by mkaply** [comment]
Yes, that's the reason, but you can get back the old behavior. 

"With Firefox 78, an additional option as added for Startpage, homepage-locked. This allows for locking the homepage, but still allowing the user to choose whether or not they want to restore their session."

So if you change Startpage to homepage-locked, you should get the old behavior.

**Comment by StFIT** [comment]
Yes, that does the job. Thank you.
And sorry. I thought I tested this already but obviously not.
