### ISSUE TITLE
browser.bookmarks settings don't work with GPO 2.3

### ISSUE THREAD

**Issue by StFIT** [mozilla/policy-templates#691]
Does Preferences (Deprecated) mean all Preferences in there are deprecated?
We used the now called Preferences (Deprecated) for e.g.
browser.bookmarks.autoExportHTML setting to true.
This worked for GPO 1.17 but not for GPO 2.3
browser.bookmarks.file still works even with GPO 2.3

**Comment by mkaply** [comment]
That wasn't my plan, but because of a bug, I broke boolean legacy preferences in 78.3 and 81 (that's why .file works - it's a string). That's also the source of your other issues.

I have a fix that I'm trying to get into Firefox ASAP, but for now the only workaround is to use the new preferences.

I'm very sorry for the problem.

**Comment by StFIT** [comment]
We tried to use the new preferences.
Software\Policies\Mozilla\Firefox\Preferences (REG_MULTI_SZ) =
{
  "browser.bookmarks.autoExportHTML": {
    "Value": true,
    "Status": "user"
  }
}
That does not work.
Preference is still "false"

This is what the browser console says:
Enterprise Policies: Error running  
function onBeforeAddons()
 for onBeforeAddons: 
Exception
?
columnNumber: 0
?
data: null
?
filename: "resource:///modules/policies/Policies.jsm"
?
lineNumber: 2023
?
location: XPCWrappedNative_NoHelper { QueryInterface: QueryInterface(), filename: Getter, name: Getter, … }
?
message: "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.setIntPref]"
?
name: "NS_ERROR_UNEXPECTED"
?
result: 2147549183
?
stack: "setDefaultPref@resource:///modules/policies/Policies.jsm:2023:16\nsetAndLockPref@resource:///modules/policies/Policies.jsm:1990:17\nonBeforeAddons@resource:///modules/policies/Policies.jsm:1488:25\n_runPoliciesCallbacks@jar:file:///C:/Program%20Files/Mozilla%20Firefox/omni.ja!/components/EnterprisePolicies.js:214:9\nBG_observe@jar:file:///C:/Program%20Files/Mozilla%20Firefox/omni.ja!/components/EnterprisePolicies.js:263:14\n"
?
<prototype>: ExceptionPrototype { toString: toString(), name: Getter, message: Getter, … }
EnterprisePolicies.js:216

**Comment by mkaply** [comment]
That looks like you're still setting the old value as well. You need to do one or the other. And if you want the old behavior, it should be:
```
{
"browser.bookmarks.autoExportHTML": {
"Value": true,
"Status": "locked"
}
}
```
I ran a quick test and it was working.

**Comment by StFIT** [comment]
We had to delete all boolean entrys in Preferences (Deprecated) first not only the browser.bookmarks.autoExportHTML.
Now we switched to the new Preferences with all our changes and everything seems to work fine.
Nothing left in Preferences (Deprecated) :)
Thank you!
