### ISSUE TITLE
GPO Wishlist: Disable 'Customize...'

### ISSUE THREAD

**Issue by sshowers** [mozilla/policy-templates#692]
It would be nice to have a GPO option that would disable the 'Customize...' entry under "Open Menu" and when you right-click the navigation bar.  I apologize if this has been batted around already but a quick search didn't return any previous requests.

**Comment by mkaply** [comment]
I'm working on this in bugzilla.

https://bugzilla.mozilla.org/show_bug.cgi?id=1461047
