### ISSUE TITLE
GPO Wish : PrintingEnabled

### ISSUE THREAD

**Issue by KeithIMyers** [mozilla/policy-templates#695]
In some enterprise environments, it is a requirement to disable printing, even if a printer is not installed, many systems have a print to PDF option.

Example of how Chrome does this - https://www.chromium.org/administrators/policy-list-3#PrintingEnabled

**Comment by ret394** [comment]
same issue is a 'valid use' scenario in many non-enterprise environments. 

Please keep up with your customer feedback, Firefox team. Increase Firefox adoption not decrease it in reference to the UI changes on Firefox bugzilla. I'll post about off-topic issue in a separate thread.

---

The chrome link, in my opinion is not strictly necessary, if it is meant as an indicator of the feature set's popluarity. 

And regardless of security(?) requirements, you do want to allow users to print to PDF. Please do correct me if I'm wrong. 
SPOILER -

**Comment by KeithIMyers** [comment]
No, I would want to block all printing including PDF

**Comment by gregorypappas** [comment]
This policy was added in Firefox 120 ([bug 1854298](https://bugzilla.mozilla.org/show_bug.cgi?id=1854298)).

**Comment by mkaply** [comment]
I'm going to close this issue since it's in Bugzilla.
