### ISSUE TITLE
GPO Wish: layout.spellcheckDefault

### ISSUE THREAD

**Issue by it-hand** [mozilla/policy-templates#696]
In our educational environment, it is a requirement to disable the spell checker so as not to influence the results. This option is availaible on Edge and Chrome.

**Comment by mkaply** [comment]
This is available via the new Preferences API:

https://home.newtabgallery.com/weather.php?lat=30.560300827026367&lon=-97.79862976074219

You can set any value under layout.

Are you using policies.json or GPO? I can explain how to use.

**Comment by it-hand** [comment]
Hi @mkaply , I use the GPO to configure our environment, If you have something to guide me... thank you!

**Comment by mkaply** [comment]
Sure.

So we have a new option in the GPO called Preferences (not the category, a new top level thing). It's just a big entry field that accepts JSON.

If you paste this in there:

{
  "layout.spellcheckDefault": {
    "Value": 0,
    "Status": "locked"
  }
}

It will turn off spellcheck completely and lock it off.

The values you can use are:
// 0 = spellcheck nothing
// 1 = check multi-line controls [default]
// 2 = check multi/single line controls

**Comment by sergiorishass** [comment]
Hello.
I have a similar but opposite situation: I need that "Check Spelling" option in context menu in Firefox appears always enabled for all user sessions, and furthemore, I have installed 2 dictionaries that I also want that they appears always enabled for all user sessions. I attach images.
What code should I write inside the JSON file? Thanks.
<img width="72" alt="Check Spelling Firefox" src="https://user-images.githubusercontent.com/124602943/217029958-3b3a0a06-3668-40d7-b744-a084caec3ee9.PNG">
<img width="144" alt="Dictionaries" src="https://user-images.githubusercontent.com/124602943/217029963-c2254301-c8dd-4754-a31a-4c8c096ccdd5.PNG">
