### ISSUE TITLE
GPO/FF wish: update interval with random delay

### ISSUE THREAD

**Issue by red-erik** [mozilla/policy-templates#697]
Hello,
we need to have something to tell FF to check for updates and to effectively update with random time interval.
This is because we need to use and internal update server but don't want 8k client trying to update in the same moment (at browser start, usually when user power on pc in the morning).
We can solve the problem of "update server" congestion using a load balancer and multiple update servers but we need to face the "network congestion problem" too.
I found something here
https://www.ghacks.net/2014/06/09/change-firefoxs-automatic-update-behavior/
but I'm not so sure it will solve our problem.
An update interval with a random delay (like WSUS client for MS updates) would be fine.
Any help or suggestion will be greatly appreciated.
Regards,

Red.

**Comment by mkaply** [comment]
I talked to the team about this and this is not something on our radar. The way we handle this internally on our servers is that if we are getting too many requests to the update server, it just tells the browser there is no update that then the browser will try again later.

That actually might be the easiest way to solve this. You could randomly (or at some interval), tell some connections that there is no update and they will try again later.

That could be done entirely by the update server.

Are you hosting the downloads themselves on the same server as the update requests?

**Comment by red-erik** [comment]
Hello,
yes, same server but I have not idea on how to configure IIS to randomly deny request of an update.
Anyway, thank you very much for your answer.
Regards,
Red.
