### ISSUE TITLE
Flash content does not open automatically when Allow Flash policy is used

### ISSUE THREAD

**Issue by amasresha** [mozilla/policy-templates#7]
Steps to reproduce:
Screen capture- https://testing-1.tinytake.com/sf/MjQxNzg0NV83MzI0OTQ1

1. Add allow flash content https://www.pizap.com/ to the group policy editor
2. Start the browser
3. Go to https://www.pizap.com/pizap-app.php?initialstate=photo
4.  Observe if flash content opens automatically

Actual Result:
Allowed flash content does not open automatically

Expected Result:
Allowed flash content should be opened automatically

**Comment by amasresha** [comment]
This is still reproducible.  I tested with the same template and the latest  nightly (Build ID: 20180313100127)

**Comment by amasresha** [comment]
Could you please reopen this issue? I could not get "reopen" option.

**Comment by mkaply** [comment]
There was a template change as well. Did you try the new template?

**Comment by amasresha** [comment]
Downloaded today retested it and it is reproducible

**Comment by amasresha** [comment]
It is working now. I had to re-download the template and create a fresh Nightly profile. I tested this on Windows 10  x64 and Window 7 x86 and it verified as fixed. 
Feel free to close it.
