### ISSUE TITLE
GPO/FF security preferences

### ISSUE THREAD

**Issue by starikm** [mozilla/policy-templates#700]
Cant find in GPO Template v2.3 security.insecure_connection_text.enabled and security.insecure_field_warning.contextual.enabled

**Comment by mkaply** [comment]
Those preferences aren't explicitly in the template by name. You have to use the new preferences policy which is a JSON string.

https://github.com/mozilla/policy-templates/blob/master/README.md#preferences

Look for Preferences at the top level GPO.

In that multitext entryfield, you can put:
```
{
  "security.insecure_connection_text.enabled": {
    "Value": true,
    "Status": "default"
  },
  "security.insecure_field_warning.contextual.enabled": {
    "Value": false,
    "Status": "default"
  }
}
```

Or you can use "locked" to lock them
