### ISSUE TITLE
Clarification on changes to 'Preferences' dictionary in v2.3

### ISSUE THREAD

**Issue by apizz** [mozilla/policy-templates#703]
In the 2.3 policy release, the formatting structure for the larger `Preferences` dictionary was changed such that the contained preferences are now themselves dictionaries with the previous preference values/types being transferred to a standard `Value` key.

While the formatting changes for existing preference keys are clear, there were several added keys not listed under the [now deprecated Preferences section](https://github.com/mozilla/policy-templates/blob/v2.3/README.md#preferences-deprecated) and as a result do not have explicitly defined value types or options.

It would helpful to continue explicitly define the keys in a similar fashion to the deprecated Preferences section (https://github.com/mozilla/policy-templates/blob/v2.3/README.md#preferences-deprecated) and which include these new keys.  They are:

- `security.insecure_connection_text.enabled`
- `security.insecure_connection_text.pbmode.enabled`
- `security.insecure_field_warning.contextual.enabled`
- `security.warn_submit_secure_to_insecure`

**Comment by mkaply** [comment]
Are you mainly interested in knowing how to properly defined them (bool) or exactly what they do?

I don't want the README to turn into documentation for all preferences :)

**Comment by mkaply** [comment]
I went ahead and duplicated the pref info into the new section and adding descriptions for these.

**Comment by apizz** [comment]
TY!  Just wanted to confirm that they all were boolean.
