### ISSUE TITLE
ExtensionSettings - order of force_installed extensions

### ISSUE THREAD

**Issue by eMPai-git** [mozilla/policy-templates#705]
## Problem

I had an unexpected behavior with force_installed extensions. It should have installed several extensions but only the first two entries were actually installed. This did work in ESR 68 with the `Extensions` policy. In ESR 78 with `ExtensionSettings` the behavior appeared the first time for me.
The `policies.json`  looked like this:

```
    "ExtensionSettings": {
      "*": {
        "installation_mode": "blocked"
      },
      "jid1-BoFifL9Vbdl2zQ@jetpack": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/decentraleyes/latest.xpi",
        "installation_mode": "force_installed"
      },
      "langpack-de@firefox-esr.mozilla.org": {
        "install_url": "https://releases.mozilla.org/pub/firefox/releases/78.3.1esr/linux-x86_64/xpi/de.xpi",
        "installation_mode": "force_installed"
      },
      "uBlock0@raymondhill.net": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi",
        "installation_mode": "force_installed"
      },
      "{33c93ccc-ceed-47d2-9645-805ea58c8a07}": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/first-party-isolation/latest.xpi",
        "installation_mode": "force_installed"
      }
    },
```

I changed the order and put the languages pack to last place in the list. Now all extensions get installed as expected.

```
    "ExtensionSettings": {
      "*": {
        "installation_mode": "blocked"
      },
      "jid1-BoFifL9Vbdl2zQ@jetpack": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/decentraleyes/latest.xpi",
        "installation_mode": "force_installed"
      },
      "uBlock0@raymondhill.net": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi",
        "installation_mode": "force_installed"
      },
      "{33c93ccc-ceed-47d2-9645-805ea58c8a07}": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/first-party-isolation/latest.xpi",
        "installation_mode": "force_installed"
      },
      "langpack-de@firefox-esr.mozilla.org": {
        "install_url": "https://releases.mozilla.org/pub/firefox/releases/78.3.1esr/linux-x86_64/xpi/de.xpi",
        "installation_mode": "force_installed"
      }
    },
```

## System

- Debian 10.6
- Firefox 78.3.1 and 78.4.0 (updated during testing, behavior on both versions)

**Comment by mkaply** [comment]
I'm seeing this error:

https://releases.mozilla.org/pub/firefox/releases/78.3.1esr/linux-x86_64/xpi/de.xpi had unexpected id (got langpack-de@firefox.mozilla.org expected langpack-de@firefox-esr.mozilla.org)

The ESR doesn't use a different langpack ID, it should be langpack-de@firefox.mozilla.org.

It should have installed the ones after, though. I'll check that.

**Comment by eMPai-git** [comment]
Thank you.

I will change the langpack ID. I cannot remember how I obtained the ID in the first place.

**Comment by mkaply** [comment]
Oddly, I'm seeing all three extensions installed in both cases.

**Comment by eMPai-git** [comment]
Maybe I should do some further testing.

Any hints on how I can help you? I didn't get an error in `about:policies`.

**Comment by mkaply** [comment]
Once you fix the ID, do they all install? Can you check the JS Console and see if there are any errors?

**Comment by eMPai-git** [comment]
It does work with the fixed ID.

I'm getting an error `OfferToSaveLoginsDefault ignored because OfferToSaveLogins is present.`. Probably should have mentioned that in my entry post. I thought this error is unrelated.

**Comment by mkaply** [comment]
That error is definitely unrelated (shouldn't break anything).

If you could try the first one that fails and see if anything comes up on the JS console, that would be great.

**Comment by eMPai-git** [comment]
Ok, here are some new findings:

If I delete the `policies.json` and look into `about:debugging#/runtime/this-firefox` I can see that it loads langpack-de@firefox-esr.mozilla.org by default.

The force_installed langpack-de@firefox.mozilla.org seems to not fully load on first start. Some texts of the UI are not translated. A second start fixes that.
The langpack-de@firefox-esr.mozilla.org seems to be there in this configuration but blocked.

So I changed the ExtensionSettings to allow langpack-de@firefox-esr.mozilla.org. Everything is fine now besides issue #706 

> If you could try the first one that fails and see if anything comes up on the JS console, that would be great.

I did not look into this, yet.

**Comment by mkaply** [comment]
So it looks like Debian is improperly renaming the language packs. I just checked our official language packs and they are definitely langpack-de@firefox.mozilla.org

So if you are installing a language pack from AMO, it should not have the -esr. I have no explanation why using the language pack from AMO isn't working on Debian.

I'm checking into this.

As far as that error goes, that theoretically shouldn't happen, but I'm going to add a check just in case.

**Comment by mkaply** [comment]
So interesting issue. Only debian has the -esr on language packs that come from debian.

So because you're installing language packs from AMO, you should NOT have the -esr on the end. Those are not the IDs when the lang packs come from AMO.

If your URLs were pointing to XPIs on Debian servers, you would use the different ID.

**Comment by eMPai-git** [comment]
So it was a Debian related issue in combination with a wrong langpack ID on my part.

It did some final tests. Here are my conclusions.
Debian 10.6
Installed packages: firefox-esr, firefox-esr-l10n-de

## 1. Behavior with force_installed langpack and wrong ID

```
{
  "policies": {
    "ExtensionSettings": {
      "*": {
        "installation_mode": "blocked",
      },
      "langpack-de@firefox-esr.mozilla.org": {
        "install_url": "https://releases.mozilla.org/pub/firefox/releases/78.4.0esr/linux-x86_64/xpi/de.xpi",
        "installation_mode": "force_installed"
      },
      "uBlock0@raymondhill.net": {
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi",
        "installation_mode": "force_installed"
      }
    }
  }
}
```

- langpack-de@firefox-esr.mozilla.org is the **wrong** ID for given `install_url`
- langpack-de@firefox-esr.mozilla.org.xpi gets activated
- it throws an error `TypeError: addon.sourceURI is null` in `Policies.jsm:2219:1`
- uBlock Extension (in this example) does **not** get installed

## 2. Behavior with force_installed langpack and correct ID

```
{
  "policies": {
    "ExtensionSettings": {
      "*": {
        "installation_mode": "blocked",
      },
      "langpack-de@firefox.mozilla.org": {
        "install_url": "https://releases.mozilla.org/pub/firefox/releases/78.4.0esr/linux-x86_64/xpi/de.xpi",
        "installation_mode": "force_installed"
      }
    }
  }
}
```

- langpack-de@firefox-esr.mozilla.org.xpi gets deactivated
- langpack-de@firefox.mozilla.org.xpi gets installed and activated

![2020-10-30_11-03-08-forced](https://user-images.githubusercontent.com/72030339/97704089-0aa4b780-1ab2-11eb-9d2c-bbdf91861978.png)

- on first start some parts of the UI are not translated

![2020-10-30_10-59-16-forced](https://user-images.githubusercontent.com/72030339/97704238-4d668f80-1ab2-11eb-84d7-cf6c2dae989f.png)

- closing and starting Firefox for a second time fixes that

![2020-10-30_11-07-05-forced-secondstart](https://user-images.githubusercontent.com/72030339/97704288-6a9b5e00-1ab2-11eb-9eea-9d0f0bb2c054.png)

## 3. Behavior with allowed Debian langpack

```
{
  "policies": {
    "ExtensionSettings": {
      "*": {
        "installation_mode": "blocked",
      },
      "langpack-de@firefox-esr.mozilla.org": {
        "installation_mode": "allowed"
      }
    }
  }
}
```

- langpack-de@firefox-esr.mozilla.org.xpi gets activated
- everything is fine

## 4. Behavior with everything blocked

```
{
  "policies": {
    "ExtensionSettings": {
      "*": {
        "installation_mode": "blocked",
      }
    }
  }
}
```


- langpack-de@firefox-esr.mozilla.org.xpi gets deactivated
- no UI translation (as expected)

**Comment by eMPai-git** [comment]
So for me the issue is resolved.
Currently I'm using *3. Behavior with allowed Debian langpack* as that did work best with the pre-installed package `firefox-esr-l10n-de` on my Debian system.
Though I'm wondering why they are renaming the language packs

**Comment by mkaply** [comment]
>  Though I'm wondering why they are renaming the language packs

It's historical going back to the days of IceWeasel and they don't want to risk moving them back (just talked to the maintainer)

FYI I did put in a bug fix based on the behavior you were seeing (the Js error). Thanks for reporting that.
