### ISSUE TITLE
GPO Wish: signon.management.page.breach-alerts.enabled

### ISSUE THREAD

**Issue by shuuryou** [mozilla/policy-templates#707]
Would it be possible to either get a policy that prevents password breach alerts from being enabled (`signon.management.page.breach-alerts.enabled`), or to make the "Preferences" JSON object to also allow `signon.*` to be controlled?

We don't want our user's passwords to be uploaded to a cloud service to check if they're part of a data breach or not. I appreciate that passwords may be uploaded to the cloud service as a one-way irreversible hash, but unfortunately that point is moot in our situation.

Chrome and Edge allow their implementation of this feature to be disabled via a dedicated group policy. Sadly this isn't the case with Firefox and our data protection officer is not pleased (strict "no cloud" policy). We currently deploy Chrome, Edge and Firefox on machines across two continents to give users the right to choose their preferred browser. We try hard to keep them all configured and locked down in the same way as far as that's possible, but we're stuck with Firefox being the odd one out in this case. 😞

**Comment by mkaply** [comment]
I just added the entire signon branch. It will be in the next Firefox and ESR update in a couple weeks.

Do you know the name of the Chrome policy off hand? I might create one with the same name.

**Comment by shuuryou** [comment]
Awesome! Thank you so much!

Here is the policy for Chrome. It's called _Enable leak detection for entered credentials_
Description: https://cloud.google.com/docs/chrome-enterprise/policies/?policy=PasswordLeakDetectionEnabled

Microsoft calls it _Allow users to be alerted if their passwords are found to be unsafe_
Description: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#passwordmonitorallowed
