### ISSUE TITLE
Error in Documentation

### ISSUE THREAD

**Issue by PjotrDeFirst** [mozilla/policy-templates#708]
Hello,

I did just spent some desperate hours trying to "allow" an extension installation using the "ExtensionSettings" policy.
Sadly my problem was an error in your documentation instead of unability on my site =)

The README.md says: The valid strings are **allowed**,blocked,force_installed, and normal_installed.

But it should be: The valid strings are **allow**,blocked,force_installed, and normal_installed.

And it continues with the other mentions of "allowed" instead of "allow" in context of extension management.

Never the less, thanks a lot for all the work commited to this project.

yours sincerly,
Peter

**Comment by mkaply** [comment]
I doublechecked the source code and it's definitely allowed:

https://searchfox.org/mozilla-central/source/browser/components/enterprisepolicies/schemas/policies-schema.json#473
```
 "enum": ["allowed", "blocked", "force_installed", "normal_installed"]
```
https://searchfox.org/mozilla-central/source/browser/components/enterprisepolicies/Policies.jsm#1021
```
extensionSettings[extensionID].installation_mode == "allowed"
```

Can you provide the JSON that you were having trouble with?

**Comment by PjotrDeFirst** [comment]
Hi,

I would realy like to be wrong. But I'm definitly able to reproduce the behaviour =/

My system: 
- Windows 10 1809 Enterprise (fully patched)
- Firefox ESR 68
- configuration via group policy (admx downloaded today)

I'm using the policy "Extension Management"

Correct behaviour A)
- forced installtion of "HTTPS Everywhere" and "German Dictionary"
- user is allowed to install "uBlock"
- all other extensions are forbidden.

Faulty behaviour B):
- forced installation of "HTTPS Everywhere" and "German Dictionary"
- users are able to install every other extension from https://addons.mozilla.org

Configration A (works as wanted):
{
"*": {
    "blocked_install_message": "Besteht eine dienstliche Notwendigkeit, wenden Sie sich bitte an die FGr35",
    "install_sources": ["about:addons","https://addons.mozilla.org/"],
    "installation_mode": "blocked",
    "allowed_types": ["extension","dictionary"]
  },
  "uBlock0@raymondhill.net": {
    "installation_mode": "**allow**",
    "install_url": "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"
  },
 "de-DE@dictionaries.addons.mozilla.org": {
    "installation_mode": "force_installed",
    "install_url": "https://addons.mozilla.org/firefox/downloads/latest/german-dictionary/latest.xpi"
 },
 "https-everywhere@eff.org": {
    "installation_mode": "force_installed",
    "install_url": "https://addons.mozilla.org/firefox/downloads/latest/https-everywhere/latest.xpi"
  }
}


Configuration B (user are allowed to install every extension from store):
{
"*": {
    "blocked_install_message": "Besteht eine dienstliche Notwendigkeit, wenden Sie sich bitte an die FGr35",
    "install_sources": ["about:addons","https://addons.mozilla.org/"],
    "installation_mode": "blocked",
    "allowed_types": ["extension","dictionary"]
  },
  "uBlock0@raymondhill.net": {
    "installation_mode": "**allowed**",
    "install_url": "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"
  },
 "de-DE@dictionaries.addons.mozilla.org": {
    "installation_mode": "force_installed",
    "install_url": "https://addons.mozilla.org/firefox/downloads/latest/german-dictionary/latest.xpi"
 },
 "https-everywhere@eff.org": {
    "installation_mode": "force_installed",
    "install_url": "https://addons.mozilla.org/firefox/downloads/latest/https-everywhere/latest.xpi"
  }
}

PS: As I'm writing this I noticed: we do use an old ESR 68 version of Firefox. Sounds like I need to have a serious discussion with our software manager.  In version 78.4.0 "allow" and "allowed" both works .
Sorry for bothering you...


Yours sincerly,
Peter

**Comment by mkaply** [comment]
I get the same behavior in Firefox 68 with both of your JSON files - uBlock origin is allowed and everything else is blocked.

I do know why allow and allowed both work, though. When we are going to install the addon, we only check for blocked:

https://searchfox.org/mozilla-central/source/toolkit/components/enterprisepolicies/EnterprisePoliciesParent.jsm#405

So anything other than blocked is allowed. This seems to be pointing to a bug in our JSON parser which I'll take a look at.

But I definitely never run into a case where everything is allowed.

When you are in the situation where everything is allowed, can you go to about:policies and see if there are any errors?

What specific version of Firefox 68 are you using?

**Comment by mkaply** [comment]
A couple other things.

1. install_url is unnecessary for "allowed" because you're allowing that ID from anywhere.

2. Because you're only allowing the one ID, you don't need install_sources. Even so, install_sources isn't being honored because of a different bug. I'm looking into that.
