### ISSUE TITLE
GPO wish: App.update.interval and App.update.PromptWaitTime

### ISSUE THREAD

**Issue by red-erik** [mozilla/policy-templates#711]
Hello,
it would be nice to have this policy settings to better control FF update process.
Regards,

Red.

**Comment by samuelcookeact** [comment]
Would also like this option.

**Comment by mkaply** [comment]
I added all the update preferences in https://bugzilla.mozilla.org/show_bug.cgi?id=1656544.

They'll be available in the ESR and regular Firefox in the next two weeks.
