### ISSUE TITLE
PictureInPicture is misdocumented in release v2.5 of README.md as accepting a boolean value in policies.json

### ISSUE THREAD

**Issue by mestriga** [mozilla/policy-templates#713]
When set to a boolean value, policy application fails. The actual implementation expects an object. References below.

Documentation:
https://github.com/mozilla/policy-templates/blob/v2.5/README.md#pictureinpicture

Implementation:
https://github.com/mozilla/gecko-dev/blob/f081504642a115cb8236bea4d8250e5cb0f39b02/browser/components/enterprisepolicies/schemas/policies-schema.json#L913

**Comment by mkaply** [comment]
Thanks. No idea how I did that.
