### ISSUE TITLE
WebsiteFilter still allows downloads

### ISSUE THREAD

**Issue by episodeiv** [mozilla/policy-templates#714]
We have blocked several potentially malicious file extensions by using the WebsiteFilter GPO setting. The user is, however, still able to right click a link and download the file. The documentation states 
> Block websites from being visited.

Which suggests to me that this is working as desired but I'd appreciate some clarification nonetheless. Is this setting supposed to block downloads as well? If not, are there any alternatives built into Firefox to restrict downloads as well?

**Comment by mkaply** [comment]
Yes, that's a bug. I've opened

https://bugzilla.mozilla.org/show_bug.cgi?id=1680095

I'm going to track this there since it's a Firefox issue. Thank sfor reporting.

**Comment by mkaply** [comment]
Also, can you verify this is still working the latest Firefox (both ESR and regular)? I rewrote the blocking code and didn't think about this usecase, but it should still work.

**Comment by episodeiv** [comment]
In 78.5.0esr and 83.0 "save as" is still possible.
