### ISSUE TITLE
GPO Wish: disable user notification to download a fresh copy of Firefox

### ISSUE THREAD

**Issue by red-erik** [mozilla/policy-templates#715]
Hello,
we update Firefox through an internal server so it's always "up to date" according to our decisions but we see
this message and we would like to suppress it. Is it possible ?
![FF_Update](https://user-images.githubusercontent.com/10245160/100347522-cd1a4800-2fe5-11eb-974a-93b3628e2ae5.png)

Regards,

Red.

**Comment by mkaply** [comment]
Can you verify that your internal update server sends out an empty XML when there is no update available versus an error?

It should be
<updates></updates>

**Comment by red-erik** [comment]
Right now is not sending anything because the folder does not exists. I'll try with your suggestion.
I read that something wqas disabled in FF startin from ver 63
https://bugzilla.mozilla.org/show_bug.cgi?id=1505611
https://www.mozilla.org/en-US/firefox/63.0/releasenotes/
"The option to Never check for updates was removed from about:preferences. You can use the DisableAppUpdate enterprise policy as a substitute. "
They suggest to DISABLE updates but is not what I want.

Red.

**Comment by mkaply** [comment]
Yeah, you definitely have to always send at least an empty update or we'll think something is wrong.

**Comment by red-erik** [comment]
Thank you very much, as usual ;-)

Red.
