### ISSUE TITLE
Multiple gpos in Firefox

### ISSUE THREAD

**Issue by schnaggi** [mozilla/policy-templates#719]
Currently I use multiple gpos to deploy a local install xpi to the user's firefox.
With the latest update of admx files it looks like just the last policy will count and applied. In the past it was possible to apply multiple gpos to one machine.
I found no documentation for that.

Windows 10, latest or previous version of Firefox ESR
I use
- set path to xpi
- update enabled, otherwise the xpi updates are not recognised
- uninstall locked

**Comment by mkaply** [comment]
Nothing has changed with regards to this. what do you see in about:policies?

**Comment by schnaggi** [comment]
Hi,

the policy (setting) is not visible there. Just the "basic gpo" for the "basic xpis". The group membership is noticed locally, we are installing the xpis in this way.
If there was no change, the situation is really strange and I have investigate the problem deeper.

**Comment by mkaply** [comment]
Can you post a screenshot? I'm not sure I understand.

**Comment by schnaggi** [comment]
so, finally I was able to get some screenshots. Sorry for the delay.
![gpo1](https://user-images.githubusercontent.com/5303553/117023204-2d31ba80-acf9-11eb-8199-095008d61e99.png)
![gpo2](https://user-images.githubusercontent.com/5303553/117023522-7a159100-acf9-11eb-926c-16bc935718e7.png)
I created these two gpos. The target is a security group in AD.
Some time ago both policies were "combined" to one and all settings were visible on the client if it is in both AD groups.
I will add a screenshot of about:policies in the near future.

**Comment by mkaply** [comment]
All we do is query the values from the Windows registry:

HKEY_CURRENT_USER\SOFTWARE\Policies\Mozilla\Firefox
and
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox

So if they aren't combined there, we wouldn't know how to do some combination.

If you definitely believe this used to work, you can use

https://mozilla.github.io/mozregression/

to see if we can figure out what version of firefox it broke in, but I don't know of any code we have that reads multiple locations and combines them.

**Comment by schnaggi** [comment]
It is not a problem of Firefox. The mentioned registry keys show the same result as in firefox.
It looks like just one policy is allowed. Any other is replaced. Enforcing seems not to work.

**Comment by mkaply** [comment]
Can I close this?

**Comment by schnaggi** [comment]
> Can I close this?

If this is the wanted behaviour. I think there should be some other options to deploy extension with multiple gpos.

**Comment by mkaply** [comment]
I'm not sure what we can do to change this behavior in Firefox.

Where would we read the other GPOs from?

The only location is the Firefox policies in the registry.

If any combining of the GPOs would be done, it would be done by some other tool before putting the info in the registry.

**Comment by schnaggi** [comment]
I don't know it is possible to create a manual counter in the admx.
The current possibility is to create one gpo for all addins but if someone get the values, any addin could be installed be the user if it is outside of %ProgramFiles% or %ProgramFIles(x86)%

**Comment by mkaply** [comment]
Sorry, I'm not following.
