### ISSUE TITLE
GPO Preferences and Intune

### ISSUE THREAD

**Issue by mvanlaar** [mozilla/policy-templates#720]
The Preference browser.privatebrowsing.autostart is not working or not supported in admx and intune versions of the 2.5 policy version. Are the other options to configure this prefenence through intune?

**Comment by mkaply** [comment]
Can you be more specific? You can set it via the new Preferences policy via Intune:

https://github.com/mozilla/policy-templates/blob/master/README.md#preferences

But generally this isn't a pref that folks mess with.

It does need be set a user pref to really work properly.

**Comment by mvanlaar** [comment]
Yes i try to set it through intune as a preference. In the locked state, But i get a "remedition failed" error on this setting. Also this preference is also not in de admx. So it is possible thats the error genereted by intune.

**Comment by mkaply** [comment]
It looks like a typo in the Intune doc

<data id="Preferences" value='

should be

<data id="JSON" value='

With this change, it's working for me locally.

**Comment by mkaply** [comment]
Were you able to verify this?

**Comment by mvanlaar** [comment]
Yes it works now
