### ISSUE TITLE
Trust Evaluate Failure for MacOS

### ISSUE THREAD

**Issue by mobilejon** [mozilla/policy-templates#725]
When running FireFox with policies and trying to use certificate-based authentication, it prompts you for keychain access because it states "MissingIntermediate" certificate and throwing a trust evaluate failure

**Comment by mobilejon** [comment]
![IntemediateCertIssue](https://user-images.githubusercontent.com/40245473/102802468-b10b8b80-4384-11eb-9282-af84603f1e49.PNG)

**Comment by mkaply** [comment]
This would be a core Firefox issue and not policies specifically. Can you open a bug here:

https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Security%3A%20PSM

Also pinging @mozkeeler just in case they have any ideas.

**Comment by mozkeeler** [comment]
Specifically which policies are you using?

**Comment by mobilejon** [comment]
This isn’t even a policy issue I guess.

macOS gets keychain prompts on install because signature issues

**Comment by mkaply** [comment]
Are you setting security.osclientcerts.autoload to true?

**Comment by mkaply** [comment]
Can I close this then?
