### ISSUE TITLE
Have Authentication language match other "URL" entry sections.

### ISSUE THREAD

**Issue by jeff-bb** [mozilla/policy-templates#73]
Eg how flash handles it.  Here is an example for NTLM --

Was -- "List of sites trusted to use NTLM authentification."

Suggested Change -- 
"If this policy is enabled, NTLM authentication is activated by default for the URLS indicated. If a top level domain is specified (http://example.org), NTLM authentication is allowed for all subdomains as well.

If this policy is disabled or not configured, the default NTLM authentication policy is followed."

If nothing else, correct the "authentification" typo

**Comment by mkaply** [comment]
Sorry, I'm in the middle of rewriting everything to have the better language. The original language was placeholder language. I'll get those finished up today.

**Comment by HeiHei90** [comment]
@jeff-bb the TLD in your example is .org not example.org. Correct me If i am wrong. You can use .org .de .whatever as wildcards.

**Comment by mkaply** [comment]
Yes, that's technically true. TLD means "the .com part"

**Comment by mkaply** [comment]
I've updated the text in

https://github.com/mozilla/policy-templates/pull/78

Can y'all take a look before I checkin?
