### ISSUE TITLE
Can't enable Preferences parameters thru GPO 

### ISSUE THREAD

**Issue by EugeneFlash** [mozilla/policy-templates#731]
Hi,

I'm trying to deploy
`

Software\Policies\Mozilla\Firefox\Preferences (REG_MULTI_SZ) ={  "network.dns.disableIPv6": {    "Value": true,    "Status": "locked"  },  "network.http.spdy.websockets": {    "Value": false,    "Status": "locked"  }}
--

`
And get an error

`

JSON string couldn't be parsed
Object expected but not received
Invalid parameters specified for Preferences.
--

`

What's wrong?

**Comment by mkaply** [comment]
I just ran a test with your values and it's working for me.

what version of Firefox are you using?

Are you setting the registry values explicitly or using GPEDIT.MSC?

Do you have a Preferences Category as well (the old preference model)

Can you export your Firefox registry category and send it to me?

**Comment by EugeneFlash** [comment]
Hi,
 - The version is 83.0 by Frontmotion (https://www.frontmotion.com/firefox/download/);
 - GPEDIT.MSC;
 - All the parameters in Preferences (Deprecated) are "Not Configured";
 - Attached.
[firefox.zip](https://github.com/mozilla/policy-templates/files/5864716/firefox.zip)

**Comment by mkaply** [comment]
You have 
```
Software\Policies\Mozilla\Firefox\Preferences (REG_MULTI_SZ) =
{
  "network.dns.disableIPv6": {
    "Value": true,
    "Status": "locked"
  },
  "network.http.spdy.websockets": {
    "Value": false,
    "Status": "locked"
  }
}
```
You need to remove the Software\Policies\Mozilla\Firefox\Preferences (REG_MULTI_SZ) = part.

It should just be:
```
{
  "network.dns.disableIPv6": {
    "Value": true,
    "Status": "locked"
  },
  "network.http.spdy.websockets": {
    "Value": false,
    "Status": "locked"
  }
}
```

**Comment by mkaply** [comment]
I see where the documentation could be misinterpreted. I'll fix.
