### ISSUE TITLE
FR: WebsiteFilterUrl downloading a blocklist file

### ISSUE THREAD

**Issue by mimi89999** [mozilla/policy-templates#735]
Hello,
The current `WebsiteFilter` is very limited. Besides the 1000 entries limit, it's difficult to quickly and automatically update it. Would it be possible to download the rules from a url, cache them and periodically check for rule updates?

**Comment by mkaply** [comment]
That's by design. It's for simple blocking or allowing of URLs.

If you need to have more complex blocking, you can use a proxy server or even an autoconfig script.

**Comment by mimi89999** [comment]
Thanks for your reply. Autoconfig seems interesting, but the config script also can't be set through GPO and what's even worse, there is very little doc on how to use it.

**Comment by mkaply** [comment]
Sorry, I said autoconfig when I meant Proxy Autoconfig:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file

You can configure this file with policy.

http://www.ericphelps.com/scripting/samples/PAC/index.htm talks about blocking sites with it.
