### ISSUE TITLE
Windows 10 finds the license file potentially harmful and blocks it

### ISSUE THREAD

**Issue by cyberravn** [mozilla/policy-templates#737]
OS: Windows 10 Pro N, version 20H2

When extracting policy_templates_v2.7, received below Windows Security Warning:

Windows found that this file is potentially harmful. To help protect your computer, Windows has blocked access to this file.

Name: LICENSE

![image](https://user-images.githubusercontent.com/13557263/107525197-984d7400-6b84-11eb-9747-7f21bcecd9a2.png)

**Comment by mkaply** [comment]
I don't even know what to do about that one. It's the MPL :)

**Comment by cyberravn** [comment]
Not sure if this is an issue encountered by others or if it stems from some configuration specific to this machine. I submitted it as a false positive to Microsoft through their [security intelligence page](https://www.microsoft.com/en-us/wdsi/filesubmission/). Submission # 02462f64-77df-448b-ab2c-0121455ab8b0

**Comment by mkaply** [comment]
Thanks. I submitted as well and we also noticed some weirdness with VirusTotal misidentifying it as a DLL so I submitted it to them as well.

OK if I close?

**Comment by cyberravn** [comment]
Needed to add one more thing, something I should have checked before creating this ticket. Although the warning message is only about the license file, the OS blocks access to all of the files extracted from the policy_templates_v2.7.zip archive except the README.md.

Other than that I am OK with this being closed. Thank you.

**Comment by cyberravn** [comment]
Further checking onto this I found that the reaction by Windows OS does not happen if the downloaded archive is "unblocked". Meaning, in order to keep Windows from deleting the extracted files:
1. Right-click on policy_templates_v2.7.zip and select Properties
2. At the bottom under the "General" tab, click on "Unblock"
3. Click OK

After above steps the archive can be extracted without issues.
