### ISSUE TITLE
DisableAppUpdate doesn't work

### ISSUE THREAD

**Issue by ineuw** [mozilla/policy-templates#738]
My version was FF 84.0.2. In Windows 10 Pro, I added a new user and when I started Firefox, it forced the FF update to 85.0.2.  The attached is my my .reg file renamed to .txt since .reg files cannot be attached.

[210212-windows-firefox-policies.txt](https://github.com/mozilla/policy-templates/files/5974799/210212-windows-firefox-policies.txt)

**Comment by mkaply** [comment]
Sorry, finally got to look at this.

I'm not able to recreate this, but I'm curious about the user scenario.

Your registry settings are per user so if you created a new user, they wouldn't get those settings. You would need to make themn machine specific in the registry to apply to all users.

**Comment by ineuw** [comment]
This is a single user desktop. I had this same happened a few days ago. I was doing a fresh install of FF 86.0.1, the registry settings for FF were already in place and as soon as I opened Firefox to configure it, the update to v87 kicked in.  Here is the link to the thread at Mozillazine http://forums.mozillazine.org/viewtopic.php?f=38&t=3073184. The update issue is my 4th post dated Sun Mar 28, 2021 6:06 pm.

**Comment by mkaply** [comment]
Because this isn't going to be a policy specific, I think you'll need to open a bug in bugzilla so the team can help debug:

https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Application%20Update

**Comment by ineuw** [comment]
Thanks. My best course is to repeat and document every step to see what happens and then I will open a bug report.
