### ISSUE TITLE
ESR 78.8: Preventing Privacy Policy tab and "Welcome to Firefox" launching on first run

### ISSUE THREAD

**Issue by rewritten1** [mozilla/policy-templates#740]
I am using Firefox ESR 78.8. I tried using the settings in the comments of issue #640 but I am still seeing the "Welcome to Firefox" on a fresh Firefox profile creation. What settings do I have to change in about:config to remove both privacy policy tab and "Welcome to Firefox" section?

Thanks.

**Comment by mkaply** [comment]
What exactly are you setting?

You need to set OverrideFirstRunPage to an empty string and use the Preferences policy to set datareporting.policy.dataSubmissionPolicyBypassNotification to true

**Comment by rewritten1** [comment]
Hi there,
After some testing, I got it working using the following _about:config_ preferences:
_firefox.cfg_ contents
```
pref("startup.homepage_welcome_url", "")
pref("trailhead.firstrun.didSeeAboutWelcome", true)
pref("datareporting.policy.dataSubmissionPolicyBypassNotification", true)
```
Then, applied the Firefox Windows registry policy, _DisableFirefoxAccounts_, by setting _HKLM\Software\Policies\Mozilla\Firefox\DisableFirefoxAccounts_ to **0**. This prevented the "Welcome to Firefox" message from appearing on first run in the new tab.

Thank you for pointing out that I could of used _OverrideFirstRunPage_, too.

**Comment by mkaply** [comment]
> This prevented the "Welcome to Firefox" message from appearing on first run in the new tab.

That's because we set "browser.aboutwelcome.enabled" to false because there was no way to get rid of the sync panel.

https://searchfox.org/mozilla-central/source/browser/components/enterprisepolicies/Policies.jsm#568

You might want to set that instead of the trailhead pref because it's more likely to stick around.
