### ISSUE TITLE
Allowing ports with GPO

### ISSUE THREAD

**Issue by itzo17** [mozilla/policy-templates#741]
Hello there,

I have tryed to push a policy which is allowing ports diffrent than 80 or 443 in Firfox 86. I know there is the possibility in about:config with network.security.ports.banned.override and the port value, but i want to deploy this for a range of users. I dont find any way to do it  in the GPO Templates. What are my options?

Thanks in Advance

**Comment by mkaply** [comment]
You can set this preferences using the Preferences policy:

https://github.com/mozilla/policy-templates/blob/master/README.md#preferences

{
  "network.security.ports.banned.override": {
    "Value": "X1,X2,X2",
    "Status": "default"
  }
}
