### ISSUE TITLE
ExtensionSettings is {}, eventhough its populated at the DC

### ISSUE THREAD

**Issue by angela-d** [mozilla/policy-templates#742]
I tried to use the 'fixed' code mkaply supplied here: https://github.com/mozilla/policy-templates/issues/539 and that sample yielded the same problem (**ExtensionSettings** is blank):

![aboutpolicies](https://user-images.githubusercontent.com/33108490/110833087-a9f86900-8261-11eb-8bf5-0b23138312b1.png)

I am not using policies.json, but I *am* using an `adminSettings` registry to control which lists are deployed for uBlock Origin (this works) - wondering if this is interfering with the ExtensionSettings option?

uBlock registry:
![ublock-registry](https://user-images.githubusercontent.com/33108490/110833446-0c516980-8262-11eb-8f70-274f6a36dade.png)

content of that registry key:
- Update
- Path: `SOFTWARE\Mozilla\ManagedStorage\uBlock0@raymondhill.net`
- Data:
```text
C:\ProgramData\uBlockOrigin\uBlockOriginConfig.json
```

Content of `C:\ProgramData\uBlockOrigin\uBlockOriginConfig.json`:
```json
{
 "name": "uBlock0@raymondhill.net",
 "description": "Custom list deployment",
 "type": "storage",
 "data": {
    "adminSettings": "{\"selectedFilterLists\":[\"ublock-badware\",\"ublock-abuse\",\"urlhaus-1\",\"spam404-0\"]}"
 }
}
```

If this is superseding, what would be the recommended approach to be able to pre-approve what extensions users can install and block any of those not referenced?

**Comment by mkaply** [comment]
That ublock config definitely wouldn't affect that. Seems like a problem with the Extension Settings policy.

Can you post (or send me) exactly what you have in the ExtensionSettings JSON? I'll debug - mkaply at mozilla.com

I would think something would show up in an error page though.

**Comment by angela-d** [comment]
If anyone else is running into this problem, @mkaply pointed out I had stray commas in my json.

I ran my output through https://jsonlint.com/ and sure enough it was error-riddled.


I updated my GPO to the fixed syntax, but still not getting any errors on `about:policies` and **ExtensionSettings** is still `{}`

In the registry, this value is showing blank (from a client machine that receives the policy):
![target-machine](https://user-images.githubusercontent.com/33108490/110860570-8bef3080-8282-11eb-845f-c2fec654d8de.png)

Is this the correct path?

**Comment by mkaply** [comment]
Well that's interesting. ExtensionSettings shouldn't be it's own category. It should be under Firefox:

Mine looks like this:

![image](https://user-images.githubusercontent.com/345868/110863211-f81f6380-8285-11eb-8d29-b23af854898c.png)

**Comment by mkaply** [comment]
https://github.com/mozilla/policy-templates/blob/master/windows/firefox.admx#L945

**Comment by angela-d** [comment]
Mystery solved!

My problem was two-fold:
1. I had typos in my json
2. Because the json policy wasn't working, I experimented adding the json directly to the registry to see if it would show -- it appears I did one-level too far in my test and created that object

Once I deleted that object, the policy worked!

Thank you for your assistance!

**Comment by mkaply** [comment]
Glad we figured it out!
