### ISSUE TITLE
Application Handlers will not apply

### ISSUE THREAD

**Issue by franzpro** [mozilla/policy-templates#746]
Hi,
I have created a GPO with application handlers. The GPO is applied and the Json Code is displayed in about:policies. 
But the set application handlers are not applied to Firefox.

Do the GPO handlers work only with the ESR version? can someone give me a tip? 

thx

**Comment by mkaply** [comment]
Can you post a screenshot of what you are seeing in about:policies and what is showing up in the Application section of Firefox Settings?

**Comment by xstelios** [comment]
I confirm the issue on firefox 82.0 (64-bit)

**Comment by xstelios** [comment]
OK. I finally made it work. I had to type the parameter in just one line.

**Comment by xstelios** [comment]
Now, I have another question.

This parameter: {"mimeTypes":{"application/msword":{"action":"useSystemDefault","ask":false}}}  is for Microsoft Word 97-2003 documents.

What is the parameter for Microsoft Word?  (after 2003 versions)

![Screenshot 2021-03-19 143819](https://user-images.githubusercontent.com/17723977/111780928-bc594f00-88c0-11eb-97bb-139ae0297cad.jpg)

**Comment by xstelios** [comment]
Ok. I found this answer too. 

vnd.openxmlformats-officedocument.wordprocessingml.document

Thanks for your help.. :))

**Comment by franzpro** [comment]
Can someone give me an example of how to set "PDF" to "open in Firefox"? My settings are still ignored.

**Comment by mkaply** [comment]
> Can someone give me an example of how to set "PDF" to "open in Firefox"? My settings are still ignored.

Unfortunately because of the way some sites serve PDFs, that won't work right now. See - https://bugzilla.mozilla.org/show_bug.cgi?id=1659794

> OK. I finally made it work. I had to type the parameter in just one line with no spaces.

That's odd. We specifically support a multiline string for this. I'll check.

As far as finding out types, the easiest way is to configure it in Firefox and then look at the file "handlers.json" in your profile directory. The format is similar to the policy so you can get the info from there.

**Comment by franzpro** [comment]
Sorry for the Delay. But PDF File are shown in Firefox, but the GPO handler are not apply.

I tried the handler like this:
"mimeTypes":{"application/pdf":{"action":3,"extensions":["pdf"]}

i expected the result like this.
![23-03-_2021_11-12-12](https://user-images.githubusercontent.com/33352129/112130584-ebc1d180-8bc8-11eb-9d8d-ddf2b7b9616e.jpg)

but for a new PC it is still on "save to disc"

Franz

**Comment by mkaply** [comment]
@franzpro That's not the format for Handlers in policy. See:

https://github.com/mozilla/policy-templates/blob/master/README.md#handlers

action should be saveToDisk, useHelperApp, or useSystemDefault.

extensions is a separate category.

**Comment by franzpro** [comment]
Hi, but that is exactly what is saved in the handlers.json File in my Firefox Profile and this works for PDF Files.
I think I understand this somehow wrong or am somehow on the wrong track :-(

Franz

**Comment by mkaply** [comment]
The Handlers policy is similar but not the same as the data in handlers.json, so you'll need to convert that to the syntax used for the Handlers policy.

I think the problem you're running into though is that 3 means "use internally" so you're trying to force Firefox to open all PDFs which won't work due to a Firefox bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1659794) combined with the fact that a lot of sites force PDFs to download so they don't open in Firefox.

You can use an extension like this:

https://addons.mozilla.org/firefox/addon/no-pdf-download/

which will force PDFs that are marked as "download" to be opened in Firefox.

**Comment by mkaply** [comment]
That sounds like the MULTI_SZ is not working correctly. I just used local group policy and the JSON parse. I can't attach a reg file, but I've pasted it below.

<code>
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Policies\Mozilla\Firefox]
"Handlers"=hex(7):7b,00,00,00,09,00,22,00,6d,00,69,00,6d,00,65,00,54,00,79,00,\
  70,00,65,00,73,00,22,00,3a,00,20,00,7b,00,00,00,09,00,09,00,22,00,61,00,70,\
  00,70,00,6c,00,69,00,63,00,61,00,74,00,69,00,6f,00,6e,00,2f,00,78,00,2d,00,\
  6a,00,61,00,76,00,61,00,2d,00,6a,00,6e,00,6c,00,70,00,2d,00,66,00,69,00,6c,\
  00,65,00,22,00,3a,00,20,00,7b,00,00,00,09,00,09,00,09,00,22,00,61,00,63,00,\
  74,00,69,00,6f,00,6e,00,22,00,3a,00,20,00,22,00,75,00,73,00,65,00,48,00,65,\
  00,6c,00,70,00,65,00,72,00,41,00,70,00,70,00,22,00,2c,00,00,00,09,00,09,00,\
  09,00,22,00,61,00,73,00,6b,00,22,00,3a,00,20,00,66,00,61,00,6c,00,73,00,65,\
  00,00,00,09,00,09,00,7d,00,00,00,09,00,7d,00,2c,00,00,00,09,00,22,00,73,00,\
  63,00,68,00,65,00,6d,00,65,00,73,00,22,00,3a,00,20,00,7b,00,00,00,09,00,09,\
  00,22,00,6d,00,61,00,69,00,6c,00,74,00,6f,00,22,00,3a,00,20,00,7b,00,00,00,\
  09,00,09,00,09,00,22,00,61,00,63,00,74,00,69,00,6f,00,6e,00,22,00,3a,00,20,\
  00,22,00,75,00,73,00,65,00,48,00,65,00,6c,00,70,00,65,00,72,00,41,00,70,00,\
  70,00,22,00,2c,00,00,00,09,00,09,00,09,00,22,00,61,00,73,00,6b,00,22,00,3a,\
  00,20,00,66,00,61,00,6c,00,73,00,65,00,2c,00,00,00,09,00,09,00,09,00,22,00,\
  68,00,61,00,6e,00,64,00,6c,00,65,00,72,00,73,00,22,00,3a,00,20,00,5b,00,7b,\
  00,00,00,09,00,09,00,09,00,09,00,22,00,6e,00,61,00,6d,00,65,00,22,00,3a,00,\
  20,00,22,00,47,00,6d,00,61,00,69,00,6c,00,22,00,2c,00,00,00,09,00,09,00,09,\
  00,09,00,22,00,75,00,72,00,69,00,54,00,65,00,6d,00,70,00,6c,00,61,00,74,00,\
  65,00,22,00,3a,00,20,00,22,00,68,00,74,00,74,00,70,00,73,00,3a,00,2f,00,2f,\
  00,6d,00,61,00,69,00,6c,00,2e,00,67,00,6f,00,6f,00,67,00,6c,00,65,00,2e,00,\
  63,00,6f,00,6d,00,2f,00,6d,00,61,00,69,00,6c,00,2f,00,3f,00,65,00,78,00,74,\
  00,73,00,72,00,63,00,3d,00,6d,00,61,00,69,00,6c,00,74,00,6f,00,26,00,75,00,\
  72,00,6c,00,3d,00,25,00,73,00,22,00,00,00,09,00,09,00,09,00,7d,00,5d,00,00,\
  00,09,00,09,00,7d,00,00,00,09,00,7d,00,2c,00,00,00,09,00,22,00,65,00,78,00,\
  74,00,65,00,6e,00,73,00,69,00,6f,00,6e,00,73,00,22,00,3a,00,20,00,7b,00,00,\
  00,09,00,09,00,22,00,6a,00,6e,00,6c,00,70,00,22,00,3a,00,20,00,7b,00,00,00,\
  09,00,09,00,09,00,22,00,61,00,63,00,74,00,69,00,6f,00,6e,00,22,00,3a,00,20,\
  00,22,00,75,00,73,00,65,00,48,00,65,00,6c,00,70,00,65,00,72,00,41,00,70,00,\
  70,00,22,00,2c,00,00,00,09,00,09,00,09,00,22,00,61,00,73,00,6b,00,22,00,3a,\
  00,20,00,66,00,61,00,6c,00,73,00,65,00,2c,00,00,00,09,00,09,00,09,00,22,00,\
  68,00,61,00,6e,00,64,00,6c,00,65,00,72,00,73,00,22,00,3a,00,20,00,5b,00,7b,\
  00,00,00,09,00,09,00,09,00,09,00,22,00,6e,00,61,00,6d,00,65,00,22,00,3a,00,\
  20,00,22,00,6a,00,70,00,32,00,6c,00,61,00,75,00,6e,00,63,00,68,00,65,00,72,\
  00,2e,00,65,00,78,00,65,00,22,00,2c,00,00,00,09,00,09,00,09,00,09,00,22,00,\
  70,00,61,00,74,00,68,00,22,00,3a,00,20,00,22,00,43,00,3a,00,5c,00,5c,00,50,\
  00,72,00,6f,00,67,00,72,00,61,00,6d,00,20,00,46,00,69,00,6c,00,65,00,73,00,\
  5c,00,5c,00,4a,00,61,00,76,00,61,00,5c,00,5c,00,6a,00,72,00,65,00,31,00,2e,\
  00,38,00,2e,00,30,00,5f,00,33,00,32,00,31,00,5c,00,5c,00,62,00,69,00,6e,00,\
  5c,00,5c,00,6a,00,70,00,32,00,6c,00,61,00,75,00,6e,00,63,00,68,00,65,00,72,\
  00,2e,00,65,00,78,00,65,00,22,00,00,00,09,00,09,00,09,00,7d,00,5d,00,00,00,\
  09,00,09,00,7d,00,00,00,09,00,7d,00,00,00,7d,00,00,00,00,00
</code>

There is one error in that file - you can't specify useHelperApp for the mime type without specifying a handler.
