### ISSUE TITLE
Preferences: Restore default search engines overrides GPO set default

### ISSUE THREAD

**Issue by HeiHei90** [mozilla/policy-templates#75]
After our Tests it seems like after hitting "Restore Default Search Engines" the Search Engine set via GPO is permanently overwritten. Closing FF and starting it again won't help either. 
Especially for encapsulated business environments with own Search Engine and no direct access to the internet, this would probably help to be fixed.

It would also be helpful, if you could lock the "Restore Default Search Engines" for Users.

**Comment by mkaply** [comment]
Restore Default Engines only applies if you have hidden engines (which we don't have the ability to do).

Can you provide a little more context as to what happened here?

**Comment by HeiHei90** [comment]
1. Configure own search engine (SharePoint search)
2. Set it as default search engine
... Everything works fine
3. User fires "restore default search engine" 
...Mozillas default search engine is set. So far so good.
4. Close FF and start it again
... assumption: own search engine, set via Gpo, is default search engine again, but this ist not the case. 

It would probably be enough, if we were able to disable the "reset default...." Button.

**Comment by mkaply** [comment]
That policy is only designed to set the default engine once. It respects user choice if they want to change the search engine. In this case, the user changed the default engine, so it wouldn't get changed back.

**Comment by HeiHei90** [comment]
Remove built in engines/disable reset button. Whatever's easier to achieve. I am a little worried, that if we remove builtin engines, we encounter different problems, but let's see.

**Comment by mkaply** [comment]
> Remove built in engines/disable reset button. Whatever's easier to achieve. I am a little worried, that if we remove builtin engines, we encounter different problems, but let's see.

CCK already provided this, so it seems logical.

**Comment by mkaply** [comment]
We've added the remove capability. I've opened a bug to discuss your other questions

https://bugzilla.mozilla.org/show_bug.cgi?id=1471727

**Comment by HeiHei90** [comment]
Lovely! Thank you. Anything I can or should do?

**Comment by HeiHei90** [comment]
Because this feature request is implemented and will be available soon, I'll close this issue.
