### ISSUE TITLE
fr-FR adml file error

### ISSUE THREAD

**Issue by archtest** [mozilla/policy-templates#752]
Hi,

There is a small mistake on french adml version in the last release, this is the only langage file with no revision number to "2.9".
When imported in PolicyDefinition folder, an error occured to read firefox template.

Could you change the revision number?

policy-templates/windows/fr-FR/firefox.adml

Actual
```xml
<?xml version="1.0" encoding="utf-8"?>
<policyDefinitionResources revision="2.8" schemaVersion="1.0" >
 ```

Corrected
```xml
<?xml version="1.0" encoding="utf-8"?>
<policyDefinitionResources revision="2.9" schemaVersion="1.0" >
 ```

Regards

**Comment by mkaply** [comment]
I am very sorry. I should have tested better. the ZIP has been updated.
