### ISSUE TITLE
ManualAppUpdateOnly is the same policy as AppAutoUpdate?

### ISSUE THREAD

**Issue by Scribe-uk** [mozilla/policy-templates#753]
This is outside my area of expertise so apologies if this seems naive, but the policy for the recently added **ManualAppUpdateOnly** seems to me to be exactly the same as **AppAutoUpdate**. Is that correct?

**Comment by mkaply** [comment]
No, with AppAutoUpdate, there are still nag dialogs. ManualAppUpdateOnly removes all places where we encourage the user to update and only update if they choose to go to the about dialog.

See:

https://bugzilla.mozilla.org/show_bug.cgi?id=1653430 for more info.

**Comment by Scribe-uk** [comment]
What I didn't understand was why the **ManualAppUpdateOnly** policy code, has the line "AppAutoUpdate" and not "ManualAppUpdateOnly", since "AppAutoUpdate" is the same line that is used in the **AppAutoUpdate** policy, which of course does a completely different thing. But anyway thanks for taking the time to look at it.

**Comment by mkaply** [comment]
Sorry, that was just a mistake on my part when cut and pasting. I'll fix. Thanks for noticing this.

**Comment by Scribe-uk** [comment]
You're welcome.
