### ISSUE TITLE
Allowing wildcards for setting permissions associated with camera, microphone, etc.

### ISSUE THREAD

**Issue by StFIT** [mozilla/policy-templates#754]
We need to set multiple urls like
one.something.com
two.something.com
...
*.something.com don't work
something.com just works for something.com

**Comment by mkaply** [comment]
Unfortunately we removed this in Firefox 42 and there's no easy way to do it with our new origin based handling.

See:

**Comment by mkaply** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1249889

This would be a Firefox bug, not something specifically with permissions.
