### ISSUE TITLE
Relaunch Notification for Mac

### ISSUE THREAD

**Issue by angela-d** [mozilla/policy-templates#755]
In [the plist](https://github.com/mozilla/policy-templates/blob/master/mac/org.mozilla.firefox.plist), is `AppAutoUpdate` similar to `RelaunchNotification` on Chrome?

 [RelaunchNotification](https://support.google.com/chrome/a/answer/7679871):
> Tells users to relaunch Chrome Browser or restart their device ... to get the latest update. 

In Windows there's an updater daemon but I'm not privy to anything like that on Mac.  It's my understanding the browser will only check for updates while it's open?  

With `AppAutoUpdate` enabled, it'll update itself and prompt for a restart.. but only if Firefox is running, correct?

Is there a better way to keep Firefox updated on Macs, short of having to maintain versions via MDM or expect the user to touch Firefox before new updates get applied?

**Comment by mkaply** [comment]
> In the plist, is AppAutoUpdate similar to RelaunchNotification on Chrome?

There's no way to force a message to the user, it just uses our normal update message.

> With AppAutoUpdate enabled, it'll update itself and prompt for a restart.. but only if Firefox is running, correct?

Correct

> Is there a better way to keep Firefox updated on Macs, short of having to maintain versions via MDM or expect the user to touch Firefox before new updates get applied?

There is not. We're working on background updaters but we don't have anything concrete to share yet.

**Comment by angela-d** [comment]
Thank you!

Background updates would be an excellent addition.
