### ISSUE TITLE
Policy Control Request: security.ssl3.rsa_des_ede3_sha

### ISSUE THREAD

**Issue by athias** [mozilla/policy-templates#763]
### Requirement:
Ability to disable deprecated ciphers through policy.

### Justification:
While reviewing the DISA STIG: V5,R1, 22 Jan 2021 - A rule was identified that does not have an ability to be controlled by GPO or policies.json.

### Reference:
```
Vul ID: V-223177
Rule ID: SV-223177r612236_rule
STIG ID: DTBF235
```

### Details of Request:
Enabled the GPO and policies.json capabilities to disable deprecated ciphers.
Specifically identified the setting `security.ssl3.rsa_des_ede3_sha` as being unable to control through policies

**Comment by mkaply** [comment]
It is able to be controlled through policy.

It's:

TLS_RSA_WITH_3DES_EDE_CBC_SHA

in:

https://github.com/mozilla/policy-templates/blob/master/README.md#disabledciphers

I'll make sure this method is referenced in the new STIG.

**Comment by athias** [comment]
Much Appreciated!
