### ISSUE TITLE
Policy Control Request: plugin.disable_full_page_plugin_for_types

### ISSUE THREAD

**Issue by athias** [mozilla/policy-templates#764]
### Requirement:
Ability to control prompt when downloading and opening specific file types

### Justification:
While reviewing the DISA STIG: V5,R1, 22 Jan 2021 - A rule was identified that does not have an ability to be controlled by GPO or policies.json.

### Reference:
```
Vul ID: V-223158
Rule ID: SV-223158r612236_rule
STIG ID: DTBF110
```

### Details of Request:
Enabled the GPO and policies.json capabilities to control prompts when downloading specific file types.
Specifically identified the setting `plugin.disable_full_page_plugin_for_types` as being unable to control through policies.

**Comment by mkaply** [comment]
This preference is no longer used by Firefox since we don't support plugins. It's being removed from the STIG (I'm working on that).
