### ISSUE TITLE
webgl.force.enabled requiered

### ISSUE THREAD

**Issue by xenothrox** [mozilla/policy-templates#766]
Hello,

first of all - I know that this topic came up multiple times and that it is probably a 'won't fix', but maybe you can help me analyze the current behavior. I've also read the already closed issues to that topic.

Again, it's all about looking for an easy way to set webgl.force.enabled to 'true'. I know that the user is able to set it via about:config (which is the workaround at the moment), but I have to look for a central solution so I can at least respond to our internal inquiry with a professional statement whether it's possible or not.

Our developer team works with a software called 'Rancher' (rancher.com). The software offers the use of a shell program, called 'kubectl shell'. This part of the whole software works only if "webgl.force.enabled" is manually set to 'enabled'.

I've tried to collect further information about the technical details and copied the context of the 'graphics section' via about:support (as webgl should work out of the box). I've attached two different 'logs' from the section, one shows the content if a user is logged on to the system directly (local), the second one shows the content if the user is logged on to the system via remote desktop connection (Windows RDP).

Important: without manually adding 'webgl.force.enabled', the shell doesn't work on any of the systems, even if the graphics section looks alright (tested with ESR 78.8.0).
I expected the feature to run out of the box as I can't see any problems within the 'graphics' section (locally logged on), that's the reason why I bring this topic up again.
[Graphics_rdp_connected.txt](https://github.com/mozilla/policy-templates/files/6434061/Graphics_rdp_connected.txt)
[Graphics_local.txt](https://github.com/mozilla/policy-templates/files/6434063/Graphics_local.txt)

I've got a feeling that this is more a bug of the Rancher software itself than of Firefox, but I'm not quite sure as I don't work with the software, so if you just say "there's always a reason why webgl is automatically set to 'disabled' and it's not caused by the browser" this would be fine for me as well.

If you need any further information (configuration details etc.) please let me know.

**Comment by mkaply** [comment]
It looks like webgl is failing because of FEATURE_FAILURE_UNKNOWN_DEVICE_VENDOR

I'm checking with our graphics team to see why this is happening.

In the meantime, I'll see about adding webgl to add policy.

**Comment by jdashg** [comment]
Does Rancher use RDP? I know nothing about Rancher, nor how a shell program interacts with Firefox. Can you tell me more?

**Comment by xenothrox** [comment]
Additional information to the attached "graphics content" (to point out the details a bit more)

Both content files were taken from the same computer. 

The 'local' one shows every possible information pretty fine (without any errors I guess, FEATURE_FAILURE_UNKNOWN_DEVICE_VENDOR not visible if I'm right) -> the shell doesn't work out of the box, only if webgl.force.enabled is set to 'true'

The 'rdp_connected' one shows lots of errors like it is not possible to read any information about the local hardware -> the shell doesn't work out of the box, only if webgl.force.enabled is set to 'true' (which is fine in my opinion as the device can't be recognized correctly, so webgl gets disabled.

In both cases, Rancher is started via Firefox (probably link or desktop shortcut), like this:

Case A: directly logged on to 'computer B' -> start Firefox / open Rancher

Case B: directly logged on to 'computer A' -> Remote Desktop Connection to 'Computer B' -> start Firefox / open Rancher

So the Rancher software is always started on the specific computer, they don't use the RDP to directly call Rancher if I got that right.

I'll make sure to talk to one of our developers to get at least some content via the F12/developer tools, maybe there is something listed that tells some details. I don't work with Rancher at all, just found two articles on rancher.com explaining how to install this shell, how it basically works (related to control the connected servers) and which commands could be used, but nothing about the browser interaction.

**Comment by mkaply** [comment]
Unfortunately this discussion fell by the wayside.

@xenothrox I assume you're still having this issue?

**Comment by xenothrox** [comment]
I've just contacted the user who told us about that issue. I'm pretty sure it still occurs, but I'll get back to you as soon as I receive an update to this.

**Comment by xenothrox** [comment]
UPDATE:
Many thanks for your patience, I've just wanted to give some additional constellations (different versions of Firefox) a try.
Result: it seems like the issue fixes itself by moving to version 91.X ESR. I think the new WebRender feature improves the whole situation with the web shell.

I'll perform some additional checks and analysis within the next days but I'm pretty sure that we do not need any further changes referring to the policies / the webgl feature on here.

**Comment by mkaply** [comment]
That's great to hear. Please let us know.

**Comment by xenothrox** [comment]
UPDATE:
After several tests we can say that the issue solved itself - finally. 
Additionally I have to say, that I'm pretty sure Firefox never had a problem or malfunction. Suddenly, the requiered WebShell works fine in 91.X ESR AND 78.X ESR.
The reporter of the "bug" noticed that there might has been an update of the Rancher software within the last weeks.. this fits perfectly with a bug reported to the developers of Rancher a few months ago. The reporter also had issues with the same WebShell when using the Safari browser.

I'm really sorry for all the trouble that came with this issue! Many thanks for your patience and help! The requiered fix of "webgl.force.enabled" via policy is no longer necessary.

**Comment by mkaply** [comment]
It's no problem. Glad it's working now!
