### ISSUE TITLE
Add policy to block Reader View

### ISSUE THREAD

**Issue by trsantos** [mozilla/policy-templates#767]
The Website Filter policy is not always useful if the user can simply add `about:reader?url=` at the beginning of the URL he/she wants to "unblock".

Anyway, thanks for the work done on these policies, it is really appreciated.

**Comment by mkaply** [comment]
Dang it!

I fixed view-source and missed that.

I'll just add it as a case here:

https://searchfox.org/mozilla-central/source/browser/components/enterprisepolicies/helpers/WebsiteFilter.jsm#109

Thanks for pointing it out.

**Comment by mkaply** [comment]
I'm going to close this issue since we're handling in bugzilla. Patch is up and it should go in soon.
