### ISSUE TITLE
Allowing WebRTC Local IP Exposure

### ISSUE THREAD

**Issue by Wrayson** [mozilla/policy-templates#769]
I'm having an issue with allowing local IP Exposure through WebRTC.
I'm setting "media.peerconnection.enabled" to true, which works but it obfuscates it's host-adress (MDNS Obfuscation).
For this I'm trying to use
"media.peerconnection.ice.obfuscate_host_addresses.whitelist" or "media.peerconnection.ice.obfuscate_host_addresses.blocklist".
This doesn't seem to work. No matter if I put the IP-Adress or domain of the Website to be allowed to use this (it's an internal project).

Does someone maybe have an example on how to use this (as in, how is the String formed? In what format? IP or Domain? etc.).

Would really appreciate this (I couldn't find another place to ask this question but here. If this is not the right place, please let me know!)

**Comment by mkaply** [comment]
It definitely should be

media.peerconnection.ice.obfuscate_host_addresses.blocklist

Looking at the source code, it says:

  // Test each domain name in the comma separated list
  // after converting from UTF8 to ASCII. Each domain
  // must match exactly or have a single leading '*.' wildcard.

so it should be foo.com,*.bar.com for example.
