### ISSUE TITLE
Applying GPO for External Protocol Permission

### ISSUE THREAD

**Issue by KoksiLasten** [mozilla/policy-templates#777]
Hi, I have some basic questions regarding the "security.external protocol requires permission line " in "about:config".
Its required for our rds to open ssh links without dialog boxes.

Is the only way to set this using the "prefs.js" or autoconfig file, I have tried setting it together with our other group-policies 
as: "security.external_protocol_requires_permission":"false"
in preferences(GPO)  only to be met with the message "Preference not allowed for security reasons".

Is there anyway to override this or would it require a local edit of the "prefs.js" file?
Many thanks /a rookie.

**Comment by mkaply** [comment]
Currently this pref requires modifying an external file or adding it to use prefs.

I can ask our security team about it, but it seems like something that could be abused.

Do any other browsers have a similar policy?

**Comment by KoksiLasten** [comment]
Chrome has something called AutoOpenAllowedForURLs in which you specify a site for allowing the policy AutoOpenFileTypes
to open different links. Also when you refer to "use prefs", it´s the javascript file i mentioned earlier?

**Comment by mkaply** [comment]
Chrome doesn't have anyway to allow ssh links though does it? Those policies are for file types, not protocols..

SSH urls can be a security issue which is why they are blocked.

For now, yes autoconfig can work for flipping that pref.

**Comment by KoksiLasten** [comment]
Well then i know the next course of action, thanks for the quick replies. 
Had alot of help from all of your posts setting up the rest.

Have a good one.

**Comment by mkaply** [comment]
Basically we're going to keep autoconfig around for setting any arbitrary prefs in cases like this where exposing it might cause security issues. I'll still ask though :)

> Had alot of help from all of your posts setting up the rest.

Glad I could help.
