### ISSUE TITLE
Wrong policy referred to in description of BackgroundAppUpdate

### ISSUE THREAD

**Issue by nikobockerman** [mozilla/policy-templates#781]
Description of BackgroundAppUpdate policy in README.md has this chapter:

> If you have disabled updates via DisableAppUpdate or disabled automatic updates via AppUpdateAuto, this policy has no effect.

`AppUpdateAuto` policy doesn't exist and should probably be `AppAutoUpdate` instead.

**Comment by mkaply** [comment]
argh :)

**Comment by mkaply** [comment]
Thanks!
