### ISSUE TITLE
Can FF policies be implemented in Windows 10 Home non-admin user account?

### ISSUE THREAD

**Issue by ineuw** [mozilla/policy-templates#782]
I couldn't find any info, so I ask here, I am using FF policies successfully in Windows as admin and in Linux, I want to create user accounts in Windows Home version and want to block Firefox updates before implementing them.

**Comment by mkaply** [comment]
Yes they can.

Some people have had luck using gpedit on Windows Home:

https://www.makeuseof.com/tag/access-group-policy-editor-even-windows-home-settings-try/

But all we are doing is just reading registry keys and these keys are documented here:

https://github.com/mozilla/policy-templates/blob/master/README.md

So if you just add the correct values in the registry, they will be read as policy.

**Comment by ineuw** [comment]
@mkaply , much thanks for the info. I apologize for asking questions here on the issues of page. But, there are questions about policy that when asked in the general Firefox forums, I am directed here. I have been using policies successfully for the past year, on both Windows and Linux, and quite familiar with this site.

**Comment by mkaply** [comment]
We have a Firefox Enterprise specific forum on SUMO that I monitor:

https://support.mozilla.org/en-US/questions/firefox-enterprise

**Comment by ineuw** [comment]
Again thanks, I will use that forum for questions.
