### ISSUE TITLE
Trouble adding preferences - other GPO settings applied without issue

### ISSUE THREAD

**Issue by SFIR777** [mozilla/policy-templates#784]
I've tried to configure silent printing as a preference is my GPO and could use some help with the formatting. I've used https://github.com/mozilla/policy-templates/blob/master/README.md#preferences as a reference, but cannot make this work.

I'm likely missing something simple and would greatly appreciate a nudge in the proper direction. 

Here is what I have in the preferences options box inside my GPO.

{
"print.always_print_silent": {
"Value": "True",
"Status": "default"
}
}

Thanks!

**Comment by SFIR777** [comment]
Formatting issue

**Comment by mkaply** [comment]
So just to followup (I see you figured it out) I assume the issue was "True" instead of true?
