### ISSUE TITLE
Extensions installed by GPO are disabled if end-user does not respond to the Add-on permissions dialog

### ISSUE THREAD

**Issue by rewritten1** [mozilla/policy-templates#787]
Title. I am trying to force-install extensions via GPO for Firefox ESR 78.12.0esr. The extensions do get installed using the "Extensions to Install" and "Prevent extensions from being disabled or removed" Windows ADMX GPO settings. However, if the end-user does not click "Enable" to the add-on permissions dialog box that appears on their run of the browser with the policy being applied the first time, the extension ends up staying disabled, even though it was policy installed. I would like to know how to install the "McAfee Endpoint Security Web Control" extension that is installed from a local source. Here is information on the extension:

Extension Name: McAfee Endpoint Security Web Control
Extension Source: C:\Program Files (x86)\McAfee\Endpoint Security\Web Control\e10swcffplg.xpi
Extension ID: {cb40da56-497a-4add-955d-3377cae4c33b}

Goal: I want the McAfee Endpoint Security Web Control extension to be force-installed from a known-static location on a local file system (C:\ drive), and have the extension enabled by default without requiring end-user input to enable it. What is my best course of action? The only other similar issue I could find about this is #592.

![mmc_f4X9Zq9cQc](https://user-images.githubusercontent.com/37819602/127347114-61c4110e-e8ba-4377-af79-252b4119265c.png)
![mmc_te7BgZkcQr](https://user-images.githubusercontent.com/37819602/127347116-2ec128b8-b2e5-442e-82fe-17f9ad9fbab1.png)
<img width="871" alt="firefox_esr_addonPermissionsError" src="https://user-images.githubusercontent.com/37819602/127347117-03d19dba-5e93-49d1-a076-03771963ff94.png">

**Comment by rewritten1** [comment]
I forgot to note that all GPO policies are configured under Computer Configuration, not User Configuration.

**Comment by mkaply** [comment]
That's quite odd because in all my testing, the permissions dialog doesn't show at all. I'll do some local testing.

**Comment by mkaply** [comment]
OK, I see what's going on here. I misread the permissions dialog.

This permissions dialog is not coming from policy, it's happening because McAfee put that extension somewhere which caused Firefox to do a third party install. Hence the "Another program installed an add-on"

Can you check and see if you have any of the registry entries here?

**Comment by rewritten1** [comment]
@mkaply Yes, I have the one in HKLM\Software\Mozilla\Firefox\Extensions, for getting the extension installed (see attached). I don't see a registry setting for the section that takes about controlling automatic installation via GPO. Would this get rid of the prompt the user sees? 
![vncviewer_ni0Sx4Dk0r](https://user-images.githubusercontent.com/37819602/127395679-b31ce857-e691-479c-831c-d80f0881f12b.png)

**Comment by mkaply** [comment]
Yes, if you got rid of this, the GPO install you show above should install the addon with no permission prompt.

**Comment by rewritten1** [comment]
That setting was placed by my GPO policy though. I didn't manually add this entry. What do I do in that case?

**Comment by mkaply** [comment]
McAfee put that setting in, not the GPO. Their installer puts that entry in the registry. So you'll need to remove it or see if the McAfee installer has an option to not add that.

**Comment by rewritten1** [comment]
Ohh, okay. I will remove it and see what happens.

**Comment by rewritten1** [comment]
I receive this error when trying to delete the entry as the built-in Administrator account (no UAC).

![vncviewer_H84BPkpttS](https://user-images.githubusercontent.com/37819602/127398221-80eda9f6-d084-40b0-be32-b7ab4a903a89.png)

**Comment by mkaply** [comment]
What do you see when you right click on Extensions and select permissions?

I've never seen that error before...

**Comment by rewritten1** [comment]
I see this:
![regedit_3dzu5A6GnX_2](https://user-images.githubusercontent.com/37819602/127421558-10eb9d54-b081-40c5-b965-34847e1a94d4.png)

**Comment by rewritten1** [comment]
I'm not sure if its the McAfee anti-malware software that is blocking its deletion or something else. Administrators is in that permissions list as being allowed to manipulate the key, which makes this behavior strange.

**Comment by mkaply** [comment]
This definitely sounds like something you might want to go to McAfee with.  I'm out of ideas...

**Comment by rewritten1** [comment]
> OK, I see what's going on here. I misread the permissions dialog.
> 
> This permissions dialog is not coming from policy, it's happening because McAfee put that extension somewhere which caused Firefox to do a third party install. Hence the "Another program installed an add-on"
> 
> Can you check and see if you have any of the registry entries here?
> 
> https://extensionworkshop.com/documentation/enterprise/enterprise-distribution/
> 
> (Ignore the Firefox 72 references, it's still enabled for ESR)

Looking again at this link, I found that setting  extensions.autoDisableScopes and extensions.enabledScopes to 0 and 15 no longer prompts the end-user with the extension dialog box to enable it. This is the behavior I was looking for. Though, I can't help but think configuring these settings 0 and 15 causes security issues.

Your right, McAfee is probably the one that needs to make the changes to the agent so it does not prompt the user for permission to enable it. Thank you for the help!

**Comment by rewritten1** [comment]
> 

Thank you for that. Looking back at this, I learned that during the McAfee endpoint security installation, one of the options part of the McAfee installer is to include the Endpoint security Web Extension and place an unchangeable registry entry at HKLM\Software\Mozilla\Firefox\Extensions. When I received the installation package for McAfee endpoint security, I could not alter the installation parameters to exclude this. Only a year later, I received the permission to uncheck this option, so that it doesn't appear under HKLM\Software\Mozilla\Firefox\Extensions as a registry entry that cannot be removed.

I consider this issue to be resolved, so I will mark at as closed.

**Comment by mkaply** [comment]
Yeah, I'm so glad they added that. Much better to install via policy.
