### ISSUE TITLE
Handlers policy

### ISSUE THREAD

**Issue by Yuzzman** [mozilla/policy-templates#788]
Hi,

I have created a GPO to define our Zimbra Webmail as default mailto handler.
I tried with 78.12.0esr (64 bits) and 90.0.2 (64 bits) (this one is not mentionned as compatible I know).
In handler policy I tried this code : 

`{"defaultHandlersVersion":{"fr":3},"mimeTypes":{"application/pdf":{"action":3,"extensions":["pdf"]}},"schemes":{"ircs":{"stubEntry":true,"handlers":[null,{"uriTemplate":"https://www.mibbit.com/?url=%s","name":"Mibbit"}]},"mailto":{"handlers":[{"name":"Zimbra","uriTemplate":"https://zimbra.contoso.com/?view=compose&to=%s"},{"name":"Yahoo! Mail","uriTemplate":"https://compose.mail.yahoo.com/?To=%s"},{"name":"Gmail","uriTemplate":"https://mail.google.com/mail/?extsrc=mailto&url=%s"}],"action":2},"irc":{"stubEntry":true,"handlers":[null,{"uriTemplate":"https://www.mibbit.com/?url=%s","name":"Mibbit"}]}}}`

and this one : 

`{"schemes":{"mailto":{"action":"useSystemDefault","ask":false,"handlers":[{"name":"Zimbra","uriTemplate":"https://zimbra.contoso.com/?view=compose&to=%s"}]}}}`

and this one : 

`{
  "schemes": {
    "mailto": {
      "action": "useSystemDefault",
      "ask": false,
      "handlers": [{
        "name": "Zimbra",
        "uriTemplate": "https://zimbra.contoso.com/?view=compose&to=%s"
      }]
    }
  }
}`

When I run gpupdate/force and open FF and go to parameter, I can select my new handler, but each time I closed FF, mailto handler goes back to "Always ask".

Do I missed something ? For sur yes, so If a new eye could help me It will be very appreciate.

Thanks,
Yuzzman.

**Comment by Yuzzman** [comment]
I tested also with "saveToDisk" instead of "useSystemDefault"

**Comment by mkaply** [comment]
It should be set to useHelperApp and that will cause it to use your handler:

{
	"schemes": {
		"mailto": {
			"action": "useHelperApp",
			"ask": false,
			"handlers": [{
				"name": "Zimbra",
				"uriTemplate": "https://zimbra.contoso.com/?view=compose&to=%s"
			}]
		}
	}
}

**Comment by Yuzzman** [comment]
Ok it works :) I was pretty sure I tested this but I'm think I was too tired.
Thanks for reply and your work ;)

**Comment by mkaply** [comment]
No problem!
