### ISSUE TITLE
GPO Wish: Ability to disable sponsored top sites and other sponsored content on about:newtab

### ISSUE THREAD

**Issue by kshade** [mozilla/policy-templates#790]
The options to disable or enable sponsored top sites (browser.newtabpage.activity-stream.showSponsored and browser.newtabpage.activity-stream.showSponsoredTopSites) are currently missing from the policy templates. Please consider adding them, along with any other advertisement toggles for the new tab page I might be missing. Thank you.

**Comment by mkaply** [comment]
Any preference that begins with browser. is available via the Preferences policy.

I'll check into adding these by name to the existing policy.

**Comment by mkaply** [comment]
I've opened this bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1724488

If it's OK, I'm going to close this issue since this will be handled in Bugzilla.

But again, if you want to do this now, you can use those prefs in the Preferences policy.
