### ISSUE TITLE
The Firefox Policies doesn´t appear under the Administrative Templates

### ISSUE THREAD

**Issue by gccarvalhobr** [mozilla/policy-templates#795]
Hello guys, i paste the files *.admx into the C:\Windows\PolicyDefinitions\, and the *.adml into the c:\Window\PolicyDefinitions\en-US, but when i access the Group Policy Management, create a new policy, edit it, and go to the User Configuration, Policies, Administrative Template, there is no Mozilla/Firefox options, what am i doing wrong? i could set with no problem Chrome and Edge default webpage, but for Firefox nothing. I´m using Windows Server 2012 R2, and all the computers are Windows 10 PRO, i downloaded the latest Firefox Policy Templates for Firefox 91.

![print_gpo](https://user-images.githubusercontent.com/20598923/129372763-1b47a083-1192-482f-ba5d-7a2cf10fd1d4.png)

What am i doing wrong?

Thanks

**Comment by mkaply** [comment]
Are you running gpedit.msc or something else? I've never seen that "retrieved from the central store" message.

Here's what it looks like for me:

![image](https://user-images.githubusercontent.com/345868/129374095-289cf31a-9247-40b7-9029-b18aebfb7d83.png)

**Comment by mkaply** [comment]
So the policy definitions need to be loaded into the AD central store

This is what I found on that

https://4sysops.com/archives/group-policy-central-store/#:~:text=In%20the%20Group%20Policy%20Management%20Editor%2C%20the%20Administrative,definitions%20%28ADMX%20files%29%20retrieved%20from%20the%20local%20computer.%E2%80%9D

**Comment by gccarvalhobr** [comment]
> So the policy definitions need to be loaded into the AD central store
> 
> This is what I found on that
> 
> https://4sysops.com/archives/group-policy-central-store/#:~:text=In%20the%20Group%20Policy%20Management%20Editor%2C%20the%20Administrative,definitions%20%28ADMX%20files%29%20retrieved%20from%20the%20local%20computer.%E2%80%9D

Perfect, i found what was my Central Store path´s, put the files on there, and now i have the Mozilla/Firefox options, thanks @mkaply
