### ISSUE TITLE
Firefox 91 "Empfohlen von Pocket" mysterium

### ISSUE THREAD

**Issue by pilgi3** [mozilla/policy-templates#796]
Currently we are testing the update from version 78 to 91 esr (german and english).
We already using GPO to configure the Firefox.
After the update on a german client in the Firefox Home settings is "Empfohlen von Pocket" enabled.
![grafik](https://user-images.githubusercontent.com/44865075/130036769-3ff28068-bc25-477e-bf43-dbf3e8a75b8d.png)

But after the update on a english client there exists no setting "Recommended by Pocket"?!
![grafik](https://user-images.githubusercontent.com/44865075/130036952-2e571fab-c32f-456f-b362-77653b795f31.png)

The GPO Firefox Home is set like this:
![grafik](https://user-images.githubusercontent.com/44865075/130037110-c1100ba4-144d-41ee-aefa-274a779a4d24.png)

Further research I installed the non-esr version on a standalone (no company settings) english client. 
No "Recommended by Pocket" setting available.
If I change the language to german, the setting is suddenly available!?

At all if I open a new tab the Pocket Section below is not shown.
Seems to be a bug in Firefox but also in the GPO as well.
Because we have not ticked "Recommended by Pocket" and the setting is still enabled at the german client.

**Comment by mkaply** [comment]
Can you check the registry and tell me what you see for FirefoxHome in HKEY_CURRENT_USER\SOFTWARE\Policies\Mozilla\Firefox (or LOCAL_MACHINE)

**Comment by pilgi3** [comment]
There are no settings under HKCU but in HKLM:
![grafik](https://user-images.githubusercontent.com/44865075/130082926-ad299d20-57c6-4bf1-abda-468f35a555b9.png)

**Comment by mkaply** [comment]
Interesting. Pocket is definitely set to 0 so it should not show. I'll see if there is something going on with the German version.

The language differences you are seeing are related to special code as to when we show Pocket, based on language and locale.

It appears we don't show pocket if you're using an English build in Germany, only a German build in Germany.

**Comment by pilgi3** [comment]
Thank you! Is a little bit strange :)
As I mentioned above the pocket section is not shown in the new tab but is enabled in the settings.

**Comment by mkaply** [comment]
You found a bug. I've opened up bug https://bugzilla.mozilla.org/show_bug.cgi?id=1729001 to fix it.

I'm going to close this and fix it over there if that's OK.
