### ISSUE TITLE
Can't get SuggestURLTemplate working

### ISSUE THREAD

**Issue by MAccadia** [mozilla/policy-templates#797]
I'm trying to add a search engine with **SearchEngines | Add**. Everything works except search suggestions (when searching in the urlbar).

I have this `policies.json` :

```json
{
  "policies": {
		"SearchSuggestEnabled": true,
	   
		"SearchEngines": {
		 "Add": [
			{
			  "Name": "Example1",
			  "URLTemplate": "https://duckduckgo.com/?q={searchTerms}",
			  "Method": "GET",
			  "IconURL": "https://duckduckgo.com/favicon.ico",
			  "Alias": "example",
			  "Description": "Description",
			  "SuggestURLTemplate": "https://duckduckgo.com/ac/?q={searchTerms}&type=list"
			}
		],
		"Default": "Example1"
		}
	}
}
```

I test with a fresh profile. The URLs seem ok and `about:policies` doesn't show any error.

(I'm testing on Firefox ESR 91.1.0)

**Comment by mkaply** [comment]
Looks like something that broke in Firefox 80 that we missed. I'll get it fixed asap.

https://bugzilla.mozilla.org/show_bug.cgi?id=1730218

I'm going to close it here since we're tracking in bugzilla.

Thanks for reporting.
