### ISSUE TITLE
Enhanced Tracking Protection Shield Icon is Not Removed When the "EnableTrackingProtection" Is Disabled

### ISSUE THREAD

**Issue by p0da** [mozilla/policy-templates#798]
Would it be possible to also remove the "enhanced tracking protection" shield icon from the toolbar when all the options under "EnableTrackingProtection" are set to false? At that point I believe it serves no purpose and is just UI clutter. Thanks for considering.

**Comment by mkaply** [comment]
The shield still provides access to other useful information and I don't think the team would be willing to remove it at this time.
