### ISSUE TITLE
Integrated Authentication

### ISSUE THREAD

**Issue by FGAGwendalG** [mozilla/policy-templates#80]
Hello,

Can you add the this parameter ?
network.negotiate-auth.trusted-URI

https://developer.mozilla.org/en-US/docs/Mozilla/Integrated_authentication

**Comment by mkaply** [comment]
That policy is already available.

See the Authentication sectionhere:

https://github.com/mozilla/policy-templates/blob/master/README.md

trusted-uri refers to SPNEGO URLs
