### ISSUE TITLE
ExtensionSettings entry in firefox.admx has an extra ">

### ISSUE THREAD

**Issue by jobisoft** [mozilla/policy-templates#801]
Search the `windows/firefox.admx` file for `">">`. There will be a hit in the ExtensionSettings entry.

It does not seem to cause issues, but it looks like a typo?

```
<policy name="ExtensionSettings" class="Both" displayName="$(string.ExtensionSettings)"  key="Software\Policies\Mozilla\Firefox" explainText="$(string.ExtensionSettings_Explain)"  presentation="$(presentation.ExtensionSettings)">">
```

**Comment by mkaply** [comment]
Thanks! I thought I had found all those.

**Comment by jobisoft** [comment]
I only found it, as I am currently writing a script which parses and modifies the admx files for Thunderbird. Speaking of which: Are there any tools we could clone, which allow us to generate our files directly from our policy schema files? Currently we grab the mozilla template files and manually remove policies which we do not support. This works somewhat, but will become even more cumbersome, once we start adding our own policies, which do not exist in Firefox.

Any help here would be greatly appreciated, and sorry for hijacking the issue, did not know how to reach you otherwise. You can reach me at john@thunderbird.net.

**Comment by mkaply** [comment]
I wonder if we could somehow split the Firefox specific policies into a different file?

And also use variables for Firefox in the ADMX. That way we could share the files between the two?

**Comment by jobisoft** [comment]
> I wonder if we could somehow split the Firefox specific policies into a different file?

We have not yet considered adding our own policies, we just clone yours. The schema files are already separate:
https://searchfox.org/mozilla-central/source/browser/components/enterprisepolicies/schemas/policies-schema.json
https://searchfox.org/comm-central/source/mozilla/browser/components/enterprisepolicies/schemas/policies-schema.json

We do not support all the Firefox policies, so what I am doing currently is to parse our `policies-schema.json` and remove everything from your `firefox.admx` file, which we do not support (and do some Firefox to Thunderbird replacements) and release that as `thunderbird.admx`.

It would indeed be great if I could see how you generate those admx files in the first place, so I could maybe generate ours directly from our own policies-schema.json. That would empower us to do the work on our own.

Alternatively, access to an intermediate data structure, which includes the admx chunks per policy/element which still has some branding placeholders would also help us. But this probably means work on your side, which I do not want to cause.

Thanks for your help!

**Comment by mkaply** [comment]
So I looked into using variable for keys and other things, but ADMX doesn't allow that.

I'm looking into the intermediate data structure idea.
