### ISSUE TITLE
DNSOverHTTPS > Provider URL does not actually use the provided DNS server

### ISSUE THREAD

**Issue by Silejonu** [mozilla/policy-templates#802]
I have the following policy settings:
```
{
  "policies": {
    "DNSOverHTTPS": {
      "Enabled":  true,
      "ProviderURL": "https://family.cloudflare-dns.com/dns-query",
      "Locked": true,
      "ExcludedDomains": [""]
    }
  }
}
```
The DNS server filled in ProviderURL is not actually fed in the settings if another server is already setup. If none is setup, then it will get added to the settings, but won't actually be active. Of course, adding the server manually will work.

Both those pages should be inaccessible if the DNS server is active:
http://phishing.testcategory.com/
http://nudity.testcategory.com/

Firefox version 92.0
OS: Ubuntu 20.04
Firefox version

**Comment by mkaply** [comment]
So I ran a test with policy and manual and http://phishing.testcategory.com/ is not blocked for me, but http://nudity.testcategory.com/ is always blocked.

This sounds like a cloudflare issue.

There is a bug that we don't show the custom provider URL when it's locked. I'll open a bug for that.

**Comment by Silejonu** [comment]
> So I ran a test with policy and manual and http://phishing.testcategory.com/ is not blocked for me, but http://nudity.testcategory.com/ is always blocked.
> 
> This sounds like a cloudflare issue.
> 
> There is a bug that we don't show the custom provider URL when it's locked. I'll open a bug for that.
> 
> 

I doubt this is a Cloudflare issue. I just tested once again on a fresh system, and the issue is still present: both URLs are correctly blocked when set up manually, buy neither is when set up through policies.

Be careful though, if you set up the policy, then disable it, the DNS address will show up in the settings box, but won't be active. From the tests I run it seems you must switch to another provider, restart Firefox, re-add the DNS, restart Firefox again, and then the DNS will be active.

Don't you have another DNS at the system/router level that blocks malware and could cause the discrepancy in results?

**Comment by mkaply** [comment]
OK, I am definitely able to recreate. I'll open a bugzilla bug and look into it.

**Comment by Silejonu** [comment]
> OK, I am definitely able to recreate. I'll open a bugzilla bug and look into it.

Thanks. Did I post the bug report in the wrong place? Do you want me to re-post where I was supposed to?

**Comment by mkaply** [comment]
No, this is a great starting place if you're not sure.

Now that we know it's a Firefox bug, we can open it here:

https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Enterprise+Policies

You can do it or I can.

**Comment by Silejonu** [comment]
> No, this is a great starting place if you're not sure.
> 
> Now that we know it's a Firefox bug, we can open it here:
> 
> https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Enterprise+Policies
> 
> You can do it or I can.

I opened an issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1732961

**Comment by mkaply** [comment]
Awesome. I'm going to close this and we'll track it there since it's a Firefox issue.
