### ISSUE TITLE
Wish: Managing Screensharing and Safebrowsing via GPO

### ISSUE THREAD

**Issue by WolfgangAndreas** [mozilla/policy-templates#803]
Hello,
due to strict privacy settings of our company it is very complicated for us to manage the following settings via mozilla.cfg. We have different departments which are using their own mozilla.cfg and it is not very flexible for us to merge these in a suitable configuration.

So.. Would it be possible to implement the management of the following configuration items via GPO? Mainly Safebrowsing and Screensharing here...

Sample GPO Name: "Disable Firefox Screensharing"
Affecting config-item: media.getusermedia.screensharing.enabled
Values: Enable / Disable / Not Configured

Sample GPO Name: "Configure Safebrowsing"
Affecting config-items:
"Enable Safebrowsing for Blocked URLs" (browser.safebrowsing.blockedURIs.enabled)    [Checkbox, On/Off]
"Enable Safebrowsing for Downloads" (browser.safebrowsing.downloads.enabled)    [Checkbox, On/Off]
"Enable Safebrowsing for Malware" (browser.safebrowsing.malware.enabled)    [Checkbox, On/Off]
"Enable Safebrowsing for Passwords" (browser.safebrowsing.passwords.enabled)    [Checkbox, On/Off]
"Enable Safebrowsing for Phishing Websites" (browser.safebrowsing.phishing.enabled)    [Checkbox, On/Off]

Most importantly: We need to make sure, there is a possibility to completely disable the Safebrowsing-Feature via GPO.

Thank you!

**Comment by mkaply** [comment]
All of these preferences are settabble via our Preferences policy (https://github.com/mozilla/policy-templates/blob/master/README.md#preferences)

There is a bug that when disabling safe browsing, some of the preferences don't properly reflect that, but it does work.

I'm curious why you want to disable safe browsing?

**Comment by WolfgangAndreas** [comment]
Ah, nice info :-) Thank you! I didn't see, that there's a deprecated one and a new one for this. We will give it a try.

Regarding disabling SafeBrowsing: We think, that this might send "unwanted telemetry data" of our user's actions to the SafeBrowsing backend, which we do not want. We have requirements that largely prohibit us from using cloud services, with a corresponding use of other solutions.

**Comment by mkaply** [comment]
>We have requirements that largely prohibit us from using cloud services, with a corresponding use of other solutions.

That's fair. Unfortunately we don't have a policy like Chrome that uses only local safe browsing checks and never hits the server.
