### ISSUE TITLE
Linux Mint version of Firefox does not respect "no update" policy

### ISSUE THREAD

**Issue by ineuw** [mozilla/policy-templates#804]
Linux Mint version of Firefox does not respect the "no update" policy. This issue is provable and repeatable. My policy settings are recognized and verified in every Firefox version (92.0.1), but the Linux Mint versions ignore this. What choices do I have in Linux?

These identical policies set in the registry of Windows 10, are respected. I have eight installations of the same versions of Firefox, four in Linux, and four in Windows 10.  Please advise.

**Comment by mkaply** [comment]
Firefox on Mint is updated by the operating system/package manager, not by Firefox so we can't control that via policy.

You'll have to check with Mint on how to disable updates.
