### ISSUE TITLE
Path for system-wide policies on Mac OS?

### ISSUE THREAD

**Issue by MikeRich88** [mozilla/policy-templates#806]
Is there a path I can place "system-wide" policies on Mac OS?

Or in other words, I'd rather not have to manipulate the .app contents. Is there another location where Firefox will check for policies?

(aka macos)

**Comment by mkaply** [comment]
Configuration profiles on macOs are how you set system wide mac policies:

**Comment by mkaply** [comment]
https://support.apple.com/guide/mac-help/configuration-profiles-standardize-settings-mh35561/mac

**Comment by MikeRich88** [comment]
sudo defaults write /Library/Preferences/org.mozilla.firefox EnterprisePoliciesEnabled -bool TRUE
sudo defaults write /Library/Preferences/org.mozilla.firefox DisableAppUpdate -bool TRUE
