### ISSUE TITLE
README link wrong

### ISSUE THREAD

**Issue by pilgi3** [mozilla/policy-templates#808]
The README link is wrong at the release page.
![image](https://user-images.githubusercontent.com/44865075/136534723-173b9997-87b1-423c-b290-cf7aaa0a32d3.png)

![image](https://user-images.githubusercontent.com/44865075/136534739-cc764d96-48d8-4c93-9d10-61d270528347.png)

**Comment by mkaply** [comment]
Thanks for catching that. i've fixed it.
