### ISSUE TITLE
install_sources do not block intsllastion from other sources

### ISSUE THREAD

**Issue by akiralight** [mozilla/policy-templates#810]
I want to only allow extensions to be installed from our internal local website and block installation from other sources (including addons.mozilla.org). I specify the ExtensionSettings policy as follows:
{
"*": {
  "blocked_install_message": "My message",
  "install_sources": ["https://website.local"],
  "allowed_types": ["extension"]
}
}
Waiting: only xpi files from https://website.local allowed to install in Firefox, others will be blocked.
Reality: I can still install any extensions from https://addons.mozilla.org  

Why is this happening and how to get the desired result?

**Comment by akiralight** [comment]
Do you mean ID-based addon installation via ExtensionSettings? This option was also considered. But there is another problem. When the ExtensionSettings are defined, all existing Firefox extensions are disabled and cannot be enabled by the user. It is unacceptable for us to disable extensions previously installed through "Estensions" policy (like Software\Policies\Mozilla\Firefox\Extensions\Install\1 = "https://.../somefile.xpi"). It would be nice if we could disable the "Extensions" policy and enable the "ExtensionSettings" policy, and all previously installed extensions remain enabled. But I have not found a way to do this.

**Comment by Selkie44** [comment]
Hello,
Any news on this bug? For a business that wants to allow only internal add-ons and prevent users from adding community extensions this is the easiest way. Otherwise, each extension must be declared with its ID and it is much more restrictive.

**Comment by mkaply** [comment]
The code is in review right now. Should have it soon

**Comment by kleener** [comment]
Hi,
what is the status?
Is it already live?

**Comment by mkaply** [comment]
Yes, this bug was finally fixed in Firefox 99. Unfortunately we couldn't backport to the ESR, but it will be in ESR 102.
