### ISSUE TITLE
Switching from Bookmarks to ManagedBookmarks duplicates bookmarks

### ISSUE THREAD

**Issue by bastux** [mozilla/policy-templates#817]
I don't know if this is solveable though, since there was no distinction between those two in the past. Would it be an idea to remove all of those bookmarks, where location (folder), url and name match those in ManageBookmarks?

Test Case (Firefox ESR 91.3 using policies.json, Windows):
Use the following config:
```
{
  "policies": {
    "DisplayBookmarksToolbar": true,
    "Bookmarks": [
      {
        "Folder": "Test",
        "Placement": "toolbar",
        "Title": "Google",
        "URL": "https://www.google.de/"
      },
      {
        "Folder": "Test",
        "Placement": "toolbar",
        "Title": "Youtube",
        "URL": "https://www.youtube.com/"
      }
    ]
  }
}
```
Start Firefox with a fresh profile
Migrate the config to ManagedBookmarks
```
{
  "policies": {
    "DisplayBookmarksToolbar": true,
    "ManagedBookmarks": [
      {
        "toplevel_name": "Test"
      },
      {
        "name": "Google",
        "url": "https://www.google.de/"
      },
      {
        "name": "Youtube",
        "url": "https://www.youtube.com/"
      }
    ]
  }
}
```
Restart Firefox with the same profile

This and the issue [ ManagedBookmarks don't use favicons #816 ](https://github.com/mozilla/policy-templates/issues/816) let me stick to Bookmarks right now.

**Comment by mkaply** [comment]
I could probably add a specific policy to remove Bookmarks or specifying an empty Bookmarks policy removes them.

**Comment by mkaply** [comment]
So if you specify [] for the bookmarks, they will be deleted. There's no way for that to work for GPO though.

I'm going to add a way to do that.

I'm working on your other bugs.

**Comment by bastux** [comment]
This seems to do the trick, thank you very much for your effort! It already worked and I double-checked, that only the bookmarks set through the policy are removed that way:

1. Started with Bookmarks policy set
2. Started Firefox with a fresh profile, created Folder Test2, copied all bookmarks over to that folder and closed FIrefox
3. Emptied Bookmarks policy, (set ManagedBookmarks)
4. Reopen Firefox

-> user-defined bookmarks in Test2 are still there
-> no bookmarks defined through Bookmarks policy
(-> bookmarks defined through ManagedBookmarks are set)
