### ISSUE TITLE
ManagedBookmarks don't honour DisablePrivateBrowsing policy

### ISSUE THREAD

**Issue by Wizard13** [mozilla/policy-templates#818]
Hi!
I have "DisablePrivateBrowsing": true, but if I use ManagedBookmarks policy and right-click on a bookmark, I still get the option to open it in a new private window and it does open it there.

**Comment by Wizard13** [comment]
@mkaply  should I file a bug in bugzilla about this?
A sample file is this:
```
{
  "policies": {
    "DisablePrivateBrowsing": true,
    "ManagedBookmarks": [
      {
        "url": "https://github.com/",
        "name": "GitHub"
      }
    ]
  }
}
```
Right click the bookmark and see the option to open it in a private window. This doesn't happen with normal bookmarks or with Bookmarks policy. I am reverting to Bookmarks policy because of this.

**Comment by mkaply** [comment]
Please do and post it here. I'll get this fixed really quick.

**Comment by Wizard13** [comment]
@mkaply The relevant bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1741217

**Comment by mkaply** [comment]
This was fixed in the latest Firefox
