### ISSUE TITLE
GPO "wish": Make "new tab" page more configurable

### ISSUE THREAD

**Issue by narutards** [mozilla/policy-templates#82]
The GPO option "Disable Pocket" (using "extensions.pocket.enabled") already gets rid of the Pocket section on the "new tab" page.

It would be really nice if the other sections were also configurable through GPO.

I'm currently looking at the following options:
- browser.newtabpage.activity-stream.feeds.section.highlights
- browser.newtabpage.activity-stream.feeds.snippets
- browser.newtabpage.activity-stream.showTopSites

https://bugzilla.mozilla.org/show_bug.cgi?id=1457146

**Comment by havx** [comment]
I agree. Speaking on behalf of my company, we ask to have extended control over the "Firefox Home Content" settings; disable pocket (including sponsored sites), disable snippets, disable highlights, and configure highlights sub-settings.

**Comment by stapia4** [comment]
We are replacing IE now that FireFox supports GPO and this is one of the first things I looked for. 

Hope it makes it in soon.

**Comment by mkaply** [comment]
This is in the new FirefoxHome policy.
