### ISSUE TITLE
Feature request: ExtensionSettings should have an option to set visibility of extension icon

### ISSUE THREAD

**Issue by Wizard13** [mozilla/policy-templates#823]
Relevant bugzilla feature request: https://bugzilla.mozilla.org/show_bug.cgi?id=1741226

Chrome and Edge have an extra option to set visibility of extension icon.

Chrome calls it toolbar_pin ( https://support.google.com/chrome/a/answer/9867568?hl=en )
From above link:

> Controls if the extension icon is pinned to the toolbar. You can set it to:
> force_pinned—The extension icon is pinned to the toolbar and visible at all times. The user can't hide it in the extension menu.
> default_unpinned—The extension starts hidden in the extension menu, and the user can pin it to the toolbar.
> If you do not set this field, it defaults to the default_unpinned behavior.

Edge calls it toolbar_state ( https://docs.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions-ref-guide )
From above link:

> This policy setting allows you to force show an installed extension to the toolbar. The default state is default_shown for all extensions. Following states are possible for this setting
> -force_shown: You can choose to force show an installed extension on the toolbar. Users will not be able to hide the specificed extension icon from the toolbar.
> -default_hidden: In this state, extensions are hidden from the toolbar on installation. Users can show them on the toolbar, if needed.
> -default_shown: This is the deafult setting of all the installed extensions on the browser.

This option could have values to force the icon (user could not be able to hide it) and to hide the icon (user could be able to show it).

**Comment by mkaply** [comment]
bugzilla is the right place for this and a bug was opened

https://bugzilla.mozilla.org/show_bug.cgi?id=1741226
