### ISSUE TITLE
GPO wish - policy to add server certificate exception (Certificates/Overrides in CCK2)

### ISSUE THREAD

**Issue by jwalawski** [mozilla/policy-templates#828]
Would it be possible to add policy to configure server certificate exceptions (similar to the Certificates/Overrides option in CCK2)? I know it is not most secure option, but it is better than training users to ignore warnings when valid certificate can't be installed on a server. Maybe the policy could have a field for certificate fingerprint to compare before adding an exception.

In the meantime, until the feature is implemented, could somebody please help with adding exception through Autoconfig. I tried the solution from [here](https://support.mozilla.org/en-US/questions/1287443) with some modifications:
- changed HTTP request method to HEAD (to limit request data, doesn't seem to work)
- added originAttributes parameter of overrideService.rememberValidityOverride method ([added between port and certificate parameters](https://searchfox.org/mozilla-central/source/security/manager/ssl/nsICertOverrideService.idl#108))
- added check of SSL error types when setting flags ([borrowed from CCK2](https://github.com/mkaply/cck2wizard/blob/master/cck2/modules/CCK2.jsm#L1282))
- option to set port other than default 443

For now this workaround seems to work (with a small problem of exception remaining in the browser despite changing overrides list). How could it be improved (removing exception when overrides list is changed; secInfo.serverCert.sha256Fingerprint === override_fingerprint before adding an exception; overrides format changed to 'host,port,fingerprint'; overrides list moved to other file/registry)?

```
// Mozilla Firefox autoconfig - certificate errors override

Cu.importGlobalProperties(['XMLHttpRequest', 'URL']);
Cu.import('resource://gre/modules/Services.jsm');

let overrides = ['localhost:8080','self-signed.badssl.com','expired.badssl.com','untrusted-root.badssl.com','wrong.host.badssl.com'];

let setOverrides;
try {
  setOverrides = getPref('setOverrides').split(',');
} catch (e) {}
if (setOverrides !== overrides) {
  Services.obs.addObserver(function observer() {
    let overrideService = Cc['@mozilla.org/security/certoverride;1'].getService(Ci.nsICertOverrideService);
    for (let i = 0; i < overrides.length; i++) {
      let xhr = new XMLHttpRequest();
      try {
		let override = overrides[i].split(":");
		let overrideURL = override[0];
		let overridePort = Number.isInteger(parseInt(override[1])) ? parseInt(override[1]) : 443;
        xhr.open('HEAD', `https://${overrideURL}:${overridePort}`);
        xhr.onerror = function () {
          if (xhr.channel && xhr.channel.securityInfo) {
            let secInfo = xhr.channel.securityInfo.QueryInterface(Ci.nsITransportSecurityInfo);
            let cert = secInfo ? secInfo.serverCert : null;
            if (cert) {
				let url = new URL(xhr.responseURL);
				let originAttr = xhr.channel.loadInfo.originAttributes;
				let flags = 0;
				if(secInfo.isUntrusted)
					flags |= overrideService.ERROR_UNTRUSTED;
				if(secInfo.isDomainMismatch)
					flags |= overrideService.ERROR_MISMATCH;
				if(secInfo.isNotValidAtThisTime)
					flags |= overrideService.ERROR_TIME;
				overrideService.rememberValidityOverride(
					url.hostname,
					overridePort,
					originAttr,
					cert,
					flags,
					false
				);
            }
          }
        };
        xhr.send(null);
      } catch (ex) {}
    }
    pref('setOverrides', overrides.join(','));
    Services.obs.removeObserver(observer, 'final-ui-startup');
  }, 'final-ui-startup');
}
```

**Comment by mkaply** [comment]
We had a long conversation about this a while ago with the security team and the consensus was that with as easy (and free) as it is to obtain certificates, this is a problem that should be going away (or solvable in other ways).

So what you're doing is the best way to do it (My most recent example of code doing this is here - https://support.mozilla.org/en-US/questions/1287443).

Another alternative would be to just put the cert_override.txt into people's profile directory.

**Comment by jwalawski** [comment]
Thank you for response and your code (I have borrowed both from linked example and CCK2). I didn't think I would get different answer, but I wanted to check one last time about this issue. At least there are some options. I haven't found any similar workarounds for Chrome/Edge.

**Comment by mkaply** [comment]
Glad my code was helpful.
