### ISSUE TITLE
PrimaryPassword doesn't work with Thunderbird 91 but with firefox ESR 91

### ISSUE THREAD

**Issue by veasna33** [mozilla/policy-templates#832]
Hello,
I use this in the  policies.json file in the distribution folder of the thunderbird program folder install but it doesn't work.

{
  "policies": {
    "PrimaryPassword": true
  }
}

It's ok with Firefox.Do you if it'll be available for Thunderbird 91?
Thx

**Comment by mkaply** [comment]
That's a question to ask here:
