### ISSUE TITLE
Blocked Cipher List is out-of-date

### ISSUE THREAD

**Issue by TVBanks98** [mozilla/policy-templates#836]
The list of cipher suites that can be blocked seems out-of-date.  Specifically, it does not include the option to block these two weak ciphers that Firefox appears to still support.  

TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)  WEAK 	256
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)  WEAK 	128

Would like to see that list maintained in future releases.  Thanks !!

**Comment by mkaply** [comment]
This will be tracked here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1745065

Thanks for reporting. Should be in the next release.
