### ISSUE TITLE
ADMX encountered error while parsing

### ISSUE THREAD

**Issue by george-potts** [mozilla/policy-templates#84]
I have just installed the firefox and mozilla ADMX and ADML files onto our domain controller running Windows Server 2012 R2.
When creating a GPO I receive the error.
--------
Encountered an error while parsing.
DTD is prohibited.

File C:\Windows\PolicyDefinitions\firefox.admx, line7, column 9
--------

and

--------
Encountered an error while parsing.
DTD is prohibited.

File C:\Windows\PolicyDefinitions\mozilla.admx, line7, column 9
--------

[admx.zip](https://github.com/mozilla/policy-templates/files/1962897/admx.zip)

**Comment by mkaply** [comment]
This error means that you tried to download the ADMX files by right clicking and downloading instead of downloading the ZIP file.

Please download the policy templates here

https://github.com/mozilla/policy-templates/releases
