### ISSUE TITLE
GPO "wish": Disable browser onboarding

### ISSUE THREAD

**Issue by hheinen** [mozilla/policy-templates#85]
In addition to "Override the first run page" it would be great, if you could set "browser.onboarding.enabled" to false via GPO. 

Code suggestion will follow.

**Comment by jjurkus** [comment]
I "solved" this by deleting onboarding@mozilla.org.xpi from %InstallDir%\browser\features\ :-D

**Comment by HeiHei90** [comment]
@jjurkus thanks for this tip. I am going to try this as soon as possible.

**Comment by HeiHei90** [comment]
@jjurkus  thank you. I tried it and it "solved" the problem, ignoring the errors FireFox throws in its browser-console. In the same way i got rid of the activity-stream.

**Comment by mkaply** [comment]
So it looks like we've gotten rid of all the onboarding stuff.
