### ISSUE TITLE
WindowsSSO not working on 95.0.2

### ISSUE THREAD

**Issue by rand0muser123** [mozilla/policy-templates#852]
Am trying to configure it via oma-uri on Intune
Set it via 
./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox/WindowsSSO
With the value
 <enabled/>
But does not appear on about:policies
Manually toggling it on via privacy and security 
"Allow Windows single sign-on for microsoft, work and school accounts" works.

All other policies are appearing.

Doing it through policies.json is not ideal as we would have to package it each time via win32app
And there would be settings applied through device config in intune as well as through policies.json

**Comment by mkaply** [comment]
Sorry, it took me some time to check this.

This is working fine for me with this OMA URI:

```
./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox/WindowsSSO
```
with a string value of
```
<enabled/>
```

What version of the ADMX are you using?

**Comment by mkaply** [comment]
Were you able to check this?

**Comment by rand0muser123** [comment]
Hi Michael,
Yes It was because we  didn't ingest the latest admx.
After ingesting it, all was right with the world.
Thanks for following up!
