### ISSUE TITLE
Possible bug policies.json BlockAbout can be bypassed

### ISSUE THREAD

**Issue by oxcelovel** [mozilla/policy-templates#853]
Windows 10 pro 19043.1415 
FF 96.0 or 95.0.2
C:\Program Files (x86)\Mozilla Firefox\distribution\policies.json
or
C:\Program Files\Mozilla Firefox\distribution\policies.json
{
  "policies": {
	"Proxy": {
		"Mode": "none",
		"Locked": true
		},
   	"BlockAboutConfig": true,
   	"BlockAboutAddons": true,
   	"BlockAboutProfiles": true,
   	"BlockAboutSupport": true,
	"DisableAppUpdate": true,
  	"DisablePrivateBrowsing": true,
   	"DisableProfileImport": true,
   	"DisableSafeMode": true
  }
}
now lets try about:config > enter
"Blocked Page" okay
now lets try about:Config > enter
oops we bypassed blocking, that capitalized letter matter
same thing works for about:Addons about:Profiles and about:Support as well
if you first enter about:Config FF reset it to about:config and Blocked Page
however when you enter once more about:Config it will be bypassed

**Comment by mkaply** [comment]
I don't see this. it always normalizes back to about:config or about:profiles and is blocked for me, even on a new profile. Can you post a video?

**Comment by oxcelovel** [comment]
https://user-images.githubusercontent.com/53994647/149447324-e9a35104-e60a-4f3c-b6ab-6558b13e003a.mp4

did it on newly created profile with no addons, also reproduced on laptop

**Comment by mkaply** [comment]
Thanks. I wasn't editing it directly. I was able to recreate.

**Comment by mkaply** [comment]
Thanks for reporting. Fixing in

https://bugzilla.mozilla.org/show_bug.cgi?id=1750221
