### ISSUE TITLE
How does BackgroundAppUpdate work?

### ISSUE THREAD

**Issue by StFIT** [mozilla/policy-templates#855]
Hi,

I used Firefox 91.4.1 ESR and closed it.
Than enabled the BackgroundAppUpdate via GPO to check if this works.
Since Firefox 91.5.0 was released 3 days ago I thought it should be now updated but it is not.
So how is this policy supposed to work. What should the policy do technically?

**Comment by mkaply** [comment]
Sorry for the delay on this. Researching.

On Windows, can you bring up the task schedule and see if you have an entry?

![image](https://user-images.githubusercontent.com/345868/156243220-cb4f17f8-6656-4323-bb06-2d9755d19862.png)

Per the docs here:

https://support.mozilla.org/en-US/kb/enable-background-updates-firefox-windows

The following things are required for background update to work:

Firefox must have been installed with the installer (not from, for example, a ZIP).
    The [Mozilla Maintenance Service](https://support.mozilla.org/en-US/kb/what-mozilla-maintenance-service) must be usable (installed and not disabled). When installing with the Firefox installer, this is the default.
    Firefox must have a default [profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles), and it must run using that profile at least once after the feature is enabled.
    Firefox must not have a language pack installed.
    [Firefox connection settings](https://support.mozilla.org/en-US/kb/connection-settings-firefox) must be configured to use the system proxy (this is the default).

**Comment by StFIT** [comment]
Thank you for your response.
No, in task schedule is no Mozilla entry.
And in Firefox Settings this is missing:
![grafik](https://user-images.githubusercontent.com/41438913/156419560-974273a7-abf3-4d32-ab91-e158fb6acf10.png)
I am quite sure this is ok:
Firefox must have been installed with the installer (not from, for example, a ZIP).
The [Mozilla Maintenance Service](https://support.mozilla.org/en-US/kb/what-mozilla-maintenance-service) must be usable (installed and not disabled). When installing with the Firefox installer, this is the default.
Firefox must have a default [profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles), and it must run using that profile at least once after the feature is enabled.
Firefox must not have a language pack installed.
[Firefox connection settings](https://support.mozilla.org/en-US/kb/connection-settings-firefox) must be configured to use the system proxy (this is the default).
I am pretty sure this is ok

**Comment by mkaply** [comment]
There should be the background update checkbox after that. Do you see it?
![image](https://user-images.githubusercontent.com/345868/156652694-aa055ad5-d6a9-4039-b76b-677f0f20914f.png)

**Comment by StFIT** [comment]
Yes.
Looks like this:
![grafik](https://user-images.githubusercontent.com/41438913/156759903-5414b46e-ac23-4d25-bdcd-61d35dda1517.png)

I tried a clean install and it´s still the same. So it has to be something with the GPO. What setting could interfere with that?

**Comment by mkaply** [comment]
I'm starting to think we just have a bug here. I'm having the same problem that I can't get the Background Updater to show up in the Task Scheduler.

Do you mind opening a bug here:

https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Application%20Update

So that we could have developers look at it?

**Comment by StFIT** [comment]
Hi Mike.
I have opened https://bugzilla.mozilla.org/show_bug.cgi?id=1758256

**Comment by mkaply** [comment]
I'm going to close this here and we'll followup in bugzilla. Thanks
