### ISSUE TITLE
Any reason for the restriction on SearchEngines -> Add? 

### ISSUE THREAD

**Issue by mainrs** [mozilla/policy-templates#856]
Is there a specific reason why only five engines can be added? I currently have over 12 installed and would like to add them all to my policies file.

**Comment by mkaply** [comment]
No, it was a completely arbitrary restriction in the GPO. There is no limit to the number of engines that can be added.

You can add as many as you want in policies.json or if you're using GPO, you can just duplicate the sections in the ADMX.

**Comment by mainrs** [comment]
Should this be fixed in the documentation then?

**Comment by mkaply** [comment]
It should. Just did it. Thanks!
