### ISSUE TITLE
Preferences - Locked status for 'Security' area not set correctly

### ISSUE THREAD

**Issue by xenothrox** [mozilla/policy-templates#857]
I've been currently analyzing the browser settings of our Firefox instances and stumbled across a few settings which do not work as I expected / configured (but I'm really sure it has worked in that configuration).

I'm running Firefox 91.5.0 ESR (64-bit), Policy templates V3.4, Windows 10 20H2.

We had the requirement to put some specific settings on the 'locked' status to prevent users from changing them. In that specific case, I'm talking about the 'Security' section under "about:preferences#privacy", 'Deceptive Content and Dangerous Software Protection'.

**Expected behavior:**
'locked' settings are locked and can not be changed under about:preferences#privacy

**Actual behavior:**
'locked' settings can still be changed under about:preferences#privacy

Under 'about:config' the related settings are marked as locked and can't be changed (as expected), but the GUI-section seems to cause some issues.

Additionally, I've tested the SafeBrowing function with the following sample site. I've put my focus on the first six öinks to check the SafeBrowsing feature.

https://testsafebrowsing.appspot.com/ 

Sometimes, the warnings are triggered correctly, sometimes not. I can't quiet figure out, what causes the behavior (for example: first link: warning displayed, sometimes not), I can't recreate it at the moment (for your information).

I'm not quiet sure if the missing 'locked' status in the GUI causes trouble here.

I've attached two screenshots of the about:config section and the corresponding GUI area as well as the content of the related 'Preferences' Policy in .json format.

The 'locked' settings under "Firefox Data Collection and Use" for example are correctly locked in the GUI section as well.

I've tested the behavior with several new profiles, but always the same result.
If you need any further information, please let me know.

![FF_Prefs_2](https://user-images.githubusercontent.com/54351662/151145696-dfd1475f-ecc4-4e77-b02c-43924b9862f4.png)
![FF_Prefs_1](https://user-images.githubusercontent.com/54351662/151145712-92eb5342-5f49-4a23-9951-f3a2bba1f68d.png)
[FF_Preferences.txt](https://github.com/mozilla/policy-templates/files/7940843/FF_Preferences.txt)

**Comment by mkaply** [comment]
Thanks for reporting this. We have a bug open for this but it hasn't been worked on:

https://bugzilla.mozilla.org/show_bug.cgi?id=1568275

These values don't map directly to preferences so the locking doesn't work correctly.

**Comment by mkaply** [comment]
I'm fixing this in Firefox, so there's nothing to do here.
