### ISSUE TITLE
Managing security.* via JSON-Preferences in GPO

### ISSUE THREAD

**Issue by WolfgangAndreas** [mozilla/policy-templates#860]
Hello There,
currently we are switching from a mozilla.cfg-managed environment to a "Preference"-based (JSON in GPO) and are encountering some difficulties.

In the description for Preferences (https://github.com/mozilla/policy-templates/blob/v3.5/README.md#preferences) there's a hint, that only some `security.`-settings are manageable.

In our case we would like to set `security.ssl.enable_ocsp_stapling` to `false`, which is not possible at this moment.

Is it planned to implement the remaining `security.*`-settings in near future? And if so, when would this be?
If not planned, how can we initiate a request? Is there a process that we can use for?

Kind regards,
Wolfgang

**Comment by mkaply** [comment]
So we do handle the security prefs one at a time as people request. There are some specific security settings that are problematic which is why we didn't implement them all. This is the right place to make the request and I've brought this up with the security team.

**Comment by WolfgangAndreas** [comment]
That's nice to hear  👍 
Thank you very much :-)

**Comment by WolfgangAndreas** [comment]
Good question.
I'll have to ask about the details again internally. As far as I understood, internally issued certificates were not accepted by FF anymore, when OCSP stapling got active.

**Comment by mkaply** [comment]
Were you able to get an answer to this?

**Comment by WolfgangAndreas** [comment]
Hey Michael, i'll come back to you as soon as i could clarify this after my vacation this week :-) Have a good time!

**Comment by mkaply** [comment]
Were you able to get an answer to this?

**Comment by mkaply** [comment]
I'm going to add OCSP support here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1771990

Closing since this will be tracked in bugzilla.
