### ISSUE TITLE
DisableFirefoxAccounts policy not working on the computer

### ISSUE THREAD

**Issue by hlekhi** [mozilla/policy-templates#861]
Hi there,

I am trying to configure the disablefirefoxaccounts policy on my computer for testing purposes. In the registry editor, I am not quite sure what should be the value data. I have set it to 1in the follow path location, but that doesn't work. 
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox
When I go to about:policies in the Mozilla Firefox browser, it gives me a policy error - Invalid parameters specified for DisableFirefoxAccounts. 

Can someone please tell what should be the data value?

Thanks in advance

**Comment by mkaply** [comment]
Here's a .reg file that shows how it works.

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox]
"DisableFirefoxAccounts"=dword:00000001
```

If you're using Windows professional, you can copy the policies files into C:\Windows\PolicyDefinitions and use gpedit.msc.
