### ISSUE TITLE
Feature request: Fine-grained extension permissions

### ISSUE THREAD

**Issue by williamtheaker** [mozilla/policy-templates#862]
Chrome supports denylisting certain permissions using the [blocked_permissions](https://support.google.com/chrome/a/answer/9867568?hl=en) key:

> If an extension requires a permission that you blocked, the user can’t install it. If users previously installed the extension, it will no longer load. If an extension contains a blocked permission as an optional requirement, it installs as usual. Then, while the extension is running, blocked permissions are automatically declined.

It also has keys to restrict which domains an extension can run on:
```
ExtensionSettings = {
 "abcdefghijklmnopabcdefghijklmnop": {
  "installation_mode": "allowed",
  "blocked_permissions": [
   "history"
  ],
 },
 "bcdefghijklmnopabcdefghijklmnopa": {
  "installation_mode": "force_installed",
  "allowed_permissions": [
   "downloads"
  ],
  "runtime_blocked_hosts": [
   "*://*.example.com"
  ],
  "runtime_allowed_hosts": [
   "*://good.example.com"
  ]
 }
}
```

Firefox adding support for the `blocked_permissions` key, along with `runtime_blocked_hosts` and `runtime_allowed_hosts`, would make it possible for admins to better scope permissions.

For example, the addon manifest for [SponsorBlock](https://addons.mozilla.org/en-US/firefox/addon/sponsorblock/) has an optional permission for "Access your data for all websites" (`"optional_permissions":["*://*/*"]`). It would be useful to allow the installation of SponsorBlock, but keep it from running on domains other than Youtube.

**Comment by mkaply** [comment]
Thanks for this. I agree this would be very useful, and I'll open a bugzilla bug to track this.

**Comment by TomPradat** [comment]
@mkaply Could you link the bugzilla bug here?

**Comment by mkaply** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1904061

Because this fix would live in Firefox, I'm going to close the bug here..
