### ISSUE TITLE
Application Handler not working after switching ESR 78 -> 91

### ISSUE THREAD

**Issue by offbytwo** [mozilla/policy-templates#863]
We have an application handler applied to open VMware VMRC on all of our customers management computers. After switching from ESR 78 to ESR 91, this policy no longer works (Firefox now asks to open the program in question, before it did not).

The policy is shown correctly in "about:policies" as active and is defined as following:

`{
   "policies" :
   {
      "Handlers" :
      {
         "schemes" :
         {
            "vmrc" :
            {
               "action" : "useSystemDefault",
               "ask" : false
            }
         }
      }
   }
}
`

When acknowledging the warning with the checkbox to not ask again, it works without acknowledging on subsequent tries, however on ESR 78 this works without acknowledging at all. I thought the <"ask" : false> is exactly for that case. Also strange is that the "handlers.json" file is not touched by the acknowledge operation and shows the following before and after it

`"vmrc":{"action":4}`

**Comment by mkaply** [comment]
Is it possible you're seeing this new dialog versus the ask dialog?

![image](https://user-images.githubusercontent.com/345868/158654831-0968298f-1a7b-427e-b834-98f42d6655d9.png)

This was added after Firefox 78 ESR. There is a new policy to add domains to it:

https://github.com/mozilla/policy-templates#autolaunchprotocolsfromorigins

**Comment by offbytwo** [comment]
@mkaply 

Thanks for your quick answer.
Meanwhile I tried out what's working and what not.
As you already said, dot at the beginning or asterisk is not working, however second level domain seem to whitelists all hosts in that domain. And don't forget the protocol at the beginning. Without it the rule does not work at all.
