### ISSUE TITLE
AD GPO add templates admx for server 2016

### ISSUE THREAD

**Issue by ekuul** [mozilla/policy-templates#868]
Hello

how to AD GPO add templates admx for server 2016. /admx, adml or adm/
GPO Firefox disable saved password.

**Comment by mkaply** [comment]
We have documentation on using Intune here:

https://support.mozilla.org/en-US/kb/managing-firefox-intune

The particular policy involved is https://github.com/mozilla/policy-templates/blob/master/README.md#offertosavelogins
