### ISSUE TITLE
GPOs dosn't apply

### ISSUE THREAD

**Issue by ToubieObie** [mozilla/policy-templates#87]
Hi,

I've added the ADMX Files to the Central Store, created a gpo with the policy for a home page.
But Firefox doesn't apply the policy. 

gpresult shows the gpo as applied...

Firefox Version: 59.0.3 (32-Bit)
Thank you

**Comment by mkaply** [comment]
Yes. Policy Support is coming in Firefox 60 which will be released Wednesday.
