### ISSUE TITLE
PromptForDownloadLocation does not work anymore on Firefox > 98

### ISSUE THREAD

**Issue by Magneticdud** [mozilla/policy-templates#873]
Suddenly after getting Firefox 98 all the computers in my company are downloading files in /downloads instead of prompting the download location. This is a big issue, users are confused, opening tickets "why is not asking me where to save".

**Comment by mkaply** [comment]
I just ran a quick check and I can't recreate, but I know some things changed with regard to helper applications.

When you go to:

![image](https://user-images.githubusercontent.com/345868/157504104-318704e4-c552-4ef3-962b-741b5b6897b3.png)

in preferences, is the second button checked?

**Comment by Magneticdud** [comment]
yes, the second button is checked, and it's greyed out (enforced by organization)

![image](https://user-images.githubusercontent.com/2940598/157510169-aaf99a39-d9a7-4c7b-8e40-a1896b7a55b1.png)

**Comment by mkaply** [comment]
I'm not seeing this behavior, it's still working for me and I don't know what the difference could be in your scenario.

Is it happening with all files or specific file types?

I was testing here and I saw the prompt on every download

https://www.thinkbroadband.com/download

IF I checked the other box, the download happened automatically.

**Comment by Magneticdud** [comment]
On a new profile it asks where to save (no open, no dialog), but on old profiles, which previously got updated to 98, it doesn't. Maybe because the update already "ruined" the profile by putting all filetypes to "save"

I gave up, I just changed the default browser to a different one as it's not consistent and it doesn't follow the company policies.

**Comment by mkaply** [comment]
I've been unable to recreate this no matter what I try. There is discussion of a similar problem in Bugzilla here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1758609#c5

And if this were happening, it would be a Firefox bug, not an issue with policies.
