### ISSUE TITLE
Problem with handlers by GPO

### ISSUE THREAD

**Issue by dimaiam** [mozilla/policy-templates#874]
Hello!

In my organization we want to put that "JNLP FILE" open with Java always.

I use "Handlers" template and put this:

```
"application/x-java-jnlp-file": {
   "jnlp": {
     "action": "useHelperApp",
      "ask": false,
      "handlers": [{
       "name": "javaws.exe",
       "path": "C:\\Program Files (x86)\\Java\\jre6\\bin\\javaws.exe"
  }]
 }
}
```
the result should be this
![2](https://user-images.githubusercontent.com/88244777/158686202-870f7720-6d9d-481c-8549-ed31a3d1586b.PNG)

Unfortunately it doesn't work, anyone can see my error?

Thanks you.

**Comment by mkaply** [comment]
What version of Firefox are you using? We only support launching JNLP files directly on the ESR because JNLP files are considered executable.

**Comment by dimaiam** [comment]
> What version of Firefox are you using? We only support launching JNLP files directly on the ESR because JNLP files are considered executable.

I was testing with version 98, but I have changed to version 91.7.1esr (64-bit). But it still doesn't work

**Comment by mkaply** [comment]
What's happening exactly? I'm wondering if maybe it's being served with a different mime type?

**Comment by dimaiam** [comment]
> What's happening exactly? I'm wondering if maybe it's being served with a different mime type?

Well I want to set JNPL File exactly like you can see in the image. I add this code to Handlers policy:

```
"application/x-java-jnlp-file": {
   "jnlp": {
     "action": "useHelperApp",
      "ask": false,
      "handlers": [{
       "name": "javaws.exe",
       "path": "C:\\Program Files (x86)\\Java\\jre6\\bin\\javaws.exe"
  }]
 }
}
```
When I go to the host and see the configuration, I have this error:
![3](https://user-images.githubusercontent.com/88244777/158689945-e1f91fdf-5b12-4d70-8769-727da9e39ff6.PNG)

**Comment by dimaiam** [comment]
> Ah, so you're missing a { at the beginning for the GPO.
> 
> ` { "application/x-java-jnlp-file": { "jnlp": { "action": "useHelperApp", "ask": false, "handlers": [{ "name": "javaws.exe", "path": "C:\\Program Files (x86)\\Java\\jre6\\bin\\javaws.exe" }] } } } `
> should work

Well seems to work:
![4](https://user-images.githubusercontent.com/88244777/158691645-79aeaaf6-b73e-47ba-8424-95ea843d5ef2.PNG)

But, the JNLP says "always ask"
![5](https://user-images.githubusercontent.com/88244777/158691690-d6cfeec8-2c68-4582-ae98-5634f23a3e8d.PNG)

**Comment by mkaply** [comment]
Sorry, I misread my own instructions.

You need to put more info in handlers.

<code>
{
	"mimeTypes": {
		"application/x-java-jnlp-file": {
			"action": "useHelperApp",
			"ask": false,
			"handlers": [{
				"name": "javaws.exe",
				"path": "C:\\Program Files (x86)\\Java\\jre6\\bin\\javaws.exe"
			}]
		}
	}
}
</code>

Can you try that?

You might also need to add the JNLP to an extensions section

<code>
{
	"mimeTypes": {
		"application/x-java-jnlp-file": {
			"action": "useHelperApp",
			"ask": false,
			"handlers": [{
				"name": "javaws.exe",
				"path": "C:\\Program Files (x86)\\Java\\jre6\\bin\\javaws.exe"
			}]
		}
	},
	"extensions": {
		".jnlp": {
			"action": "useHelperApp",
			"ask": false,
			"handlers": [{
				"name": "javaws.exe",
				"path": "C:\\Program Files (x86)\\Java\\jre6\\bin\\javaws.exe"
			}]
		}
	}
}
</code>

**Comment by dimaiam** [comment]
> Sorry, I misread my own instructions.
> 
> You need to put more info in handlers.
> 
> ` { "mimeTypes": { "application/x-java-jnlp-file": { "action": "useHelperApp", "ask": false, "handlers": [{ "name": "javaws.exe", "path": "C:\\Program Files (x86)\\Java\\jre6\\bin\\javaws.exe" }] } } } `
> Can you try that?
> 
> You might also need to add the JNLP to an extensions section
> 
> ` { "mimeTypes": { "application/x-java-jnlp-file": { "action": "useHelperApp", "ask": false, "handlers": [{ "name": "javaws.exe", "path": "C:\\Program Files (x86)\\Java\\jre6\\bin\\javaws.exe" }] } }, "extensions": { ".jnlp": { "action": "useHelperApp", "ask": false, "handlers": [{ "name": "javaws.exe", "path": "C:\\Program Files (x86)\\Java\\jre6\\bin\\javaws.exe" }] } } } `


this work perfect!. Thanks you!!!
{ "mimeTypes": { "application/x-java-jnlp-file": { "action": "useHelperApp", "ask": false, "handlers": [{ "name": "javaws.exe", "path": "C:\\Program Files (x86)\\Java\\jre6\\bin\\javaws.exe" }] } } }
