### ISSUE TITLE
policy request:  Disable various notifications

### ISSUE THREAD

**Issue by philipp-sumo** [mozilla/policy-templates#88]
It would be great to have a policy (or policies) to disable various notifications to be able to create a more seamless experience. i'd have thought in particular of:
* disabling the privacy policy tab on first launch.
* disable the prompt to refresh when an old profile is detected - "browser.disableResetPrompt" (this may be in the way for people who load a preconfigured profile)
* disable the prompt to refresh after a slow startup is detected - "browser.slowStartup.notificationDisabled"
* disabling snippets

**Comment by asadotzler** [comment]
Disabling snippets is covered in issue #82.

**Comment by mkaply** [comment]
privacy tab is covered in new Preferences policy.
Reset prompt is covered by disabling refresh firefox.
Disabling snippets is in the new new tab policy.

We don't show the slow startup notification unless your profile is over 90 days old (unused), so I don't think that's needed here.
