### ISSUE TITLE
Disable basic authentication policy in Firefox not available 

### ISSUE THREAD

**Issue by raksahoo** [mozilla/policy-templates#881]
Hi Team,

We are struggling to find policy/settings in Firefox to disable "HTTP basic authentication". For chromium based browser we can do that using https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#basicauthoverhttpenabled .

Can yo suggest.

Regards,
Rakesh

**Comment by mkaply** [comment]
We don't have a way to do that. I've opened a bug, since this would be a core Firefox change.

You can keep track of it here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1763671

**Comment by raksahoo** [comment]
Thanks a lot mkaply. Any tentative timelines will be much appreciated?

**Comment by mkaply** [comment]
Firefox 102 is our next ESR so I'll try to get something before then. So maybe 8 weeks.
