### ISSUE TITLE
"Encountered an error while parsing. DTD is prohibited" error message when opening gpedit.msc with newly-installed Firefox ADMX/ADML templates.

### ISSUE THREAD

**Issue by tromlet** [mozilla/policy-templates#886]
Hey all -

I've installed `firefox.admx` to `C:\Windows\PolicyDefinitions` along with it's corresponding `firefox.adml` to `C:\Windows\PolicyDefinitions\en-US`, and I get a strange error message (that pops up twice) whenever I try to fire up `gpedit.msc`:

```
Encountered an error while parsing.
DTD is prohibited.

File C:\Windows\PolicyDefinitions\firefox.admx, line 7, column 9
```

I looked at the code and couldn't find anything particularly egregious at line 7, column 9 - just an `r`. The second `r` in `resources`, in a line that looks like: `<resources minRequiredRevision="3.8"/>`

I don't understand. As it turns out, I get the exact same error with the Thunderbird ADMX templates.

I'm running Windows Server 2019 Standard x64 in a virtual machine.

**Comment by mkaply** [comment]
That's really odd. Where did you download the files from? The releases page?

**Comment by tromlet** [comment]
Actually no! I think I actually downloaded them straight from the github files themselves... I'll try the releases page, fair point. :P
