### ISSUE TITLE
Disable Creditcards autofill

### ISSUE THREAD

**Issue by asmith3006** [mozilla/policy-templates#887]
Can I use this JSON method to disable
```
extensions.formautofill.creditCards.enabled
extensions.formautofill.creditCards.available 
```

I don't want my users saving card details on their business machines.

**Comment by mkaply** [comment]
Yes, the Preferences policy allows you to set those preferences:

https://github.com/mozilla/policy-templates/blob/master/README.md#preferences

**Comment by WolfgangAndreas** [comment]
Hi, we noticed, that disabling is possible but not LOCKING the settings. Users can still enable the autofill-feature.
Is this a bug?

Regards,
Wolfgang

**Comment by mkaply** [comment]
As in, if you lock them in policy, they are still enabled in preferences?

**Comment by mkaply** [comment]
yep, that's a bug.

Do you mind opening a bug here:

https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Enterprise+Policies

IF not, I can.

**Comment by WolfgangAndreas** [comment]
Will open a Bug. Thank you for clarifying 😀
