### ISSUE TITLE
Handlers' syntax 

### ISSUE THREAD

**Issue by Quentincmr** [mozilla/policy-templates#888]
Hello,

I have an issue with the Handlers configuration. I can't find how to manage several extensions or mimetype.
For exemple when I  use 
```
{"mimeTypes": {
    "application/x-java-jnlp-file": {
      "action": "useSystemDefault",
      "ask": false}
},
  "extensions": {
    "pdf": {
      "action": "useHelperApp",
      "ask": false,
      "handlers": [{
        "name": "Adobe Acrobat",
        "path": "C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe"
      }]
}}}
```
It's working.
But I don't know how to add an other mimetype, it's not working anymore if I try the following
```
{"mimeTypes": {
    "application/x-iz-compressed": {
      "action": "useSystemDefault",
      "ask": false},
    "application/x-java-jnlp-file": {
      "action": "useSystemDefault",
      "ask": false},
"extensions": {
    "pdf": {
      "action": "useHelperApp",
      "ask": false,
      "handlers": [{
        "name": "Adobe Acrobat",
        "path": "C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe"
      }]
}}}
```
or
```
{"mimeTypes": {
    "application/x-iz-compressed": {
      "action": "useSystemDefault",
      "ask": false}
},
"mimeTypes": {
    "application/x-java-jnlp-file": {
      "action": "useSystemDefault",
      "ask": false}
},
"extensions": {
    "pdf": {
      "action": "useHelperApp",
      "ask": false,
      "handlers": [{
        "name": "Adobe Acrobat",
        "path": "C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe"
      }]
}}}
```
Could you help me with that ?  Thanks.

**Comment by mkaply** [comment]
You can't duplicate things in JSON, so it should be more like this:

<code>
{
	"mimeTypes": {
		"application/x-iz-compressed": {
			"action": "useSystemDefault",
			"ask": false
		},
		"application/x-java-jnlp-file": {
			"action": "useSystemDefault",
			"ask": false
		}
	},
	"extensions": {
		"pdf": {
			"action": "useHelperApp",
			"ask": false,
			"handlers": [{
				"name": "Adobe Acrobat",
				"path": "C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe"
			}]
		}
	}
}
</code>
