### ISSUE TITLE
Cookies_Allow (maybe also Cookies_AllowSession and Cookies_Block) wrong in ADMX or documentation 

### ISSUE THREAD

**Issue by MrJackLantern** [mozilla/policy-templates#889]
Hi,

either the ADMX file is wrong, or the documentation for it. After the policy failed a lot and I could not tell way, I looked up the ADMX file and what will be installed. So I discovered an error either on your ADMX or your documentation. With the id which stands in your ADMX file the policy works.

The documentation says (which doesn't work)

```
./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~Cookies/Cookies_Allow

<enabled/>
<data id="Cookies_Allow" value="1&#xF000;https://example.com"/>
```

But the ADMX will install the id as "Permissions" (which works) so it must look like this:

```
./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox~Cookies/Cookies_Allow

<enabled/>
<data id="Permissions" value="1&#xF000;https://example.com"/>
```

I don't have tested it for Cookies_AllowSession and  Cookies_Block but from my understanding this should also be wrong since the documentation and the ADMX are different here too.

Sorry for my bad english, it is not my mother tongue.

Have a nice day

**Comment by mkaply** [comment]
You are correct. That's mistake in the documentation. I'll fix. Thank you for finding it!

And never apologize for being able to speak two languages. I understood perfectly.
