### ISSUE TITLE
GPO "wish": Proxy Configuration

### ISSUE THREAD

**Issue by jakieu** [mozilla/policy-templates#89]
The most important GPO for me would be the proxy settings like Address, Port, Exceptions etc. This already works via "the old method" (autoconfig and .cfg) so it would be great to add this to the templates.

**Comment by HeiHei90** [comment]
You are able to configure Proxy-Settings with this ADMX-Templates. For example: autoconfig, http-proxy, ftp-proxy...etc

**Comment by HeiHei90** [comment]
It's in "Proxy Settings" under Firefox.

**Comment by jakieu** [comment]
I've been blind. Looked only in the subfolders -.-

**Comment by HeiHei90** [comment]
That means you are happy and want to close this Issue? :)

**Comment by jakieu** [comment]
Yes I'm happy with it - issue solved. ;-)
