### ISSUE TITLE
Translation: GPO 'Tracking Protection' missing information 

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#895]
GPO: Tracking protection (moved)
Translation language: de-de

Missing: The phrase `(moved)`.

_This gpo movement is a bit confusing. Could you describe where it is moved to or remove the old definition because it makes the reports strange._

**Comment by mkaply** [comment]
The readme doesn't need to be changed when things are moved in the Windows GPO. The content is in the same place as it always was:

https://github.com/mozilla/policy-templates/#enabletrackingprotection

All that changes is where it is located in the GPO UI and the Intune URLS.

Again, I'm unclear as to what you mean by "reports"

**Comment by htcfreek** [comment]
> Again, I'm unclear as to what you mean by "reports"
> 

This page/overview (exame image from web): https://images.app.goo.gl/78ZWrJ8KDcrhvh5b9

**Comment by htcfreek** [comment]
@mkaply 
I think the first step here is fixing the translation and add the movement note. (Can do this too.)

The second step is to evaluate how the code has to be improved that the overview/report is correct: Only the configured policies shows as configured. (Screenshot about the current behavior come tomorrow.)

**Comment by htcfreek** [comment]
Here is a screenshot of the problem with the incorrect report/configuration overview:
![image](https://user-images.githubusercontent.com/61519853/170662141-08d5e60d-96a2-451d-a32b-81318fa7de59.png)

**Comment by htcfreek** [comment]
> This seems like a Microsoft bug when something is duplicated in two places in the GPO.
> 
> What's the command you run to generate this specific report? My report doesn't show the Firefox items.

There is no command. The report is generated by the "Group Policy Management Application".

But you can try to reproduce it locally with the following steps:
1. Copy the admx and adml-folder to `c:\windows\policy definition`
2. set gpo via gpedit.msc
3. run `gpresult /h c:\mypath.html` in cmd
4. open html file and see if it contains the ff policies

**Comment by htcfreek** [comment]
> > This seems like a Microsoft bug when something is duplicated in two places in the GPO.
> > 

Yes. Seen today that some settings from ms templates are affected too. There is a conflict between printer.admx and ms-securityguid admx templates. 😅

> > What's the command you run to generate this specific report? My report doesn't show the Firefox items.
> 
> There is no command. The report is generated by the "Group Policy Management Application".
> 
> But you can try to reproduce it locally with the following steps:
> 1. Copy the admx and adml-folder to `c:\windows\policy definition`
> 2. set gpo via gpedit.msc
> 3. run `gpresult /h c:\mypath.html` in cmd
> 4. open html file and see if it contains the ff policies

**Comment by mkaply** [comment]
So I guess the real question is then do I need to have them in two places? Or if I move a policy and then remove the old one, will the new setting be set?

**Comment by htcfreek** [comment]
> So I guess the real question is then do I need to have them in two places? Or if I move a policy and then remove the old one, will the new setting be set?

You don't need two place  (Except when the regkey path/value changes.)

Then only thing that will happen is that the comments created by the admin will be lost/can't be assigned to show in the management ui anymore. But if you write a hint in the release notes admins can export a report/makes screenshot and create the comments again.

So I think it won't be a problem to remove the old entries in the admx.

(I can check how the comments are assigned to the gpo in the next hours.)
