### ISSUE TITLE
Bug: Telemtry policy incomplete 

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#897]
The telemetry policy does not set `browser.crashReports.unsubmittedCheck.autoSubmit2` to false and locked!

**Comment by mkaply** [comment]
It is off by default and you can use the preferences policy to set and lock it if you want.

The telemetry pref is focused on turning off things that were on.

**Comment by htcfreek** [comment]
@mkaply 
The preference works and the user can't change the setting. But it looks like a ui bug because the checkbox is not greyed out.
