### ISSUE TITLE
FR: Addon-Policy to force install warning

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#898]
There is no policy to set/enforce `xpinstall.whitelist.required` and this isn't supported as preference.

**Comment by htcfreek** [comment]
@mkaply 
Can you open an issue for this on the internal bug tracker please. Thank you.

**Comment by htcfreek** [comment]
> @mkaply 
> Can you open an issue for this on the internal bug tracker please. Thank you.

Have you opened it?

**Comment by htcfreek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1772409

**Comment by mkaply** [comment]
This was fixed.
