### ISSUE TITLE
FR: support for security.OCSP.enabled preference

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#899]
Please add support for the preference `security.OCSP.enabled` to enforce the cert ocsp check. This supported by Chrome and Edge.

**Comment by mkaply** [comment]
What is the name of the policy on Chrome/Edge?

**Comment by htcfreek** [comment]
> What is the name of the policy on Chrome/Edge?

`Enable online OCSP/CRL checks`

**Comment by mkaply** [comment]
So we already enable the checks, so you wouldn't need to set them via policy.

But as you point out, we don't set security.OCSP.require

I wonder if Require online OCSP/CRL checks for local trust anchors maps to that.

**Comment by htcfreek** [comment]
> So we already enable the checks, so you wouldn't need to set them via policy.

How is this set? What do you mean? Especially as there is a ui checkbox that can be changed by user which refers to the preference `security.OSCP.enabled`.

**Comment by mkaply** [comment]
I'm simply saying it is on by default. I assume you want to lock it so a user can't turn it off?

**Comment by htcfreek** [comment]
> I'm simply saying it is on by default. I assume you want to lock it so a user can't turn it off?

yes

**Comment by htcfreek** [comment]
> > What is the name of the policy on Chrome/Edge?
> 
> `Enable online OCSP/CRL checks`
> 
> (And additional there is this feature too: `Require online OCSP/CRL checks for local trust anchors`.)

FYI: https://chromeenterprise.google/policies/#EnableOnlineRevocationChecks

**Comment by htcfreek** [comment]
Will this be supported in a future release?

**Comment by mkaply** [comment]
Yes, I'll be opening a bug to get this added.

**Comment by mkaply** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1771990

I'm going to close this issue since it will be handled in bugzilla.

**Comment by serkonda7** [comment]
I'm setting up firefox in a lab environment where I need to turn of `security.ocsp.enabled`.
How is the progress on supporting this in policies?

**Comment by mkaply** [comment]
I kept thinking I needed to make this a policy, but I'm just going to add these to preferences. Should be in Firefox within a month or so.
