### ISSUE TITLE
Why no policies for telemetry settings?

### ISSUE THREAD

**Issue by MichiFr** [mozilla/policy-templates#9]
The subjects tells it already: Why no policies for telemetry settings?

Still lots of work to be done manually if the devs won't release a full set of policies. And for enterprise usage it is important to stop FF from sending out telemetry data to various servers in the wild.

**Comment by mkaply** [comment]
They just aren't in yet. I'm implementing the ADMX changes as we implement the policies.

Telemetry is covered here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1429153
