### ISSUE TITLE
GPO "wish": User Agent String

### ISSUE THREAD

**Issue by BryannaM** [mozilla/policy-templates#90]
Hello, we make use of SAML authentication and we want to support windows integrated authentication. Microsoft relies on UserAgents with ADFS to see who gets the forms based sign on and who gets the integrated. 

To make it easy for the program to understand what clients are intranet clients that support it, the easiest thing is to glue a custom string at the end of the user agent with our company name to identify which are our domain joined internal clients. 

So for example it might look like this

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0 CompanyName

Internet Explorer supports this via group policy but Firefox having it would be very helpful.

**Comment by HeiHei90** [comment]
This as Gpo?

https://www.howtogeek.com/113439/how-to-change-your-browsers-user-agent-without-installing-any-extensions/

**Comment by BryannaM** [comment]
I really don't need to be able to modify the whole user agent string but, ya being able to just set it with a simple Group Policy would be awesome and make my users happy we can do SSO with passthrough auth with something other then Internet Explorer.

**Comment by mkaply** [comment]
Interesting. I didn't know about this one. Does it have to be at the end?

**Comment by mkaply** [comment]
I had been told in the past that the best way to not break things was to put it in the semicolon section - Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0; CompanyName; Anything you want) Gecko/20100101 Firefox/59.0

I'll talk to our webcompat folks.

**Comment by BryannaM** [comment]
Well you are probably right, the sticking it at the end is just what i heard with IE from Microsoft and well if you have heard difference it is probably true. For me it does not exactly matter I would just appreciate some way to add an extra string. I really appreciate y'all looking at this.

**Comment by Wizard13** [comment]
Is there any progress with this or is it abandoned?

**Comment by mkaply** [comment]
We're not going to do this. I would recommend using an extension that does this.
