### ISSUE TITLE
FR: Disable network protocol quic

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#900]
Please add support for a policy to disable the network protocol Quic like in MS Edge and Google Chrome. This should be disabled for security reasons. If it is enabled firewalls can't do their work correctly in some cases. (https://www.networkstraining.com/what-is-quic-protocol/)

I read somewhere that the quic protocol is part of HTTP3 but I wasn't sure if it is a good idea to disable HTTP3 (`network.http.http3.enabled`). Or is quic and HTTP3 the same?

**Comment by htcfreek** [comment]
https://chromeenterprise.google/policies/#QuicAllowed

**Comment by mkaply** [comment]
After talking to the Networking folks, Quic is the HTTP3 protocol, so they are the same.

So if you want to disable Quic, you can use that preference. I'm not going to add a specific policy for this.
