### ISSUE TITLE
Bug: German report incorrect for DNS-over-HTTPS

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#901]
The german reports (english ones not verified) are incorrect for the policies under `/Mozilla/Forefox/DNS over HTTPS`: The reports says `not configured`even if the policies are configured. Instead the configured values are shown under `/Mozilla/Firefox` in the policy `Configure DNS-over-HTTPS`.

**Comment by mkaply** [comment]
I'm sorry, but I don't understand what you mean by "reports"

Are you saying there is an issue with the translation or with the code?

Adding @vossni who helped with some of the German translation.

**Comment by vossni** [comment]
Ich vermute du meinst den Bericht den man für Gruppenrichtlinien erstellen kann oder? Verstehe ich es richtig, du erstellst diesen Bericht und obwohl die Einstellungen konfiguriert sind, werden diese im Bericht als "Nicht konfiguriert" angezeigt?

**Comment by htcfreek** [comment]
> I'm sorry, but I don't understand what you mean by "reports"

This page/overview (example image from web): https://images.app.goo.gl/78ZWrJ8KDcrhvh5b9

**Comment by htcfreek** [comment]
@mkaply 
The thing to do is to evaluate how the code has to be improved that the overview/report is correct: Only the configured policies shows as configured. (Screenshot about the current behavior come tomorrow.)

Btw I can fix translation here as well if you want me to do this. 😉

**Comment by vossni** [comment]
I can confirm the behavior. I have set the settings "Enabled" and "Locked" under Mozilla/Firefox/DNS over HTTPs to the value "Disabled" and "Enabled" respectively, but in the overview of settings in the group policy management both settings are displayed as "Not configured".

**Comment by htcfreek** [comment]
> I can confirm the behavior. I have set the settings "Enabled" and "Locked" under Mozilla/Firefox/DNS over HTTPs to the value "Disabled" and "Enabled" respectively, but in the overview of settings in the group policy management both settings are displayed as "Not configured".

But the old settings position is shown as configured. Correct?

**Comment by vossni** [comment]
Yes, the "moved" settings are shown as configured.

**Comment by htcfreek** [comment]
Here are the screenshots:

![image](https://user-images.githubusercontent.com/61519853/170663205-4cc4dd60-e086-4050-abc1-f0a9a2b3d576.png)

![image](https://user-images.githubusercontent.com/61519853/170663287-3cab7895-5e13-4086-a4b0-0eb925a43c3b.png)

**Comment by mkaply** [comment]
This is fixed by the same change that fixed #895

**Comment by htcfreek** [comment]
@mkaply 
I can confirm that bug is gone and the reports are correct now. Thank you for fixing this annoying bug
