### ISSUE TITLE
FR: Support for HTTPS-Only-Mode

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#902]
Please add support for the configuration of HTTPS-Only-Mode inclusive locking the UI or allow the configuration of the following preferences:
* `dom.security.https_only_mode`
* `dom.security.https_only_mode_pbm`

**Comment by mkaply** [comment]
These can be set via the Preferences policy.

**Comment by htcfreek** [comment]
> These can be set via the Preferences policy.

Aaah. You are right. I didn't see the listing of `dom.`.

**Comment by htcfreek** [comment]
@mkaply 
Does setting the preference also looks the ui?

**Comment by mkaply** [comment]
In this case, no.

I already have a bugzilla bug opened to fix this. So it's on our list.

https://bugzilla.mozilla.org/show_bug.cgi?id=1739714
