### ISSUE TITLE
FF Unable to parse JSON for Preferences

### ISSUE THREAD

**Issue by SemperFu** [mozilla/policy-templates#908]
I am using the latest DISA STIGS which include Firefox V6R2 for DoD Policies. I've tested this in multiple environments so it seems to be their policy that is the issue. But Firefox does not like it. I've tried modifying a few things to test but still get errors. Was hoping someone could point out what may be the issue so I can go back to DISA to get this fixed. 

```
<enabled/>
<data id="JSON" value='
{
"security.default_personal_cert": {
"Value": "Ask Every Time",
"Status": "locked"
},
"browser.search.update": {
"Value": false,
"Status": "locked"
},
"dom.disable_window_move_resize": {
"Value": true,
"Status": "locked"
},
"dom.disable_window_flip": {
"Value": true,
"Status": "locked"
},
"browser.contentblocking.category": {
"Value": "strict",
"Status": "locked"
},
"extensions.htmlaboutaddons.recommendations.enabled": {
"Value": false,
"Status": "locked"
}
}'/>
```

**Comment by mkaply** [comment]
What error are you seeing?

That's definitely valid JSON.

Are you seeing an error in about:policies?

**Comment by SemperFu** [comment]
> What error are you seeing?
> 
> That's definitely valid JSON.
> 
> Are you seeing an error in about:policies?

Yes I see "Unable to parse JSON for Preferences" in about policies.

> it has to look like this:
> 
> I know these suggestions and the comments are a bit stupid.

Looks like that works. I will reach out to DISA to get it fixed. Thank you for the quick response.

**Comment by mkaply** [comment]
I work with DISA on the STIG, so I can help get it fixed.

I guess I'm misunderstanding something. Your example was the version for Intune, the other version by htcfreek was what to use in the policy directly.

Where were you placing this JSON?

**Comment by SemperFu** [comment]
@mkaply I already contacted them and they corrected this. This was going in a GPO. It will be released in the July GPO package. Thank you for your help.
