### ISSUE TITLE
Locked settings: Don't know why

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#909]
The following settings are locked on one of my machines but not on the other:
![grafik](https://user-images.githubusercontent.com/61519853/171680480-3e9b2bee-b0d3-4bea-a0e5-23f503798795.png)

Do you know when they are locked? The strange thing is that both machines have the same policy set. (I don't find a difference that makes sense.)

**Comment by mkaply** [comment]
Those are UserMessaging - ExtensionRecommendations and FeatureRecommendations

**Comment by htcfreek** [comment]
But i have disabled it on the client where the screenshot comes from. And I have not set it on the machine where it works. 🤔

**Comment by htcfreek** [comment]
> You said "please reopen the issue until tomorrow"

Yes but this was on Thursday. 😅 So you can close it.
