### ISSUE TITLE
Adress bar suggestions settings not locked

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#910]
Adress bar suggestions settings in UI not locked even if "Adressbar Sugestions" policy under "User-Messaging" group is disabled. It is only a ui bug as the sugestions are gone.

**Comment by mkaply** [comment]
That sounds like a translation issue. User MEssaging doesn't control address bar suggestions.

**Comment by htcfreek** [comment]
> > Does "Firefox 77 or later" mean only on 77 or not on esr branch?
> 
> IT means it didn't go on the ESR until the next ESR after 77. In this specific case, we didn't backport to the 68 ESR, it went on the 78 ESR.
> 

What is with esr 91?

> > What does it control then. The German name is "Address bar suggestions".
> 
> So we had this feature that as you surf the web, go to websites, we could recommend extensions or other Firefox features (extension recommendations, feature recommendations). The recommendations happened in the URL bar.
> 
> It looked like this:
> 
> https://techdows.com/2018/12/firefox-64-release-version-to-limit-cfr-recommended-add-ons-to-three-only.html
> 
> So those should translate the same as the two items you saw the disabling problems with.
> 

Do i need this and "recommodations for extension" set to disabled?

**Comment by htcfreek** [comment]
> > What is with esr 91?
> 
> Once it landed, it was in all subsequent versions.

So this means the user messaging pokicies marked as "ff 71 only" have outdated version info as they should work in esr 91?

> > Do i need this and "recommodations for extension" set to disabled?
> 
> Yes. the Shield option does this as well, but I'm going to remove that (to fix your bug)

good to know. then i will not set it. It wasn't set for months without any complaints. 😅

**Comment by mkaply** [comment]
> So this means the user messaging pokicies marked as "ff 71 only" have outdated version info as they should work in esr 91?

Yeah, those are poorly worded. What it was meant to say at that point in time was "Firefox 71 and later, but not the Firefox 68 ESr"

Most policies are backported to the ESR, those weren't.

**Comment by mkaply** [comment]
> Please be patient. When you remove it without a new one that links to the reg key you produce dead keys in the policy file. So in that case you should add a very very big hint to the release notes!!

Sorry, I wasn't clear. I'm only going to remove the fact that the Shield policy modifies those two additional preferences that are in UserMessaging. Setting those prefs shouldn't have been done in two places.

And never remove anything from the GPO, I just mark it as deprecated for the reason you said.

**Comment by htcfreek** [comment]
> > Please be patient. When you remove it without a new one that links to the reg key you produce dead keys in the policy file. So in that case you should add a very very big hint to the release notes!!
> 
> Sorry, I wasn't clear. I'm only going to remove the fact that the Shield policy modifies those two additional preferences that are in UserMessaging. Setting those prefs shouldn't have been done in two places.

Okay this means later I have to set the following at the same time together to disable all of them:
- studies: disabled
- recommendations for extensions: disabled
- recommendations for futures: disabled
- search bar inventions: disabled

Is that correct?

**Comment by mkaply** [comment]
Yes, that is correct.

**Comment by htcfreek** [comment]
@mkaply 
Any updates on this or ist there any time frame when this might be fixed? I will check later if it is still an issue.

**Comment by mkaply** [comment]
So this should be fixed. What was missing is that I didn't mention "Locked" for User Messaging in the docs or GPO.

I have added it now, so these can be locked. Can you check?

**Comment by htcfreek** [comment]
I will check this within the next days. I have to update some settings that are not configuration because of the "lock collision" bug with that is fixed now.

Can you tell me the exact UI path that should be locked now? I am a bit confused with the many different places (Search suggestions, feature suggestions, address bar suggestions).

**Comment by htcfreek** [comment]
> You were specifically asking about UserMessaging.
> 
> You can add Locked to that and it will lock those preferences.

Does UserMessaging has no check boxes in the UI?

**Comment by htcfreek** [comment]
> > You were specifically asking about UserMessaging.
> > You can add Locked to that and it will lock those preferences.
> 
> Does UserMessaging has no check boxes in the UI?

I think I got it. There are only UI controls in the settings ui for the following three things:
- studies: disabled
- recommendations for extensions: disabled
- recommendations for features: disabled

And `search bar inventions: disabled` has now menu in the settings tab.

**Comment by htcfreek** [comment]
I didn't had time to test it yet.

**Comment by htcfreek** [comment]
This is fixed with ESR 115.0
