### ISSUE TITLE
Mixed Preferences not possible

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#912]
It isn't posible to mix the preferences policy from user and machine. Then only the values form machine are set.

There should be a Note in the policy description.

**Comment by mkaply** [comment]
This is true of GPO in general. I don't feel a need to call this out specifically. On Windows it always reads either user or machine and doesn't combine them,

**Comment by htcfreek** [comment]
> This is true of GPO in general. I don't feel a need to call this out specifically. On Windows it always reads either user or machine and doesn't combine them,

Not every setting. The zone list of ie does combine as far as I know.
