### ISSUE TITLE
BUG: Conflict between DisableFirefoxStudies and UserMessaging

### ISSUE THREAD

**Issue by htcfreek** [mozilla/policy-templates#914]
While investigating #909 I found the following bugs:
- The policies for DisableFirefoxStudies and UserMessaging (ExtensionRecommendations, FeatureRecommendations) conflicting.
- The policies for UserMessaging (ExtensionRecommendations, FeatureRecommendations) don't disable the settings ui.

If you set the policy DisableFirefoxStudies the ui elements for the following settings are unchecked and looked:
- Settings UI > General > Browsing > Recommend extensions as you browse
- Settings UI > General > Browsing > Recommend features as you browse

If you the disable the policies for ExtensionRecommendations and FeatureRecommendations the ui settings aren't looked anymore. It is even possible to enable the settings regardless of the state of DisableFirefoxStudies.

_Note: We configure the policies using Active Directory GPOs._
_FF 91.10.0esr; ADMX v3.10_

![image](https://user-images.githubusercontent.com/61519853/171825637-98bcd740-d6fe-423c-918a-a21407b163ce.png)

![image](https://user-images.githubusercontent.com/61519853/171827466-ece285db-624f-4abf-87f7-b6c145d0ef94.png)

![image](https://user-images.githubusercontent.com/61519853/171828180-6e2862d1-c1a4-4035-b1b0-53ff210b3fe7.png)

**Comment by htcfreek** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1772503
https://bugzilla.mozilla.org/show_bug.cgi?id=1772504

**Comment by mkaply** [comment]
Thanks, I See the problem. I'm going to close this bug and take care of it in Bugzilla.
