### ISSUE TITLE
Is the ExtensionSettings installation mode "removed" supported?

### ISSUE THREAD

**Issue by ding-dang-do** [mozilla/policy-templates#919]
In Chromes full description of the [ExtensionSettings](https://www.chromium.org/administrators/policy-list-3/extension-settings-full/) there is a fifth installation mode called `removed`. I know it's not part of the Mozilla [documention](https://github.com/mozilla/policy-templates/tree/v3.9#extensionsettings), but I tried it, because this is a very interesting mode. My hope was, it's already supported.

So, it does something, but not what it should do. The Chrome documentation states:
> **blocks** installation of the extension and removes it from the device if already installed.

I tested it with the latest templates v3.10 for Firefox 91.10ESR and the result is:
> **allows** installation of the extension and removes it from the device if already installed.

The extension can be installed by the user, but is removed with every Firefox restart.

Is this a feature, a bug or just a random result?

Greets ddd

**Comment by mkaply** [comment]
It's a bug. I never added support for removed. What's the difference between blocked and removed?

**Comment by mkaply** [comment]
In our case, blocked does the same as removed:

"Blocks installation of the extension and removes it from the device if already installed."

I'm not sure why they differentiated the two. If you block an extension, you want it removed.
