### ISSUE TITLE
GPO wishes - What we still have set in our cfg

### ISSUE THREAD

**Issue by Greensystemsgo** [mozilla/policy-templates#92]
lockPref("app.update.auto", false);
lockPref("app.update.enabled", false);
lockPref("app.update.service.enabled", false);
lockPref("app.update.silent", false);
lockPref("app.update.staging.enabled", false);
lockPref("geo.enabled", false);
lockPref("permissions.default.camera", 2);
lockPref("permissions.default.desktop-notification", 2);
lockPref("permissions.default.geo", 2);
lockPref("permissions.default.microphone", 2);
lockPref("browser.search.suggest.enabled", false);

More of a Mozilla issue then a gpo issue, but we would like to remove the ability for users to delete history. We do retain everything on the firewall level but would be nice to keep local as well.

**Comment by mkaply** [comment]
FYI, support for the following policies is in Firefox 62 (and ESR 60.2)

lockPref("permissions.default.camera", 2);
lockPref("permissions.default.desktop-notification", 2);
lockPref("permissions.default.geo", 2);
lockPref("permissions.default.microphone", 2);

**Comment by mkaply** [comment]
These should be mostly available at this point. If you don't want the update service, you can choose not to install it.

I'm working on a policy to prevent history deletion.
