### ISSUE TITLE
Fix release description

### ISSUE THREAD

**Issue by r0v** [mozilla/policy-templates#920]
Hi, I found an error in last policy-templates release description
"Policy templates for Firefox 101 and Firefox ESR 91.10". Link to README
has incorrect value (current tag was created without "v" before major
number) which redirect to unexist site. It's not big deal but makes
whole repo consistent and clear. I hope you find it useful in some way.

**Comment by mkaply** [comment]
Thanks. I had messed up the release name which messed up other things.
