### ISSUE TITLE
Feature Request: Please make DisableAppUpdate available to non-ESR

### ISSUE THREAD

**Issue by bp88** [mozilla/policy-templates#93]
In our enterprise environment, we do not necessarily deploy Firefox ESR. However, our users do not have admin access. We would like to disable updates as we already push out Firefox to our end users. We do not want to be forced to use Firefox ESR which only gets security updates for the most part. This restriction for ESR only users is a bit weird to us and we request that you reconsider this and allow this preference to be available to the regular Firefox stable release.

**Comment by bp88** [comment]
@MichiFr I just saw your request being closed in #83. This is certainly not a good look for Mozilla. Google Chrome certainly doesn't have such restrictions. Weird that they are going with ESR only for some of these enterprise policies.

**Comment by mkaply** [comment]
I'm planning to move some of the pref based policies to work on RR and continuing to make things easier.

> Google Chrome certainly doesn't have such restrictions. 

This is not true. On Windows, Chrome has a number of policies that only work if you are connected to an ActiveDirectory server.

**Comment by jjurkus** [comment]
All my home users (including myself) are using Firefox ESR.
No problems there, only some sites think you are on a newer version, so they send you to another page and say certain plugins don't work anymore. While on other sites those plugins continue working.

**Comment by mkaply** [comment]
This is resolved. Starting with Firefox 62, all policies except search are available on RR either as machine GPO or in policies.json
