### ISSUE TITLE
Trouble with enterprise policy using snap package

### ISSUE THREAD

**Issue by tresf** [mozilla/policy-templates#936]
Hi,

I'm using Ubuntu 22.04 which currently defaults to the Firefox snap version 103.0.

I'm attempting to write a custom `policies.json`.  Previously, I did this by installing the file to the Firefox installation directory, but snaps make this impossible due to a read-only filesystem.

According to [this Ubuntu Discourse conversation](https://discourse.ubuntu.com/t/how-to-customize-the-firefox-snap-with-enterprise-policies/23074), the fallback location is `/etc/firefox/policies/policies.json`.  The answer even goes into detail explaining that this feature may take some time to land.

Unfortunately, I'm having some difficulties getting the policy to work.

Contents of `/etc/firefox/policies/policies.json`:

```json
{
  "policies": {
    "Certificates": {
      "Install": ["mycert.crt"]
    }
  }
}
```

Contents of `/usr/lib/mozilla/certificates`

```
ls -al /usr/lib/mozilla/certificates
total 12
drwxr-xr-x 2 root root 4096 Jul 26 13:51 .
drwxr-xr-x 3 root root 4096 Jul 26 13:35 ..
-rw-r--r-- 1 root root 1440 Jul 26 13:51 mycert.crt
```

What's needed to get the snap to recognize my policy?

**Comment by mkaply** [comment]
What do you see when you go to about:policies?

(Want to verify its being read at all)

We definitely made this work

https://bugzilla.mozilla.org/show_bug.cgi?id=1717216

**Comment by mkaply** [comment]
So now that I think about this more, you can't load a CRT this way. The snap can't read /usr/lib/mozilla/certificates. You would have to put the certs in /etc/firefox/policies as well and use a fully qualified path

**Comment by tresf** [comment]
Slight update... the policy file is being read, as a baseline test, I did the following, and it works.

```
{
  "policies": {
    "Homepage": {
      "URL": "http://google.com/"
    }
  }
}
```

... so I believe for some reason my certificate isn't being picked up.  I tried hard-coding the full path and that didn't seem to work either.

**Comment by tresf** [comment]
> So now that I think about this more, you can't load a CRT this way. The snap can't read /usr/lib/mozilla/certificates. You would have to put the certs in `/etc/firefox/policies` as well and use a fully qualified path


Thanks, so the following should be OK?

Contents of /etc/firefox/policies

```
ls -al /etc/firefox/policies
total 12
drwxr-xr-x 2 root root 4096 Jul 26 13:51 .
drwxr-xr-x 3 root root 4096 Jul 26 13:35 ..
-rw-r--r-- 1 root root 1440 Jul 26 13:51 policies.json
-rw-r--r-- 1 root root 1440 Jul 26 13:51 mycert.crt
```

... or should I use a subfolder for these?

**Comment by mkaply** [comment]
I think that should be fine.

**Comment by tresf** [comment]
Thanks, that works. :)
