### ISSUE TITLE
GPO Wish List (DoD STIG Configuration)

### ISSUE THREAD

**Issue by infopowerbroker** [mozilla/policy-templates#94]
My compliance guy likes to use DoD STIG, and he's looking for the following values. Any chance these can get placed in the GPO (Some values are in here, but I didn't necessarily see the lock option in the GPO). (I tried to check for which ones were already done, but the lockpref was throwing me off...)
***
lockPref("browser.download.dir", "N:");
lockPref("browser.download.downloadDir", "N:");
lockPref("app.update.enabled", false);
lockPref("extensions.update.enabled", false);
lockPref("browser.shell.checkDefaultBrowser", false);
lockPref("browser.search.update", false);
lockPref("browser.formfill.enable", false); 
lockPref("signon.prefillForms", false);
lockPref("dom.disable_open_during_load", true);
lockPref("dom.disable_window_move_resize", true); 
lockPref("dom.event.contextmenu.enabled", false);
lockPref("dom.disable_window_status_change", true); 
lockPref("dom.disable_window_flip", true);
lockPref("dom.disable_window_open_feature.status", true); 
lockPref("security.warn_leaving_secure", true); 
lockPref("security.default_personal_cert", "Ask Every Time"); 
lockPref("signon.rememberSignons", false);
lockPref("xpinstall.whitelist.required", true);
lockPref(“network.protocol-handler.external.shell”,false); 
lockPref("security.tls.version.min" ,"2"); 
lockPref(“security.tls.version.max", "3");
lockPref("plugin.disable_full_page_plugin_for_types", "application/pdf,application/doc,application/xls,application/bat,application/ppt,application/mdb,application/mde,application/fdf,application/xfdf,application/lsl,application/lso,application/lss,application/iqy,application/rqy,application/xlk,application/pot,application/pps,application/dot,application/wbk,application/ps,application/eps,application/wch,application/wcm,application/wbi,application/wb1,application/wb3,application/rtf,application/wch,application/wcm,application/ad,application/adp,application/xlt, application/dos, application/wks");
lockPref("privacy.item.history", false)
***
Please let me know if I can provide any additional information. The STIG document can be downloaded from https://iase.disa.mil/stigs/app-security/browser-guidance/Pages/index.aspx

**Comment by infopowerbroker** [comment]
I have seen a bunch of organizations pick and choose settings from the STIG (and write up exceptions for various business requirements), so making them individually selectable would probably be ideal (as compared to an 'apply DISA STIG settings' single option). (Plus, the next revision of the STIG guidance could reference the GPO setting by name, which would make it easy for the IT admin to find).

**Comment by mkaply** [comment]
FYI, a number of these preferences aren't used anymore or default to the value that the DOS STIG specifies.

We're looking at the rest.

**Comment by mkaply** [comment]
All of the relevant prefs are now in our Preferences policy in Firefox 68.
