### ISSUE TITLE
Can't figure out ExtensionSettings Policy to block specific extension updating

### ISSUE THREAD

**Issue by MonfGeiger** [mozilla/policy-templates#944]
im trying to parse all the stuff in this section [here](https://github.com/mozilla/policy-templates/blob/master/README.md#ExtensionSettings) so I can block a specific extension from EVER (if possible) receiving any updates whatsoever no matter how many times I check for updates manually. its quite a bit confusing for me, got no clue what im doing

I tried to use the Windows (GPO) json example as a base and this is what I got
```
{
  "{bee8b1f2-823a-424c-959c-f8f76c8b2306}": {
    "updates_disabled": "true"
  }
}
```
the id is there, the line I want to use is there as well. at first, I tried putting this in via the GPO editor in the extension settings thing, but i kept getting it wrong, then I tried the /distribution/policies.json file method and I keep getting THAT wrong as well. pls halp

**Comment by mkaply** [comment]
That is correct, but it should be true, not "true"

**Comment by MonfGeiger** [comment]
would this work if i copy/pasted it in the extension management section of the GPO editor, or would the format above change any?

**Comment by MonfGeiger** [comment]
also tried the .json file again, got an error saying "Policies file doesn't contain a 'policies' object"

**Comment by MonfGeiger** [comment]
just used the GPO method and it worked, that popup blocker extension didnt get detected when searching for an update. ill copy both to keep them as a template, but if I wanted to have multiple entries for the GPO editor method of blocking updates, how would I add/format that?

**Comment by MonfGeiger** [comment]
yep :|

**Comment by mkaply** [comment]
You would add the additional entries into the block:

```
{
	"policies": {
		"ExtensionSettings": {
			"{bee8b1f2-823a-424c-959c-f8f76c8b2306}": {
				"updates_disabled": "true"
			},
			"extensionid2@foo.com": {
				"updates_disabled": "true"
			}
		}
	}
}
```
