### ISSUE TITLE
GPO wish - Split HomePage and Startup Preferences

### ISSUE THREAD

**Issue by mwdesign** [mozilla/policy-templates#95]
Have set a HomePage URL and locked it but unable to then change how Firefox Starts Up. 
Would like to see the HomePage locked to a particular URL but when firefox starts up, 'Show your windows and tabs from last time'. It seems that these two policies are combined into the setting.

**Comment by mkaply** [comment]
I'll look at adding a policy for that.

**Comment by mkaply** [comment]
This was added in Firefox 64/60.4

There's a new option on Homepage - StartPage
