### ISSUE TITLE
How to permanently disable Firefox "Suggest"

### ISSUE THREAD

**Issue by WolfgangAndreas** [mozilla/policy-templates#951]
Hi there,

for one of our Customers (German Goverment Provider of IT-Solutions) we need to permanently disable the Feature "Firefox Suggest" because we suspect, that it could be sending "unwanted" data traffic.

We understand, that this feature is currently only available in the US. But in case it will be rolled out to Europe as well, we would like to ensure that it is disabled in advance.

We already disabled the basic "search suggestions" via GPO but we can not be sure if this has an effect on the new "firefox suggest" feature.

Is there a possible configuration via GPO to disable it?

Thank you in advance,
Wolfgang

**Comment by mkaply** [comment]
you can use the Preferences policy to disable it.

The preferences are documented here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1749535#c3

**Comment by WolfgangAndreas** [comment]
Hi Michael,
thank you very much :-)

This was very helpful.

Regards,
Wolfgang
