### ISSUE TITLE
Feature request: add ability to disable Firefox Suggest suggestions

### ISSUE THREAD

**Issue by williamtheaker** [mozilla/policy-templates#953]
I have `SearchSuggestEnabled` disabled because I don't like my browser sending requests based on what I enter into the address bar, other than the URI I'm trying to visit.

Despite having `SearchSuggestEnabled` set to false, a recent update (105.0.1 maybe?) enabled "suggestions from web" and "suggestions from sponsors", which feels counter to the policy configuration. I only really want to disable those two types of suggestions, but defining a list of enabled Firefox Suggestion types could work.

**Comment by mkaply** [comment]
You can use the preferences policy to disable them.

See:

https://bugzilla.mozilla.org/show_bug.cgi?id=1749535#c3

**Comment by williamtheaker** [comment]
Thanks that's good enough for me. If anyone else has this issue, this policy snippet should get you started:
```
{
  "policies": {
    "Preferences": {
      "browser.urlbar.suggest.quicksuggest.dataCollection.enabled": {
        "Value": false,
        "Status": "default"
      },
      "browser.urlbar.suggest.quicksuggest.nonsponsored": {
        "Value": false,
        "Status": "default"
      },
      "browser.urlbar.suggest.quicksuggest.sponsored": {
        "Value": false,
        "Status": "default"
      },
    }
  }
}
```
