### ISSUE TITLE
'DisableTelemetry' policy vs 'toolkit.telemetry.unified'

### ISSUE THREAD

**Issue by DavidLaun** [mozilla/policy-templates#955]
One of our customers is going for a "silent client". Therefore we disabled the Firefox telemetry via gpo using the 'DisableTelemetry' setting.

We now found the following documentation:
https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/internals/preferences.html

We noticed the following statement:

> toolkit.telemetry.unified
> 
> This controls whether unified behavior is enabled. If true:
> 
> Telemetry is always enabled and recording base data.
> 
> Telemetry will send additional main pings.
> 

The toolkit.telemetry.unified setting is not being diabled by the "DisableTelemetry" setting and obviously can't be disabled via gpo/preferences/JSON which produces an error (visible on about:policies):
"Unable to set preference toolkit.telemetry.unified. Preference not allowed for stability reasons."

According to the documentation above it should not be enabled in our case though, since we want ALL telemetry to be disabled.

How could this be resolved?

**Comment by mkaply** [comment]
We set preferences that disable the uploading of telemetry so the setting of unified is overridden.

        setAndLockPref("datareporting.healthreport.uploadEnabled", false);
        setAndLockPref("datareporting.policy.dataSubmissionEnabled", false);
        setAndLockPref("toolkit.telemetry.archive.enabled", false);

Looking further down that documentation on that page:

datareporting.healthreport.uploadEnabled

    If unified is true, this controls whether we send Telemetry data. If unified is false, we don’t use this value.

toolkit.telemetry.archive.enabled

    Allow pings to be archived locally. This can only be enabled if unified is on.

datareporting.policy.dataSubmissionEnabled

    This is the data submission master kill switch. If disabled, no policy is shown or upload takes place, ever.



Are you seeing data being sent?

**Comment by DavidLaun** [comment]
Thank you, this answered all our questions at once.

No, we didn't see specific data being sent.

**Comment by mkaply** [comment]
Awesome. Glad I could help. Please don't hesitate to reach out if you have other questions.
