### ISSUE TITLE
Enable Tracking Protection can block authentication button for some websites

### ISSUE THREAD

**Issue by pierre-guillot** [mozilla/policy-templates#962]
Hello, 

i'm Using ADMX for firefox V4.4 with firefox ESR 102.4.

My problem is on ony website, but this can be a problem on others sites.

Without firefox ADMX, if you connect to https://www.yesss-fr.com/connexion, you can see that website loads "googleanalytics elements" and tracking protection allowed this tracking content :

https://img.tedomum.net/data/Allow%20Tracking%20Content-d09446.png
https://img.tedomum.net/data/Load%20google%20analytics-17ead9.png

In this situation, the website works, you can click on the "je me connecte" button and have a warning that you credentials are invalids :

https://img.tedomum.net/data/credentials-249461.png

Here is how is configured the tracking protection (all by default) : 

https://img.tedomum.net/data/Tracking-parameters-e7bcbe.png

NOW, i install the ADMX locally on  the computer then I enabled only three elements on the ADMX tracking protection  : 

https://img.tedomum.net/data/ADMX-Tracking-53577d.png

Update GPO on the computer and return on the website. Now, google analytics is not loaded and you can't connect to the website : 

https://img.tedomum.net/data/NO-googleanalytics-e085e5.png
https://img.tedomum.net/data/No-google-detection-17d2d6.png

If you return to parameters, after GPO was enable, the configuration is like this : 

https://img.tedomum.net/data/Trakcing-parameters-with-gpo-9c6f4c.png

WIth ADMX enable, if you want to avoid this problem, you can : 

- disable cookies protection
- disable tracking protection content
- remove yesss-fr cookies

https://img.tedomum.net/data/avoid-problem1-b63bc3.png
https://img.tedomum.net/data/remove-cookie-6bd494.png

**Comment by mkaply** [comment]
This is not a policy issue.
