### ISSUE TITLE
HTTPS Only Mode - was that removed?

### ISSUE THREAD

**Issue by ThreshTheRed** [mozilla/policy-templates#963]
Hello there.

I was following this topic (https://support.mozilla.org/en-US/questions/1349839), to create .json file in Firefox directory, since I couldn't enforce https only mode via GPO.
I can't find it here - was that removed?

**Comment by mkaply** [comment]
We don't have a policy yet, but you can set it via the preferences policy. See the example here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1793905

Once I fix that UI bug, I plan to implement the actual policy.

**Comment by ThreshTheRed** [comment]
So, the way I do it, is - I go to GPO/Computer Conf/Files ->Create new file -> C:\Program Files\Mozilla Firefox\distribution\policies.json with content:

```
{

 "dom.security.https_only_mode": {
   "Value": true,
   "Status": "locked"
 }

}
```
Is it the correct way? Description "GPO/Preferences" isn't very detailed.

Greetings

**Comment by mkaply** [comment]
If you're using policies.json, it needs to have some other stuff around it:

```
{
	"policies": {
		"Preferences": {
			"dom.security.https_only_mode": {
				"Value": true,
				"Status": "locked"
			}
		}
	}
}
```

And I do plan to add an HTTPSOnly policy.

**Comment by ThreshTheRed** [comment]
It's not greyed out (unfortunately) but every time I change the value manually via Firefox, it reverts the changes after every restart, so it's kinda ok for me right now, thanks!

**Comment by mkaply** [comment]
Yep, that bug was fixed yesterday. Sorry about that.

I'm going to mark this closed since we're handling the policy change in Firefox.
