### ISSUE TITLE
Strange behavior when adding and removing search engines

### ISSUE THREAD

**Issue by ri-gilfanov** [mozilla/policy-templates#970]
**Software environment**
- OS: Alt K Workstation 10.1
- Firefox (ESR): 102.2.0

**Current behavior**

Step 1. Added this settings to `/etc/firefox/policies/policies.json`:
```
"SearchEngines": {
    "Add": [
        {
            "Name": "Яндекс",
            "URLTemplate": "https://yandex.ru/search/?text={searchTerms}",
            "Method": "GET",
            "IconURL": "https://yandex.ru/favicon.ico",
            "Alias": "ya",
            "SuggestURLTemplate": "https://suggest.yandex.ru/suggest-ff.cgi?part={searchTerms}"
        },
        {
            "Name": "Brave",
            "URLTemplate": "https://search.brave.com/search?q={searchTerms}",
            "Method": "GET",
            "IconURL": "https://cdn.search.brave.com/serp/v1/static/brand/9b3cd14668935362449eebb1854f575091a1169bf51aba6a8c17b39f64a9d07e-favicon-16x16.png",
            "Alias": "brave",
            "SuggestURLTemplate": "https://search.brave.com/api/suggest?q={searchTerms}"
        }
    ],
    "Default": "Яндекс",
    "Remove": ["DuckDuckGo", "Google", "Википедия (ru)"]
}
```
Step 2. Create user, login and launch Firefox. Policies is work

Step 3. Close Firefox

Step 4. Launch Firefox again. Policies is not work:

- Yandex search engine is removed
- Google search engine is added
- Google search engine set by default

**Expected behavior**

Policies should work not only on the first launch of the Firefox, but also on subsequent launches.

Thanks.

**Comment by ri-gilfanov** [comment]
@mkaply , thank you for the quick reaction. Javascript console is clear and have not any errors:
![Screenshot_20221108_175342](https://user-images.githubusercontent.com/29487864/200573520-408eec96-79a5-42ca-a54e-94d18f02e34d.png)

The message from above is translated something like this:
> Your default search engine has been changed. Yandex is no longer used as the default search engine in Firefox. Now your default search engine is Google. To change it, go to settings. [More](https://support.mozilla.org/ru/kb/moya-poiskovaya-sistema-po-umolchaniyu-izmenilas-p?as=u&utm_source=inproduct).

Additional Information.

- It seems that to recreate the situation, the browser should work for several minutes after the first launch. Then at the next launch, the search engines settings may be reset.
- The issue was preceded by a migration from Firefox 105.0.1 to Firefox 102.2 ESR.
- After the migration, the file `/etc/firefox/policies/policies.json.rpmnew` with the following content:
```
{
 "policies": {
   "ShowHomeButton": true
 }
}
```
- Then we applied configuration scripts in which there is a copy of our policy to `/etc/firefox/policies`:
```
cp /root/tonb/modes/prod/etc/firefox/policies/policies.json /etc/firefox/policies/
```
I began to reduce policy on the test computer to reduce possible side effects. Today I recreated the problem with this policy:
```
{
    "policies": {
        "DisableTelemetry": true,
        "Extensions": {
            "Install": [
                "https://addons.mozilla.org/firefox/downloads/file/1163931/russian_spellcheck_dictionary_yo_based_on_aot-0.4.3.1webext.xpi",
                "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"
            ],
            "Uninstall": [],
            "Locked": []
        },
	"ExtensionUpdate": true,
        "HardwareAcceleration": true,
        "OverrideFirstRunPage": "",
        "OverridePostUpdatePage": "",
	    "Preferences": {
            "browser.sessionhistory.max_total_viewers": 1,
            "datareporting.policy.dataSubmissionPolicyBypassNotification": true,
            "dom.ipc.forkserver.enable": true,
            "dom.ipc.processCount": 2,
            "general.autoScroll": {
                "Value": true,
                "Status": "default"
            },
            "gfx.webrender.all": true
        },
        "SearchEngines": {
             "Add": [
                 {
                     "Name": "Яндекс",
                     "URLTemplate": "https://yandex.ru/search/?text={searchTerms}",
                     "Method": "GET",
                     "IconURL": "https://yandex.ru/favicon.ico",
                     "Alias": "ya",
                     "SuggestURLTemplate": "https://suggest.yandex.ru/suggest-ff.cgi?part={searchTerms}"
                 },
                 {
                     "Name": "Brave",
                     "URLTemplate": "https://search.brave.com/search?q={searchTerms}",
                     "Method": "GET",
                     "IconURL": "https://cdn.search.brave.com/serp/v1/static/brand/9b3cd14668935362449eebb1854f575091a1169bf51aba6a8c17b39f64a9d07e-favicon-16x16.png",
                     "Alias": "brave",
                     "SuggestURLTemplate": "https://search.brave.com/api/suggest?q={searchTerms}"
                  }
          ],
          "Default": "Яндекс",
          "Remove": ["DuckDuckGo", "Google", "Википедия (ru)"]
      }
    }
}
```

**Comment by mkaply** [comment]
I think I know what might be causing that. I'm looking into it.

Can you try naming the engine with something extra in parenthesis instead of Yandex as a test like "Яндекс (ru)" and see what that does?

**Comment by ri-gilfanov** [comment]
@mkaply , I changed a policy so:
```
"SearchEngines": {
    "Add": [
        {
            "Name": "Яндекс (ru)",
            "URLTemplate": "https://yandex.ru/search/?text={searchTerms}",
            "Method": "GET",
            "IconURL": "https://yandex.ru/favicon.ico",
            "Alias": "ya",
            "SuggestURLTemplate": "https://suggest.yandex.ru/suggest-ff.cgi?part={searchTerms}"
        }
    ],
    "Default": "Яндекс (ru)"
}
```
When clicking on the address bar, I see two Yandex search engines:

- Yandex (@Yandex)
- Yandex (ru) (Ya)

Then I repeated typical steps:

- I made a search query to make sure that the search is carried out by the search engine by defending.
- Then I waited for 2-3 minutes and closed the browser.
- And I launched the browser again.

As a result. When clicking on the address bar:

- `Yandex (@Yandex)` is gone.
- `Yandex (ru) (Ya)` has been preserved and it is search engine by default.

It seems you helped me. I checked twice. The above policy works. Thank you!

**Comment by mkaply** [comment]
As long as you don't name it "Яндекс", I think it will work.

You might just try experimenting with adding a space after it or something like that so it looks the same.
