### ISSUE TITLE
ESR 102.3: Unknown policy: extensions

### ISSUE THREAD

**Issue by taschkalex** [mozilla/policy-templates#972]
Hi guys,

i tried to configure pdf documents to be opened by Acrobat Reader according to this documentation: https://github.com/mozilla/policy-templates/blob/master/README.md#Handlers

I am using a policies.json

The setting is not taking effect. About:policies is telling me "Unknown policy: extensions".
Is there a workaround?

**Comment by mkaply** [comment]
It sounds like you have extensions at the top level instead of "Handlers". Can you post your policies.json?

**Comment by taschkalex** [comment]
Hi Mike,

thank you very much für your help. You are absolutely right. 
[broken_policies.json.txt](https://github.com/mozilla/policy-templates/files/9977749/broken_policies.json.txt)
[fixed_policies.json.txt](https://github.com/mozilla/policy-templates/files/9977751/fixed_policies.json.txt)
