### ISSUE TITLE
Intune Firefox Extensions ADMX Length Limit

### ISSUE THREAD

**Issue by tkudya** [mozilla/policy-templates#973]
I am using the Firefox Intune ADMX to manage extensions installed on Browsers. I have managed to allow a few extensions but as I start adding more extensions I am no longer Able with the following message "The value must have a length of at most 1023."
Whats the available workaround to allow more extensions
![image](https://user-images.githubusercontent.com/78653328/200846517-767641d3-d933-47e6-bc06-bdd20eebb337.png)

{ "*": { 
"blocked_install_message": "Please email if you think an extension should be unblocked.", 
"install_sources": ["about:addons","https://addons.mozilla.org/"],
"installation_mode": "blocked",
"allowed_types": ["extension"] 
},
"{@react-devtools}": { 
"installation_mode": "allowed", 
"install_url": "https://addons.mozilla.org/firefox/downloads/latest/react-devtools/latest.xpi" },
"extension@redux.devtools": { 
"installation_mode": "allowed",
 "{446900e4-71c2-419f-a6a7-df9c091e268b}": { "installation_mode": "allowed", "install_url": "https://addons.mozilla.org/firefox/downloads/latest/bitwarden-password-manager/latest.xpi" }, 
"{support@lastpass.com}": { "installation_mode": "allowed", "install_url": "https://addons.mozilla.org/firefox/downloads/latest/lastpass-password-manager/latest.xpi"},
"{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}": { 
"installation_mode": "allowed", 
"install_url": "https://addons.mozilla.org/firefox/downloads/latest/styl-us/latest.xpi" },
"{943b8007-a895-44af-a672-4f4ea548c95f}": { 
"installation_mode": "allowed", 
"install_url": "https://addons.mozilla.org/firefox/downloads/latest/markdown-viewer-webext/latest.xpi" },
"installation_mode": "allowed",
"install_url": "https://addons.mozilla.org/firefox/downloads/latest/reduxdevtools/latest.xpi" },
"uBlock0@raymondhill.net": { 
"installation_mode": "allowed", 
}
}

**Comment by mkaply** [comment]
What version of the ADMX templates are you using? That field should be a MULTI_SZ now (not a single line) and have a limit of 16384

        <multiText id="ExtensionSettings" valueName="ExtensionSettings"  maxLength="16384"/>

**Comment by tkudya** [comment]
I am not using using the Custom ADMX import intune anyore but the Device Configuration - "Administrative Templates" option that's now available in Intune.  
![image](https://user-images.githubusercontent.com/78653328/201134316-03d7d377-dcf4-4cf1-9920-790291e2e3a7.png)

**Comment by mkaply** [comment]
Interesting. I haven't used that yet, but it sounds like they have a bug. They are not handling multiText correctly and implementing a limit that I don't have. I'll take a look.

**Comment by mkaply** [comment]
I've reported a bug through the Support Center feature. We'll see what they say.

**Comment by tkudya** [comment]
@mkaply Have you managed to get an answer from Microsoft? I can raise a support ticket with Microsoft

**Comment by mkaply** [comment]
I'm in communication with their product manager, but opening a support ticket would be great as well.

**Comment by sky2133** [comment]
is there a way to fix ? I have the same issue using imported firefox admx on intune, intune console just provided a single line instead multiple text, so that unable to paste the rule using json schedule

**Comment by mkaply** [comment]
I'll reach out to Microsoft again. Unfortunately this is their bug because they aren't honoring the maxLength in the ADMX.

Please raise a support ticket if you can.

**Comment by mkaply** [comment]
Feel free to let them know they can reach out to me if they want to discuss further.

I'm going to close this since it';s a Microsoft issue.

**Comment by sky2133** [comment]
Hi Michael,

can you share your email address, so that I can give it to microsoft support team.
________________________________

**Comment by mkaply** [comment]
mkaply at mozilla.com

Thanks!

**Comment by htcfreek** [comment]
Is this bug in intune fixed now?

**Comment by mkaply** [comment]
In order to work around this, I created one line versions of all the JSON policies.

If you search in this document:

https://mozilla.github.io/policy-templates/

for JSONOneLine

you'll find the information.

These should show up when you import the Custom ADMX/ADML

**Comment by htcfreek** [comment]
> In order to work around this, I created one line versions of all the JSON policies.
> 
> If you search in this document:
> 
> https://mozilla.github.io/policy-templates/
> 
> for JSONOneLine
> 
> you'll find the information.
> 
> These should show up when you import the Custom ADMX/ADML

I asked for a policy I implemented in a different project. But I understood the issue wrong. Now I see that it is about the max length per value.

**Comment by mkaply** [comment]
Max per textline, plus the UI is bad. It should be a multiline text field so you can paste in the JSON in regular format.
