### ISSUE TITLE
Proxy group policy not applied unless "lock" checkbox is checked

### ISSUE THREAD

**Issue by YohanRodriguezMDM** [mozilla/policy-templates#976]
(French guy here, sorry for my mistakes)

Hi everyone, 

I have an issue with my proxy group policy. I used last version (4.4) of admx/adml files with these parameters : 

I **did not** check the checkbox "Don't allow proxy settings to be changed."
Connection Type : Auto
URL : myURL

**about:policies shows :** 
Mode : "autoConfig"
AutoConfigURL : myURL

But my proxy settings are still on manual : 

![image](https://user-images.githubusercontent.com/71087699/202712887-4cbc2190-5e19-457b-b172-27408905fe8a.png)

If I check "Don't allow proxy settings to be changed.", my settings are applied, but obviously I can't change them to manual if needed.

Thanks for your help :)

**Comment by mkaply** [comment]
If you have a local version of the settings, it will be used unless you lock them. So it sounds like you have local changes.

**Comment by YohanRodriguezMDM** [comment]
> If you have a local version of the settings, it will be used unless you lock them. So it sounds like you have local changes.

That's what I understood from my testing but it seems not to be mentioned anywhere in the documentation :)
