### ISSUE TITLE
Handler for Mailto isn't working

### ISSUE THREAD

**Issue by ne0YT** [mozilla/policy-templates#977]
When I create a Handler-Entry for mailto it won't work and tell me :

Handlers | {}
on
about:policies#active
there's no error-msg.

Using Windows GPO I create this Entry:

NAME = 1
HKEY_CURRENT_USER
Software\Policies\Mozilla\Firefox\Handlers
REG_MULTI_SZ

```
{
	"schemes": {
		"mailto": {
			"action": "useHelperApp",
			"ask": false,
			"handlers": [{
				"name": "myMailserver",
				"uriTemplate": "https://mymailserver.tld/new?%s"
			}]
		}
	}
}
```

**Comment by mkaply** [comment]
Sorry for the delay on this. I just tried it and it's working for me.

What do you see when you go to about:preferences and scroll down to Applications. Do you see an entry?

![image](https://user-images.githubusercontent.com/345868/206028145-5eccd37c-7239-4101-87aa-b82563d001ab.png)

**Comment by ne0YT** [comment]
> about:preferences
I get "always ask"

> about:policies#active
can you post your output of this?

**Comment by mkaply** [comment]
![image](https://user-images.githubusercontent.com/345868/206229632-ffddae50-ae46-41e6-b68b-01c4ba932b7f.png)

**Comment by ne0YT** [comment]
> ![image](https://user-images.githubusercontent.com/345868/206229632-ffddae50-ae46-41e6-b68b-01c4ba932b7f.png)

did you set it up exactly as I posted? because for me it results in:
```
Handlers | {}
```

**Comment by ne0YT** [comment]
so only the {} appear for me, nothing else

**Comment by mkaply** [comment]
So you're manually creating the REG_MULTI_SZ? I'm wondering if that's causing the issue.

Can you try doing a REG_SZ instead and putting all the JSON on one concatenated line?

**Comment by ne0YT** [comment]
Yes, I created the Reg-Entry using Windows GPO for each user, which should have it.
I switched to "REG_SZ"
and set:
```
{"schemes":{"mailto":{"action":"useHelperApp","ask":false,"handlers":[{"name":"myMailserver","uriTemplate":"https://mymailserver.tld/new?%s"}]}}}
```
resulting in the same Entry under about:policies#active:
```
Handlers | {}
```

**Comment by mkaply** [comment]
Can you export the .reg file for me so I can look at it locally?

Preferably your entire Firefox subkey if you can do that.

Feel free to email it - mkaply at mozilla.com

**Comment by mkaply** [comment]
So Handlers should be a value in Firefox, not a key with values underneath it. So the .reg would look like this:

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Policies\Mozilla\Firefox]
"Handlers"="{\"schemes\":{\"mailto\":{\"action\":\"useHelperApp\",\"ask\":false,\"handlers\":[{\"name\":\"myMailserver\",\"uriTemplate\":\"https://mymailserver.tld/new?%s\"}]}}}"

![image](https://user-images.githubusercontent.com/345868/206297881-cd97dbfa-1544-4a6f-b3c1-7531511bbb77.png)

I'm assuming you did this by hand versus using the Group Policy Editor?

**Comment by ne0YT** [comment]
I used the GPO Editor. it works when I set it up like you show in the screenshot.
![image](https://user-images.githubusercontent.com/97364807/206860338-cb440ed8-7b42-462e-842c-1251ec439425.png)

**Comment by mkaply** [comment]
That's odd. it works when I use the GPO Editor. I'll double check things.
