### ISSUE TITLE
How to add several entries of X extension?

### ISSUE THREAD

**Issue by Cees381** [mozilla/policy-templates#984]
I've been scouring through https://github.com/mozilla/policy-templates/blob/master/README.md, and well, I can't find the proper way of adding several extensions, in 1 line. I've tried many different variations, but none of them work... please help?

```
{
  "policies": {
    "Extensions": {
      "Locked":  ["coldturkey@getcoldturkey.com"] ["54e2eb33-18eb-46ad-a4e4-1329c29f6e17"]
    }
  }
}
```

**Comment by Cees381** [comment]
Nvm, after many tries, I got it working by: "Locked":  ["coldturkey@getcoldturkey.com", "{54e2eb33-18eb-46ad-a4e4-1329c29f6e17}"]

**Comment by mkaply** [comment]
Yeah, you definitely need the {}

You might also checkout the ExtensionSettings policy.

https://github.com/mozilla/policy-templates/blob/master/README.md#extensionsettings
