### ISSUE TITLE
specify multiple certificates in policies.json

### ISSUE THREAD

**Issue by eylenth** [mozilla/policy-templates#985]
Hi

I tried to configure the following option in /usr/lib/firefox/distribution/policies.json
```json
{
  "policies": {
    "Certificates": {
      "Install": ["cert1.der", "/home/username/cert2.pem"]
    }
  }
}
```
see https://github.com/mozilla/policy-templates/blob/master/README.md#policiesjson-15
That is working properly.
But the thing is I also want to specify several certificates in the json file, since we need add multilple root certificates in our firefox settings

I already tried the following json syntax:
```json
{
  "policies": {
    "Certificates": {
      "Install": [
        {"cert1.der", "/home/username/cert2.pem"},
        {"cert3.der", "/home/username/cert4.pem"},
        {"cert5.der", "/home/username/cert6.pem"}
      ]
    }
  }
}
```
but that didn't work neither.
Could someone help me with the correct json syntax ?

**Comment by mkaply** [comment]
Install is an array, so you would just add them all as you did the first two:

```
"Install": ["cert1.der", "/home/username/cert2.pem", "cert3.der", "/home/username/cert4.pem", "cert5.der", "/home/username/cert6.pem"]
```

**Comment by eylenth** [comment]
ok thank you, it did work
