### ISSUE TITLE
children bookmark folder within managed bookmark folder

### ISSUE THREAD

**Issue by tkimpton** [mozilla/policy-templates#986]
For other browsers like Google Chrome and Microsoft Edge its possible to have another folder within the managed bookmark folder on the toolbar. Can this be done for Firefox? For Firefox it currently isn't possible to do this and to keep things unified on managed browsers in the Enterprise we have to just use the one top level folder on the toolbar for ALL browsers which is a real shame.

**Comment by tkimpton** [comment]
example for Edge

	<key>ManagedFavorites</key>
	<array>
		<dict>
			<key>toplevel_name</key>
			<string>Managed Bookmarks</string>
		</dict>
		<dict>
			<key>name</key>
			<string>xxx</string>
			<key>url</key>
			<string>xxx</string>
		</dict>
		<dict>
			<key>name</key>
			<string>xxx</string>
			<key>url</key>
			<string>xxx</string>
		</dict>
		<dict>
			<key>name</key>
			<string>xxx</string>
			<key>url</key>
			<string>xxx</string>
		</dict>
		<dict>
			<key>name</key>
			<string>xxx</string>
			<key>url</key>
			<string>xxx</string>
		</dict>
		<dict>
			<key>name</key>
			<string>xxx</string>
			<key>url</key>
			<string>xxx</string>
		</dict>
		<dict>
			<key>name</key>
			<string>xxx</string>
			<key>url</key>
			<string>xxx</string>
		</dict>
		<dict>
			<key>children</key>
			<array>
			<dict>
			<key>name</key>
			<string>xxx/string>
			<key>url</key>
			<string>xxx</string>
			</dict>
			<dict>
			<key>name</key>
			<string>xxxx</string>
			<key>url</key>
			<string>xxx</string>
			</dict>
			<dict>
			<key>name</key>
			<string>xxx</string>
			<key>url</key>
			<string>xxx</string>
			</dict>
			</array>
			<key>name</key>
			<string>Managed Bookmarks Embedded Folder</string>
		</dict>
	</array>
</dict>
</plist>

**Comment by mkaply** [comment]
We support the same schema as Chrome/Edge for Managed Bookmarks including children.

See:

https://github.com/mozilla/policy-templates/blob/master/README.md#managedbookmarks

The syntax of this policy is exactly the same as the [Chrome ManagedBookmarks policy](https://cloud.google.com/docs/chrome-enterprise/policies/?policy=ManagedBookmarks).

**Comment by tkimpton** [comment]
Yep doesn’t work on Firefox. I tried lots of times. I will try again.

**Comment by mkaply** [comment]
The key is ManagedBookmarks on Firefox.

Can you give me your plist? Are you seeing nothing?

**Comment by tkimpton** [comment]
Thanks very much, i needed to change Bookmarks to ManagedBookmarks and it worked.
