### ISSUE TITLE
Unable to parse JSON for ExtensionSettings

### ISSUE THREAD

**Issue by JoostOG** [mozilla/policy-templates#992]
Hi,

I keep running into the error message "Unable to parse JSON for ExtensionSettings" with the policy:ExtensionSettings
Here the .json i'm trying to use.
[Firefox_Extensions.txt](https://github.com/mozilla/policy-templates/files/10466819/Firefox_Extensions.txt)

The method I eventually want to use is through Intune.
Within Intune, I imported the ADMX templates and used the "Extension Management" policy here.

Steps taken for troubleshooting:
- Policy changed by the OMA-URI (as described in the instructions)
- Directly modified the registery value under: HKEY_LOCAL_MACHINE_SOFTWAREPoliciesMozillaFirefox
- Put the example JSON from the instructions into the registery value. (https://github.com/mozilla/policy-templates/blob/master/README.md#windows-gpo-50)

All of the above steps end in: Unable to parse JSON for ExtensionSettings

**Comment by mkaply** [comment]
You have a couple trailing commas that are causing the issue.

I use https://jsonlint.com/ for testing my JSON. It works really well.

**Comment by JoostOG** [comment]
Indeed, I checked the json with https://jsonlint.com/ and took out the errors.

Unfortunately, I keep running into the error message "Unable to parse JSON for ExtensionSettings"

New version: [Firefox_Extensions.txt](https://github.com/mozilla/policy-templates/files/10480259/Firefox_Extensions.txt)

**Comment by mkaply** [comment]
Sorry this is such a hassle. Is it possible you have a blank line or space at the beginning?

If you go to about:config in Firefox and create a new string preference called

browser.policies.loglevel

and set it's value to 

debug

You should see some better errors. If they don't show up in Errors on about:policies, you can open the Javascript console (Ctrl+Shift+J)

Let me know if you want to work with me directly to figure this out. I'm more than happy to jump on a call.

**Comment by JoostOG** [comment]
I solved the problem by removing the following line.
6. "install_sources": ["https://addons.mozilla.org/", "about:addons"]

@mkaply thanks for your support so far

**Comment by mkaply** [comment]
I should have caught that. about:addons doesn't work in that case (and that line isn't really necessary if you've specified addons you want. It's more intended to allow installing addons from other sources besides AMO).

Glad it's working for you!
