### ISSUE TITLE
Unable to Apply Proxy Policy In Microsoft Intune

### ISSUE THREAD

**Issue by scheblein** [mozilla/policy-templates#995]
For over a year, we've tried to figure out the way to apply the proxy policy to our Windows 10 clients in Intune. Unfortunately, it's always errored with an error code: -2016281112 or 0x87d1fde8. Googling brought us this: [Error with OMA-URI in Intune: Always be careful after Copy Paste](https://www.systanddeploy.com/2020/04/error-with-oma-uri-in-intune-always-be.html), so we double-checked and didn't see any unicode character errors.

We apply the identical policy to Mac clients in Jamf Pro and it applies successfully.

**Mac:**
```
<key>Proxy</key>
<dict>
  <key>AutoLogin</key>
  <true/>
  <key>Locked</key>
  <false/>
  <key>Mode</key>
  <string>autoDetect</string>
  <key>Passthrough</key>
  <string>&lt;local&gt;</string>
  <key>SocksVersion</key>
  <string>5</string>
</dict>
```

**Windows (tried both with and without line breaks, and with \<local> and \&lt;local\&gt;)**
```
<enabled/>
<data id="ProxyLocked" value="false"/>
<data id="ConnectionType" value="autoDetect"/>
<data id="SOCKSVersion" value="5"/>
<data id="Passthrough" value="&lt;local&gt;"/>
<data id="AutoLogin" value="true"/>
```

This was mildly important before, but as we have just learned that "Use system proxy settings" actually [does **nothing** in Windows when WPAD is used](https://bugzilla.mozilla.org/show_bug.cgi?id=621429#c71), it has now become much more important.

What are we missing?

**Comment by mkaply** [comment]
I'm at a complete loss on this. All the documentation on Microsoft's site (and looking at the Google stuff) says this should work, but clearly it doesn't. (I've recreated it on my Intune implentation).

When I originally implemented this, I thought the right way to do proxy was to put it all on one page, and I think that's what the ADMX injection is not happy with.

In the next update to the ADMX, I'm going to move Proxy to be individual items in a Proxy category and it should hopefully solve this.

**Comment by mkaply** [comment]
I discovered why this is happening and switching to categories will fix it.

It appears that if I specify entries in the ADMX file, ALL of those entries have to exist in the string for the entry in Intune.

So the "Fix" for your problem would be to remove the items that you aren't using from the ADMX that is being ingested (not  a good fix at all).

The better fix is for me to move away from combining all the proxy entries into one policy which I will be doing for the next release.

**Comment by mkaply** [comment]
I switched to categories.
