### ISSUE TITLE
Thunderbird signature settings

### ISSUE THREAD

**Issue by LukaszSellmann** [mozilla/policy-templates#998]
Hi

Is there a way to set up user preferences by using json in GPO "Preferences" ? 
Does this work with program global preferences only ?
I've been searching to set up user signatures by GPO ,or maybe there is another way to set up `mail.identity.id1.sig_file` for users.

**Comment by mkaply** [comment]
When you say "user" do you mean Thunderbird user or user on the computer?

**Comment by LukaszSellmann** [comment]
actually i mean signature for email account in thunderbird , i assume that part `id1` in `mail.identity.id1.sig_file` is id of configured email account in thunderbird.

**Comment by mkaply** [comment]
Yes, you can set those preferences in Thunderbird via policy. 

The Thunderbird policies are maintained here.

https://github.com/drlellinger/thunderbird-policies
